// Facility level-narration pack 1. ONE author owns this file.
// Keys are facility keys; each array is indexed from LEVEL 2 (level 1 is the club's starting state), so
// entry [0] is what reaching level 2 looks like and entry [8] is level 10.
//
// Each array is a single place changing over decades, in order: scaffolding and kettles at the bottom,
// scale and its costs at the top. Level 10 is meant to land slightly cold — getting everything you
// wanted is its own kind of ending.
export const FAC_LEVEL_STORY_1: Record<string, string[]> = {
  stadium: [
    "Scaffolding goes up behind the far goal and a portacabin becomes the ticket office.",
    "Terracing on three sides now, and a hand-painted sign at the turnstiles telling you which queue is which.",
    "Seats. Four hundred of them, plastic, bolted onto what used to be a bank of railway sleepers.",
    "The far stand gets a roof, and for the first time in the club's life rain is somebody else's problem.",
    "Floodlights that do not hum. Kick-off can be at eight on a Tuesday and nobody has to squint.",
    "The old main stand comes down in a week. It had stood for sixty years and it takes four men and a machine.",
    "Twenty thousand under cover, a police liaison, and a stewarding budget that would once have run the whole club.",
    "They widen the concourse and lose the tea hut that had been there since before anyone can properly remember.",
    "The away end has its own car park now, and nobody remembers the field it used to be.",
  ],
  training: [
    "A second pitch, drained badly, but it means the first one gets a rest in February.",
    "Somebody's dad brings a strimmer up on Sundays and the far touchline stops disappearing into the nettles.",
    "Portacabin gym: two bikes, a rack of weights, and a heater that trips the power if you use both.",
    "Proper drainage, at last. Winter sessions stop being ninety minutes of standing in water.",
    "A fitness coach with a laptop, and a squad that no longer comes apart after seventy minutes.",
    "An indoor barn with a full-size surface. Nobody trains in the rain any more unless the manager wants them to.",
    "Sixteen pitches, a gate on the lane, and a man whose entire job is the grass.",
    "Players arrive, work, eat and leave without meeting anybody who is not on the payroll.",
    "It has its own postcode. The old fields the first team used to use are a housing estate, and the sign off the gate is the only thing anybody kept.",
  ],
  youth: [
    "Two coaches on a Thursday night, a bag of bibs, and thirty lads off the estate.",
    "A charity match pays for a minibus, and the catchment becomes forty miles instead of four.",
    "Under-14s through to under-18s, all of them, with fixtures that mean something.",
    "A head of youth is appointed. The first thing she does is throw out the old trial notes.",
    "Boys are turning down bigger clubs to come here, which has never once happened before.",
    "Three from the intake go straight into the first-team squad and none of them look out of place.",
    "Other clubs stop scouting the academy for players and start scouting it for coaches.",
    "An intake of forty, and a duty-of-care document that runs to sixty pages because it has to.",
    "They arrive at nine having never known anywhere else, and most will be told at sixteen that they are not good enough. Delivering that is now somebody's full-time job.",
  ],
  scouting: [
    "An old pro gets his petrol paid to watch parks football on a Saturday morning.",
    "Three part-timers, one shared notebook, and an argument every fortnight about whose eye is better.",
    "A room above the ticket office with a map, pins in it, and a kettle that is never off.",
    "Reports come in typed now, to a template, and the arguments get shorter.",
    "A network abroad. Somebody's cousin in a port city sends up a name that turns out to be worth a fortune.",
    "Full-time chief scout, six regional men, and a budget that no longer gets justified line by line.",
    "They watch a boy for three years before making contact, because they can afford to wait.",
    "The database holds eleven thousand players, and the club has seen almost every one of them in the flesh.",
    "The old pro who started it is dead, the room above the ticket office is a corporate box, and his notebooks sit in a cupboard nobody has the authority to empty.",
  ],
  medical: [
    "A proper couch, and a second physio who comes in Tuesdays and matchdays.",
    "The ice bath is a wheelie bin, but it is a dedicated wheelie bin.",
    "A treatment room that is not also the boot room. Hamstrings stop being a guess.",
    "A club doctor on the payroll, and the phrase 'he'll be all right' quietly stops counting as medical advice.",
    "Scans inside a day instead of a fortnight, which changes what the word 'setback' means here.",
    "Sports science, load monitoring, and three players a year who never find out what they avoided.",
    "Rehab pool, altitude room, and a gait lab that cost more than the training ground once did.",
    "Other clubs start sending their players here, and paying for the privilege.",
    "A department of twenty-two, and a lad on the couch who has not been seen by the same person twice.",
  ],
  sponsor: [
    "A local builder's name goes on the shirt and the money covers the away travel.",
    "Two boards along the far touchline, sold over the phone by the chairman's daughter.",
    "A commercial manager, an office, and the first contract anybody here has had a solicitor read.",
    "The kit deal is worth more than the highest wage on the books. Nobody says that out loud.",
    "Pre-season abroad, paid for by a company that wants photographs of the squad in its own colours.",
    "Naming rights on the training ground. The staff still use the old name and always will.",
    "Thirty people in commercial, and four days of pre-season given over to shooting adverts.",
    "Sponsors in eleven markets, and a shirt with three logos on it that a man has to explain to his son.",
    "The badge is simplified so it renders cleanly at small sizes. The old one had a ship on it, for reasons nobody on the board can now tell you.",
  ],
  fanzone: [
    "A burger van, a marquee, and somebody's speaker balanced on a wheelie bin.",
    "The old social club reopens on matchdays and the singing starts an hour before kick-off.",
    "A drum in the corner of the terrace. Half the ground hates it and it stays.",
    "A supporters' bar behind the away end, with a hundred scarves nailed to the ceiling.",
    "The lower tier is standing again, safely and legally, and it sounds the way it used to.",
    "Matchdays start at eleven with a fan park, and the pubs in town quietly notice.",
    "A tifo the length of a stand, made in a warehouse by eighty people over two months.",
    "The noise is a fixture in itself now. Away supporters buy tickets for it.",
    "There is an anthem, and it comes out of the speakers at a volume that means nobody can hear whether the crowd are singing it.",
  ],
  data: [
    "A laptop, a spreadsheet, and a lad doing it for expenses and a season ticket.",
    "Every match filmed off a scaffold tower behind the goal, in all weathers, by a volunteer.",
    "An analyst on the staff. The first thing he proves is that the side defends corners badly.",
    "Opposition packs on the coach, and a manager who has stopped pretending not to read them.",
    "Set-piece coach, tracking data, and eleven goals a season that begin on a laptop.",
    "They start valuing players by the numbers before anyone watches them, and it works often enough to be uncomfortable.",
    "Fourteen in the department, half of whom never played the game past school.",
    "The model recommends selling a terrace favourite. The model turns out to be right.",
    "Every decision has a number under it now, and the last man on the staff who signed players on a feeling took early retirement in the summer.",
  ],
  shop: [
    "A trestle table in the car park, shirts in a cardboard box, cash in a tin.",
    "The old ticket hut becomes a shop, open ninety minutes before kick-off and shut the rest of the week.",
    "A proper till, an actual stockroom, and a woman who knows every regular's size.",
    "Mail order. Six shirts a week go out to people who have never stood in the ground.",
    "A unit in the town centre, open six days, badge lit up over the door.",
    "Third kits, retro ranges, and a calendar that decides when the club is allowed to be nostalgic.",
    "Online sales pass the gate receipts. The board notes it; the terraces do not.",
    "Shirts get made to a forecast now, in numbers that need a warehouse, and the forecast is usually right.",
    "The woman who knew everyone's size retired eight years ago. There are four shops, and she would not recognise one of them.",
  ],
  dorm: [
    "Two spare rooms in a house on the main road, and a landlady who feeds them far too much.",
    "Four digs families on the books, vetted properly, and a boy from ninety miles off who would otherwise have gone home.",
    "A converted terrace behind the ground: six beds, one bathroom, and a curfew nobody enforces well.",
    "Purpose-built block, study room, a cook. The first intake who do not have to choose between school and football.",
    "Twenty-four places, a house parent on site, and lights out that means lights out.",
    "Boys start arriving from abroad at sixteen, and the club employs somebody whose job is ringing their mothers.",
    "One wing for the under-16s and one for the ones who are nearly there. The corridor between them matters enormously.",
    "Sixty beds, a chaplain, a counsellor, and a leavers' programme for the ones it does not come off for.",
    "Every June a minibus takes the released boys home, and by August the block is full again.",
  ],
  women: [
    "A side is entered in the county league. They train on the school pitch, because the men have the ground.",
    "The badge on the shirt matches the men's now. It took two seasons of asking.",
    "A paid manager, a fixture list in the programme, and a hundred and twelve at the first home game.",
    "They get the main pitch twice a month. It is negotiated every month and it is never simple.",
    "Full-time contracts for eight of them, and a captain who was working shifts until March.",
    "Promotion, a five-figure crowd for the derby, and a queue at the shop for a shirt with a different name on the back.",
    "Shared medical, shared analysts, shared everything, and a budget line that stops being defended at every board meeting.",
    "They win something the men's side never has, and it goes in the same cabinet.",
    "It is a business now, with its own executive, its own ground, and supporters who have never once watched the men.",
  ],
  community: [
    "A coach runs a session at the primary school on Fridays and the club pays for the balls.",
    "A food-bank collection at the turnstiles, and the pile is bigger the first week than anybody had planned for.",
    "A registered trust, two staff, and an office in what used to be the referee's room.",
    "Walking football, a veterans' group, and a hundred and forty people in the ground on a Tuesday who are not there for a match.",
    "Holiday clubs across the borough, and a council that starts returning calls the same day.",
    "The trust employs more people than the football club did a decade ago.",
    "A health programme, a jobs programme, and men in their sixties who will tell you it got them out of the house.",
    "When the town loses its biggest employer, the trust is what people ring.",
    "It is what the club is known for now, and there are directors who would rather the reporters asked about the football.",
  ],
};
