// AUTO-GENERATED by tools/reindex_badges.py — do not edit by hand.
// The club badges present under client/public/badges/. Delete unwanted badge-*.png and
// re-run the script to regenerate this list; crest.ts assigns each club one by name-hash.
export const BADGES: readonly string[] = [
];
