// AUTO-GENERATED by tools/rd_kits.py — 2-tone recolorable jersey templates.
// Sentinel colours: base = rgb(255,0,255), accent = rgb(0,255,255). Recolor via client/src/kit.ts.
export const KITS: readonly string[] = ['kit-checkerboard.png', 'kit-chestband.png', 'kit-chevron.png', 'kit-halves.png', 'kit-hoops.png', 'kit-pinstripe.png', 'kit-placket.png', 'kit-quarters.png', 'kit-sash.png', 'kit-sidepanels.png', 'kit-sleeves.png', 'kit-solid.png', 'kit-splithoop.png', 'kit-stripes.png', 'kit-twinstripe.png', 'kit-yoke.png'];
