// ── Player / manager face portraits — hash-assigned from age-banded pools (client/public/portraits) ──
// Three pools (youth / prime / veteran) generated by tools/rd_portraits.py so a prospect never wears a
// veteran face and vice-versa. portraitImg() returns an <img> that hides itself if the file is missing,
// so the surrounding UI never shows a broken image.
import { PORTRAITS } from './portrait-manifest';

function h32(s: string): number { let h = 2166136261; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return (h >>> 0) || 1; }

export type Band = 'youth' | 'prime' | 'veteran';

/** Pick an age band from an age (and whether the person is a manager/coach). */
export function bandForAge(age: number | undefined, manager = false): Band {
  if (manager) return 'veteran';
  if (age == null) return 'prime';
  if (age <= 19) return 'youth';
  if (age >= 38) return 'veteran';
  return 'prime';
}

/** The portrait image url for a person. '' if the pool is empty.
 *
 *  ONE MAN KEEPS HIS FACE AS HE AGES. This hashed `name + band`, so the band was part of the key and each
 *  life stage landed on an unrelated index: Nils Ashcombe was youth-10, then prime-18, then veteran-2 —
 *  three different people. Nobody noticed on the Family Record, where each node is one man at one stage,
 *  but it is glaring the moment faces appear in the squad: a nineteen-year-old you signed becomes somebody
 *  else on his twentieth birthday, and again at thirty-eight.
 *
 *  The pools are now PARALLEL — index k is the same person in youth, prime and veteran, generated as an
 *  aged triplet with the same heritage, skin and hair — so hashing the name ALONE picks one identity and
 *  the band only chooses which age of him to show.
 *
 *  The modulo still uses each pool's own length so a mismatched or partially-loaded set degrades to the old
 *  behaviour (a stable but unrelated face) rather than throwing. `sameIdentityAcrossBands` says whether the
 *  guarantee currently holds; `qa_portraits.ts` asserts it does. */
export function portraitUrl(name: string, band: Band): string {
  const pool = PORTRAITS[band] ?? [];
  return pool.length ? `/portraits/${pool[h32(name) % pool.length]}` : '';
}

/** True when the three pools are parallel, which is what makes a face survive ageing. */
export function sameIdentityAcrossBands(): boolean {
  const lens = (['youth', 'prime', 'veteran'] as Band[]).map((b) => (PORTRAITS[b] ?? []).length);
  return lens.every((n) => n > 0 && n === lens[0]);
}

/** An <img> for a face portrait; self-hides on load error so callers can keep a fallback behind it. */
export function portraitImg(name: string, band: Band, size = 48, cls = ''): string {
  const url = portraitUrl(name, band);
  if (!url) return '';
  return `<img class="portrait${cls ? ' ' + cls : ''}" src="${url}" width="${size}" height="${size}" alt="" loading="lazy" onerror="this.onerror=null;this.style.display='none'" />`;
}
