// ── Player / manager face portraits — hash-assigned from age-banded pools (client/public/portraits) ──
// Three pools (youth / prime / veteran) generated by tools/rd_portraits.py so a prospect never wears a
// veteran face and vice-versa. portraitImg() returns an <img> that hides itself if the file is missing,
// so the surrounding UI never shows a broken image.
import { PORTRAITS } from './portrait-manifest';

function h32(s: string): number { let h = 2166136261; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return (h >>> 0) || 1; }

export type Band = 'youth' | 'prime' | 'veteran';

/** Pick an age band from an age (and whether the person is a manager/coach). */
export function bandForAge(age: number | undefined, manager = false): Band {
  if (manager) return 'veteran';
  if (age == null) return 'prime';
  if (age <= 19) return 'youth';
  if (age >= 38) return 'veteran';
  return 'prime';
}

/** The portrait image url for a person (stable per name within the band). '' if the pool is empty. */
export function portraitUrl(name: string, band: Band): string {
  const pool = PORTRAITS[band] ?? [];
  return pool.length ? `/portraits/${pool[h32(name + band) % pool.length]}` : '';
}

/** An <img> for a face portrait; self-hides on load error so callers can keep a fallback behind it. */
export function portraitImg(name: string, band: Band, size = 48, cls = ''): string {
  const url = portraitUrl(name, band);
  if (!url) return '';
  return `<img class="portrait${cls ? ' ' + cls : ''}" src="${url}" width="${size}" height="${size}" alt="" loading="lazy" onerror="this.onerror=null;this.style.display='none'" />`;
}
