// ── Pixel-art sprite system ─────────────────────────────────────────────────
// Tiny self-contained pixel-art icons drawn as inline SVG (no external assets, so
// they work offline and inherit the theme). Each sprite is authored as a grid of
// single-char pixels + a palette; `crispEdges` keeps the blocky pixel look at any size.
// Kept deliberately small and used sparingly — a little pixel flavour, not clutter.

// Shared palette — reused across sprites for a coherent look. '.' / ' ' = transparent.
const PAL: Record<string, string> = {
  k: '#10102a', // dark outline
  d: '#33335f', // shadow stone
  s: '#6b6f9c', // stone / concrete
  S: '#9aa0d0', // light stone
  w: '#eef2ff', // white
  g: '#2fbf6e', // grass
  G: '#46e08a', // grass highlight
  y: '#ffce3a', // gold
  o: '#ff9a3c', // orange
  r: '#ff5d6c', // red
  c: '#37e6ff', // cyan
  b: '#4d8bff', // blue
  p: '#e8b48a', // skin
  n: '#7a5a3a', // brown
  m: '#ff6ab0', // pink
  l: '#c9a24a', // dark gold
  t: '#1f8f5a', // dark grass
  u: '#8b5cff', // royal purple (matches theme --purple)
  e: '#39ff9e', // midfield green (matches theme --mf exactly)
  f: '#ff7a3c', // forward orange (matches theme --fw exactly)
};

/** Build an inline-SVG pixel sprite from a char grid. Rows may vary in length. */
function px(grid: string[], palette: Record<string, string> = PAL): string {
  const h = grid.length;
  const w = Math.max(...grid.map((r) => r.length));
  let rects = '';
  for (let y = 0; y < h; y++) {
    const row = grid[y];
    for (let x = 0; x < row.length; x++) {
      const ch = row[x];
      const fill = palette[ch];
      if (fill) rects += `<rect x="${x}" y="${y}" width="1" height="1" fill="${fill}"/>`;
    }
  }
  return `<svg class="px" viewBox="0 0 ${w} ${h}" xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges" preserveAspectRatio="xMidYMid meet">${rects}</svg>`;
}

// ── Sprite definitions (16×16 unless noted) ─────────────────────────────────
const SPRITES: Record<string, string[]> = {
  // 🏟️ Stadium — floodlit bowl around a green pitch
  stadium: [
    'y..............y',
    'ky............ky',
    '.k............k.',
    '.SssssssssssssS.',
    'sSSSSSSSSSSSSSSs',
    'sSgggggggggggggS',
    'sSgttttttttttggS',
    'sSgtGGGGGGGGtggS',
    'sSgtGwwwwwwGtggS',
    'sSgtGwGGGGwGtggS',
    'sSgtGwwwwwwGtggS',
    'sSgtGGGGGGGGtggS',
    'sSgggggggggggggS',
    'sSSSSSSSSSSSSSSs',
    '.dssssssssssssd.',
    '..dddddddddddd..',
  ],
  // 🏋️ Training Ground — a dumbbell (fills more of the frame than most icons here so it doesn't
  // read as a tiny "H" when shrunk to facility-card size — was letterboxed with 3 empty rows top
  // and bottom; now spans nearly the full 16px height).
  training: [
    '................',
    '..kk......kk....',
    '.kSSk....kSSk...',
    '.kSSk....kSSk...',
    '.kSSk....kSSk...',
    '.kSSkkkkkkSSk...',
    '.kSSSllllSSSk...',
    '.kSSSllllSSSk...',
    '.kSSkkkkkkSSk...',
    '.kSSk....kSSk...',
    '.kSSk....kSSk...',
    '.kSSk....kSSk...',
    '..kk......kk....',
    '................',
    '................',
    '................',
  ],
  // 🎓 Youth Academy — a green sprout in a pot (home-grown talent)
  youth: [
    '................',
    '................',
    '.......t........',
    '......tGt.......',
    '.....GGtGG......',
    '....GG.t.GG.....',
    '....G..t..G.....',
    '.......t........',
    '.......t........',
    '.....kkkkk......',
    '....knnnnnk.....',
    '....knSSSnk.....',
    '....knnnnnk.....',
    '.....kkkkk......',
    '................',
    '................',
  ],
  // 🔭 Scouting HQ — binoculars
  scouting: [
    '................',
    '................',
    '..kkk....kkk....',
    '.kcbck..kcbck...',
    '.kccck..kccck...',
    '.kccckkkkccck...',
    '.kSSSccccSSSk...',
    '.kSSSk..kSSSk...',
    '..kkk....kkk....',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // 🏥 Medical Centre — a med kit / red cross
  medical: [
    '................',
    '................',
    '...kwwwwwwwwk...',
    '..kwwwwwwwwwwk..',
    '..kwwwwrrwwwwk..',
    '..kwwwwrrwwwwk..',
    '..kwrrrrrrrrwk..',
    '..kwrrrrrrrrwk..',
    '..kwwwwrrwwwwk..',
    '..kwwwwrrwwwwk..',
    '..kwwwwwwwwwwk..',
    '...kwwwwwwwwk...',
    '................',
    '................',
    '................',
    '................',
  ],
  // 📣 Commercial Dept — a stack of gold coins
  sponsor: [
    '................',
    '................',
    '................',
    '....kkkkkk......',
    '...kyllllyk.....',
    '....kkkkkk......',
    '...kyllllyk.....',
    '....kkkkkk......',
    '..kyyllllyyk....',
    '..kyllllllyk....',
    '...kkkkkkkk.....',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // 🎉 Fan Zone — a football scarf
  fanzone: [
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..krrwwrrwwrrk..',
    '..krrwwrrwwrrk..',
    '..krrwwrrwwrrk..',
    '..kkkkkkkkkkkk..',
    '..k.k.k.k.k.k...',
    '..k.k.k.k.k.k...',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // ⚽ Football
  ball: [
    '................',
    '.....kkkkkk.....',
    '...kkwwwwwwkk...',
    '..kwwwwwwwwwwk..',
    '..kwwwwkkwwwwk..',
    '.kwwwkkkkkkwwwk.',
    '.kwwwkkkkkkwwwk.',
    '.kwwwwkkkkwwwwk.',
    '.kwwkwwwwwwkwwk.',
    '.kwwkwwwwwwkwwk.',
    '..kwwwwwwwwwwk..',
    '..kwwwwwwwwwwk..',
    '...kkwwwwwwkk...',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  // 🏆 Trophy
  trophy: [
    '................',
    '..kkkkkkkkkk....',
    '..kyyyyyyyyk....',
    '.kykyyyyyykyk...',
    'kyykyyyyyykyyk..',
    'kyykyyyyyykyyk..',
    '.kykyyyyyykyk...',
    '..kyyyyyyyyk....',
    '...kyyyyyyk.....',
    '....kyyyyk......',
    '.....kyyk.......',
    '....kkyykk......',
    '...kyyyyyyk.....',
    '...kkkkkkkk.....',
    '................',
    '................',
  ],
  // 🥇 Medal — ribboned disc, for POTM / season awards
  medal: [
    '................',
    '......r....r....',
    '......rr..rr....',
    '.......rrrr.....',
    '.......kkkk.....',
    '......kyyyyk....',
    '.....kyyllyyk...',
    '.....kyyllyyk...',
    '.....kyllwlyk...',
    '.....kyyllyyk...',
    '......kyyyyk....',
    '.......kkkk.....',
    '................',
    '................',
    '................',
    '................',
  ],
  // 🟨 Referee card — yellow booking
  card: [
    '................',
    '................',
    '...kkkkkkkkk....',
    '..kyyyyyyyyyk...',
    '..kyyyyyyyyyk...',
    '..kyyyyyyyyyk...',
    '..kyyyyyyyyyk...',
    '..kyyyyyyyyyk...',
    '..kyyyyyyyyyk...',
    '..kyyyyyyyyyk...',
    '...kkkkkkkkk....',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // 🟥 Referee card — red booking (same shape as `card`, red fill so a sending-off never shows
  // a yellow icon)
  'card-red': [
    '................',
    '................',
    '...kkkkkkkkk....',
    '..krrrrrrrrrk...',
    '..krrrrrrrrrk...',
    '..krrrrrrrrrk...',
    '..krrrrrrrrrk...',
    '..krrrrrrrrrk...',
    '..krrrrrrrrrk...',
    '..krrrrrrrrrk...',
    '...kkkkkkkkk....',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // 🎽 Kit — a folded jersey with a number, for kit customizer / squad list
  kit: [
    '................',
    '...kk.....kk....',
    '..kbk.k...kkbk..',
    '..kbkkkkkkkkbk..',
    '..kbkbbbbbbkbk..',
    '...kbbbbbbbbk...',
    '...kbbwwwwbbk...',
    '...kbbwbbwwbk...',
    '...kbbwbbwwbk...',
    '...kbbwwwwbbk...',
    '...kbbbbbbbbk...',
    '...kbbbbbbbbk...',
    '....kkkkkkkk....',
    '................',
    '................',
    '................',
  ],
  // 🧤 Position jerseys — GK/DF/MF/FW, tinted to match the existing --gk/--df/--mf/--fw theme
  // tokens exactly, so they read as an extension of the squad-table role colouring, not a new code.
  'role-gk': [
    '................',
    '...kk.....kk....',
    '..kyk.k...kkyk..',
    '..kykkkkkkkkyk..',
    '..kykyyyyyykyk..',
    '...kyyyyyyyyk...',
    '...kyywwwwyyk...',
    '...kyywyywwyk...',
    '...kyywyywwyk...',
    '...kyywwwwyyk...',
    '...kyyyyyyyyk...',
    '...kyyyyyyyyk...',
    '....kkkkkkkk....',
    '................',
    '................',
    '................',
  ],
  'role-df': [
    '................',
    '...kk.....kk....',
    '..kbk.k...kkbk..',
    '..kbkkkkkkkkbk..',
    '..kbkbbbbbbkbk..',
    '...kbbbbbbbbk...',
    '...kbbwwwwbbk...',
    '...kbbwbbwwbk...',
    '...kbbwbbwwbk...',
    '...kbbwwwwbbk...',
    '...kbbbbbbbbk...',
    '...kbbbbbbbbk...',
    '....kkkkkkkk....',
    '................',
    '................',
    '................',
  ],
  'role-mf': [
    '................',
    '...kk.....kk....',
    '..kek.k...kkek..',
    '..kekkkkkkkkek..',
    '..kekeeeeeekek..',
    '...keeeeeeeek...',
    '...keewwwweek...',
    '...keeweewwek...',
    '...keeweewwek...',
    '...keewwwweek...',
    '...keeeeeeeek...',
    '...keeeeeeeek...',
    '....kkkkkkkk....',
    '................',
    '................',
    '................',
  ],
  'role-fw': [
    '................',
    '...kk.....kk....',
    '..kfk.k...kkfk..',
    '..kfkkkkkkkkfk..',
    '..kfkffffffkfk..',
    '...kffffffffk...',
    '...kffwwwwffk...',
    '...kffwffwwfk...',
    '...kffwffwwfk...',
    '...kffwwwwffk...',
    '...kffffffffk...',
    '...kffffffffk...',
    '....kkkkkkkk....',
    '................',
    '................',
    '................',
  ],
  // 🚩 Flag — a pennant on a pole, generic marker for competitions / nations
  flag: [
    '..k.............',
    '..k.............',
    '..kooooooo......',
    '..kooooooo......',
    '..koooyoooo.....',
    '..koooooo.......',
    '..koooooo.......',
    '..k.............',
    '..k.............',
    '..k.............',
    '..k.............',
    '..k.............',
    '.kkk............',
    '.dkd............',
    '................',
    '................',
  ],
  // 🛡️ Badge — a generic shield crest, for club/competition placeholders
  badge: [
    '................',
    '...kkkkkkkkk....',
    '..kbbbbbbbbbk...',
    '..kbbbwwwbbbk...',
    '..kbbwwyywbbk...',
    '..kbbwwyywbbk...',
    '..kbbbwwwbbbk...',
    '..kbbbbbbbbbk...',
    '...kbbbbbbbk....',
    '....kbbbbbk.....',
    '.....kbbbk......',
    '......kbk.......',
    '.......k........',
    '................',
    '................',
    '................',
  ],
  // 👑 Crown — the "Royalty" bloodline emblem, for dynasty / legend moments
  // 🌿 Laurel wreath — a champion's laurel, for legend/hall-of-fame moments
  laurel: [
    '................',
    '.g............g.',
    '.gg....yy....gg.',
    '..gG...yy...Gg..',
    '..gGg.....gGg...',
    '...gGg...gGg....',
    '...gGGg.gGGg....',
    '....gGgggGg.....',
    '....gGGGGGg.....',
    '.....ggggg......',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // 🏰 Royal banner — a hanging dynasty pennant, for succession / bloodline chapter breaks
  banner: [
    '................',
    '..kkkkkkkkkkkk..',
    '..uuuuuuuuuuuu..',
    '..uyyyyyyyyyyu..',
    '..uyuuuuuuuuyu..',
    '..uyuuwwwwuuyu..',
    '..uyuuwyywuuyu..',
    '..uyuuwwwwuuyu..',
    '..uyuuuuuuuuyu..',
    '..uyyyyyyyyyyu..',
    '..uuuuuuuuuuuu..',
    '..uuu......uuu..',
    '..uu........uu..',
    '...u........u...',
    '................',
    '................',
  ],
  // 🖋️ Royal seal — a wax seal on a decree, for contract / legacy-milestone moments
  seal: [
    '................',
    '................',
    '....rrrrrrr.....',
    '...rrrrrrrrr....',
    '..rrryyyyyrrr...',
    '..rryyyyyyyrr...',
    '..rryyywyyyrr...',
    '..rryyyyyyyrr...',
    '..rrryyyyyrrr...',
    '...rrrrrrrrr....',
    '....rrr.rrr.....',
    '.....rr.rr......',
    '................',
    '................',
    '................',
    '................',
  ],
  // 🎗️ Captain's armband — striped cuff, for the captaincy pick / squad leadership screens
  armband: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kyyyyyykkyyyyk.',
    '.kyyyyyyykkyyyk.',
    '.kyyyyyyyykkyyk.',
    '.kyyyyyyyyykkyk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // 📜 Contract scroll — for signing / renewal moments
  contract: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.ks....rr....sk.',
    '.kkkkkkrrkkkkkk.',
    '.ksSSSSyySSSSsk.',
    '.ksSSSSyySSSSsk.',
    '.kkkkkkrrkkkkkk.',
    '.ks....rr....sk.',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // 💼 Agent's briefcase — for the agent-selection screen
  briefcase: [
    '................',
    '................',
    '......kkkk......',
    '......k..k......',
    '......k..k......',
    '..kkkkkkkkkkkk..',
    '..knnnnnnnnnnk..',
    '..knnnnyynnnnk..',
    '..kkkkkyykkkkk..',
    '..knnnnyynnnnk..',
    '..knnnnnnnnnnk..',
    '..knnnnnnnnnnk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
  ],
  // ⭐ Star — for ratings / scout star-grades, sits alongside the ★ text glyph already used elsewhere
  star: [
    '................',
    '................',
    '................',
    '.......yy.......',
    '.......yy.......',
    '......yyyy......',
    '..yyyyyyyyyyyy..',
    '...yyyyyyyyyy...',
    '....yyyyyyyy....',
    '.....yyyyyy.....',
    '.....yyyyyy.....',
    '.....yyyyyy.....',
    '....yy....yy....',
    '....y......y....',
    '................',
    '................',
  ],
  // 📅 Calendar — a season/matchday marker with a highlighted "today" cell
  calendar: [
    '................',
    '.....k....k.....',
    '.....k....k.....',
    '..kkkkkkkkkkkk..',
    '..krrrrrrrrrrk..',
    '..krrrrrrrrrrk..',
    '..kwwwwSwwSwwk..',
    '..kwwwwSwwSwwk..',
    '..kSSSSSSSSSSk..',
    '..kwwwwSwwSwwk..',
    '..kwwwwSyySwwk..',
    '..kwwwwSyySwwk..',
    '..kwwwwSwwSwwk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  crown: [
    '................',
    '..y.y.y.y.y.y...',
    '..yyyyyyyyyyy...',
    '.yyyyyyyyyyyyy..',
    '.yllllllllllly..',
    '.ylylylylylyly..',
    '.yllllllllllly..',
    '.yyyyyyyyyyyyy..',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  // 🪙 Coin — a single earned coin, for the closed coin economy
  coin: [
    '................',
    '................',
    '....kkkkkk......',
    '...kyyyyyyk.....',
    '..kyyllllyyk....',
    '..kylyllylyk....',
    '..kyllwwllyk....',
    '..kylwwwwlyk....',
    '..kyllwwllyk....',
    '..kylyllylyk....',
    '..kyyllllyyk....',
    '...kyyyyyyk.....',
    '....kkkkkk......',
    '................',
    '................',
    '................',
  ],
  // 🗣️ Referee whistle — silver bowl + mouthpiece + lanyard loop
  whistle: [
    '................',
    '................',
    '....kkkkk.......',
    '...kSSSSSk......',
    '..kSSSSSSSk.....',
    '..kSSkkkSSk.....',
    '..kSSSSSSSk.....',
    '...kSSSSSk......',
    '....kkkkk.......',
    '.......k........',
    '.......k........',
    '......k.k.......',
    '................',
    '................',
    '................',
    '................',
  ],
  // 👟 Football boot
  boot: [
    '................',
    '................',
    '...kkk..........',
    '..kwwwk.........',
    '..kwwwk.........',
    '..kwwwkkkkk.....',
    '..kwwwwwwwwkk...',
    '..kwwwwwwwwwwk..',
    '..kwwwwwwwwwwwk.',
    '..kkkkkkkkkkkkk.',
    '...k.k.k.k.k.k..',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
};

/** Returns an inline pixel-art SVG for `name`, or '' if unknown. */
export function sprite(name: string): string {
  const g = SPRITES[name];
  return g ? px(g) : '';
}
