// DEMAND — see shared/src/prompts/README for the authoring rules.
// What the moment ASKS of him. Kept setting-neutral so it reads sensibly whether the
// situation is a training drill, a dressing-room moment or a cup tie (a drill is not
// "the kind of moment careers are remembered for" — that mismatch kills the immersion).
// The per-tag "what this moment is asking for" line — one of three components of EVERY scenario prompt,
// so it is read 120 times a career. At six lines a tag a single career nearly exhausted it, and by the
// fifth heir of a dynasty 95% of prompt sentences were text an earlier generation had already read.
// Twelve each. (PT-404)
export const DEMAND: Record<string, string[]> = {
  aggression: ['They want to see some steel from him.', 'It’s about winning the physical battle.', 'He needs to show he won’t be pushed around.', 'It calls for a bit of nastiness, in the right way.', 'This is a moment to plant a flag and not budge.', 'They need to see he can dish it out as well as take it.', 'Somebody has to put a foot in here.', 'It wants an edge, and he has to find one.', 'The game needs somebody to stop being polite.', 'They want to see whether he can be the one nobody fancies.', 'It is a question of appetite as much as ability.', 'The moment belongs to whoever wants it more.'],
  creativity: ['They’re looking for a spark of invention.', 'It wants imagination — something unexpected.', 'He needs a solution no one else can see.', 'It calls for a moment nobody saw coming.', 'The situation is crying out for a flash of ingenuity.', 'They want proof he can think a half-step ahead of everyone else.', 'The obvious ball will not do here.', 'It wants the answer nobody has thought of yet.', 'Everything sensible has already been tried.', 'They are waiting for him to see something.', 'It needs an idea more than it needs a technique.', 'The picture is there for anyone who can find it.'],
  composure: ['It asks for a cool head under pressure.', 'The test is whether he can keep calm.', 'He needs to slow it down and stay in control.', 'It’s about not letting the moment get too big for him.', 'They want to see the pulse stay steady when it matters.', 'The test is simple: can he trust himself under the heat?', 'The noise is the test, not the football.', 'It asks him to take the extra half-second.', 'Everyone around him is rushing; that is the trap.', 'It wants a still head in a loud place.', 'The panic is the opponent here.', 'He needs to look like he has done this before.'],
  teamwork: ['It’s about bringing others into the play.', 'They want to see him link it and share it.', 'It’s a test of how he lifts the players around him.', 'It calls for the unselfish option, not the flashy one.', 'They want to see him make someone else look good.', 'The moment rewards trust — giving it up and getting it back.', 'It is not his moment unless he makes it somebody else\'s.', 'The right pass is the boring one.', 'It wants him to be useful rather than brilliant.', 'Somebody has to do the work that never gets clipped.', 'It rewards the run nobody will notice.', 'The team need him more than the highlights do.'],
  leadership: ['They want him to take charge of this.', 'It’s a chance to show he can lead.', 'He needs to grab it and drag the rest with him.', 'It calls for someone to stand up and be counted.', 'They need a voice, and it might as well be his.', 'This is the kind of moment that either makes a captain or exposes one.', 'Heads are dropping and somebody has to lift them.', 'It wants a voice more than a touch.', 'Ten people are waiting to be told what happens next.', 'Somebody has to take responsibility for this one.', 'The room needs a standard set, right now.', 'It is the kind of moment people remember who stepped up in.'],
  stamina: ['It’s a test of his engine.', 'It comes down to who keeps going longest.', 'They want to see him cover every blade of grass.', 'It’s about the effort nobody notices until it’s missing.', 'The legs are tired — the question is whether his are, too.', 'They want to see if there’s anything left in the tank.', 'It comes down to who is still running at the end.', 'The legs have gone; the question is what is left after that.', 'It wants him to make the run for the fourth time.', 'Everyone is tired — that is the whole point of it.', 'There is no clever way through this one, only work.', 'It asks how much he has actually got.'],
  flair: ['It’s a chance to show his imagination.', 'It’s the moment to try something bold.', 'They want to see a bit of magic from him.', 'It calls for something the coaching manual doesn’t cover.', 'This is the moment to back himself and go for broke.', 'They want to see him make it look easy when it isn’t.', 'It is a moment that will either look wonderful or very stupid.', 'The safe option is available, and dull.', 'It wants him to trust the thing he can do.', 'Somebody has to try something here.', 'The crowd can feel one coming.', 'It is the sort of moment careers get remembered for.'],
  keeping: ['It’s down to him to keep them out.', 'It’s a test of his hands and his nerve.', 'They need him to be the wall behind them.', 'It calls for a shot-stopper’s stubbornness.', 'The moment needs a clean take and no fuss.', 'They want to see him command the space that’s his.', 'Everything now depends on the man in the different shirt.', 'It asks him to be certain when nobody else is.', 'The box is his and he has to say so.', 'One touch decides this, and it is his.', 'It wants safe hands and a loud voice.', 'There is nobody behind him to fix it.'],
};
