// SETTINGS — see shared/src/prompts/README for the authoring rules.
// settings by chapter (age band) — a young park pitch grows into a stadium
export const SETTINGS: Record<string, string[]> = {
  Grassroots: ['on a muddy park pitch', 'under grey skies at the local rec', 'with a scatter of parents watching from the touchline', 'on a frostbitten Sunday-league morning', 'between two sets of jumpers-for-goalposts', 'as a dog wandered across the far corner', 'on a pitch more mud than grass', 'with the ball skidding off the wet surface', 'as steam rose off the players in the cold', 'past a car park doubling as the changing rooms', 'with a lone parent-referee keeping order'],
  Academy: ["on the academy's back pitches", 'in a youth-team fixture', 'under the academy floodlights', 'in a coaches-only trial game', 'on the manicured academy turf', 'in front of the youth-development staff', 'on the pristine academy 3G', 'in a behind-closed-doors development game', 'with the age-group coaches lining the touchline', 'in a possession drill that spilled into a real match', 'under the watchful eye of the head of youth'],
  Scholar: ['in a youth-league fixture', 'in front of the scholarship staff', 'with his YTS place on the line', 'on a bitter midweek youth night', 'in a trial game against older lads', 'with the academy director watching closely', 'in a rain-lashed youth-league tie', 'with his scholarship review looming', 'against a physical, streetwise older side', 'on the academy floodlit training pitch', 'with the release list at the back of every mind'],
  'Youth Team': ['in a reserve-team match', 'with a couple of scouts jotting notes', 'in front of a smattering of regulars', 'on a wind-whipped afternoon', 'in a tight, chippy reserve derby', 'with a first-team coach watching from the tunnel', 'in a stop-start reserve fixture', 'before a handful in the main stand', "with the gaffer up in the directors' box", 'on a heavy, energy-sapping surface', 'in a niggly, foul-strewn reserve match'],
  Breakthrough: ['in front of a proper crowd now', 'with the first-team staff watching on', 'as the terraces found their voice', 'under real floodlights, real pressure', 'with the home end starting to sing his name', 'on a raucous midweek night', 'with his name on a few lips in the crowd', 'as the atmosphere crackled', 'in front of a watching, hopeful home end', 'with the step up written all over the occasion', 'under lights and rising expectation'],
  'First Team': ['as a first-team regular now', 'with the shirt his to lose', 'in front of a demanding home crowd', 'with the pressure of a starting spot', 'under the weight of real expectation', 'on a proper league Saturday', 'with the number on his back earned', 'in front of a crowd that expects', 'on a tense, must-not-lose afternoon', "with the season's rhythm in full swing", 'under the steady glare of the regulars'],
  Establishing: ['before a full, expectant stand', 'with cameras tracking his every touch', 'in the thick of a proper contest', 'with a lot of eyes on him', 'as a sell-out crowd leaned in', 'with the pundits watching for a reason to doubt him', 'with the whole ground tuned to him', 'as the neutrals watched to be convinced', 'in a fixture the league had circled', 'with reputations on the line', 'before a stand that had come to see him'],
};
