// board authoring pack 1. One author owns this file. Keys must match the bank keys in shared/src/board.ts.
import type { Bank } from '../prompts/merge.js';
export const BOARD_EXTRA_1: Bank = {
  delighted: [
    `The board's review reads like a thank-you letter with a budget attached.`,
    `Upstairs, the mood is close to giddy. Nobody up there is asking difficult questions.`,
    `The chairman has stopped talking about targets and started talking about ambitions.`,
    `A glowing appraisal from the directors — the sort a manager should photograph and keep.`,
    `The board describe the season as a benchmark, and they mean it as the highest compliment.`,
    `Whatever was promised at the start, the board agree it has been comfortably surpassed.`,
    `The directors have quietly begun using the word "project" instead of "situation".`,
    `A warm end-of-season meeting. The only pressure in the room is the pressure to accept praise.`,
    `The board are talking about building on this rather than recovering from anything.`,
    `Upstairs they are already discussing what the club could look like in three years.`,
    `The chairman's summary runs to two sentences, both of them complimentary.`,
    `A boardroom that has entirely run out of things to worry about, at least for now.`,
    `The directors describe the manager's work as the best value the club has had in years.`,
    `Congratulations from every corner of the boardroom, and one or two from outside it.`,
    `The board's only concern this season is how to keep hold of the manager who delivered it.`,
    `A season that has changed how the directors talk about the club in public.`,
    `The board have gone from cautious to evangelical in the space of one campaign.`,
    `Upstairs they are describing this as the season the club stopped apologising for itself.`,
    `The directors have set aside their usual caution and are simply enjoying themselves.`,
    `A boardroom review that spends more time on thanks than on targets.`,
    `The chairman is telling anyone within earshot that he knew it all along. He didn't.`,
    `The board consider the season an unqualified success and see no reason to hedge about it.`,
    `Real warmth from the directors — the kind that survives a bad start next year.`,
    `The board have banked enough goodwill this season to see the manager through a rough patch.`,
    `A season the boardroom will use as a reference point for a very long time.`,
    `Upstairs, the mood is one of delighted disbelief that it has gone this well.`,
    `The directors talk about the manager as an asset now, which is corporate for beloved.`,
    `A short board meeting. There was very little to discuss and a great deal to celebrate.`,
    `The board's assessment is that everything asked for was delivered, and then some.`,
    `The chairman opened the review by shaking the manager's hand. That never happens.`,
    `Directors who spent last summer nervous have spent this one boasting.`,
    `The boardroom verdict is emphatic: this is exactly what the club hired the manager to do.`,
    `A season that has moved the club's own expectations of itself upward, permanently.`,
    `The board are delighted, and unusually willing to say so where people can hear it.`,
    `Upstairs the talk is of consolidation, but nobody in the room really means it.`,
    `The directors' only criticism is that they will now have to find a harder target.`,
    `A glowing verdict, delivered with the rare enthusiasm of people who feel vindicated.`,
    `The board have described this as a season that repaid every penny of their patience.`,
    `Nothing but approval upstairs. The manager could ask for most things and get them.`,
    `The chairman has been fielding congratulations all week and enjoying every one of them.`,
    `A boardroom in genuinely high spirits — a rare and valuable thing at any club.`,
    `The directors regard the campaign as proof that the long-term plan was the right one.`,
    `Upstairs, the season is already being described as a turning point in the club's history.`,
    `The board's summary is brief, glowing, and entirely without conditions attached.`,
    `A verdict from the boardroom that reads more like a testimonial than an appraisal.`,
    `The directors have agreed, unanimously, that the manager has exceeded every measure set.`,
    `A season so good the board have quietly stopped comparing it to previous ones.`,
  ],
  pleased: [
    `The board's verdict is positive without being effusive — solid progress, properly noted.`,
    `Upstairs they are satisfied. Not thrilled, but genuinely, measurably satisfied.`,
    `The directors regard the season as a step in the right direction and have said so.`,
    `A constructive end-of-season review. The good outweighed the bad, and everyone agrees.`,
    `The board are pleased, and pleased boards are quiet boards. That is worth something.`,
    `The chairman's summary is warm, brief and encouraging. There is no sting in the tail.`,
    `Upstairs, the sense is of a club moving forward at roughly the pace it hoped for.`,
    `The directors note real improvement and see no reason to interfere with it.`,
    `A season the board consider a fair return on what they put in.`,
    `Approval from the boardroom, with the mild suggestion that there is more to come.`,
    `The board describe the campaign as encouraging — their favourite word for progress.`,
    `Nothing but supportive noises upstairs, and a clear willingness to keep backing the plan.`,
    `The directors are content. The manager has done what was asked, without much drama.`,
    `A positive review, delivered in the boardroom's usual understated register.`,
    `The board see a squad heading somewhere and a manager who knows where that is.`,
    `Upstairs the mood is one of quiet confidence rather than celebration.`,
    `The chairman uses the phrase "good foundations" more than once, and means it kindly.`,
    `A satisfied boardroom. No fireworks, no demands, no awkward silences.`,
    `The directors have noted the improvement and, more importantly, noted why it happened.`,
    `The board's verdict: better than last time, and heading the right way.`,
    `A short meeting with warm handshakes at the end of it.`,
    `Upstairs there is real appreciation for how the difficult moments were handled.`,
    `The directors are pleased with the direction and content to let it continue undisturbed.`,
    `A boardroom that sees progress and has decided not to get in the way of it.`,
    `The board consider the season a success within the terms they set. That matters.`,
    `Approval, expressed the way boards express it: with a nod and a slightly larger budget.`,
    `The chairman describes the campaign as pleasing, which from him is close to rapture.`,
    `Upstairs the season is filed under "progress" and nobody feels the need to argue.`,
    `The directors are satisfied that the club is better run than it was a year ago.`,
    `A warm but measured review — the board are pleased and slightly wary of saying so too loudly.`,
    `The board note the manager delivered on the brief, and that counts for a lot upstairs.`,
    `Positive noises all round, with the gentle implication that the bar rises from here.`,
    `The directors express their thanks and mean roughly eighty per cent of it.`,
    `A pleased boardroom is a manager's best working condition, and this is one.`,
    `Upstairs they talk about momentum and about not squandering it. Both fairly.`,
    `The board's assessment is that the club has taken a genuine step forward this season.`,
    `A constructive, forward-looking review with no lingering complaints attached.`,
    `The directors have quietly extended their patience, which is how boards say thank you.`,
    `The chairman notes the improvement in the club's standing and credits the dugout for it.`,
    `A boardroom content to keep doing what it has been doing, which is backing the manager.`,
    `The board see steady progress and have chosen to reward it with silence and support.`,
    `Upstairs, the verdict is favourable. Not a triumph, but comfortably on the right side.`,
    `The directors describe the season as solid, which in that room is high praise.`,
    `A review that finds far more to commend than to correct.`,
    `The board are pleased, and have said as much in writing, which they rarely bother to do.`,
    `Encouraging feedback from upstairs, with a clear expectation of more next time.`,
    `The chairman closes the meeting by saying the club is in better hands than it was.`,
  ],
  patient: [
    `The board's verdict is neutral — nothing to celebrate, nothing to answer for.`,
    `Upstairs the mood is watchful. Not hostile, not warm. Simply watchful.`,
    `The directors have logged the season as roughly what they expected and moved on.`,
    `A short, unremarkable board meeting. The manager was neither praised nor challenged.`,
    `The board are waiting to see what comes next before forming a stronger opinion.`,
    `Upstairs they describe the season as "as anticipated", which is neither compliment nor complaint.`,
    `The chairman's summary is polite, brief and entirely non-committal.`,
    `A boardroom keeping its powder dry. The verdict will come next season.`,
    `The directors see a club standing still, and have decided that is acceptable for now.`,
    `No strong feelings upstairs — the season landed exactly where it was projected to.`,
    `The board consider the campaign neither a success nor a failure, and say so plainly.`,
    `A holding pattern from the boardroom. They want to see the next step before judging.`,
    `The directors express support, and phrase it in a way that leaves themselves room.`,
    `Upstairs the season is described as "a base to build on", which is code for adequate.`,
    `The board have no complaints and no compliments. That is the whole verdict.`,
    `A meeting notable for how little anyone felt strongly about anything.`,
    `The chairman says the club is where it should be and leaves it at that.`,
    `The directors are giving the plan time. Their patience is real but not unlimited.`,
    `A boardroom that has decided to reserve judgement for another twelve months.`,
    `Upstairs the tone is fair-minded: a season without disasters and without breakthroughs.`,
    `The board note the club met its baseline expectations. Nobody sounds excited about it.`,
    `An even-handed review with one eye firmly on what happens next.`,
    `The directors want to see evidence of a step up, but they are not demanding it yet.`,
    `The board's position is best described as supportive neutrality.`,
    `Upstairs, nobody is worried and nobody is impressed. It is an unusual equilibrium.`,
    `A brief appraisal that could be summarised as: carry on, and show us more.`,
    `The chairman describes the season as steady, and steady is not a word he uses fondly.`,
    `The directors accept the season for what it was and are curious about the sequel.`,
    `A boardroom with its arms folded — not in anger, just in wait.`,
    `The board have banked no goodwill this season, and spent none either.`,
    `Upstairs the season is treated as a data point rather than an achievement.`,
    `A neutral verdict, delivered without warmth or edge.`,
    `The directors say the right things without quite committing to any of them.`,
    `The board are content to let the project run, while noting they are watching it run.`,
    `A quiet meeting. Nobody had a speech prepared, in either direction.`,
    `The chairman's only real request is that next season looks different from this one.`,
    `The board see a club treading water and have decided treading water is survivable.`,
    `Upstairs, the verdict is: nothing broken, nothing built. Try again.`,
    `A measured, unemotional review that gives the manager neither cover nor a warning.`,
    `The directors describe the season as acceptable, which is the flattest word available.`,
    `The board's patience remains intact, and they would like the manager to notice that it's finite.`,
    `A neutral appraisal from a boardroom that clearly expected roughly this all along.`,
    `Upstairs they are neither buying nor selling. They are simply holding.`,
    `The board acknowledge a season of consolidation and hope the next one has more in it.`,
    `A verdict without heat. The directors have seen worse and they have seen better.`,
    `The chairman thanks the manager for a stable year, and stability is genuinely valued here.`,
  ],
  concerned: [
    `The board's review contains more questions than conclusions, and none of them are friendly.`,
    `Upstairs, the season is being described as a setback rather than a wobble.`,
    `The directors have started asking what the plan is, which is never a good sign.`,
    `A cooler boardroom this year. The support is still there, but it has conditions now.`,
    `The board note the season fell short and would like to understand precisely why.`,
    `Concern upstairs — expressed politely, but expressed clearly and more than once.`,
    `The chairman's summary is careful, which means he chose every word to avoid a headline.`,
    `A meeting where the manager did most of the talking and the directors did most of the listening.`,
    `The board want to see a response, and they have made that request explicit.`,
    `Upstairs the mood has shifted from encouragement to scrutiny.`,
    `The directors describe the campaign as disappointing, and use the word deliberately.`,
    `A boardroom that has begun keeping notes.`,
    `The board have asked for a plan in writing, which is their way of raising an eyebrow.`,
    `Support remains, but the warmth has gone out of it.`,
    `The directors are unconvinced by the explanations offered so far.`,
    `Upstairs there is real unease about the direction, though nobody has said so publicly.`,
    `The board's verdict is that the season fell below what the club is capable of.`,
    `A frank review. The manager was asked several things he could not comfortably answer.`,
    `The chairman uses the phrase "we expected more" once, and it hangs in the room.`,
    `The board are not panicking, but they are no longer relaxed either.`,
    `Upstairs the tone is businesslike and noticeably less friendly than it was.`,
    `The directors want improvement and have attached a rough timescale to that wish.`,
    `A boardroom review that reads as a warning dressed as feedback.`,
    `The board note that patience has been extended once already, without saying it aloud.`,
    `Concern about the squad, concern about the results, concern about the trajectory.`,
    `A meeting with fewer pleasantries at the start and none at all at the end.`,
    `The directors have asked for a full account of where the season went wrong.`,
    `Upstairs they are worried, and the worry is starting to show in how they speak.`,
    `The board's assessment is that the club is drifting, and drifting costs money.`,
    `A pointed review. Nothing was said aggressively, but nothing was said softly either.`,
    `The chairman asks a direct question about next season and waits for a direct answer.`,
    `The directors are querying decisions they previously waved through without comment.`,
    `Upstairs the goodwill built up in better years is being drawn down noticeably.`,
    `A boardroom that would like to be reassured, and has not been.`,
    `The board describe the season as below expectation and expect that to be addressed.`,
    `Unease is the word. Not anger, not yet, but a clear and growing unease.`,
    `The directors have started talking about the season in the past tense with some relief.`,
    `A review conducted with the polite chill of people preparing to be less polite.`,
    `The board want to see a different second half to the story, and soon.`,
    `Upstairs, the phrase "we need to see progress" gets used three times in twenty minutes.`,
    `The chairman remains supportive in public and noticeably less so behind the door.`,
    `The directors accept there were mitigating factors. They do not accept all of them.`,
    `A meeting where the manager's plans were examined rather than approved.`,
    `The board's concern is real and has now been formally minuted.`,
    `Upstairs they are asking whether the current approach can deliver what was promised.`,
    `A cool, forensic appraisal from a boardroom that has stopped taking things on trust.`,
  ],
  restless: [
    `The boardroom has run out of patience with explanations and would like some results.`,
    `Upstairs, the conversation has moved from "why" to "when", and that is a bad sign.`,
    `The directors are openly unhappy, and the effort to hide it has been abandoned.`,
    `A tense review. Several long silences, and none of them comfortable.`,
    `The board describe the season as unacceptable, and nobody in the room contradicts them.`,
    `Restlessness upstairs — the kind that makes every corridor conversation feel loaded.`,
    `The chairman's tone has changed. It is shorter, flatter and noticeably colder.`,
    `The directors want to know what will be different, and they want specifics.`,
    `A boardroom that has stopped offering reassurance and started asking for guarantees.`,
    `The board have made it clear that another season like this would be a serious problem.`,
    `Upstairs the mood is impatient, and the impatience is no longer being managed carefully.`,
    `A review that felt less like a discussion and more like an examination under lights.`,
    `The directors question the squad, the approach and the results, in that order.`,
    `The board's verdict is blunt: the club has gone backwards and that must stop.`,
    `Whispers upstairs have become conversations, and the conversations are not supportive.`,
    `A hard meeting. The manager left it with a much shorter list of allies.`,
    `The chairman states plainly that the club expected considerably better than this.`,
    `The directors have begun discussing contingencies, though they say they haven't.`,
    `Upstairs, the goodwill is gone and what remains is a set of demands.`,
    `A boardroom that has decided the benefit of the doubt has been exhausted.`,
    `The board's patience is visibly, measurably thin. Everyone in the building can feel it.`,
    `A meeting conducted with the frosty courtesy of people who have already made up their minds.`,
    `The directors want a plan, a timescale, and evidence. They have said so twice.`,
    `Upstairs the season is being described as a failure without any qualification.`,
    `The board note the gap between promise and delivery, and note it repeatedly.`,
    `A sharp, uncomfortable review with very little in the way of mitigation accepted.`,
    `The chairman does not shake hands at the end of the meeting, and everyone notices.`,
    `The directors are restless, vocal, and no longer inclined to be diplomatic about it.`,
    `The board demand a response and have made clear it must come quickly.`,
    `A boardroom where the manager was interrupted more than once, which is new.`,
    `Upstairs, the questions are now about competence rather than circumstance.`,
    `The directors express serious dissatisfaction and put it on the record.`,
    `A grim review. Nobody pretended the season was anything other than what it was.`,
    `The board have started asking about the squad's value rather than its potential.`,
    `The chairman's summary is four words long and none of them are encouraging.`,
    `Upstairs they want change, and they are not especially fussy about what kind.`,
    `A restless boardroom is a dangerous place, and this one is thoroughly restless.`,
    `The directors have made their expectations for next season uncomfortably specific.`,
    `The board's message is that the club cannot afford another year like this one.`,
    `A meeting with a hard edge to it from the first minute to the last.`,
    `Upstairs, the manager's judgement is being questioned in a way it never was before.`,
    `The board are unhappy, unimpressed, and no longer bothering to soften either.`,
    `A review where every achievement was acknowledged briefly and every failure at length.`,
    `The directors want to see fight, and they have not seen enough of it.`,
    `The boardroom has gone from supportive to sceptical in the space of one campaign.`,
    `A cold, difficult session that will be remembered by everyone who sat through it.`,
  ],
  furious: [
    `The board are incandescent, and the meeting was conducted almost entirely at volume.`,
    `Upstairs the anger is total. Nothing about the season is being defended by anyone.`,
    `The chairman opened the review with a sentence that will be repeated for years.`,
    `A brutal boardroom. Every mitigating factor was raised and every one was dismissed.`,
    `The directors describe the season as a catastrophe and refuse to soften the word.`,
    `Fury upstairs — the kind that turns corridors quiet when the manager walks down them.`,
    `The board's verdict is scorching. There is no praise in it anywhere.`,
    `A meeting so hostile that the minutes will be written very carefully indeed.`,
    `The directors demand answers, and none of the ones offered came close to satisfying them.`,
    `Upstairs, the season is being described as the worst in living memory at this club.`,
    `The board have lost confidence in almost every part of the operation.`,
    `A savaging. There is no other word for what happened in that room.`,
    `The chairman says the club has been embarrassed, and says it more than once.`,
    `The directors are furious about the results, the performances and the excuses.`,
    `A review that was less an appraisal than a reckoning.`,
    `Upstairs the mood is poisonous, and it will take a great deal more than words to fix.`,
    `The board make clear that the club's standing has been damaged and somebody must answer.`,
    `Real anger in the boardroom — the kind that gets remembered long after the season does.`,
    `The directors reject every explanation put in front of them, one after another.`,
    `A furious session. The manager barely got a sentence out uninterrupted.`,
    `The board's assessment could be printed on a single line and it would still sting.`,
    `Upstairs they are asking how this was allowed to happen, and asking it very loudly.`,
    `The chairman's fury is undisguised and directed squarely at the dugout.`,
    `A meeting nobody in the building will forget, for all the wrong reasons.`,
    `The directors say the season has cost the club dearly, in money and in reputation.`,
    `Anger, disbelief and a total absence of sympathy. That is the boardroom's verdict.`,
    `The board describe the campaign in terms that would not survive being printed.`,
    `Upstairs, the manager has no defenders left. Not one.`,
    `A blistering review with no attempt at balance and no interest in context.`,
    `The directors demand a complete overhaul and expect it to start immediately.`,
    `The board are livid, and the next press conference will be picked over word by word.`,
    `A meeting that ran twice as long as planned and got worse with every minute.`,
    `The chairman calls the season indefensible, and nobody around the table disagrees.`,
    `Upstairs the anger has hardened into something colder and considerably more dangerous.`,
    `The board make clear that the situation cannot continue as it is. That is all they say.`,
    `A furious boardroom, a shattered season, and a manager with everything left to prove.`,
    `The directors have withdrawn every assumption of good faith they once extended.`,
    `A verdict delivered through gritted teeth by people who feel personally let down.`,
    `Upstairs they are talking about damage limitation, which tells you everything.`,
    `The board's fury is matched only by their bewilderment at how it came to this.`,
    `A hostile, exhausting session in which nothing at all was resolved.`,
    `The chairman says the club deserves better, and lets the silence do the rest.`,
    `The directors are beyond concerned and beyond restless. This is something else entirely.`,
    `A review that offered no route back, only a list of failures.`,
    `The board are as angry as this club's boardroom has ever been. That is the whole message.`,
    `Upstairs, the only thing keeping the temperature down is that nobody trusts themselves to speak.`,
  ],
};
