// prestige authoring pack 1. One author owns this file. Keys must match the bank keys in shared/src/prestige.ts.
import type { Bank } from '../prompts/merge.js';
export const PRESTIGE_EXTRA_1: Bank = {
  'Rookie Gaffer': [
    "A name on a team sheet and a whistle in the pocket. It starts here.",
    "Nobody knows who you are yet. That is the point of a beginning.",
    "The first badge on the tracksuit. Everything after this is earned.",
    "A dugout, a clipboard, and eleven people who have to listen to you. Start there.",
    "Not a reputation yet. A starting position.",
    "The first season is mostly about finding out what you do not know.",
    "A rookie gaffer, and the players are still working out whether to take you seriously.",
    "Every manager who ever mattered stood exactly here once, with exactly this little behind them.",
    "The name means nothing outside the building. Give it time.",
    "First job, first team talk, first long drive home wondering about a substitution.",
    "There is no track record to hide behind. Only the next match.",
    "A career in the dugout, day one. The rest is unwritten and unpromised.",
    "The tracksuit is new and the ideas are borrowed. Both of those change.",
    "A rookie in the trade, learning the difference between knowing football and managing footballers.",
    "Nobody in this game starts at the top. This is what the bottom looks like.",
    "The first rung. It does not look like much and every ladder has one.",
    "A gaffer, technically. The word will fit better in a few years.",
    "First appointment. The players will decide within a fortnight whether it was a good one.",
    "There is a long way between here and being talked about. The road only goes one way.",
    "A rookie boss with nothing on the CV but ambition and a coaching badge.",
    "The kitman knows more about this club than the manager does. That is normal at the start.",
    "Standing in a technical area for the first time is stranger than anyone tells you.",
    "The reputation is zero. That means it can only be built.",
    "A first job in management, and the phone does not ring with offers yet. It will or it will not.",
    "Nothing won, nothing lost, nothing proven. A clean sheet of paper.",
    "The first season teaches humility faster than any coaching course.",
    "A rookie gaffer, and the biggest lesson so far is how little of it is about tactics.",
    "New in the dugout, and every decision still feels like it might be the wrong one.",
    "A career begins. Most of them do not get far. This one has a chance.",
    "The first team talk was too long. They always are.",
    "A rookie, and the players are watching how the boss reacts to a bad result more than a good one.",
    "Start of the road. No medals, no headlines, no idea what is coming.",
    "The name goes on the door in tape rather than brass. That says it all.",
    "A first job, and every result feels like a verdict on a whole future.",
    "There is nothing here yet but a willingness to do the work. It is enough to start with.",
    "A rookie manager, and the ambition is currently much larger than the reputation.",
    "The dugout is the coldest place in the ground and the only place worth standing.",
    "First steps. Everybody who has ever lifted anything took these ones first.",
    "A new gaffer with a lot to prove and nobody yet asking him to prove it.",
    "The badge on the tracksuit is the club's, not yours. Earning it takes seasons.",
    "A rookie, and the first real lesson is that the job never actually stops.",
    "Nobody is writing about this appointment. That is the freedom of starting out.",
    "The beginning of a career in management, which is a strange and unreasonable thing to want.",
    "A first post, and the only currency available is honest work.",
    "The record is blank. That is not a weakness. It is a starting line."
  ],
  'Local Hero': [
    "People in the town have started recognising the face in the supermarket. That is new.",
    "The local paper has begun using the name in headlines without explaining who it belongs to.",
    "A reputation forming in these parts. Not far beyond them yet, but it is forming.",
    "Somebody in the club shop asked for an autograph. It was a small moment and it registered.",
    "Word is spreading locally. The results are doing the talking.",
    "The name means something within about twenty miles of the ground now.",
    "A local hero, which is a smaller thing than it sounds and a bigger one than it looks.",
    "The pub near the ground has an opinion about the team selection. That means people care.",
    "A reputation built on results in a place that noticed. That is how they all begin.",
    "Not famous. Known. There is a real difference and this is the good half of it.",
    "Local standing earned honestly, one weekend at a time.",
    "The supporters have started singing something. It is not very good and it is not going away.",
    "A name that carries weight in one town. Every big name started with one town.",
    "The barber knows the fixture list now. That is how you measure this sort of thing.",
    "A local hero. The players' families have stopped asking who the manager is.",
    "Recognition in the community, which for a football manager is the first real currency.",
    "The reputation has outgrown the training ground and reached the high street.",
    "People stop to talk about last Saturday. Most of them are wrong and all of them care.",
    "A local name, built on a run of results people actually turned up to watch.",
    "The club's supporters trust the man in the dugout now. That took longer than the wins did.",
    "A hero locally, which is worth more in this job than most people outside it understand.",
    "The name gets a mention on regional radio. Small stage, real progress.",
    "Something has been built here, and the town has noticed it being built.",
    "A local reputation, and the first tentative sense that this might actually be a career.",
    "The applause when the name is read out has changed in quality. Warmer.",
    "A manager the town has decided it likes. That is not nothing.",
    "Standing in the community, earned by turning up and getting it right often enough.",
    "The local hero tag arrives quietly, usually via somebody else saying it first.",
    "People who do not follow football have heard the name. That is the local test passed.",
    "A reputation that stops at the county boundary. For now.",
    "The name on the team sheet has started to reassure rather than worry.",
    "A local hero, and the pressure that comes with it has arrived at the same time.",
    "Word of mouth has done what no press release could. The town rates him.",
    "A manager with genuine local standing, and a growing sense that it could travel.",
    "The club is being talked about again, and the man in the dugout is the reason why.",
    "A reputation forming in these parts, and it is being formed the hard way.",
    "Locally, the name now carries an expectation. That is the price of the recognition.",
    "The supporters have started turning up early. That is the clearest compliment there is.",
    "A local hero, which means the criticism will be personal from now on too.",
    "People remember the results. That is all a reputation ever is.",
    "The name is known in the town, in the league, and by a couple of scouts. Progress.",
    "A local standing built without a single headline outside the region.",
    "Something is happening at this club, and the town has decided who to credit for it.",
    "The manager's name is on a homemade banner. That is a milestone in this trade.",
    "A local hero, and there is a long way to go, and that is exactly the right position to be in."
  ],
  'Promising Boss': [
    "The wider game has started paying attention, which is a mixed blessing.",
    "Other clubs have made discreet enquiries. Nothing formal. Nothing ignored either.",
    "A promising boss now, and promising is a word that comes with a clock attached.",
    "The name appears in national coverage without a description after it.",
    "People outside the region have opinions about the way this side plays.",
    "A reputation that has escaped the local paper and reached the trade properly.",
    "Being called promising is flattering, and it is also a bill that eventually comes due.",
    "The profile is growing, and with it the number of people waiting to be proved right.",
    "A manager other managers have started watching tape of. That is real progress.",
    "The phone rings more often now, and not all of it is about this club.",
    "A promising boss, and there is a genuine sense of a career gathering momentum.",
    "Agents have started returning calls within the hour. That is how you know.",
    "The style of play is being discussed by people who have never been to the ground.",
    "No longer a local name. A name, with a growing set of expectations attached.",
    "A promising manager, and the difficult part of any career is what comes after promising.",
    "The board have started worrying about losing him. That is a compliment of sorts.",
    "A reputation with reach now, and the next appointment matters more than the last one.",
    "The national press have run a piece. Short, but it ran.",
    "A boss with prospects, which is a lovely thing to be and an uncomfortable thing to stay.",
    "The wider footballing world is taking notice, and it does not take notice for long.",
    "A promising boss, and everything from here is about turning promise into evidence.",
    "The name comes up in conversations about jobs he has not applied for.",
    "A profile that has grown faster than the trophy cabinet. That gap has to close.",
    "Scouts and directors of football have the name in their notebooks now.",
    "Promising, and painfully aware that the word is temporary in both directions.",
    "The reputation travels further than the man does. That is a new experience.",
    "A boss with a growing name, and a growing awareness of how quickly names can shrink.",
    "The football is good enough that neutrals have started watching. That is the real test passed.",
    "A promising manager, and the interview requests have started arriving from national outlets.",
    "There is a buzz about this appointment now that did not exist eighteen months ago.",
    "A name being mentioned in circles that were closed a season ago.",
    "The wider game has decided this is somebody worth keeping an eye on.",
    "A promising boss, and the risk now is believing the write-ups.",
    "Directors at bigger clubs have started asking around about him. Quietly.",
    "The profile is growing, and the job is exactly the same as it was. That is worth remembering.",
    "A manager on the rise, and rising is the only part of this trade anybody enjoys.",
    "Promise noticed, and the pressure to convert it noticed even more keenly.",
    "The name is no longer a curiosity in the national game. It is a candidate.",
    "A promising boss, with everything still to prove and a real platform to prove it from.",
    "People have started describing his teams by his name rather than the club's.",
    "A growing reputation, and the sense that the next two seasons decide a great deal.",
    "Noticed by the wider game, which means the mistakes get noticed too now.",
    "A promising manager, and the honest assessment is that it is deserved and unfinished.",
    "The trade has an opinion on him now. Most of it is positive. All of it is provisional.",
    "A name with momentum behind it, and momentum is the hardest thing in football to keep."
  ],
  'Established Manager': [
    "Established now. Nobody prefaces the name with a qualifier any more.",
    "A manager with a body of work rather than a good season. That is the difference.",
    "The word promising has been quietly dropped. It has been replaced by something better.",
    "Respected in the trade, which takes longer and lasts longer than being talked about.",
    "An established name in the dugout. Boards ring rather than enquire now.",
    "Longevity has done what results alone could not. The reputation has weight.",
    "No longer a rising manager. Simply a manager, in the fullest sense of the word.",
    "The CV stands on its own. It does not need explaining to anybody.",
    "An established manager, and the difference is that the benefit of the doubt now exists.",
    "Players sign because of who is in the dugout. That is a genuine milestone.",
    "The name carries across the game now, and it carries a track record with it.",
    "Established. It is a less exciting word than promising and a far more valuable one.",
    "A manager whose methods are studied rather than questioned.",
    "The reputation has survived a bad run, which is the truest test of an established one.",
    "Respect rather than recognition. It is quieter and it is worth much more.",
    "An established name, and the phone calls now come from people who do not need to explain themselves.",
    "A body of work that speaks without needing an advocate.",
    "Established in the dugout, and the industry has stopped treating him as a prospect.",
    "The kind of manager clubs appoint to steady things rather than to gamble.",
    "A reputation built over years rather than months. Those are the ones that hold.",
    "Established, and there is a real satisfaction in a name that no longer needs defending.",
    "Other coaches ask for a coffee and a conversation. That is how the trade shows respect.",
    "A manager with standing, earned across more than one club and more than one crisis.",
    "The board consult rather than instruct now. That shift takes years.",
    "An established manager, and it means the next job is a choice rather than an offer.",
    "The reputation is durable, and durability is the rarest quality in this profession.",
    "Established. It sounds unglamorous and it is the foundation of everything that follows.",
    "A name that appears on shortlists without anybody having to argue for it.",
    "The trade has stopped asking whether he can do it and started asking where he will do it next.",
    "An established manager, and the mistakes are now forgiven rather than fatal.",
    "A career with proper substance behind it. Seasons, not moments.",
    "Established in the game, and the respect comes from peers rather than press.",
    "The name on a team sheet means something to opposition managers now.",
    "A manager of standing, which is a position that took a great many difficult afternoons to reach.",
    "Established, and the ambition has quietly shifted from being noticed to being remembered.",
    "The reputation is stable, and stability in this trade is an achievement in itself.",
    "A manager who no longer has to prove he belongs. Only what he can do next.",
    "Established, and there is a whole generation of players who have come through under him now.",
    "The name is a fixture in the game rather than a story in it.",
    "A body of work that would look respectable if the career stopped tomorrow. It will not.",
    "Established, and the first genuine sense that this will be a life's work rather than a job.",
    "The industry treats him as a known quantity, which is exactly what he set out to become.",
    "A manager with a reputation that arrives in the room before he does.",
    "Established in the trade, and the questions have changed from whether to how far.",
    "Respect, earned slowly, which is the only way it is ever worth having."
  ],
  'Seasoned Tactician': [
    "The tactics board is second nature now. So is knowing when to leave it alone.",
    "Years of decisions, filed away and available instantly. That is what seasoned means.",
    "A tactician now, and the reputation is for the thinking rather than the shouting.",
    "The game has been seen from every angle, and the angles have started to repeat.",
    "Seasoned. He has met most problems this sport can produce and solved a decent share of them.",
    "The in-game changes come earlier than they used to. Experience buys you those minutes.",
    "A seasoned operator, and the calm in the technical area is the most visible proof.",
    "Opposition managers set their side up specifically to counter him now. That is a compliment.",
    "The know-how has been earned the hard way, in games that went badly and were learned from.",
    "A tactician with genuine range. Nobody at this level plays only one way any more.",
    "Seasoned, and it shows most clearly in what he no longer does.",
    "The tactical reputation now precedes the man, which changes how every match is approached.",
    "Years of it. Good seasons, bad seasons, and a great deal of quiet study in between.",
    "A seasoned tactician, and the substitutions have started looking prophetic to people watching.",
    "The plan is always there. The skill is knowing which parts to abandon at half time.",
    "Coaching courses invite him to speak now. The trade recognises a thinker when it sees one.",
    "Seasoned, which means he has been wrong often enough to know how to be right.",
    "A manager whose sides are described as well drilled. He would say organised. Same thing.",
    "The tactical vocabulary of the game is something he now contributes to rather than borrows from.",
    "Seasoned know-how, sharpened by every season that did not go to plan.",
    "A tactician of standing, and the analysis department has started asking him for reading rather than the other way round.",
    "Experience has turned instinct into method and method back into instinct.",
    "Seasoned, and the biggest change is how little the unexpected unsettles him now.",
    "The dugout is a calmer place than it was. Not because he cares less, because he knows more.",
    "A seasoned tactician, and the pattern recognition is the thing younger coaches cannot fake.",
    "Every shape, every press, every awkward away trip. Seen it, filed it, adapted it.",
    "The reputation is for outthinking sides rather than outspending them.",
    "Seasoned, and it has cost a great many late nights to become so.",
    "A tactician whose teams are hard to play against, which is the highest technical praise available.",
    "Years of decisions have compounded into something that looks a lot like judgement.",
    "Seasoned, and the players trust the plan because it has been right before.",
    "The tactical reputation is real, and it was built on losses as much as on wins.",
    "A seasoned operator, comfortable in any dugout, against any shape, in any weather.",
    "The half-time adjustments have become the thing he is known for. Earned reputation.",
    "Seasoned, and there is a whole set of problems that no longer feel like problems.",
    "A tactician now, in the proper sense. The badge was always there; the knowledge took longer.",
    "Experience has made the difficult decisions faster rather than easier.",
    "Seasoned know-how, and it is the sort that cannot be bought, hired or hurried.",
    "A manager who reads a match the way a good defender reads a striker. Early.",
    "The tactical side of the job has become the enjoyable part rather than the anxious one.",
    "Seasoned, and the sharpest thing about him now is the questions he asks the staff.",
    "A tactician with real depth, forged in seasons where nothing came easily.",
    "The know-how is genuine, hard-won, and quietly formidable.",
    "Seasoned, and there is no situation left in this sport that he has not stood in before.",
    "Years in the trade have sharpened everything down to something that looks effortless. It is not."
  ],
  'Trophy Winner': [
    "Silverware. Everything before this was potential; this is the proof.",
    "A trophy winner. There is a hard line in this profession and it has now been crossed.",
    "Something in the cabinet with the name attached to it. Nobody can revise that away.",
    "The medals have started to accumulate, and so has the credibility that comes with them.",
    "A winner of things. In this trade that is the only category that ultimately matters.",
    "Trophy winner. Two words that change how every previous season gets described.",
    "The reputation now rests on something solid rather than something promised.",
    "Silverware on the shelf, and the arguments about whether he could win it are finished.",
    "A trophy in the record. The profession divides into those who have one and those who do not.",
    "Winning changes a manager's standing faster than a decade of good football.",
    "A trophy winner now, and the phrase gets used in every introduction from here on.",
    "The medal is small, heavy and permanent. Like the reputation it brings.",
    "Silverware, and the doubters have gone quiet in the way doubters always do.",
    "A winner. It is the simplest and most brutal measure this sport has, and it has been met.",
    "The cabinet has something in it. Everything else follows from that.",
    "Trophy winner, and there is a genuine hunger for the next one already.",
    "A manager who has lifted something. That is a permanent change in status.",
    "The medals are adding up, and so is the sense that this career has real substance.",
    "Silverware won, and the club's history now includes his name in a list that lasts.",
    "A trophy winner, and the difference in how boards treat him is immediate and obvious.",
    "Winning is a habit that has to start somewhere. It has started.",
    "The trophy is in a case and the reputation has moved up a floor.",
    "A winner of silverware, and the pressure has changed from proving it to repeating it.",
    "Something tangible at last. Football does not care much for anything else.",
    "Trophy winner. It was the whole point of the coaching badges and the long drives.",
    "The medal ceremony was the shortest and most important part of the whole season.",
    "A trophy in the cabinet, and every player who was there is bonded to it forever.",
    "Silverware, and the man in the dugout will be asked about it at every press conference for years.",
    "A winner. There is no argument left to have about whether he can do the job.",
    "The trophy validates every decision that looked wrong at the time.",
    "Trophy winner, and the celebration lasted about a day before the next target appeared.",
    "Silverware on the shelf. The rest of the profession has to acknowledge it whether it wants to or not.",
    "A manager with a trophy, which is a different animal to a manager with a philosophy.",
    "The cabinet is no longer empty, and the whole club feels different for it.",
    "Won something. In a career built on nearly, that word is everything.",
    "A trophy winner, and the appetite that got him here has not diminished at all.",
    "Silverware, and there is a photograph of the lift that will outlive everybody in it.",
    "The medals are starting to add up, and reputations are built on exactly that arithmetic.",
    "A winner now. The word attaches itself to the name permanently.",
    "Trophy winner, and it turns out the hardest part was believing it was possible.",
    "Something won, properly, in front of people who will never forget it.",
    "A trophy in the record book, and a career that now has a headline rather than a summary.",
    "Silverware. It changes what a manager can ask of a squad, and of a boardroom.",
    "A winner of things, and this profession has very little time for anything else.",
    "The trophy is won, and the only question anybody asks now is what comes after it."
  ],
  'Elite Manager': [
    "Elite company. The names mentioned alongside his are the ones he grew up watching.",
    "A manager at the very top of the trade, with the record to justify the position.",
    "Elite, and the job at this level is as much about handling expectation as handling players.",
    "The very best clubs consider him one of their own. That took an entire career.",
    "An elite manager, and the pressure at this altitude is unlike anything below it.",
    "The name belongs in any conversation about the best in the game. That is simply true now.",
    "Elite. A word thrown around cheaply everywhere except in this profession.",
    "At this level the margins are tiny and the consequences enormous. He has learned to live there.",
    "An elite manager, and the invitation to the top table came without anybody having to make a case.",
    "The reputation is continental now, and it was built one difficult season at a time.",
    "Elite company, and the strange thing about arriving is how ordinary the daily work still is.",
    "A manager whose appointment moves a club's whole trajectory. Very few reach that.",
    "The elite tier, where the trophies are expected rather than celebrated.",
    "An elite name, and the demands scale exactly with the standing.",
    "The best players in the game want to work with him. That is the clearest signal there is.",
    "Elite, and the honest reflection is that the job got harder, not easier, on the way up.",
    "A manager operating at the sport's top level, with a record that stands scrutiny anywhere.",
    "The name is a shorthand now. People say it and mean a style, a standard, a method.",
    "Elite company, and the peers at this level are the toughest audience in football.",
    "A manager of the very highest standing, and it has been earned rather than granted.",
    "The elite bracket, where a good season is the minimum and anything less is a crisis.",
    "An elite manager, and there are perhaps a dozen people on the planet doing this job at this level.",
    "The standing is such that a rejection from him is news in itself.",
    "Elite, and it is the sort of position that takes twenty years to reach and one season to lose.",
    "A name mentioned alongside the very best, and not as an outsider in that conversation.",
    "The elite level, and the interesting part is how much of it is still about the same simple things.",
    "An elite manager, and the record now includes things nobody expected when he started.",
    "The very top of the profession, reached the long way round, which is the only real way.",
    "Elite company, and every match is analysed by people whose whole job is analysing him.",
    "A manager at the summit of the club game, with a body of work that will not be dismissed.",
    "The elite tier, and the difference from the one below it is almost entirely psychological.",
    "An elite name in the dugout, and the club that has him knows exactly what it has.",
    "The best in the business consider him one of them. That is the whole ambition, met.",
    "Elite, and the ambition has quietly changed from competing to defining an era.",
    "A manager whose ideas are copied across the continent. That is elite by any measure.",
    "The standing is enormous, and the appetite for the next thing is somehow undiminished.",
    "Elite company, and the loneliness of the job increases with every step up. Nobody mentions that.",
    "A manager at the top of the sport, still doing the same drills he did in his first job.",
    "The elite level, and the record book at this point makes for genuinely remarkable reading.",
    "An elite manager, and he would be the first to name the twenty people who got him here.",
    "The very best in the game, and the standard he is judged against is now his own past.",
    "Elite, and the trophies are expected, which is a very peculiar kind of privilege.",
    "A name at the top of the profession, arrived at through decades rather than seasons.",
    "The elite bracket, where reputations are enormous and patience is not.",
    "An elite manager, and this is what a career looks like when almost everything goes right."
  ],
  'Footballing Legend': [
    "Legend. A word this sport uses carelessly and, in this case, correctly.",
    "The career is already a chapter in the game's history rather than a page in the trade press.",
    "A footballing legend, and the honours list reads like something from another era.",
    "Whatever comes next, the standing is permanent. That is what legend actually means.",
    "The name will be used to describe other managers, which is the truest sign of the status.",
    "A legend of the game, and there are supporters who have never known the club without him.",
    "The record is beyond argument. It has been for some time.",
    "Legend status, and the strange part is that the job still feels like a job most mornings.",
    "A career that will be studied. Not admired — studied.",
    "The name belongs to the sport now rather than to any one club.",
    "A footballing legend, and the honest reflection is that it happened one season at a time.",
    "There are stands and streets named after less. That will come.",
    "Legend, and the achievements are now so numerous they get summarised rather than listed.",
    "A career for the history books, and the books have already started including it.",
    "The status is permanent and the appetite, remarkably, is not diminished.",
    "A legend of the dugout, and the players he has developed are managing clubs of their own.",
    "The name carries across generations now. Grandfathers explain it to grandchildren.",
    "A footballing legend by any honest measure, and by a good few dishonest ones too.",
    "The career has outgrown the trade press and entered the general culture.",
    "Legend, and the man himself would give a list of names before he accepted the word.",
    "A body of work that will be referenced long after everyone involved has gone.",
    "The sport has a small number of these careers per generation. This is one of them.",
    "Legend status, earned across decades, clubs, and a great deal of hard weather.",
    "A footballing legend, and the anecdotes have started to become slightly inaccurate. That is the sign.",
    "The name is spoken with a particular tone. Only a handful of managers ever get that.",
    "A career that ranks with the very best the game has produced. Simply true.",
    "Legend, and the honours have long since stopped being the point of it.",
    "The story writes itself from here, and it has been a very good story.",
    "A footballing legend, and there is barely a corner of the sport untouched by the influence.",
    "The standing is historical rather than contemporary now. That is the highest compliment.",
    "Legend, and there will be documentaries. There are probably already documentaries.",
    "A career that redefined what was possible at more than one club.",
    "The name is a benchmark. Managers are measured against it and mostly fall short.",
    "A footballing legend, and the record of it will be read by people not yet born.",
    "Legend, and the daily work is still team selection, set pieces and difficult conversations.",
    "The achievements have accumulated into something that no longer needs describing.",
    "A legend of the game, and the game knows it, whatever he says about it publicly.",
    "The career belongs to football's history now, filed with the very best of them.",
    "Legend status, and it arrived so gradually that nobody can name the season it happened.",
    "A footballing legend, and there is a whole coaching philosophy carrying his fingerprints.",
    "The name will be on a list in fifty years, and it will be near the top of it.",
    "Legend, and every young manager in the trade would take a fraction of this career.",
    "A body of work of genuine historical weight. Very few ever build one.",
    "The status is settled. The only question left is how much further it goes.",
    "A footballing legend, and the most impressive thing is that the work rate never changed."
  ],
  'Immortal Gaffer': [
    "Immortal. There is no rank above this and no argument about who occupies it.",
    "The top of the managerial pyramid, reached and held. Nothing left to climb.",
    "A career for the ages, and the game will be discussing it for as long as it is played.",
    "Immortal, and the record is so complete that it reads like an invention.",
    "There is no higher standing available in this profession. This is the summit.",
    "The name is now permanently attached to the sport itself rather than to any club or era.",
    "Immortal gaffer, and the achievements have passed beyond comparison into something else.",
    "A career that will define what greatness in a dugout means for a very long time.",
    "The very top, claimed outright. Nobody else is standing here.",
    "Immortal, and the honours list has to be printed on more than one page.",
    "A managerial career of a kind the sport produces perhaps twice a century.",
    "The pyramid has a point at the top, and it has been reached.",
    "Immortal, and it took every single season, every bad night and every long drive to get here.",
    "A career that will be taught rather than remembered.",
    "The highest rank the game has, and the standing is beyond any possible revision.",
    "Immortal gaffer. The word is absurd and in this case it fits exactly.",
    "There is nothing left to win, and somehow the appetite is still there.",
    "A career for the ages, built by a person who mostly just kept turning up and doing the work.",
    "Immortal, and the statues will look nothing like him and it will not matter.",
    "The summit of the profession, occupied by a name that will never leave it.",
    "A record that will stand as the standard for generations of managers to come.",
    "Immortal, and everyone who ever worked under him has a story they will tell forever.",
    "The very top of the game, reached the only way it can be: over an entire lifetime.",
    "A career that has changed what supporters at more than one club believe is possible.",
    "Immortal gaffer, and the trophy cabinet needed rebuilding twice along the way.",
    "There is no rank beyond this one. The list ends here and his name is on the end of it.",
    "A managerial life of extraordinary weight, and it started in an empty dressing room somewhere.",
    "Immortal, and the sport will keep the name long after everybody who saw it has gone.",
    "The peak of the profession, and the view from it is apparently much the same as anywhere else.",
    "A career for the ages, and the most remarkable part is how ordinary the daily habits stayed.",
    "Immortal, and the achievements are now measured against history rather than rivals.",
    "The highest possible standing in the managerial game, earned across a whole working life.",
    "A name that will be attached to the sport permanently. Nothing can undo it.",
    "Immortal gaffer, and there is a real argument that nobody has ever done it better.",
    "The top of the pyramid. There was never any guarantee anybody would reach it.",
    "A career that will be argued about, admired and imitated for as long as football exists.",
    "Immortal, and the influence extends to managers who never met him and never will.",
    "The summit, and the honest reflection is that it was built out of a thousand ordinary Tuesdays.",
    "A managerial record without equal, assembled patiently, over decades, without shortcuts.",
    "Immortal, and there is no meaningful way left to measure this career except against itself.",
    "The very highest rank, and the game itself is different for the fact of this career.",
    "A career for the ages, and the family name goes into the sport's permanent record with it.",
    "Immortal gaffer. The end of the ladder, and a very long way from where it started.",
    "There is nothing above this. There never has been, for anybody.",
    "A career that finishes any argument about what a manager can achieve in one lifetime."
  ],
};
