#!/usr/bin/env python3
"""Curate the badge set: drop user-rejected badges, regenerate variants with REALISTIC colours only.

Keeps the pixelated-original survivors (badge-1..93) minus the user's deletions, then regenerates the
variant slots from those survivors using colour-MIX onto a realistic football palette (NO hue-rotation —
that's what produced the fluorescent colours). Blank centres still get a subtle star/ring/stripe.
Rewrites badge-1..N, the manifest, and the numbered sheet.  Run: python3 tools/curate_badges.py
"""
import os, glob, math
from collections import Counter
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "client", "public", "badges")
SURVIVOR_MAX = 93          # badge-1..93 are the pixelated originals; 94+ were recoloured variants
TARGET = 150
USER_DELETE = {4,11,13,14,20,23,31,35,39,44,45,49,51,75,90,97,104,106,107,113,116,124,129,132,137,138,142,144,148}

# realistic club colours only (deep, muted — no fluorescent/neon)
MIXPAL = [(163,26,42),(20,42,84),(24,84,52),(200,164,66),(74,20,44),(150,110,30),(28,64,92),
          (60,32,88),(24,84,84),(30,64,112),(40,72,36),(176,96,32),(20,80,120),(112,26,52),
          (72,78,88),(96,40,40),(40,50,70)]

def h32(s):
    h = 2166136261
    for c in str(s): h = ((h ^ ord(c)) * 16777619) & 0xffffffff
    return h or 1

def color_mix(im, seed):
    px = im.load(); freq = Counter()
    for y in range(32):
        for x in range(32):
            p = px[x, y]
            if p[3] > 128: freq[p[:3]] += 1
    mapping = {}; idx = seed
    for c, _ in sorted(freq.items(), key=lambda kv: -kv[1]):
        mx, mn = max(c), min(c)
        if mx < 70 or (mx > 205 and mx - mn < 32):   # dark outline / near-white → keep
            continue
        mapping[c] = MIXPAL[idx % len(MIXPAL)]; idx += 5
    out = im.copy(); o = out.load()
    for y in range(32):
        for x in range(32):
            p = px[x, y]
            if p[:3] in mapping: o[x, y] = mapping[p[:3]] + (p[3],)
    return out

def center_flat(im):
    px = im.load(); c = Counter()
    for y in range(11, 21):
        for x in range(11, 21):
            p = px[x, y]
            if p[3] > 128: c[p[:3]] += 1
    tot = sum(c.values())
    if tot < 60: return None
    col, n = c.most_common(1)[0]
    return col if n / tot > 0.7 else None

def lum(c): return 0.299*c[0] + 0.587*c[1] + 0.114*c[2]

def stamp(im, seed, base):
    d = ImageDraw.Draw(im)
    fg = (28, 30, 44) if lum(base) > 140 else (245, 246, 250)
    ol = (245, 246, 250) if lum(base) > 140 else (16, 16, 28)
    kind = ["star", "ring", "stripes", "disc"][seed % 4]; cx = cy = 16
    def outlined(fn):
        for dx, dy in ((-1,0),(1,0),(0,-1),(0,1)): fn(dx, dy, ol)
        fn(0, 0, fg)
    if kind == "star":
        pts = lambda dx,dy: [(cx+dx + (5 if i%2==0 else 2.1)*math.cos(-math.pi/2+i*math.pi/5),
                              cy+dy + (5 if i%2==0 else 2.1)*math.sin(-math.pi/2+i*math.pi/5)) for i in range(10)]
        outlined(lambda dx,dy,c: d.polygon(pts(dx,dy), fill=c+(255,)))
    elif kind == "ring":
        outlined(lambda dx,dy,c: d.ellipse([cx-5+dx,cy-5+dy,cx+5+dx,cy+5+dy], outline=c+(255,), width=2))
    elif kind == "disc":
        outlined(lambda dx,dy,c: d.ellipse([cx-4+dx,cy-4+dy,cx+4+dx,cy+4+dy], fill=c+(255,)))
    else:
        for yy in (cy-3, cy, cy+3):
            outlined(lambda dx,dy,c,yy=yy: d.rectangle([cx-6+dx, yy+dy, cx+6+dx, yy+1+dy], fill=c+(255,)))

def main():
    base = [Image.open(os.path.join(OUT, f"badge-{n}.png")).convert("RGBA")
            for n in range(1, SURVIVOR_MAX + 1)
            if n not in USER_DELETE and os.path.exists(os.path.join(OUT, f"badge-{n}.png"))]
    print(f"kept {len(base)} original survivors (removed {len([n for n in USER_DELETE if n <= SURVIVOR_MAX])} of yours)")
    final = list(base); i = 0
    while len(final) < TARGET:
        v = color_mix(base[i % len(base)], i * 7 + 3)   # realistic recolour only
        flat = center_flat(v)
        if flat is not None: stamp(v, i, flat)
        final.append(v); i += 1
    for f in glob.glob(os.path.join(OUT, "*.png")): os.remove(f)
    for n, im in enumerate(final, 1): im.save(os.path.join(OUT, f"badge-{n}.png"))
    # manifest
    with open(os.path.join(ROOT, "client", "src", "badge-manifest.ts"), "w") as f:
        f.write("// AUTO-GENERATED by tools/reindex_badges.py — do not edit by hand.\n")
        f.write("export const BADGES: readonly string[] = [\n")
        for n in range(1, len(final) + 1): f.write(f"  'badge-{n}.png',\n")
        f.write("];\n")
    # numbered contact sheet
    cols, badge, pad, lblh = 10, 32, 6, 12; cw, ch = badge+pad*2, badge+lblh+pad
    rows = (len(final) + cols - 1) // cols
    sheet = Image.new("RGBA", (cols*cw, rows*ch), (235, 235, 242, 255)); d = ImageDraw.Draw(sheet)
    try: font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 9)
    except Exception: font = ImageFont.load_default()
    for i, im in enumerate(final):
        cx, cy = (i % cols)*cw, (i // cols)*ch
        sheet.alpha_composite(im, (cx+pad, cy+pad))
        d.text((cx+cw//2, cy+badge+pad+1), str(i+1), fill=(20,20,30,255), anchor="ma", font=font)
    sheet.resize((sheet.width*3, sheet.height*3), Image.NEAREST).save("/tmp/badges_numbered.png")
    print(f"wrote {len(final)} badges ({len(final)-len(base)} realistic variants); sheet /tmp/badges_numbered.png")

if __name__ == "__main__":
    main()
