#!/usr/bin/env python3
"""Validate a generated portrait set and install it as the live library.

Refuses to install anything it has not checked. The three pools must come out PARALLEL — index k the same
person in youth, prime and veteran — because portraitUrl hashes the name alone and lets the band pick which
age of that person to show. Unequal or gappy pools silently break that guarantee: a name would resolve to a
different relative index in each band and every player would change face as he ages, which is the bug this
whole exercise exists to fix.

Run:  python3 tools/portrait_install.py <staging-dir> [--go]
"""
import argparse, os, re, shutil, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIVE = os.path.join(ROOT, "client", "public", "portraits")
MANIFEST = os.path.join(ROOT, "client", "src", "portrait-manifest.ts")
BANDS = ("youth", "prime", "veteran")

def scan(d):
    got = {b: {} for b in BANDS}
    for f in os.listdir(d):
        m = re.fullmatch(r"portrait-(youth|prime|veteran)-(\d+)\.png", f)
        if m: got[m.group(1)][int(m.group(2))] = f
    return got

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("staging")
    ap.add_argument("--go", action="store_true", help="actually install (default is a report)")
    a = ap.parse_args()
    got = scan(a.staging)
    problems = []

    counts = {b: len(got[b]) for b in BANDS}
    print(f"  staged: youth {counts['youth']}, prime {counts['prime']}, veteran {counts['veteran']}")

    # The set of identity indices present must be IDENTICAL across the three bands, and contiguous from 0.
    # A missing index in one band is not a small gap — it shifts nothing (we key by number, not position),
    # but it means that identity has no face at that age, so a player would vanish from the tree on ageing.
    common = set(got["youth"]) & set(got["prime"]) & set(got["veteran"])
    for b in BANDS:
        missing = sorted(set(common) ^ set(got[b]))[:5]
        if set(got[b]) != common:
            problems.append(f"{b} has {len(set(got[b]) ^ common)} index/indices the other bands lack (e.g. {missing})")
    if not common:
        problems.append("no identity index is present in all three bands")

    # Every file must actually decode, at the expected size.
    bad = []
    for b in BANDS:
        for i, f in sorted(got[b].items()):
            p = os.path.join(a.staging, f)
            try:
                im = Image.open(p); im.load()
                if im.size != (64, 64): bad.append(f"{f} is {im.size}")
            except Exception as e:
                bad.append(f"{f} unreadable: {str(e)[:40]}")
    if bad: problems.append(f"{len(bad)} malformed file(s): {bad[:3]}")

    print(f"  {len(common)} identities complete across all three bands")
    for p in problems: print(f"  PROBLEM: {p}")
    if problems and a.go:
        print("\nrefusing to install — fix the above first"); return 1
    if not a.go:
        print("\nreport only. Re-run with --go to install."); return 0

    # Install: the live pools become exactly the complete identities, renumbered 0..N-1 so they are
    # contiguous and parallel. The previous 64 are retired — they were three independent pools of unequal
    # length and cannot participate in an identity-stable lookup.
    ids = sorted(common)
    for f in os.listdir(LIVE):
        if f.startswith("portrait-"): os.remove(os.path.join(LIVE, f))
    for b in BANDS:
        for new, old in enumerate(ids):
            shutil.copy2(os.path.join(a.staging, got[b][old]), os.path.join(LIVE, f"portrait-{b}-{new}.png"))
    n = len(ids)
    with open(MANIFEST, "w") as f:
        f.write("// AUTO-GENERATED by tools/portrait_install.py — do not edit by hand.\n")
        f.write("//\n")
        f.write("// THE THREE POOLS ARE PARALLEL: index k is the same person in youth, prime and veteran,\n")
        f.write("// generated as an aged triplet with one heritage, skin tone and hair style throughout.\n")
        f.write("// portraitUrl() therefore hashes the NAME ALONE and lets the band choose which age to show,\n")
        f.write("// so a player keeps his face as he ages. shared/qa_portraits.ts asserts this holds.\n")
        f.write("export const PORTRAITS: Record<'youth' | 'prime' | 'veteran', readonly string[]> = {\n")
        for b in BANDS:
            names = ", ".join(f"'portrait-{b}-{i}.png'" for i in range(n))
            f.write(f"  {b}: [{names}],\n")
        f.write("};\n")
    print(f"\n  installed {n} identities x 3 bands = {n*3} portraits, manifest regenerated")
    return 0

if __name__ == "__main__":
    sys.exit(main())
