#!/usr/bin/env python3
"""Generate recolorable pixel-art kit (jersey) templates via the Retro Diffusion API.

8 patterns (solid/stripes/hoops/halves/sash/quarters/pinstripe/chevron). Each is generated as a white-body
+ black-pattern jersey so the two zones separate cleanly, then NORMALIZED to two sentinel colours
(base = magenta 255,0,255, accent = cyan 0,255,255) that the client recolors to each club's actual two
colours at render time (client/src/kit.ts). Original AI art -> zero licensing risk. Key from $RD_API_KEY
or gitignored tools/.rd_key. Writes kit-<pattern>.png (normalized), kit-manifest.ts, and a preview sheet
showing every template in two sample colourways.

Run:  RD_API_KEY=rdpk-... python3 tools/rd_kits.py      (or RD_REGEN="sash,hoops")
"""
import os, sys, json, base64, io, time, urllib.request
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "client", "public", "kits")
ENDPOINT = "https://api.retrodiffusion.ai/v1/inferences"
STYLE = os.environ.get("RD_STYLE", "rd_fast__default")
GEN = int(os.environ.get("RD_SIZE", "64"))
FINAL = 48
BASE = (255, 0, 255)   # sentinel -> club primary colour
ACC = (0, 255, 255)    # sentinel -> club secondary colour

KITS = {
    "solid": "a plain white football jersey shirt with a black collar and black sleeve trim",
    "stripes": "a football jersey shirt with bold white and black vertical stripes",
    "hoops": "a football jersey shirt with white and black horizontal hoops",
    "halves": "a football jersey shirt split vertically into a white half and a black half",
    "sash": "a white football jersey shirt with a single diagonal black sash",
    "quarters": "a football jersey shirt in a quartered white and black pattern",
    "pinstripe": "a white football jersey shirt with thin black pinstripes",
    "chevron": "a white football jersey shirt with a bold black chevron V across the chest",
}

def prompt_for(desc):
    return f"{desc}, front view, flat solid colors, bold dark outline, plain background, pixel art, no text, no logo"

def api_key():
    k = os.environ.get("RD_API_KEY")
    if k: return k.strip()
    for p in (os.path.join(ROOT, "tools", ".rd_key"), os.path.expanduser("~/.rd_key")):
        if os.path.exists(p):
            with open(p) as f: return f.read().strip()
    sys.exit("No API key. Set RD_API_KEY or put it in tools/.rd_key")

def request(key, prompt, seed, retries=4):
    body = json.dumps({"prompt": prompt, "prompt_style": STYLE, "width": GEN, "height": GEN,
                       "num_images": 1, "seed": seed, "remove_bg": True}).encode()
    last = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(ENDPOINT, data=body, method="POST",
                                         headers={"X-RD-Token": key, "Content-Type": "application/json"})
            with urllib.request.urlopen(req, timeout=120) as r:
                res = json.loads(r.read())
            if res.get("base64_images"): return res
            last = res.get("error", res)
        except Exception as e:
            last = e
        time.sleep(2 + attempt * 2)
    raise RuntimeError(f"failed after {retries} attempts: {last}")

def normalize(im):
    """Crop, square-pad, downscale, then map light->BASE sentinel, dark->ACC sentinel (2-tone template)."""
    im = im.convert("RGBA")
    bbox = im.getbbox()
    if bbox: im = im.crop(bbox)
    w, h = im.size; s = max(w, h)
    sq = Image.new("RGBA", (s, s), (0, 0, 0, 0)); sq.paste(im, ((s - w) // 2, (s - h) // 2))
    small = sq.resize((FINAL, FINAL), Image.LANCZOS)
    px = small.load()
    out = Image.new("RGBA", (FINAL, FINAL), (0, 0, 0, 0)); op = out.load()
    for y in range(FINAL):
        for x in range(FINAL):
            r, g, b, a = px[x, y]
            if a < 110: continue
            lum = 0.299 * r + 0.587 * g + 0.114 * b
            op[x, y] = (*BASE, 255) if lum >= 128 else (*ACC, 255)
    return out

def recolor(tpl, primary, secondary):
    out = Image.new("RGBA", tpl.size, (0, 0, 0, 0)); tp, oq = tpl.load(), out.load()
    for y in range(tpl.size[1]):
        for x in range(tpl.size[0]):
            r, g, b, a = tp[x, y]
            if a < 110: continue
            oq[x, y] = (*primary, 255) if (r, g, b) == BASE else (*secondary, 255)
    return out

def write_manifest():
    import glob
    fs = sorted(glob.glob(os.path.join(OUT, "kit-*.png")))
    names = ", ".join(f"'{os.path.basename(f)}'" for f in fs)
    with open(os.path.join(ROOT, "client", "src", "kit-manifest.ts"), "w") as f:
        f.write("// AUTO-GENERATED by tools/rd_kits.py — 2-tone recolorable jersey templates.\n"
                "// Sentinel colours: base = rgb(255,0,255), accent = rgb(0,255,255). Recolor via client/src/kit.ts.\n"
                f"export const KITS: readonly string[] = [{names}];\n")
    print("wrote client/src/kit-manifest.ts")

def preview():
    import glob
    fs = sorted(glob.glob(os.path.join(OUT, "kit-*.png")))
    ways = [((20, 40, 90), (240, 200, 60)), ((150, 25, 30), (20, 20, 20))]  # navy/gold, red/black
    cell, pad, lbl = 56, 8, 12
    sheet = Image.new("RGB", (len(ways) * (cell + pad) + pad, len(fs) * (cell + lbl + pad) + pad), (24, 24, 28))
    d = ImageDraw.Draw(sheet)
    try: font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 9)
    except Exception: font = ImageFont.load_default()
    for r, fp in enumerate(fs):
        tpl = Image.open(fp).convert("RGBA")
        name = os.path.basename(fp)[4:-4]
        for c, (p1, p2) in enumerate(ways):
            img = recolor(tpl, p1, p2).resize((cell, cell), Image.NEAREST)
            x = pad + c * (cell + pad); y = pad + r * (cell + lbl + pad)
            sheet.paste(img, (x, y), img)
        d.text((pad, pad + r * (cell + lbl + pad) + cell + 1), name, fill=(210, 210, 215), font=font)
    sheet.save("/tmp/kits_sheet.png")
    print(f"preview -> /tmp/kits_sheet.png ({len(fs)} templates x {len(ways)} colourways)")

def main():
    key = api_key()
    os.makedirs(OUT, exist_ok=True)
    regen = os.environ.get("RD_REGEN", "").strip()
    todo = [k for k in regen.replace(" ", "").split(",") if k] if regen else list(KITS.keys())
    print(f"generating {len(todo)} kit template(s)")
    for k in todo:
        if k not in KITS: print(f"  ?? unknown kit '{k}'"); continue
        try:
            res = request(key, prompt_for(KITS[k]), 9100 + list(KITS).index(k) * 13)
            im = Image.open(io.BytesIO(base64.b64decode(res["base64_images"][0])))
            normalize(im).save(os.path.join(OUT, f"kit-{k}.png"))
            print(f"  {k:10} (balance {res.get('remaining_balance')})")
        except Exception as e:
            print(f"  {k} error (skipped):", e)
    write_manifest(); preview()

if __name__ == "__main__":
    main()
