#!/usr/bin/env python3
"""Generate age-banded pixel-art face portraits for players/managers via the Retro Diffusion API.

Three pools — youth / prime / veteran — so a 40-year-old gaffer never shows a teen face. Portraits are
hash-assigned to procedurally-generated people (same pattern as club crests). Original AI art -> zero
licensing risk. Key from $RD_API_KEY or gitignored tools/.rd_key, never chat/repo. Head-and-shoulders,
transparent background, varied skin tones / hair / facial hair, downscaled to 48x48. Writes
portrait-<band>-<i>.png, a banded manifest (portrait-manifest.ts), and a labelled contact sheet per band.

Run:  RD_API_KEY=rdpk-... python3 tools/rd_portraits.py            (all bands)
      RD_BAND=youth python3 tools/rd_portraits.py                  (one band)
      RD_REGEN="prime-3,veteran-7" python3 tools/rd_portraits.py   (specific portraits)
"""
import os, sys, json, base64, io, time, urllib.request
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "client", "public", "portraits")
ENDPOINT = "https://api.retrodiffusion.ai/v1/inferences"
STYLE = os.environ.get("RD_STYLE", "rd_fast__default")
GEN = int(os.environ.get("RD_SIZE", "64"))
FINAL = 48

BANDS = {"youth": 20, "prime": 24, "veteran": 20}
SKIN = ["pale", "fair", "light-brown", "olive", "tan", "brown", "dark-brown", "deep-brown"]
HAIR = ["short black hair", "brown buzz cut", "curly brown hair", "blond hair", "red hair",
    "long dark hair", "shaved head", "short afro", "slicked-back black hair", "wavy brown hair",
    "cornrows", "tight curls"]
FACE = ["clean-shaven", "light stubble", "clean-shaven", "short beard", "clean-shaven", "moustache"]

def band_desc(band, i):
    skin = SKIN[i % len(SKIN)]; hair = HAIR[(i * 5 + 1) % len(HAIR)]; face = FACE[(i * 3) % len(FACE)]
    if band == "youth":
        who = "a teenage male football academy prospect, youthful face"; face = "clean-shaven"
    elif band == "prime":
        who = "an adult male professional footballer, athletic, determined expression"
    else:  # veteran
        who = "an older male football manager in his fifties, wise, weathered face"
        hair = ["grey hair", "balding grey hair", "silver hair", "short grey hair", "bald head"][i % 5]
        face = ["clean-shaven", "grey stubble", "short grey beard", "grey moustache"][i % 4]
    return f"a pixel art portrait of {who}, {skin} skin, {hair}, {face}, head and shoulders facing forward, plain flat background, retro 8-bit style, clean bold outline"

def api_key():
    k = os.environ.get("RD_API_KEY")
    if k: return k.strip()
    for p in (os.path.join(ROOT, "tools", ".rd_key"), os.path.expanduser("~/.rd_key")):
        if os.path.exists(p):
            with open(p) as f: return f.read().strip()
    sys.exit("No API key. Set RD_API_KEY or put it in tools/.rd_key")

def request(key, prompt, seed, retries=4):
    body = json.dumps({"prompt": prompt, "prompt_style": STYLE, "width": GEN, "height": GEN,
                       "num_images": 1, "seed": seed, "remove_bg": True}).encode()
    last = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(ENDPOINT, data=body, method="POST",
                                         headers={"X-RD-Token": key, "Content-Type": "application/json"})
            with urllib.request.urlopen(req, timeout=120) as r:
                res = json.loads(r.read())
            if res.get("base64_images"): return res
            last = res.get("error", res)
        except Exception as e:
            last = e
        time.sleep(2 + attempt * 2)
    raise RuntimeError(f"failed after {retries} attempts: {last}")

def pixelate(im):
    im = im.convert("RGBA")
    bbox = im.getbbox()
    if bbox: im = im.crop(bbox)
    w, h = im.size; s = max(w, h)
    sq = Image.new("RGBA", (s, s), (0, 0, 0, 0)); sq.paste(im, ((s - w) // 2, (s - h) // 2))
    small = sq.resize((FINAL, FINAL), Image.LANCZOS)
    rgb = small.convert("RGB").quantize(colors=24, method=Image.FASTOCTREE).convert("RGB")
    a = small.getchannel("A").point(lambda v: 255 if v > 110 else 0)
    return Image.merge("RGBA", (*rgb.split(), a))

SEED0 = {"youth": 6000, "prime": 6500, "veteran": 7000}

def gen_one(key, band, i):
    res = request(key, band_desc(band, i), SEED0[band] + i * 17)
    im = Image.open(io.BytesIO(base64.b64decode(res["base64_images"][0])))
    pixelate(im).save(os.path.join(OUT, f"portrait-{band}-{i}.png"))
    return res.get("remaining_balance")

def write_manifest():
    import glob
    lines = ["// AUTO-GENERATED by tools/rd_portraits.py — pixel-art face portraits, hash-assigned by age band.",
             "export const PORTRAITS: Record<'youth' | 'prime' | 'veteran', readonly string[]> = {"]
    for band in BANDS:
        fs = sorted(glob.glob(os.path.join(OUT, f"portrait-{band}-*.png")), key=lambda p: int(p.split("-")[-1].split(".")[0]))
        names = ", ".join(f"'{os.path.basename(f)}'" for f in fs)
        lines.append(f"  {band}: [{names}],")
    lines.append("};")
    with open(os.path.join(ROOT, "client", "src", "portrait-manifest.ts"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote client/src/portrait-manifest.ts")

def contact_sheet():
    import glob
    cols, cell, pad, lbl = 10, 52, 6, 12
    try: font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 9)
    except Exception: font = ImageFont.load_default()
    for band in BANDS:
        fs = sorted(glob.glob(os.path.join(OUT, f"portrait-{band}-*.png")), key=lambda p: int(p.split("-")[-1].split(".")[0]))
        if not fs: continue
        rows = (len(fs) + cols - 1) // cols
        sheet = Image.new("RGB", (cols * (cell + pad) + pad, rows * (cell + lbl + pad) + pad), (24, 24, 28))
        d = ImageDraw.Draw(sheet)
        for k, f in enumerate(fs):
            r, cc = divmod(k, cols); x = pad + cc * (cell + pad); y = pad + r * (cell + lbl + pad)
            sheet.paste(Image.open(f).convert("RGBA").resize((cell, cell), Image.NEAREST), (x, y), Image.open(f).convert("RGBA").resize((cell, cell), Image.NEAREST))
            d.text((x, y + cell + 1), f"{band[:3]}-{k}", fill=(210, 210, 215), font=font)
        sheet.save(f"/tmp/portraits_{band}.png")
        print(f"contact sheet -> /tmp/portraits_{band}.png ({len(fs)})")

def main():
    key = api_key()
    os.makedirs(OUT, exist_ok=True)
    regen = os.environ.get("RD_REGEN", "").strip()
    only = os.environ.get("RD_BAND", "").strip()
    if regen:
        for tok in regen.replace(" ", "").split(","):
            if not tok: continue
            band, i = tok.rsplit("-", 1); i = int(i)
            try: print(f"  {tok}: balance {gen_one(key, band, i)}")
            except Exception as e: print(f"  {tok} error (kept old):", e)
    else:
        for band, n in BANDS.items():
            if only and band != only: continue
            print(f"== {band} ({n}) ==")
            for i in range(n):
                try: print(f"  {band}-{i}: balance {gen_one(key, band, i)}")
                except Exception as e: print(f"  {band}-{i} error (skipped):", e)
    write_manifest()
    contact_sheet()

if __name__ == "__main__":
    main()
