#!/usr/bin/env python3
"""Rebuild the badge manifest from whatever badge-*.png files currently exist.

Workflow: open client/public/badges/ and delete any badge-<n>.png you don't want (use the numbered
sheet as a reference — filenames don't change, so numbers stay valid), then run this. It regenerates
client/src/badge-manifest.ts (the list crest.ts reads) and a fresh numbered contact sheet at
/tmp/badges_numbered.png. No renaming, so your deletions are all that matter.

Run:  python3 tools/reindex_badges.py
"""
import os, glob
try:
    from PIL import Image, ImageDraw, ImageFont
    HAVE_PIL = True
except Exception:
    HAVE_PIL = False

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BADGES = os.path.join(ROOT, "client", "public", "badges")
MANIFEST = os.path.join(ROOT, "client", "src", "badge-manifest.ts")

def num(p): return int(os.path.basename(p).split("-")[-1].split(".")[0])

def main():
    files = sorted(glob.glob(os.path.join(BADGES, "badge-*.png")), key=num)
    names = [os.path.basename(f) for f in files]
    with open(MANIFEST, "w") as f:
        f.write("// AUTO-GENERATED by tools/reindex_badges.py — do not edit by hand.\n")
        f.write("// The club badges present under client/public/badges/. Delete unwanted badge-*.png and\n")
        f.write("// re-run the script to regenerate this list; crest.ts assigns each club one by name-hash.\n")
        f.write("export const BADGES: readonly string[] = [\n")
        for n in names:
            f.write(f"  '{n}',\n")
        f.write("];\n")
    print(f"wrote manifest with {len(names)} badges → {os.path.relpath(MANIFEST, ROOT)}")
    if HAVE_PIL and files:
        cols, badge, pad, lblh = 10, 32, 6, 12
        cw, ch = badge + pad*2, badge + lblh + pad
        rows = (len(files) + cols - 1) // cols
        sheet = Image.new("RGBA", (cols*cw, rows*ch), (235, 235, 242, 255))
        d = ImageDraw.Draw(sheet)
        try: font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 9)
        except Exception: font = ImageFont.load_default()
        for i, fp in enumerate(files):
            cx, cy = (i % cols)*cw, (i // cols)*ch
            sheet.alpha_composite(Image.open(fp).convert("RGBA"), (cx+pad, cy+pad))
            d.text((cx+cw//2, cy+badge+pad+1), str(num(fp)), fill=(20, 20, 30, 255), anchor="ma", font=font)
        sheet.resize((sheet.width*3, sheet.height*3), Image.NEAREST).save("/tmp/badges_numbered.png")
        print("numbered sheet → /tmp/badges_numbered.png")

if __name__ == "__main__":
    main()
