// Authoring pack K. One author owns this file — nobody else writes to it, so packs never collide.
// Keys must match the bank they extend (see shared/src/prompts/*.ts for the key names and the house voice).
import type { Bank } from '../merge.js';
export const KIND_SETUP_K: Bank = {};
export const DEMAND_K: Bank = {};
export const FRAME_K: Bank = {};
export const SETTINGS_K: Bank = {
  'Youth Team': [
    'out on the far pitch, the one with the slope',
    'with the kit man still counting bibs on the touchline',
    'before an audience of eleven, most of them dads',
    'under floodlights with one bank of bulbs gone',
    'against a side carrying three trialists',
    'after a two-hour coach ride to the coast',
    'beside a rugby pitch sharing the same changing block',
    'through the last twenty minutes of a dead game',
    'at the far end of a pitch marked out that morning',
    'down at the training ground on a wet Tuesday',
    'over at the council pitches while the main ground was relaid',
    'alongside two senior pros getting minutes back after injury',
    'with a burst ball bag propped against the dugout',
    'twenty minutes into a game already gone',
    'on a bobbled pitch',
    'with the groundsman waiting by the gate to lock up',
    'with a linesman in a tracksuit and trainers',
    'before a row of empty blue seats and a shut tea hut',
    'under a sky that had been threatening it since breakfast',
    'against grown men on second contracts',
    'after the under-18s had chewed up the same grass at eleven',
    'past the hour, both sides gone in the legs',
    'at the end of a week spent training with the first team',
    'down the road at the non-league ground they borrowed',
    'out on a pitch shared with a rugby club, lines everywhere',
    'with three missed calls from his agent',
    'in a behind-closed-doors friendly',
    'with the first team working two pitches over',
    'as the rain came in sideways off the car park',
    "with frost still on the far touchline at two o'clock",
    'while the physio shouted at him to stay on his feet',
    'before nobody but a man walking a dog round the perimeter',
    'watched by the under-18s from behind the far goal',
    "with a loan club's chief scout somewhere in the main stand",
    'with the youth-team manager saying nothing at all',
    'a bus ride from his digs, with no lift home after',
    'at a one o\'clock kickoff, moved to save the floodlight bill',
    'with the crossbar still wet from the morning session',
    'six days before the first-team squad went up on the board',
    'before the coach came back out with the team sheet',
    'the week two of the second years cleared their pegs',
    'under a coach who had a good word for nobody',
    'under a low sun that had the keeper squinting all half',
    'at a ground built for four thousand, holding about twenty',
    'against a reserve side full of lads on the same deal',
    'against a centre-half eight years older and a yard cleverer',
    'against a team who had already beaten them twice',
    'after a fortnight of finishing drills that would not go in',
    'the Thursday after his first session with the seniors',
    'after the club had told two of his mates on the Monday',
    'beside a dugout with half its roof missing',
    'beside a corner flag somebody had trodden flat',
    'past a linesman who had given nothing all afternoon',
    'gone three o\'clock, the light already going',
    'through a flat, sideways second half',
    'through six minutes of injury time nobody had asked for',
    'at a ground where the turnstiles were not even open',
    'back at the training ground, first team long gone home',
    'out on grass that had not recovered from a rugby weekend',
    'out wide where the pitch turned to sand',
    'down at the college pitches on a Wednesday morning',
    'in a reserve league nobody kept a proper table for',
    "over at another club's training ground, on trial for a fortnight",
    'alongside a lad who had signed his first deal that morning',
    'alongside a trialist from Cork who barely said a word',
    'two days after his agent had first rung the manager',
    'six weeks from the end of his contract',
    'a fortnight into training with the senior group',
    'ten minutes after coming on for a lad who had pulled up',
    'the day the loan paperwork went in',
    'minutes after a bollocking on the touchline',
    'in front of a scout eating chips out of the paper',
    'in a reserve fixture kicking off at half one',
    'in the rain, at a ground with one working turnstile',
    'in a game that mattered to twenty-two lads and nobody else',
    'timed all afternoon by a first-team fitness coach',
    'with the reserve keeper bawling instructions nobody could hear',
    'at nil-nil with everybody drifting',
    'in boots taped where they had split at the seam',
    'with the wind taking every goal kick straight back',
    'watched by a photographer from the local paper on the far side',
    "with a bag of ice already on somebody's knee behind the bench",
    'while the club secretary kept the time on his wristwatch',
    'with two coaches arguing over who was meant to be marking who',
    'under a referee whose whistle went every thirty seconds',
    'with a ball boy who had wandered off somewhere',
    'with nothing at stake beyond a Monday conversation',
    'on a surface cutting up badly in both goalmouths',
    'as sleet came across from the industrial estate',
    "beside a dugout where the groundsman's dog was asleep",
    'with half the squad away on first-team duty',
    'in front of a goal with a hole in the netting',
    'with the tea urn already on in the clubhouse',
    'alongside an assistant manager writing something down every few minutes',
    'on a school pitch, the fixture moved twice that week',
    'under a referee borrowed from the local Sunday league',
    'with the nets tied on with cable ties',
    'in the third game of eight days',
    'with two first-teamers in the side, neither happy to be there',
    'on a Wednesday afternoon with the ground to themselves',
    'before a crowd you could count from the halfway line',
    'out on the grass an hour before anybody else',
    'after a night in digs with a radiator that clanked',
    'in a fixture postponed twice and played in February mud',
    'against a side whose bench was three lads and a coach',
    'under the same floodlights he had watched from the terrace at ten',
    'at the near post, where the pitch had gone to mud',
    'with a first-team debut list going up that week',
    'through the second half, one substitute left',
    'past a defender who had been at the club nine years',
    'down at the ground on the day the youth squad was cut',
    'beside two dads and a woman with a flask',
    'over the far side, where nobody could see it properly',
    'alongside a keeper who had been released and knew it',
    'after a session where the seniors had shown him up',
    "the afternoon before the manager's meeting",
    'in a game the reserves needed to win for nothing at all',
    'with an ambulance parked behind the goal for the afternoon',
    'on a pitch the groundsman had begged them not to use',
    'before a scout who left at half-time',
    'under a coach counting sprints on a clipboard',
    'against lads he had come through the academy with',
    'after the bus had got lost twice on the way',
    'beside a stand shut off with tape',
    "past a linesman's flag that stayed down",
    'through a half where the ball was in the air more than on the floor',
    'at a training ground pitch with the sprinklers still going at one end',
    'out on the astroturf when the grass was frozen',
    'down at the reserves after a week nowhere near the squad',
    'over at the training ground, playing eleven against eleven',
    'alongside a trialist the club never signed',
    'forty minutes into a fixture already lost',
    'the morning after the first-year lads were told',
    'in a match nobody had bothered to advertise',
    'on the same afternoon his old room-mate was let go',
    'with a coach on the touchline holding a stopwatch and nothing else',
    "before a directors' box with one director in it",
    'under a roof that dripped on the front two rows',
    'against a side that had travelled sixty miles for it',
    'after his agent had told him to score, whatever it took',
    'beside a pitch where the under-16s were finishing',
    'through a game held up twice for a broken corner flag',
    'at half past one on a Tuesday in November',
    'out on a pitch with a crossbar that sagged',
    'down the far end, away from the coaches',
    'over the winter, in games nobody remembered',
    'alongside senior pros who did not know his name',
    'nine days before the contract talks',
    'in a game his mum had driven four hours to watch',
    'on grass still frozen in the shade of the stand',
    'with a first-team coach timing him from the touchline',
    'in an empty ground with the gates left open',
    'against a reserve team of trialists and comeback merchants',
    'after fifty minutes of nothing',
    'before a full changing room of lads waiting on the same news',
    'under the noise of a road behind the far stand',
    'past two o\'clock, the pitch already dark at one end',
    'through the last week of the season',
    'at a ground where the away end was a fence',
    'out on the pitch first, as usual',
    'down at a training ground eleven miles from his digs',
    'over the head of a defender playing his last month at the club',
    'alongside a lad who had already been offered terms',
    'a week after being left out of the youth cup squad',
    'in front of the youth-team coach and a bloke with a clipboard',
    'on a Thursday, on grass that had been played on twice already',
    'with the reserve manager doing the warm-up himself',
    'before an away crowd of nobody',
    'under a floodlight pylon that hummed',
    'against a side already relegated in a league nobody followed',
    'after a night bus back from a game up north',
    'beside a groundsman leaning on his rake',
    'past the coaching staff on the touchline',
    'through drizzle that never quite became rain',
    'at a ground where the changing rooms had no hot water',
    'out on the wing with nobody within thirty yards',
    'down at the reserves for the fourth week running',
    'over at the far touchline, half a pitch from anyone',
    'alongside a centre-half twice released and back on trial',
    'twelve months into a two-year deal',
    'in a game played out with both benches emptied',
    'on a heavy afternoon at a borrowed ground',
    'with the light going and no floodlights to put on',
    'before the coach had said a word about his contract',
    'in a game that ended with more players on the pitch than people in the stand',
  ],
};
export const CHILD_SETUP_K: Bank = {};
export const EVENT_PREFIX_K: Bank = {};
export const BIG_SETTINGS_K: string[] = [];
