// Authoring pack R. One author owns this file — nobody else writes to it, so packs never collide.
import type { Bank } from '../merge.js';
export const KIND_SETUP_R: Bank = {};
export const DEMAND_R: Bank = {};
export const FRAME_R: Bank = {
  'First Team': [
    "Ice bath at half seven, and the physio counts him down from twenty, ",
    "Something went tight in the groin in the eighteenth minute and stayed tight, ",
    "Wintergreen and instant coffee — that is what the treatment room smells of, and it will for the rest of his life, ",
    "Strapping. Always strapping now, before he can even think about warming up, ",
    "He has a knee that tells him what the weather is doing tomorrow, ",
    "Two years ago he played Saturday, Tuesday, Saturday and felt nothing at all, ",
    "Scan on Thursday, results Monday, and a weekend of not knowing in between, ",
    "Grade one, the doctor says, as though that is good news, ",
    "Fourteen minutes on the bike before anyone else is in the building, ",
    "Watching a lad in the next bed start his second cruciate rehab, ",
    "His ankle clicks going up stairs and he has decided not to mention it, ",
    "Compression tights under the tracksuit and a hot water bottle on the coach, ",
    "Recovery is a job now — it has a timetable and a man who checks, ",
    "Somebody has printed his running numbers off and wants a quiet word about the last twenty minutes of Saturday, which were not good enough, ",
    "Nine hours of sleep is a target he is measured against on a spreadsheet, ",
    "A stud caught his shin and the sock came away with blood in it, ",
    "Physio said six weeks. The manager said four, ",
    "Half the treatment room is lads he came through the youth team with, ",
    "Massage table, Tuesday, ten past nine, the same slot every single week, ",
    "They weigh him before and after training and the number goes on a board, ",
    "Cramp in both calves at eighty-eight minutes and no substitutes left, ",
    "Nothing is torn. Nothing is torn, and yet, ",
    "In January the gym smells different than it does in August, ",
    "He has learned that a hamstring gives you about a second of warning, ",
    "Twenty-one years old and there is a folder with his name on it in the medical room, ",
    "Stop the anti-inflammatories before games, the doc says, and does not say what to do instead, ",
    "Boots half a size up since the toe, and nobody knows except the kit man, ",
    "A dead leg on Saturday that is still purple on Wednesday, ",
    "Rehab is a corner of the gym, a ball, a wall, and forty-five minutes alone, ",
    "First real injury of his life, ",
    "Standing on one leg on a wobble board while the rest of them go out, ",
    "First wage lands and it is more than his father earned in a year, ",
    "A mortgage application asks what he does for a living, ",
    "Twelve grand a week, and he still checks what the car park costs, ",
    "An accountant, in Nantwich, who does forty players, ",
    "Somebody at the club hands him a card for a financial adviser, ",
    "His mum will not let him pay for the shopping and that is the end of it, ",
    "A lease car came with the contract. He has never asked what it costs, ",
    "Buying a house at twenty-one from a solicitor who calls him sir, ",
    "Every lad from school has an idea that needs eight thousand pounds, ",
    "Tax. Nobody warned him about the January bill, ",
    "He still uses the bank account he opened when he was fourteen, ",
    "An agent's invoice comes through with a percentage on it he reads twice, ",
    "They talk about watches in there the way his dad talked about vans, ",
    "Paying his brother's rent quietly and telling nobody else in the family, ",
    "A charity dinner where a shirt goes for forty-one thousand pounds, ",
    "Signing-on fee, in two halves, untouched, ",
    "Appearance bonuses, which turn every team sheet into a payslip, ",
    "Bloke fitting the kitchen asked for a photograph before he wrote the invoice, ",
    "A pension. At twenty-one. The PFA posted a leaflet about it, ",
    "Nobody in the family will accept money and nobody will stop hinting, ",
    "Four times. That is what the man on the next peg earns, and everybody in the room knows it to the pound, ",
    "He has never once seen the actual contract, only heard it described, ",
    "Sky moved the game to Friday night and nobody thought to ask him, ",
    "A local reporter waits by the players' entrance with his phone already recording, ",
    "In talks, says the paper, before anyone at the club has spoken to him, ",
    "Forty seconds on the radio, and a back page, ",
    "Media training on a Wednesday, taught by a woman who used to do politics, ",
    "Any regrets about the second goal — the first question, every time, ",
    "His surname is spelled wrong on the television graphic again, ",
    "Someone has clipped his worst touch of the season and set it to music, ",
    "One for the future, says the programme, in his fortieth appearance, ",
    "A phone-in has spent nine minutes on whether he can head a ball, ",
    "Photographers at the training-ground gate on the morning the manager is discussed, ",
    "He has been told not to read anything, which is not the same as not reading it, ",
    "Match of the Day gave him eleven seconds and a mispronounced surname, ",
    "Press officer would like him to say they take each game as it comes, ",
    "Interviewed pitchside, still steaming, still furious, live, ",
    "A columnist who never played has written eight hundred words about his attitude, ",
    "Fans' forum in the function room, Thursday, two hundred tickets sold, ",
    "His name is on the back of a shirt in the club shop window, ",
    "A hundred and forty photographs to sign, ",
    "A hospital visit at ten on a Tuesday and a ward that goes very quiet, ",
    "Someone has made a flag with his face on it and he cannot look at it, ",
    "Two supporters wanted a picture while he was buying petrol, ",
    "Same seat on the coach every week — third row, window, ",
    "Four hours to the north-east, home at two, back in at ten, ",
    "That hotel outside Wolverhampton with the carpet he could draw from memory, ",
    "Pre-match meal at half eleven: chicken, pasta, beans on toast, ",
    "Fire alarm in the team hotel at four in the morning, thirty men in a car park in shorts, ",
    "Coach leaves at nine. Nine means nine. He learned that once, and only once, ",
    "Cards at the back, headphones in the middle, staff down the front, ",
    "Away at Plymouth on a Tuesday in February, ",
    "Kit lorry goes down the night before with everything in it, ",
    "Motorway services at midnight, thirty men in matching club coats, ",
    "He knows which stop on the M6 does the decent coffee, ",
    "A hotel room in Barnsley with the curtains shut at three in the afternoon, ",
    "Two nights away for a game ninety miles up the road, ",
    "Police escort through a town where nobody wants them, ",
    "Somebody snores on the coach and everybody has known about it for years, ",
    "Six hours on a Thursday to play in front of four thousand people, ",
    "Team meeting under somebody's wedding table plan, ",
    "Alan has been kit man here thirty-one years and remembers every one of them, ",
    "His shirt is hung up before he arrives, number and all, ",
    "Two women in the laundry call him love and take absolutely nothing from him, ",
    "A fifteen-year-old cleans his boots and will not meet his eye, ",
    "Bob on the mowers has views on how they play and shares them, ",
    "A chef who has cooked for four managers and outlasted all four, ",
    "Reception knows his mother's name and asks after her every Monday, ",
    "Somebody has moved his peg two places down the dressing room, ",
    "An extra pair of socks appears in his bag every week, has done since October, and nobody has ever once mentioned it to him, ",
    "Sammy the masseur is sixty-eight and has told the same joke since October, ",
    "An analyst younger than he is has cut him a twelve-minute video, ",
    "Left boot first. It has been left boot first since he was nine, ",
    "Same playlist, same order, no shuffle, ",
    "He touches the top of the tunnel doorway going out. Every time, ",
    "Toast at ten past eight, two slices, no butter, ",
    "Haircut on a Friday whether he needs one or not, ",
    "He will not tie his laces until the buzzer goes, ",
    "Same shinpads as two seasons ago, cracked down one side, ",
    "Last out of the tunnel. It was an accident once and now it is a rule, ",
    "A wristband he has not taken off since the play-off semi-final, ",
    "Three touches of the crossbar in the warm-up, ",
    "Game forty-one of forty-six, and it is still only March, ",
    "Boxing Day away, then the twenty-eighth at home, ",
    "Three games in seven days with four hundred miles in the middle, ",
    "At some point the season stopped being a set of matches and became a corridor, ",
    "February, and the pitch has not been properly green since November, ",
    "Nineteen games in and he has started every one of them, ",
    "Fixtures came out in June and he read the whole thing like a sentence handed down, ",
    "Two days off in eleven weeks, and one of them is a travel day, ",
    "There is a Tuesday in this run that he genuinely cannot remember, ",
    "August felt like a beginning. It is January and nothing has begun, ",
    "Everyone is counting down to the international break like a holiday, ",
    "By April his body knows what day it is before he does, ",
    "A centre-half of thirty-four who has done this eleven hundred times, ",
    "For the first minute the man marking him talked about his own career, ",
    "Elbows in the first tackle, and a nod afterwards, ",
    "He got kicked for ninety minutes by somebody who never went in the book, ",
    "A right-back who talks the entire game and never once stops running, ",
    "Being told exactly what he is going to do before he does it, ",
    "Nobody dives in any more. They wait, and they wait, and then they take the ball off him without appearing to try, ",
    "He is up against a keeper who was in a World Cup squad in 2010, ",
    "Somebody grabbed his shirt at a corner and held it for four seconds, ",
    "He has stopped being the youngest man on the pitch, ",
    "Eight games, they say the manager has. Everyone is counting them, ",
    "Three of the staff cleared their offices on a Monday morning, ",
    "His best mate at the club was sold on deadline day at half eleven at night, ",
    "A new signing arrives who plays exactly where he plays, ",
    "His dad still asks whether he gets the Saturday off, ",
    "In came the chairman, which has not happened once in fourteen years, ",
    "Nobody has said the word sacked and it is the only word in the building, ",
    "A caretaker for three weeks who keeps calling everyone by their surname, ",
    "New manager watched a full session and said nothing to anybody, ",
    "Two lads he shared a room with all last season are at other clubs now, ",
    "There is a fee agreed for somebody and the somebody does not know yet, ",
    "His name is in a bracket in a paragraph about somebody else's future, ",
    "Eighteen months left, and the club has not opened a conversation, ",
    "An agent who ignored him in October rings twice, ",
    "Coffee with the captain, who asked him what he actually wanted, ",
    "Contract talks are a phrase in a newspaper and nothing in his life, ",
    "He is out of contract next summer and everyone knows except his mother, ",
    "A club three divisions up sent someone to watch him and did not say so, ",
    "His grandad has a scrapbook and gets the clippings wrong sometimes, ",
    "Family group chat treats a one-nil away like a school sports day, ",
    "His sister has stopped coming because of what people shout, ",
    "Home for Sunday dinner, and nobody mentions the game at all, ",
    "Dad has an opinion about the formation and has had it since October, ",
    "His mum keeps the shirts in a drawer, folded, unworn, ",
    "Nan tells the neighbours he is doing well, love, when he is not playing, ",
    "Lads he grew up with are three years into apprenticeships and mortgages, ",
    "Twenty-eight tickets requested for an away game with an allocation of twelve, ",
    "Somebody at home is telling people they are close and they are not, ",
    "He has a shirt number now and people expect to see it, ",
    "Seventeen. The eight went to a man they paid two million for, ",
    "Nobody claps him off the pitch any more, which is a kind of arrival, ",
    "Four hundred and twelve minutes without a goal and counting, ",
    "Under-eighteens call him by his surname now, ",
    "He is on the list for the first-team photograph, third row, second from the left, ",
    "His name is on the tunnel wall, printed, not written, ",
    "The stewards nod him through without checking, ",
    "Somebody in the crowd shouted his name and it was not encouragement, ",
    "Man of the match: a bottle of something and a photograph by the sponsor board, ",
    "He had eleven touches on Saturday and heard about all eleven on Monday, ",
    "Day after a game: walking, stretching, nothing, ",
    "Video runs long and it is all defending set pieces, ",
    "Small-sided game on a Thursday, bibs, and it means more than it should, ",
    "Steve has a new whistle, ",
    "Wednesday: gym, shape work, in for half nine, out by one, ",
    "Nobody has explained why he was taken off and he has not asked, ",
    "Team sheet goes up at two and he reads it from the bottom, ",
    "Substituted at sixty-two and the number went up before he saw it, ",
    "Named on the bench for a home game he assumed he was starting, ",
    "Warming up along the touchline in front of the away end, twice, ",
    "Told on the Thursday, which is a kindness, that he is not playing Saturday, ",
    "He trained badly on Tuesday and it will not be forgotten by Saturday, ",
    "Good morning in the corridor, and nothing else, all week, ",
    "Cones out at twenty to ten in sleet, ",
    "A double session, and the second one is the one nobody talks about, ",
    "First team is not a place. It is a Thursday afternoon that keeps arriving, ",
    "Twelve months ago this dressing room went quiet when he walked in, ",
    "He is expected to speak at half time now, ",
    "There is a bare patch at his own ground he could find blindfolded, ",
    "Nine thousand people, and he can hear one man behind the dugout, ",
    "Away support of four hundred and thirty in a corner, singing all game, ",
    "Kick-off at twelve thirty and he has been awake since half five, ",
    "Floodlights on at half past two in December, ",
    "Rain since Thursday, and the ball is not going to bounce today, ",
    "Playing in a stadium where his dad watched from the terrace in 1994, ",
    "A pitch inspection at nine and nobody knowing until eleven, ",
    "Somebody's testimonial on a Sunday, and he is in the squad for it, ",
    "Whoever the testimonial is for played eleven years here and won nothing at all, ",
    "A minute's applause before kick-off for a supporter he never met, ",
    "Tunnels are narrower than they look on television, ",
    "He has an actual squad number in the programme, in bold, ",
    "Signing an autograph for a boy the age he was when he signed, ",
    "Registered, insured, contracted, and listed on a spreadsheet in an office he has never seen, ",
    "A drugs tester waiting outside the dressing room after training on a Tuesday, ",
    "Two hours to produce a sample and a man watching, ",
    "An app wants to know where he sleeps, ",
    "An FA charge for something he said in the tunnel, ",
    "Booked for the fifth time, which means a Saturday off he did not want, ",
    "Sent off in the eighty-first and the walk is longer than he expected, ",
    "Three-match ban, and the first game of it is on television, ",
    "A hearing on a Wednesday in a hotel near Wembley, ",
    "Fined two weeks' wages by the players' committee for being late twice, ",
    "Fines list on the wall, and he is on it twice, ",
    "Twenty pounds for a phone going off in a team meeting, ",
    "He has been at this club since he was eight and it feels like a job now, ",
    "That badge on his chest was on his bedroom wall for eleven years, ",
    "Nobody tells you that the thing you wanted becomes the thing you do, ",
    "Monday morning, and the game on Saturday is already gone, ",
    "It is a job, with a start time and a car park and a canteen. It is also the only job he ever wanted. Both, ",
    "Four years of this and he will be twenty-five, which is not young, ",
    "Careers end. Everyone in the building knows somebody it happened to, ",
    "Alan the kit man was a player here once, apparently, ",
    "A coach on the staff played four hundred games and now drives the minibus, ",
    "He watched a thirty-three-year-old get released in May, ",
    "Reserve keeper is thirty-six and doing his badges on Mondays, ",
    "Somebody asked what he would do otherwise and he had no answer at all, ",
    "He has started keeping the match programmes, which he never used to, ",
    "A season ticket holder gave him a photograph of himself aged twelve, ",
    "Fifty-eight appearances, four goals, and a folder of clippings his nan keeps, ",
    "Reserves at a non-league ground, Tuesday, ",
    "Dropped to the bench, then out of the squad, then back in, in a fortnight, ",
    "Eighty-nine minutes on Saturday and he is not even tired on Sunday, ",
    "Nothing happened in the game. Nothing happens in most games, ",
    "A nil-nil in the rain in front of six thousand, and it counts the same, ",
    "One point in five, and the manager has changed the shape three times, ",
    "Bottom four in October, which nobody at the club had planned for, ",
    "Six points off the play-offs with fourteen to go, ",
    "They have not won away since the second of December, ",
    "Four hundred travelling fans applauded them off after a four-nil, which was worse, ",
    "Booed off at half time in his own stadium, ",
    "A winner in the ninety-fourth and the noise arrives about a second late, ",
    "Beat the team above them and it changed nothing by Tuesday, ",
    "Promotion is arithmetic now, and somebody has done the arithmetic on a whiteboard, ",
    "Eleven games left and the manager has stopped talking about the table, ",
    "He is in a relegation fight for the first time in his life, ",
    "Winning ugly, which he had heard about and never done, ",
    "Cup draw on a Monday night, and they get a non-league side away, ",
    "A third-round tie on television against a club he supported as a boy, ",
    "Out of the cup on penalties and back on the coach by ten, ",
    "He took one and it went in and nobody has mentioned it since, ",
    "Beaten by a side two divisions below, ",
    "Cup week, and the manager rests seven of them and plays him, ",
    "Wednesday night under lights, forty-one thousand, and he is in the eleven, ",
    "First goal at that end and he did not know what to do with his hands, ",
    "Scored on Saturday. Trained on Monday. Nobody said a word, ",
    "Twenty-four hours after the best game of his life, cones, in sleet, ",
    "An assist that the statisticians took off him on the Tuesday, ",
    "Set-piece duty, which is new, and which he wanted, ",
    "He takes the corners now, both sides, ",
    "Told to press the left centre-half and told it eleven times, ",
    "A tactical instruction he does not agree with and will carry out anyway, ",
    "Man-marking somebody for ninety minutes and touching the ball nine times, ",
    "Played out of position on Saturday and did well, which is a problem, ",
    "Filling in at right-back because two men are injured, ",
    "Ten yards deeper, the manager wants him, and half his game has gone with it, ",
    "New coach, new patterns, and eleven men learning them in three days, ",
    "His role has a name on a whiteboard, ",
    "Shouted at by his own captain in front of eleven thousand people, ",
    "A senior pro told him at the training ground gate to sort his first touch out, ",
    "Nobody talks in the dressing room after a bad one for about nine minutes, ",
    "Louder after a draw than after a win, that room, and after eighteen months of it he has stopped asking anybody why, ",
    "Somebody put a fine on him for celebrating against his old loan club, ",
    "Two of the lads have children and talk about nothing else, ",
    "He is the youngest in a room where the average age is twenty-nine, ",
    "Fourteen years the goalkeeper has been here, and nobody has heard him raise his voice, ",
    "A senior player has stopped speaking to the manager and everyone can see it, ",
    "Two of them had to be separated on the training pitch on Thursday, ",
    "Nobody sits in Chalky's seat and Chalky left in July, ",
    "There is a lad in the squad who has not played since September, ",
    "He gave a debutant his shirt on Saturday, which is a thing he had thought about doing since he was about fourteen, ",
    "There is an order to that room, unwritten, unbending, and he has worked out roughly where in it he sits, ",
    "Christmas Day training at eleven, then a hotel, ",
    "New Year's Eve in a Travelodge with a two o'clock kick-off tomorrow, ",
    "His girlfriend's family are all at a wedding he cannot attend, ",
    "A friend's stag do he has said no to twice now, ",
    "Everybody he knows is out on a Friday and he is asleep by ten, ",
    "Sunday is a day off if the result was right, ",
    "Two empty weeks in June, ",
    "Pre-season starts on the fourth of July and the date is on his fridge, ",
    "Back in for testing and he has been running since the third week of the break, ",
    "Austria: four games, one pitch, ",
    "Double sessions in thirty degrees and a bleep test on the Friday, ",
    "New signings arrive in July and he is one of the ones showing them round, ",
    "Twenty-one and there are four players in the squad younger than him, ",
    "A sixteen-year-old came up to train and did something he could not do at sixteen, ",
    "He is somebody's example now, which he has not adjusted to, ",
    "Academy lads clean the first-team boots and he can remember doing it, ",
    "A trialist all week, and no name, ",
    "Rain on the training pitch at ten past nine on a Tuesday in March, ",
    "Everyone in at eight tomorrow. No reason given, ",
    "A day off cancelled by text at nine on a Sunday night, ",
    "Sat in the car park for ten minutes before going in, ",
    "Forty minutes to training and he does it with the radio off, ",
    "He has developed a habit of arriving ninety minutes early, ",
    "First in, most days, which nobody has noticed and he prefers that, ",
    "Somebody has parked in his space and he genuinely does not mind, ",
    "Canteen does a roast on a Thursday and it is the best thing about Thursdays, ",
    "Urine test, body fat, and a questionnaire, before ten, ",
    "Rate your sleep out of ten, says the app, before eight every morning, ",
    "Heart rate monitor on, GPS vest on, and every metre of it logged, ",
    "He ran twelve point one kilometres on Saturday and it is on a printout, ",
    "According to the numbers he is slower in the last fifteen than he was in August, ",
    "His numbers, next to somebody else's, in a meeting, ",
    "Twenty-two years old on Thursday and there is a cake in the canteen, ",
    "His agent has a plan for him and the plan involves other people's clubs, ",
    "A phone call from a number he does not recognise about a move abroad, ",
    "Interest, they keep saying. Interest, and nothing else, ",
    "January comes and everyone in the building looks at everyone else, ",
    "Loaned out for half a season would solve a problem for the club, and a different one for the man ahead of him, and nothing at all for him, ",
    "Deadline day, and he sat with his phone face down on the kitchen table, ",
    "Nothing happened on deadline day, which is also a thing that happens, ",
    "Window shut. He is still here. So is the man ahead of him, ",
    "A club he has never been to has offered him more money than he has ever seen, ",
    "He would have to move two hundred miles, on his own, in January, and not one person involved has asked him whether he wants to, ",
    "Being wanted somewhere else is a strange way to be told you are doing well, ",
    "Half a season on loan taught him what a bad dressing room sounds like, ",
    "A striker came in on loan and took his place in eleven days, ",
    "Whoever replaced him is on ten grand a week more and is worse, ",
    "Saturday, in a club suit, in the stand, ",
    "Not in the eighteen, and the walk out of the ground afterwards is very long, ",
    "Nineteen unused minutes on the bench and a bib he never took off, ",
    "Warmed up four times and did not get on, ",
    "Three minutes at the end of a five-nil, ",
    "He has stopped looking at the bench when he is playing badly, ",
    "Eleven weeks without a start, and the training is the only thing keeping him honest, ",
    "A run of five starts and he can feel the difference in everything, ",
    "It has taken him fourteen months to be picked without it being news, ",
    "Nobody claps a good pass any more, which is how he knows he belongs, ",
    "There is nothing about this that is a surprise now, and that is the surprise, ",
    "He has been booed and cheered by the same eight thousand people in one afternoon, ",
    "His name goes out over the tannoy before kick-off and the noise that comes back is neither one thing nor the other, ",
    "A ball boy asked him for his gloves and he had already given them away, ",
    "Sunlight at three o'clock in October across half the pitch, ",
    "One floodlight in the corner has been broken since he was fifteen, ",
    "There is a pigeon that lives in the roof at the away end, ",
    "Kick-off delayed eleven minutes for crowd congestion, ",
    "Somebody threw a coin and the referee took both teams off, ",
    "A referee who spoke to him by his first name the whole game, ",
    "Linesman got it wrong and there is no camera at this ground to prove it, ",
    "Nine minutes added on and they were leading by one, ",
    "Extra time on a Tuesday in November with work on Thursday, ",
    "He has learned the referee's name before the game now, which is new, ",
    "A goal chalked off and the fourth official would not look at him, ",
    "Moved to a Sunday for television. Again, ",
    "A Friday-night game gives them an extra day and nobody knows what to do with it, ",
    "Two thirty on a Saturday is not the kick-off time any more and it never will be again, ",
    "Nine three o'clock Saturdays in a season, ",
    "Television cameras at training on a Thursday, filming the warm-up, ",
    "A documentary crew has been in the building since August, ",
    "Somebody miked him up for a friendly and he said almost nothing for ninety minutes, ",
    "A sponsor's evening on the one night of the week he had nothing on, ",
    "A supermarket opening at eleven on a Saturday morning before a night game, ",
    "A junior presentation night, and a few words expected, ",
    "Four hundred school children in a sports hall and one of them asked what he earns, ",
    "Community department want him for a coaching session in a car park in February, ",
    "Next season's kit, shot in April, in a coat, ",
    "Sponsor changed their name and every shirt had to be reprinted, ",
    "New kit unveiled in May and his is not one of the shirts on the poster, ",
    "He has three pairs of boots from a company that has stopped answering emails, ",
    "A boot deal worth less than a month's wages that he would not give up for anything, ",
    "Somebody sends him free trainers now and he has no idea why, ",
    "Groin, hamstring, calf, ankle. Four words that run his year, ",
    "First job of the morning is finding out what hurts, ",
    "He can no longer play three in six days without paying for it, ",
    "Learning what a niggle is, which is a word that means eight weeks eventually, ",
    "Eleven of the squad are in the treatment room on a Monday morning, ",
    "A surgeon's secretary rang about a date for the scope, ",
    "Six weeks in a boot, and the boot comes off next Tuesday, ",
    "Watching his own team play from a treatment table with the sound off, ",
    "He has done more running injured this month than fit, ",
    "First tackle back is the whole thing, and everybody in the building knows it, ",
    "Back on the grass. Alone. Straight lines, ",
    "Cleared to play and nobody has said the word ready, ",
    "Sixty-eight minutes in a reserve game to get his legs back, ",
    "A yard short. Everyone can see it and nobody will say it, ",
    "There is a programme with his name on it that runs past the end of the season, ",
    "He is insured for an amount somebody mentioned once and he has not forgotten, ",
    "An asset, somebody upstairs called him, ",
    "Somebody upstairs calls the squad the playing budget, ",
    "There is a transfer valuation on him and he has heard the number, ",
    "Eighteen thousand people paid to watch him work on Saturday, ",
    "A grown man in the second row calls him by his first name every home game, ",
    "Whoever writes the programme has been writing it since 1979, ",
    "Two lads from his year group in the academy are working in a warehouse now, ",
    "He is the only one from that under-sixteens photograph still at the club, ",
    "There were fourteen of them at fifteen. There is one, ",
    "A message from a lad he came through with, asking about trials, ",
    "He has started replying to those messages properly, which takes an evening, ",
    "His old youth coach still texts after every game, three words, always, ",
    "Nobody prepares you for the Wednesdays, ",
    "Married men in the squad talk about school runs and he listens, ",
    "Senior lads go home after training. The young ones stay for pool, ",
    "He does not stay for pool any more, ",
    "Everything closes at four and the afternoon is very long, ",
    "A whole day off in the week and nowhere in particular to be, ",
    "He has taken up golf badly, like everybody else, ",
    "They offered him an Open University course, business studies, two evenings a week, and he binned the leaflet in the car park on the way out, ",
    "There is a badge he could start doing on Monday evenings, at twenty-one, ",
    "A PFA course on money, and eleven of them signed up for it, ",
    "He can drive, cook two things, and finish a season. That is the list, ",
    "Nobody tells you how much of it is waiting, ",
    "Forty minutes on a hotel bed with the curtains drawn, waiting for a coach, ",
    "Two hours between the meeting and the meal, and nothing in them, ",
    "He has read more books in one season of hotel rooms and coach journeys than in the whole of the rest of his life put together, ",
    "Younger ones play cards. He looks out of the window, ",
    "Same three songs before every game since he was nineteen, ",
    "A superstition about which peg he uses that has survived two dressing-room refits, ",
    "Shirt goes on last — after the shorts, after the socks, after everything, ",
    "He will not step on the line coming out and he has never told anyone, ",
    "Gum before kick-off, spat out on the halfway line, every match, ",
    "A pair of gloves he has worn since a game he played well in, in a match in March, ",
    "He shakes the referee's hand before anyone else does, deliberately, ",
    "Nine minutes in the warm-up doing exactly what he did at fourteen, ",
    "Alan knows the routine better than he does and has it laid out by half twelve, ",
    "There is an order to the room and he learned it by getting it wrong, ",
    "Cold water on the back of the neck before he goes out, ",
    "Boots done up, undone, done up again, ",
    "His father drove him to games for eleven years and now watches on a laptop, ",
    "Two hundred appearances gets you a plaque on the corridor wall and a handshake in the boardroom, and he is roughly a quarter of the way there, ",
    "Some of this is going to be the best of it and he cannot tell which part, ",
  ],
};
export const SETTINGS_R: Bank = {};
export const CHILD_SETUP_R: Bank = {};
export const EVENT_PREFIX_R: Bank = {};
export const BIG_SETTINGS_R: string[] = [];
