// Authoring pack Q. One author owns this file — nobody else writes to it, so packs never collide.
import type { Bank } from '../merge.js';
export const KIND_SETUP_Q: Bank = {};
export const DEMAND_Q: Bank = {};
export const FRAME_Q: Bank = {
  'First Team': [
    'Payday lands and the number still looks like a typo, ',
    'The mortgage application asks him to state his occupation, the length of his contract, and what he expects to be doing at forty, ',
    'Four hundred quid on a coat, and he put it back on the rail, ',
    'An accountant he has met twice knows more about his life than his mother does, ',
    'Nobody at the bank believes the salary figure until they see the paperwork, ',
    'He bought his mum a car and she has driven it once, ',
    'The lads talk about pensions in the physio room, which is somehow the strangest part, ',
    'Standing in a kitchen showroom on a Tuesday, being asked about worktops, ',
    'Money arriving faster than he can think of anything sensible to do with it, ',
    'His old wage from the youth deal would be a week of this, ',
    'Two brothers, one of whom now asks, and one of whom never will, ',
    'Leather folder, confident handshake, financial advice, ',
    'The rent on the flat he grew up in, cleared in an afternoon, ',
    'Signing for a parcel in a house that is too big for one person, ',
    'Three defeats on the spin, and the manager has stopped doing the Friday joke, ',
    'The staff car park empties earlier than it used to, ',
    'A board statement of full support went out at four o’clock, which everybody understood, ',
    'Training was shorter today, and nobody asked why, ',
    'The gaffer went round the room one by one on Friday, told each of them what he wanted, and got to him fourth, ',
    'A television crew was already outside the gates at nine in the morning, ',
    'His name in the manager’s team notes, written in biro, underlined twice, ',
    'The assistant took Thursday’s session, and said the gaffer had a meeting, ',
    'Being asked, at twenty-one, what the mood in the dressing room is like, ',
    'A new man comes in on Monday and every shirt is up for grabs again, ',
    'Coaches he has known for four years, who ran him at fifteen in the rain, cleared their desks by lunchtime on the Monday, ',
    'They kept the fitness coach and let go of everyone else, ',
    'The interim gaffer used to take him for under-18s on a Wednesday, ',
    'Everything he was taught for six years is now the wrong way of doing it, ',
    'His contract has eighteen months on it and a local paper ran the number before he did, ',
    'An agent he has not spoken to in a year is suddenly very available, ',
    'Sat in a room while two men who are not him discuss what he is worth, ',
    'The club want an answer by the end of the international break, ',
    'Reading about his own release clause on his phone in a hotel corridor, ',
    'His dad has opinions about the contract and none of them are useful, ',
    'Somebody leaked the talks, and it wasn’t him, ',
    'A phone number for a club up north, given to him by someone who shouldn’t have, ',
    'Loyalty bonus, appearance clause, a page of things he does not fully understand, ',
    'The chairman shook his hand at a charity thing and said nothing about the contract, ',
    'The centre-half he faced on Saturday has been doing this since before he could shave, ',
    'Ninety minutes of an elbow finding the same rib, ',
    'Learning that the shirt-pull happens before the ball arrives, not after, ',
    'A man of thirty-four talked to him for the whole of the first half, quietly, close to his ear, and never once about football, ',
    'They put the smallest full-back in the league on him and it worked, ',
    'He has started watching where the referee is before he goes down, ',
    'Two studs down the back of the calf in the eleventh minute, no free kick, and eighty more to get through, ',
    'The opposition captain shook his hand after and got his name wrong, ',
    'Nobody warned him how loud men are on a pitch with four thousand people in it, ',
    'He is stronger than he was in April, and it is still not enough, ',
    'A physio’s assessment on a Monday morning, and the word scan said too casually, ',
    'Six weeks, they said, which everyone knows means eight, ',
    'Ice, elevation, and a Saturday spent in a tracksuit in the stand, ',
    'A hamstring he has mentioned to nobody, ',
    'The physio bed, sound off, ',
    'He knows now that his left ankle tells him what the weather is doing, ',
    'A club doctor asking him to rate the pain out of ten, on a Monday, before a Saturday he wants, and him lying, ',
    'The strapping goes on before every session now, and it is not coming off, ',
    'Rehab is two lads, a resistance band, and a corridor, ',
    'Somebody in the crowd shouted that he was faking it while he was still on the floor with the physio kneeling over him, ',
    'Back in training on the Thursday, and going into the first tackle a fraction late, ',
    'A specialist with a twelve-week waiting list that the club somehow skips, ',
    'Two lockers down, emptied on a Wednesday, and nobody says anything at breakfast, ',
    'The lad he shared a room with on every away trip since he was seventeen signed for a club in Belgium on Monday morning, ',
    'A group chat with eleven people in it and four of them at other clubs now, ',
    'They sold the captain in January and told the players through the club website, ',
    'His best mate at the club got a move and he is expected to be pleased about it, ',
    'Deadline day, and his phone going off about somebody else, ',
    'A signing who plays exactly where he plays, ',
    'The kit man took one name off the back of a shirt and put another one on, ',
    'His mum still asks whether he gets Christmas off, ',
    'Back at his nan’s on a Sunday, eating off the same plates, ',
    'An uncle who has never watched a full match tells him where he went wrong, ',
    'They ask what he does all day, since the game is only on a Saturday, ',
    'His sister’s wedding is on a Saturday in October and he cannot go, ',
    'Dad has a scrapbook and has not told him about it, ',
    'Coming home to a street where he is still the lad from number forty-one, ',
    'Nobody in the family says work about it, even now, ',
    'A cousin wants twelve tickets for the game on Saturday and does not understand, and will not accept, why that is a problem, ',
    'His mother has framed the debut programme and hung it in the downstairs loo, ',
    'Forty-six league games, and this is the twelfth, ',
    'Tuesday, Saturday, Tuesday, Saturday, since the second week of August, ',
    'Four hours on a coach to play at seven forty-five on a Tuesday, ',
    'The Sunday after a Saturday is not a day off, it is a swim and a bike, ',
    'He has slept in eleven hotels since the season started, ',
    'Christmas dinner at one o’clock, on a plate, at the training ground, ',
    'Boxing Day away at a place he could not find on a map, ',
    'The fixture was moved to Sunday lunchtime for television and nobody asked anybody, ',
    'Two hundred miles up, two hundred back, and in his own bed by four, ',
    'February, and the pitches have gone, and the games keep coming, ',
    'Number eight, and people expect to see it on the team sheet, ',
    'A shirt with his name on it in the club shop window, ',
    'A boy waiting outside the players’ entrance in the rain had his name across the back of a shirt, spelt wrong, ',
    'He is in the programme now under senior squad, not development, ',
    'They put him on the season ticket poster without asking, arms folded, in a kit the club has not worn since August, ',
    'Nobody calls him son now, ',
    'His picture is on the wall of the corridor between the gym and the canteen, next to a lad who left for Scotland in January, ',
    '"It goes quick," said a man with four hundred appearances, and left it there, ',
    'The kit man has been here thirty years, remembers every one of them, and has an opinion about each that he keeps to himself, ',
    'Being asked to speak first in a team meeting for the first time, ',
    'A testimonial for a lad who came through the year he was born, ',
    'He knows which of the senior lads to sit next to on a bad coach journey, ',
    'The captain pulled him aside by the tunnel and said six words, ',
    'The lads have stopped hiding his boots, which means something, ',
    'There is a bloke in the squad older than his dad was when he was born, ',
    'A phone-in has decided he is the problem, ',
    'Somebody wrote his surname on a bedsheet and hung it over a hoarding, ',
    'A local reporter who used to be nice to him has stopped being nice to him, ',
    'Six minutes of him on the highlights and four of them are the mistake, ',
    'He has been asked for a photograph in a petrol station at half eleven at night, ',
    'The away end sang about him for a full minute, and none of it was kind, ',
    'People shout his name in a supermarket and expect a wave, ',
    'A supporters’ club dinner in a function room, and a speech he did not write, ',
    'The training ground has a new coffee machine, ',
    'Somebody has repainted the lines on the training pitch and they are slightly wrong, ',
    'Gravel car park, ruined shoes, ',
    'His boots come in a box with his name printed on the side now, ',
    'There is a leak in the away dressing room at the ground they play at on Saturday, ',
    'The bus leaves at twenty past nine and it always leaves at twenty past nine, ',
    'Nine in the morning, gym, and the radio on in the corner, ',
    'A sponsor’s photograph, holding a shirt, smiling on a count of three, ',
    'He drives past his old school on the way to training every morning, and there is a boy at the gate who waves, ',
    'A man from a boot company wants to know what colour he prefers, ',
    'Media training, in a room with a camera on a tripod and a woman with a clipboard, ',
    'Hospital visit on a Thursday, and a ward he cannot stop thinking about, ',
    'A school in the town centre, thirty children, and a question about how much he earns, ',
    'Eleven minutes off the bench in a game in November, and that was the whole month, ',
    'Dropped for the derby, and told forty minutes before kick-off, ',
    'He has played left-back twice this season and neither went well, ',
    'Told he is on the bench again, and told it kindly, which is worse, ',
    'The analyst has a clip of him ready and the room goes quiet, ',
    'A GPS vest that says he ran less on Saturday than he thought he did, ',
    'Numbers on a screen telling him what his own legs did, ',
    'His first goal for the club went in off his knee and he does not care, ',
    'He took the penalty because nobody else moved, ',
    'Captain for a Tuesday night cup tie, and the armband is too big, ',
    'Fourth round away at a top-flight side, live on the television, ',
    'They are three points off the bottom in March, ',
    'A win on Saturday and the whole building smells different on Monday, ',
    'Play-offs, or nothing, and eight games to sort it out, ',
    'Referees know his name now, ',
    'Two yellows in three weeks, and a quiet word about his tackling, ',
    'A disciplinary hearing on a Tuesday over something he said in the tunnel, ',
    'Fined two weeks’ wages by the club for being late twice, ',
    'A chef at the training ground who weighs his rice, ',
    'No bread after Wednesday, apparently, ',
    'A sleep coach, of all things, ',
    'He has not slept properly on a Friday since he was nineteen, ',
    'Twenty past eleven and still awake with the game going round, ',
    'His girlfriend has a job with normal hours and it makes both their lives odd, ',
    'Friends from school have stopped inviting him, assuming he is busy, ',
    'The lads he grew up with have jobs now, and vans, and Saturdays of their own, and have stopped asking how it is going, ',
    'Somebody from his year group works at the ground on matchday, stewarding, ',
    'He does not know how to talk about anything except football at a dinner table, ',
    'A tax bill arrives in January that nobody prepared him for, ',
    'Two cars, one driven, ',
    'An alarm system he cannot work, ',
    'He still puts the left sock on first, and would not say that out loud, ',
    'Same seat on the coach since August, and everybody knows it, ',
    'A call-up to the under-21s that means two more flights in a busy month, ',
    'An international break, and the training ground down to six players, ',
    'A stadium with nobody in it, on a Tuesday afternoon, in another country, ',
    'The academy lads clean his boots and one of them is very good, ',
    'A sixteen-year-old trained with the first team on Thursday and did not look out of place, ',
    'Two loan lads arrived in January and neither has unpacked, ',
    'The reserve fixture is at one o’clock on a Monday, and he might be in it, ',
    'Six thousand people, and he can hear one of them clearly, ',
    'An away trip where the floodlights failed for eleven minutes, ',
    'The pitch at Fleetwood in January, ',
    'He has been booed off at home once, and remembers the exact minute, ',
    'Applause on the seventy-fourth minute for a substitution, and he cannot tell what kind, ',
    'Warming up in front of the away end with the ball coming back at him, ',
    'The tunnel at three o’clock, and the noise arriving before the light does, ',
    'A minute’s applause for a supporter who came to every game for fifty years, ',
    'Black armbands on Saturday, and none of the lads knew the man, ',
    'His agent has a new client, seventeen, and talks about him constantly, ',
    'Somebody offered him an appearance fee for opening a car showroom, ',
    'An email from a charity that has clearly been sent to the whole squad, ',
    'Boot money: less than people assume, ',
    'A photographer wants him to hold the ball above his head and look serious, ',
    'His shirt number is on a birthday cake for a kid he has never met, ',
    'Two seasons ago he was cleaning this same dressing room, ',
    'The physio room has the same posters it had when he was fifteen, ',
    'He has been at this club eleven years, since the trials, and it is starting to feel like a fact about him, ',
    'A lad he came through the youth team with is playing non-league on a Saturday, ',
    'Three of the eight who signed scholarship forms with him are out of the game, ',
    'His old youth coach still calls him by his full name, ',
    'Fifty-one appearances since he turned twenty, ',
    'He has played more minutes this season than in the previous three combined, ',
    'Twenty-nine games in, and the legs have started answering back, ',
    'Nine goals, and he is not a striker, and people have noticed, ',
    'One assist in fourteen, and somebody keeps that number, ',
    'The gaffer wants him ten yards further forward and will not explain why, ',
    'A new system on Monday, with cones, and a lot of stopping and starting, ',
    'They have played him out of position for six weeks and it is working, ',
    'He is being asked to do a job he is not sure he is any good at, ',
    'Watching a video of himself losing the ball, twice, with the room watching too, ',
    'A season ticket holder wrote him a letter, on paper, in pen, about a goal in October and what it meant to her father, ',
    'Signing a plaster cast at the hospital gates, ',
    'Somebody’s grandad in the car park who used to play for the club in 1971, ',
    'The old players’ association invites him to a lunch and he goes, ',
    'A framed photograph of a team from 1987 on the corridor wall, and nobody in it he knows, ',
    'Rain since Tuesday, and the training pitches are gone, ',
    'Frost, and the session moved indoors, ',
    'Standing water in the goalmouth, ',
    'The game got called off at two o’clock and he had already eaten, ',
    'Snow in the north, and a coach that left at six in the morning for nothing, ',
    'His phone has two hundred unread messages after a good Saturday, ',
    'And nothing at all after a bad one, ',
    'He has stopped reading anything on his phone between Friday and Sunday, ',
    'Somebody online is pretending to be him, ',
    'The club’s media officer asks him to post something, and drafts it for him, ',
    'Interviewed pitchside, still breathing hard, being asked about the manager’s future, ',
    'Nine seconds to say something that will be repeated all week, ',
    'A journalist rang his mother’s house, on a number he did not know still existed, ',
    'The word wantaway in a headline above a photograph of his own face, taken in March, when he had said nothing to anybody, ',
    'A back page he did not read but everybody assumes he did, ',
    'He is the third-highest earner in the building and the fourteenth-best player in it, ',
    'It turns out the best players are also, mostly, decent men, ',
    'The best player at the club trains hardest, which he had assumed was a lie, ',
    'A man in the squad who has done this at the top and come back down, ',
    'He watched a thirty-three-year-old finish last in every run and start on Saturday, ',
    'Coaching badges, level two, in a classroom in Burton for four days, ',
    'The union sent a booklet about life after football and he put it in a drawer, ',
    'A retired pro came in to talk to the squad and half of them were on their phones, ',
    'Somebody asked him what he would do if it stopped tomorrow, ',
    'Twenty-two, and men he plays with are already working out what happens at thirty, ',
    'Two hours in a dentist’s chair on a Wednesday because there was finally time, ',
    'A passport renewal, an occupation box, and a word he still writes carefully, ',
    'Filling in a form that asks for the name of his employer, ',
    'The bank wants three months of payslips and he has never had a payslip, ',
    'A letting agent who does not believe a word of it, ',
    'His dad works Saturdays and has seen four games all season, ',
    'Both parents in the family stand, and he can find them in eight seconds, ',
    'Mum will not watch when he takes a set piece, ',
    'They drove three hundred miles to watch him not come on, ',
    'His nan died in February, the club sent flowers, and the manager mentioned it once, briefly, in front of everybody, ',
    'A twelve o’clock kick-off, live, and the shops in town shut for it, ',
    'The fixture list came out in June and he read it like a novel, ',
    'Ninety minutes on a Sunday teatime in front of cameras, and the pitch cutting up, ',
    'A cup replay squeezed into a Tuesday that was supposed to be off, ',
    'The broadcasters moved it again, and the club put out a statement apologising to the supporters, ',
    'He has a routine now, and the routine is most of it, ',
    'Same café, same order, half nine, ',
    'Ninety-two minutes played, then a warm-down on a cold pitch in front of an empty ground while a man rakes the goalmouth, ',
    'Someone in the crowd shouted for a shirt and he threw it, ',
    'The last of the stewards locking up as the coach pulls out, ',
    'A trialist, a fortnight, gone, ',
    'A goalkeeper signed on Thursday who does not know anyone’s name, ',
    'Middle row in the squad photograph, ',
    'His name on the board above a peg in the corner, ',
    'Somebody moved his peg two along and he noticed immediately, ',
    'Twenty-one years old and the youngest man in the back four by six years, ',
    'He is the senior player on a Tuesday night team full of teenagers, ',
    'A seventeen-year-old asked him for advice and he had none, ',
    'Explaining to a kid what a bad run actually feels like, ',
    'The apprentices have started calling him by his surname only, the way he used to talk about the men who were here then, ',
    'Six weeks without a goal and a manager who keeps picking him, ',
    'Out of the side for a month, back in through somebody else’s injury, ',
    'He got in the team because a man he likes broke his foot, ',
    'The player he replaced is fit again on Thursday, ',
    'Two of them for one shirt, and they share a lift to training, ',
    'A new stand going up behind the goal, and the noise of it all week, ',
    'Last season’s shirts, half price, ',
    'Attendance eleven thousand and something, announced over the tannoy, ',
    'Somebody at the club has decided the badge needs changing, and there are eleven thousand people in the town who disagree, ',
    'A takeover rumour, and nobody in the building knows any more than the supporters do, ',
    'The wage bill was in the accounts and the local paper printed it, ',
    'A club that has never paid the players late, and everybody mentions that, ',
    'August, thirty degrees, double sessions, and the season a fortnight away, ',
    'Pre-season in a hotel in Austria with one pitch and a lot of running, ',
    'A friendly at a non-league ground where he played as a child, ',
    'The first day back, and the bleep test, and the same joke about it, ',
    'Weighed on the first morning of pre-season in front of everybody, ',
    'He is good at this, on the good days, and knows what that is worth, ',
    'Saturday went well and Monday started at half seven anyway, ',
    'A performance nobody mentioned, which he took as a compliment, ',
    'The gaffer said fine and walked past, and that is the review, ',
    'One touch in the second half that he will think about for a week, ',
    'Everything he does now is written down by somebody, ',
    'And still, on a Tuesday, cones, ',
    'A working footballer, twenty-two, with a shirt number, a bad knee and a mortgage, ',
  ],
};
export const SETTINGS_Q: Bank = {};
export const CHILD_SETUP_Q: Bank = {};
export const EVENT_PREFIX_Q: Bank = {};
export const BIG_SETTINGS_Q: string[] = [];
