// Authoring pack N. One author owns this file — nobody else writes to it, so packs never collide.
import type { Bank } from '../merge.js';
export const KIND_SETUP_N: Bank = {};
export const DEMAND_N: Bank = {};
export const FRAME_N: Bank = {};
export const SETTINGS_N: Bank = {
  'First Team': [
    // — weather —
    'in sleet coming sideways off the sea',
    'on a pitch frozen hard down the shaded flank',
    'after ninety minutes of rain that never once eased',
    'under a sky that had been black since three',
    'in fog that took the far post away entirely',
    'as the wind took every goal kick out for a throw',
    'on an August afternoon nobody had dressed for',
    'in the sort of drizzle that soaks a shirt slowly',
    'as hail rattled off the dugout roof',
    'through a downpour that emptied the open corner',
    'on a night cold enough to see the linesman breathing',
    'in a gale blowing the full length of the pitch',
    'as the rain arrived at half two, exactly as forecast',
    'under low cloud sitting on top of the floodlights',
    'on a still, mild evening in the first week of March',
    "as the sun went down straight into the keeper's eyes",
    'in wind strong enough to lay the corner flags flat',
    'on a greasy surface under fine, steady rain',
    'over frost still lying in one half at kick-off',
    'on the hottest Saturday of the season',
    'as the ball turned heavy somewhere around the hour',
    'behind the wind for forty-five minutes and into it for forty-five',
    'after a morning of rain and an afternoon of sun',
    'in air cold enough to hurt the lungs by the twentieth minute',
    'through a squall that came in off the away end',
    'while steam came off the backs of both sets of players',
    'on an evening warm enough to play in short sleeves in October',
    'in horizontal rain with the covers still off the far terrace',

    // — the pitch —
    'on a surface cut up badly between the eighteen-yard lines',
    'across goalmouths piled high with sand',
    'on a pitch that had held a rugby match on the Friday',
    'over relaid turf still showing in strips',
    'on grass long enough to slow every pass by a yard',
    'over a bobbling, tired end-of-season surface',
    'on a pitch watered far too heavily before kick-off',
    'where the ball skidded on the near touchline and stuck everywhere else',
    'on a surface the referee had inspected twice that morning',
    'across a bald patch in front of the North Stand goal',
    'on a pitch that had been playable at nine and doubtful by noon',
    'while the groundstaff forked the six-yard box at half-time',
    'on turf laid three weeks earlier and not settled',
    'across a slope that only shows itself in the last twenty minutes',
    'on a surface that ate studs',
    'where the paint on the halfway line had already gone',

    // — travel —
    'after four hours on the coach and a stop outside Stafford',
    'off the back of a Tuesday night in Plymouth',
    'having left the training ground at seven that morning',
    'after a flight delayed two hours out of a small airport',
    'in an away dressing room the size of a garage',
    'at a ground the coach could not get near for roadworks',
    'following the longest trip of the calendar',
    'after a pre-match meal eaten at eleven in a hotel by a roundabout',
    'having slept badly in a bed a foot too short',
    'off a coach that had sat stationary for fifty minutes on the ring road',
    'after a service station stop and a walk round the car park',
    'at a stadium three changes and a bus from the station',
    'having beaten the kit skip to the ground by an hour',
    'after a night in a Travelodge overlooking a retail park',
    'on the back of two away trips in five days',
    'having arrived at the ground with fifty minutes to spare',
    'after a warm-up cut short because the coach got lost',
    'after a journey nobody spoke through',
    'having done the same drive four times in three seasons',

    // — officials —
    'in front of a referee who had booked three inside half an hour',
    'with a linesman running the near side on a strapped knee',
    'under a referee who talked constantly and gave nothing',
    'as the fourth official held six minutes over his head',
    'against a referee who let almost everything go',
    'under an assistant who had already been wrong twice',
    'under an official promoted from the league below that summer',
    'as the whistle went for something nobody in the ground saw',
    'after a free-kick moved forward ten yards for talking',
    'in front of a referee the away support had recognised on the team sheet',
    'with a linesman who kept his flag down and was right to',
    'under officials who came out to a chorus and went off to a bigger one',
    'after the referee had a word with both captains before kick-off',
    'past an assistant referee stood square on the shoulder of the last man',
    'past a linesman who never once broke into a run',

    // — the away end —
    'in front of two thousand who had come up on the early train',
    'as the away end sang through the entire second half',
    'backed by a corner of the ground that never sat down',
    'in front of an away section still filing in at twenty past',
    'before four hundred travelling supporters and nine hundred empty seats',
    'to a noise from behind the goal that carried onto the pitch',
    'while the away end taunted the home keeper every time he touched it',
    'in front of the section that had sold out in a morning',
    'beneath a flag draped over the barrier in the top tier',
    'in front of away support penned into a corner behind netting',
    'as the travelling end started up again after going two down',
    'to a drum going in the away end from the eighth minute',
    'in front of supporters who had paid thirty-two pounds to stand in the rain',
    'to whistles from three sides and singing from the fourth',

    // — television —
    'in a Sunday lunchtime kick-off moved for the cameras',
    'below a gantry crew set up over the halfway line',
    'on a Monday night, the ground half empty because of it',
    'under the little red light of the pitchside camera',
    'in a game shifted from Saturday to a Friday at three weeks notice',
    'under a rig on a wire running the length of the stand',
    'in front of a camera walking backwards down the touchline',
    'on the day the broadcast picked their ground as the main game',
    'past an interviewer already waiting in the mouth of the tunnel',
    'in a fixture nobody outside two cities was going to watch',
    'yards from a pitchside reporter crouched by the corner flag',
    'as the studio panel picked over the first half at the break',
    'on a night when the highlights would lead with someone else',
    'tracked down the far side by a cameraman for a full minute',
    "at an eight o'clock kick-off on a school night",

    // — the calendar —
    'in the third game inside seven days',
    "on Boxing Day, three o'clock, everybody there",
    'on a wet Tuesday in November with nothing much riding on it',
    'four games out, the table finally meaning something',
    'in the first week of a season that would run to fifty-two matches',
    'on the last Saturday before the winter break',
    'in a rearranged fixture played on a Wednesday in April',
    'two days after an extra-time cup tie',
    'in the second of three games in eight days',
    'after the window shut and the squad settled as it was going to stay',
    'on the opening day, everybody unbeaten and everybody unfit',
    'at the third attempt, twice postponed',
    'on the twenty-ninth of December, legs gone, points needed',
    'between two international breaks a fortnight apart',
    'in the last home match before the summer',
    'seven days out from a semi-final nobody would talk about',
    'on the Saturday after a midweek in which he played the full ninety',
    'in a fixture that had been moved three times since June',
    'on a Sunday in early May with the season all but done',

    // — crowd and ground —
    "beside a sponsor's board coming loose behind the near goal",
    'in front of a stand still filling at ten past three',
    'at a ground with one corner closed for redevelopment',
    'at a ground where the away tunnel came out at the corner flag',
    'under scaffolding still up on the roof of the main stand',
    'in front of a crowd of nine thousand in a ground built for thirty',
    'after a tannoy cut out halfway through the team news',
    'at a stadium with the pitch six feet from the front row',
    'in front of a full house on a season-ticket renewal weekend',
    'watched by stewards facing the crowd and not the game',
    'at a ground small enough for individual voices to carry',
    'under floodlights on three pylons and a temporary fourth',
    'in front of a crowd that turned on the bench before the half hour',
    'as a queue stood outside the turnstiles at kick-off',
    'in a ground where the dugouts sit below pitch level',
    'past shuttered club shop windows and a concourse packed at ten to five',
    'in front of the sort of crowd that applauds a good clearance',
    'at a ground with a running track between the pitch and the stands',
    'as a supporters group unfurled a banner across the whole lower tier',

    // — the opposition, the marking, the physical side —
    'against a centre-half who has done this for eleven seasons',
    'marked by a man who had played four hundred league games',
    'against a full-back giving away five years and half a yard',
    'up against a defender who fouled early and got away with it',
    'against a side sat in two banks of four from the first whistle',
    'tracked by a midfielder every time he crossed the halfway line',
    'against opponents who had not conceded in six',
    'up against a keeper eight inches taller than anyone else on the pitch',
    'two of them on him every time the ball came in',
    'against a team that had been on the coach since eight that morning too',
    'against a defence that stepped up on every set piece',
    'on a hamstring that had been tight since Thursday',
    'on legs that had done four games in twelve days',
    'both ankles strapped, a session missed on the Friday',
    'after a knock in the warm-up he told nobody about',
    'back out for the second half after ice on the knee at the break',
    'against a man who had been sent off the last time they met',
    'up against somebody who had been in the first team since he was at school',

    // — the manager, the club, the noise around it —
    'under a manager who stood on the touchline for the full ninety',
    'under a manager who had lost four of the last five',
    "with the chairman watching from the directors' box",
    'after a week in which the manager had said nothing to the press',
    'as the bench stood from the first minute',
    'under a caretaker taking his second game',
    'where the assistant did all the shouting',
    'in the week his contract talks appeared in a Sunday paper',
    'watched by two scouts sat together in the back row',
    'after a Friday meeting that ran long',
    'while a new signing watched from the stand, unregistered',
    'in front of a bench of eight, five of them under twenty',
    'with the manager watching from the stand, serving a touchline ban',
    'the week the club announced a loss for the financial year',
    'while a fitness coach counted his sprints from the side',
    'in front of the same three photographers who follow the club everywhere',
    'after a team meeting on the Thursday that went round in circles',

    // — winning ugly, the grind, and the flat lines —
    'in a game that was not going to be a good one',
    'at nought each and an hour gone',
    'in a match settled by a set piece and very little else',
    'grinding out the last twenty minutes a goal up',
    'everybody behind the ball, the clock running down',
    'in the sort of game the league is mostly made of',
    'at nil-nil in the eighty-fourth minute',
    'a goal down and playing badly',
    'in a match neither side deserved to win',
    'two up and playing like it',
    'in the last ten with the crowd whistling for full time',
    'the ball out of play more than it stayed in',
    'in a game of eleven corners and no shots on target',
    'after an hour in which nothing at all had happened',
    'in a scrappy first half nobody would remember',
    'the game stretched, both sides tired',

    // — the small, specific, and useless-but-true —
    'as a plastic bottle rolled across the six-yard box',
    'as the tannoy played the same song it plays every home game',
    'while somebody in the front row shouted the same word for ninety minutes',
    'a seagull stood on the penalty spot for the whole interval',
    'while the ball boy on the far side kept getting it wrong',
    'past substitute boards still showing numbers from ten minutes earlier',
    'beside a substitute sat under a coat',
    'after the ball went into the away end and did not come back',
    'as a smoke flare went off behind the goal at kick-off',
    'in a shirt with the sponsor changed halfway through the season',
    'in the away kit for no reason anybody could see',
    'wearing the third kit because of a colour clash nobody believed in',
    'with a black armband on',
    "after a minute's applause in the seventh minute",
    'shirt numbers peeling off the back by February',
    'in boots he had worn for three months too long',
    'name spelt wrong in the programme',
    'in a shirt heavy with rain by the twentieth minute',

    // — mixed openings, varied length —
    'before a ball had been kicked in anger',
    'inside two minutes of coming on',
    'past a defender who had been booked already',
    'out on the right where the wind was worst',
    'down at a ground with an artificial surface',
    'through the middle of a back four dropping deeper every minute',
    'alongside a captain who had been at the club fourteen years',
    'beside a debutant who had been told at eleven that morning',
    'under a roof that held the noise in',
    'after the equaliser, with everything still to play for',
    'at the near post from a corner taken short',
    'behind a midfield that had stopped running',
    'across a back line stretched thin by injuries',
    'without three of the first-choice back four',
    'off the bench with twenty-five minutes to change it',
    'into the last ten minutes of a game already won',
    'from the first whistle, no easing in',
    'as the substitution board went up with his number on it',
    'seconds after a goal that changed the shape of the afternoon',
    'in a half his side spent entirely in their own third',
    'toward an away end that could see it coming',
    'against ten men for the last half hour',
    'down to twenty-two tired men and a referee',
    'having started the previous eleven',
    'in only his second start of the calendar year',
    'on the day he was named captain for the afternoon',
    'in front of a crowd that had booed the team off the week before',
    'a week after the worst result of the season',
    'past a league table pinned up in the corridor outside',
    'at a club two divisions above where he started',
    'in a ground he had been to twice before as a supporter',
    'twenty minutes after the anthem for a cup tie nobody rated',
    'past a bench that had been on its feet since the interval',
    'as the tunnel filled up before the whistle had gone',
    'in the ninety-fourth minute of five added',
    'as the away support started leaving early and then stopped',
    'over a back four that had been together all season',
    'against a side that had beaten them twice already',
    'in front of a home end that had waited eleven months for it',
    'in a fixture with a hundred and thirty years behind it',
    'in a derby with police horses on the ring road since noon',
    'at a ground where the visitors had not won since the seventies',
    'the day after his old club were on the television',
    'three days before the reserves would use the same pitch',
    'somewhere in the middle of a run of eight without a win',
    'in the second half of a game the manager had described as a must-win',
    'having been substituted at half-time the week before',
    'after a fortnight out with a foot injury nobody could name',
    'in a fixture that would decide very little',
    'in a match that would decide almost everything',
    'a fortnight before the fixture list turned brutal',
    'at the end of a week with two funerals of the game in the papers',
    'overlapped by a full-back every time he checked inside',
    'to a crowd that had already made its mind up about him',
    'under a stand that throws the noise back down',
    'from a throw-in taken quickly while the defence complained',
    'everybody in the ground knowing what was coming next',
    'in the sort of conditions the fixtures are meant to avoid',
    'away at Rotherham',
    'ten men, eighty minutes',
    'nil-nil, eighty-first minute',
    'floodlights on at two',
    'sideways, wet, ugly',
    'a fortnight into pre-season proper',
    'boots swapped at half-time',
    'off a corner nobody attacked',
    'the second Tuesday in a row',
    'on a night when the last train back left at ten past ten and half the away end had to go at eighty-five',
    'against a side who had come up the night before, stayed twenty miles out, and looked like it for an hour',
    'at a ground where the away dressing room has one shower that works and the manager mentioned it in the papers afterwards',
    'in the sort of November week where the pitch was doubtful on Thursday, doubtful on Friday, and perfectly fine by three on Saturday',
    'after a season in which he had started thirty-one league games, four cup ties, and been left out once, in September, for reasons nobody explained',
    'away at a fortress',
    'under a closed roof',
    'on plastic',
    'in front of empty seats',
    'after the international break',
    'past a tiring left-back',
    'in a wind that never dropped below a gale, in a ground open at three corners, on the coldest night of the winter',
    'referee, crowd, weather and fixture list all pulling the same way for once',
    'on the far side, away from the benches',
    'the linesman flat out, the crowd already up',
    'against a team playing their fourth game in eleven days as well',
    'behind a striker who had not scored since October',
    'in a first half played almost entirely at walking pace',
    'in front of a stand that had been renamed over the summer',
    'off an advantage the referee played that came to nothing',
    'after a goal-line clearance nobody was sure had crossed',
    'through a spell of ten minutes when neither side could keep the ball',
    'in weather and light that made the far corner guesswork',
    'in the last home game before a takeover went through',
    'a backlog behind him, a pile-up ahead',
    'at half past twelve on a Sunday with the pubs still shut',
    'to a ground that had held forty thousand in its day',
    'as the home end thinned out at eighty-eight minutes',
    'in the middle of a season with two managers in it',
    'against a promotion side with two thousand travelling',
    'in front of an academy group sat together in the family stand',
    'watched by his old youth-team coach from somewhere in the crowd',
    'in the sixth minute of a game that had been level for eighty',
    'as a physio came on before the ball had gone dead',
    'in a stadium where the tunnel is in the corner and the walk is long',
    'in front of a press box of nine men and one laptop that would not connect',
  ],
};
export const CHILD_SETUP_N: Bank = {};
export const EVENT_PREFIX_N: Bank = {};
export const BIG_SETTINGS_N: string[] = [];
