// Authoring pack A. One author owns this file — nobody else writes to it, so packs never collide.
// Keys must match the bank they extend (see shared/src/prompts/*.ts for the key names and the house voice).
import type { Bank } from '../merge.js';
export const KIND_SETUP_A: Bank = {
  match: [
    "Nil-nil at half-time, and the away end has started to grumble.",
    "Two down with half an hour left, and the gaps are appearing.",
    "The referee has booked three of them already and the game is fraying.",
    "Rain coming sideways off the sea, and the ball is skidding twenty yards.",
    "A one-goal lead, eleven minutes left, and their centre-half has gone up front.",
    "Their full-back has been booked and cannot go near him again.",
    "Floodlights, a Tuesday, and eight hundred people in the ground.",
    "He has touched the ball four times in forty minutes.",
    "The pitch has cut up badly in front of the dugouts.",
    "A penalty has been awarded and nobody has picked the ball up yet.",
    "The game has slowed to walking pace and somebody has to change that.",
    "Their keeper has gone down and is taking his time about it.",
    "An hour gone, level, and both benches are up on their feet.",
    "The wind is holding every long ball up.",
    "He is on a yellow and the man he is marking knows it.",
    "Their captain has started talking to the referee about him by name.",
    "A goal down at home to a side third from bottom.",
    "The ball keeps coming back at them and the clearances are getting shorter.",
    "Injury time, a free-kick in his own half, and the keeper is coming up.",
    "The gaffer is on the touchline pointing at the space behind their left-back.",
    "Third game in eight days, and everybody's legs have gone.",
    "A ball over the top and a footrace he is not certain of winning.",
    "Frost on the surface, and the wrong studs in his boots.",
    "Kick-off in a stadium three times the size of anywhere he has played.",
    "The crowd have turned on their own goalkeeper.",
    "He has a yard on the man beside him and one chance to use it.",
    "Level on the night, behind on aggregate, twenty minutes to find something.",
    "A substitute has come on with instructions to kick him.",
    "The linesman has flagged him offside twice and been wrong once.",
    "The ball sits up nicely on the edge of the box with nobody closing.",
    "Their midfield has stopped tracking runners, and somebody has noticed.",
    "A derby, and the first tackle of the game is about to be made.",
    "Sun low behind the stand, and the keeper cannot see a thing.",
    "The gaffer has changed the shape and nobody looks sure where they are.",
    "Six minutes of added time, and the board has only just gone up.",
    "He has been given the ball with his back to goal and a man on him.",
    "A cup tie against a side four divisions below, on a pitch to match.",
    "The away end is singing and their team cannot get out of their half.",
    "His marker has gone off injured and the replacement is slower.",
    "A long throw coming in, and the six-yard box is full of bodies.",
    "Their best player has drifted into the space he is meant to cover.",
    "Two-nil up, and the game is starting to drift, which is how leads go.",
    "A booking for dissent has left the whole team walking a line.",
    "The game is being played entirely in one half, and it is theirs.",
    "Half-time, and the gaffer has not spoken for two minutes.",
    "A friendly in July that has quietly turned into something else.",
    "Snow banked round the edges, lines swept, and an orange ball.",
    "His side have had one shot and it went into the second tier.",
    "A goal has just been ruled out and nobody in the ground knows why.",
    "The opposition are down to ten and have gone to five at the back.",
    "He is captain for the afternoon and the armband keeps sliding down.",
    "Their winger has beaten the same man three times in ten minutes.",
    "A ball bouncing loose in the middle of the park with nobody near it.",
    "Playing on plastic, in front of a shed, on a night nobody wanted.",
    "The manager is looking down the bench and he can feel it.",
    "Trailing at the break in a game they were expected to win comfortably.",
    "Ninety seconds gone and the tempo is already unpleasant.",
    "A team-mate has gone down and stayed down.",
    "Level, late, and neither side wants the replay.",
    "A quiet ground, a tight game, and one moment coming that everybody will remember.",
  ],
  training: [
    "Frost on the training pitches, and the session going ahead anyway.",
    "A new coach has arrived with a stopwatch and firm ideas.",
    "The gaffer has stopped the drill twice, and it was his fault both times.",
    "Finishing practice, and the keeper is in the mood to embarrass somebody.",
    "Bleep test day, and everybody remembers last year's numbers.",
    "He has been pulled out of the first-team group and put in with the kids.",
    "A double session in thirty degrees on a pre-season tour.",
    "The set-piece coach has drawn something on a whiteboard nobody understands.",
    "Heading drills, and the club doctor standing there counting.",
    "He is being asked to take the long throws, which is new.",
    "A closed session, gates covered, and no explanation given.",
    "The reserve keeper has saved everything for half an hour.",
    "Weights first, pitch second, and his legs already feel wrong.",
    "Somebody has left a tackle in and the session has gone quiet.",
    "The analyst has him in a vest that tracks every yard he runs.",
    "A morning off, cancelled at nine the night before.",
    "The gaffer wants the press to watch this session, which changes it.",
    "Shooting at a wall, alone, an hour after everyone else has gone.",
    "He has been paired with the player keeping him out of the side.",
    "A drill built entirely around not giving the ball away.",
    "Trialists in today, and one of them plays where he plays.",
    "The gaffer has asked him to stay behind, which could mean anything.",
    "Pitches frozen, session moved to the sports hall, boots useless.",
    "Two hundred crosses, and the same instruction after every one.",
    "A running number came back low on Saturday and somebody wants a word.",
    "The new signing's first session, and the group are quietly measuring him.",
    "The under-eighteens have been brought up to make the numbers.",
    "Restarts, over and over, until the shape holds without anyone speaking.",
    "His weak foot, for an hour, in front of everybody.",
    "A fitness coach with a heart-rate monitor and no interest in excuses.",
    "The session is short because the gaffer wants legs for Saturday.",
    "A ten-minute run that everybody dreads more than the ninety.",
    "Cold, dark, and a floodlight out at the far end.",
    "The rehab group is one man on the far pitch while the team play.",
    "Video first: eleven minutes of the same mistake from four angles.",
    "He has been asked to play the role of Saturday's opponent.",
    "A coach shouting at him about where he plants his standing foot.",
    "The lads have a bet running on the crossbar challenge.",
    "Small-sided, three touch, and his first touch has deserted him.",
    "First day back after the summer, and the scales are out.",
    "The under-twenty-threes coach wants him for a game on Monday.",
    "A walk-through in trainers on a Friday, everything at half pace.",
    "Somebody has been timing his sprints without telling him.",
    "He has been asked to demonstrate a drill in front of the group.",
    "Twelve minutes of standing still while a coach explains a press.",
    "He has trained well all week and there is no sign it counts for anything.",
    "An extra session he asked for, on a day off, with one coach.",
    "The nutritionist is in at eight, with printouts and a look.",
    "The pitch is like a car park and the ball will not sit down.",
    "A rondo he has been stuck in the middle of for four minutes.",
    "New boots he has not broken in, and no time to change them.",
    "Sports science want him on the bike, not on the grass.",
    "The captain has started refereeing the small-sided games himself.",
    "A drill designed to make him uncomfortable, which it is doing.",
    "The staff have moved him to the other side of the pitch for the week.",
  ],
  social: [
    "A new lad has arrived and nobody spoke to him at breakfast.",
    "Somebody has been taking the mickey and it has stopped being funny.",
    "The kit man has been let go after nineteen years.",
    "Two hours in a service station three hours from home.",
    "The card school at the back of the coach has grown teeth.",
    "A team-mate has been living out of a hotel for four months.",
    "The apprentices are being made to clean boots the old way.",
    "One of the squad has started praying before games, and it has been noticed.",
    "A birthday nobody has mentioned.",
    "The physio has told him something in confidence about somebody else.",
    "A group chat he has been left out of.",
    "The lads are going out, and the fixture is Tuesday.",
    "A younger player has copied his haircut, his boots and his warm-up.",
    "Somebody has parked in the wrong space and the club are quietly furious.",
    "The senior pros want the music changed and nobody will say it out loud.",
    "A team-mate's marriage is going and everybody can tell.",
    "He is the oldest man in the room for the first time.",
    "Christmas Day training, and a family who have got used to it.",
    "A player has been fined by the group and thinks it unfair.",
    "He has been put in a room with the one nobody wants to share with.",
    "The dressing room has a pecking order, and his peg has moved.",
    "Somebody has brought their kids to training and the mood has softened.",
    "A fines meeting, and a bill he intends to dispute.",
    "He has been asked to say a few words at a funeral.",
    "The lads have found out where he grew up and made it a running joke.",
    "A team-mate is drinking more than he says he is.",
    "The captaincy is being discussed, and his name has come up.",
    "A supporter has waited two hours outside for a photograph.",
    "He has been invited to something by somebody he does not like.",
    "A released youth player is packing his boots in the corridor.",
    "The club have brought a psychologist in and nobody wants to go first.",
    "A quiet lad in the squad has stopped eating with everybody else.",
    "Somebody made a joke about the gaffer and it got back to him.",
    "The bus leaves in four minutes and one player is missing.",
    "His old room-mate has been sold and somebody else has the bed.",
    "He has been asked to lead the warm-up and does not know why.",
    "A team-mate keeps borrowing money and never mentions it again.",
    "The staff have organised a night out that everybody has to attend.",
    "He is translating for a player who arrived on Thursday.",
    "A dressing-room tradition he thinks has gone too far.",
    "His agent has started ringing his team-mates.",
    "A local lad in the squad is getting stick from his own supporters.",
    "The players have been asked to vote on something and it is close.",
    "A hotel corridor at midnight before an away game.",
    "Somebody has taken credit for something he did.",
    "He is the only one who saw what happened in the tunnel.",
    "A team-mate has asked him to lie for him, casually, as though it is nothing.",
    "Two players have fallen out over a parking space and it is not about the space.",
    "A charity auction where the squad are all expected to bid.",
    "The new signing earns more than everybody and it is public knowledge.",
    "He has been asked to speak on behalf of the players.",
    "A member of staff has been ill and nobody has visited.",
    "The younger lads have started asking him what it used to be like.",
    "A retirement dinner for a man who played six hundred games here.",
    "He has been left off a list and nobody will explain the list.",
  ],
  contract: [
    "A three-year offer with a wage that drops in the third.",
    "The club have added an appearance bonus he is unlikely to reach.",
    "His contract has eleven months left and nobody has mentioned it.",
    "The meeting has been arranged at a hotel rather than the training ground.",
    "The offer arrives by email on a Sunday night.",
    "He has been told the money is there and the structure is the problem.",
    "Two agents are claiming to represent him.",
    "There is a release clause, and the club want it taken out.",
    "He is being offered a year less than he asked for and more per week.",
    "The club want an image-rights arrangement he does not understand.",
    "His wife reads the offer before he does.",
    "A signing-on fee paid across four years, which is not a signing-on fee.",
    "He is out of contract in the summer and the club have gone quiet.",
    "The offer comes with a condition about where he lives.",
    "He is the last of the squad to be spoken to.",
    "Somebody in the boardroom has changed, and so has the mood.",
    "There is a bonus for promotion and nothing for staying up.",
    "The club have offered a one-year extension purely to protect a fee.",
    "He is thirty-three, and the offer says so.",
    "His agent wants a meeting without him in the room.",
    "The number is right and the length is wrong.",
    "A rival's offer includes a car and a school he has not heard of.",
    "The club say wages are capped, and everybody knows they are not.",
    "A pay cut is being described as a restructure.",
    "The offer was better two months ago, before the injury.",
    "He has been asked to sign before the scan results come back.",
    "There is a clause that cuts his wage if the club go down.",
    "His old contract was signed at nineteen by somebody who never explained it.",
    "The chief executive has flown back early to get this done.",
    "The club want him to take less so they can sign somebody else.",
    "He is being asked to trust a verbal promise about next summer.",
    "A four-year deal that would take him to the end of everything.",
    "His agent is pushing the option that pays the agent more.",
    "There is a clause about media appearances that he has not read.",
    "Nobody has said no, and nobody has said yes, for six weeks.",
    "He is offered the same money as a player half his age.",
    "A loyalty bonus has been added, and a photograph requested for it.",
    "There is a buy-back clause, and it is not in his favour.",
    "He has to decide before the medical, before the manager, before anything.",
    "The terms are agreed and the paperwork keeps not arriving.",
    "He would be tied to a club that may not exist in three years.",
    "His father, who has never advised him wrongly, says take less.",
    "The club will not put in writing what they said in the room.",
    "A contract offer arrives the week after his best game in a year.",
    "He signs or he leaves, and both are being presented as his idea.",
  ],
  loan: [
    "A club in the third tier want him and can pay half the wage.",
    "The manager who wants him on loan may not last the season.",
    "A month's loan, extendable, with nobody committing to anything.",
    "He would be playing Saturdays in front of two thousand.",
    "The loan club want him as a striker, and he is not one.",
    "His parent club would pay his wages, which tells him something.",
    "A loan abroad, to a league he has never watched.",
    "He has been out on loan twice and come back to the same bench.",
    "A side need a body for six weeks, and he is the body.",
    "A loan to a club managed by a man who fell out with his agent.",
    "He would live in a hotel by a ring road for four months.",
    "It is this, or eight months of under-twenty-threes football.",
    "The loan club have already signed two players in his position.",
    "A youth coach he trusts says go, and go now.",
    "He would miss the birth if he went.",
    "There is interest from a club he considers beneath him.",
    "Two loans on the table: one that plays him, one that pays him.",
    "A club in a promotion race want cover, not a starter.",
    "He would be going back to the town he left at sixteen.",
    "The parent club want written reports every fortnight, which is unusual.",
    "A loan until January, when all of it gets decided again.",
    "He has never lived on his own and would have to.",
    "The loan manager wants him pressing for ninety minutes, every game.",
    "Nobody at his own club has said they would miss him.",
    "A big club with a small role, or a small club with a big one.",
    "He would be the best-paid man in the dressing room, and they would know.",
    "The move would end the season he had planned in his head.",
    "He is being sent away, and the word being used is opportunity.",
    "A loan to a rival, which the supporters will not enjoy.",
    "Four hours on a train each way, or move, and there is no third option.",
    "The loan club's pitch has been described to him by three different people.",
    "He would come back in May to a squad that has forgotten him.",
    "An emergency loan, from Thursday, with a game on Saturday.",
    "The club taking him have not won at home since October.",
    "It would be his fourth dressing room in two years.",
    "He would learn more in ten games there than in a season here.",
    "His girlfriend has just started a job in this city.",
    "The gaffer says it is his decision, which is not quite true.",
    "A loan with a fee attached, which makes him a commodity out loud.",
    "He would be replacing somebody the supporters there love.",
    "The offer is from a club run by people his agent does not trust.",
    "Six months to prove he is worth keeping, somewhere he does not want to be.",
    "A club two hours north with a reputation for playing kids.",
    "He has been told he will train on his own if he stays.",
    "The loan would mean playing against his own club in March.",
  ],
  setback: [
    "Two penalties all season, and he has missed both of them.",
    "His own goal was the highlight of the round.",
    "He was taken off after thirty-one minutes and nobody looked at him.",
    "The gaffer named him in the press, which is not the gaffer's way.",
    "He has not completed a pass in the opposition half for two games.",
    "A season-defining chance, six yards out, over the bar.",
    "The supporters applauded ironically when he finally won a header.",
    "He came on with the game level, and it was not level for long.",
    "He has been dropped for a player he taught the drill to.",
    "There is a compilation of his errors, and it has a name.",
    "A back-pass that was not a back-pass, and the whole ground groaning.",
    "His number went up on the board and the away end cheered.",
    "He gave away the free-kick, the goal came from it, and he knew instantly.",
    "Three games, three defeats, and he started all of them.",
    "He has been left out of the travelling squad for a game up the road.",
    "The under-twenty-threes fixture list has his name on it for Monday.",
    "He was outrun by a thirty-six-year-old and it is on the news.",
    "A goalless run that has gone past the point of being funny.",
    "He has stopped asking for the ball in tight areas.",
    "The gaffer's post-match interview mentioned individual errors, plural.",
    "He was sent off for something stupid in a game already won.",
    "His father drove four hours to watch him have that game.",
    "A misplaced clearance, paused and circled on television.",
    "The captain shouted at him and the microphones caught it.",
    "He was withdrawn at half-time for tactical reasons that fooled nobody.",
    "Every touch on Saturday was met with a noise from behind the goal.",
    "He has been asked whether he is fit, and he is entirely fit.",
    "A hamstring that was not a hamstring, and now nobody believes him.",
    "The statistic that keeps being read out is his.",
    "Somebody has started a petition about his selection.",
    "He is being left out to protect him, apparently.",
    "His last four performances have been described as a run of form.",
    "A young lad has taken his shirt number and nobody asked him.",
    "He conceded the penalty in the ninetieth minute of a semi-final.",
    "The gaffer put an arm round him, which felt like the end of something.",
    "Two months without a start, and the questions have stopped coming.",
    "He was booed off his own pitch for the first time.",
    "He has stopped watching the highlights.",
    "A team-mate has quietly stopped passing to him.",
    "He is being written about in the past tense.",
    "The mistake came in the last minute of a game he had played well in.",
    "First game back, and he made exactly the same error again.",
    "He has been told the supporters need to see a reaction.",
    "A cup exit to a non-league side, and his part in it.",
    "Nobody has said anything to him all week, which is the point.",
  ],
  media: [
    "A documentary crew have been given access nobody warned him about.",
    "He has been asked to write a column and does not want to.",
    "A former team-mate has published a book with a chapter in it.",
    "The club's own channel wants a sit-down about the bad month.",
    "A radio pundit has decided he is the problem and says so weekly.",
    "His post-match interview was three sentences, and all three are headlines.",
    "A newspaper has run his wages next to a piece about the town.",
    "A photographer has been following his car.",
    "He has been asked onto a panel show with people who criticise him.",
    "Somebody has written a profile of him without speaking to him.",
    "The press want him for the anniversary of something he would rather forget.",
    "A television company want the family involved.",
    "He has been misquoted, and the correction is four lines on page nine.",
    "An interview he gave in March has been published in August.",
    "A journalist has found his old youth coach and is asking questions.",
    "He is asked live on air about a team-mate who has been arrested.",
    "The club want him to front an announcement he disagrees with.",
    "A tabloid has a photograph of him at three in the morning.",
    "He is booked on a national programme the day after a defeat.",
    "A local reporter who was kind to him at seventeen wants a favour.",
    "A story about the manager's future, and he is asked to comment.",
    "His agent has been briefing without telling him.",
    "The interview is about football for six minutes, and then it is not.",
    "He is asked, gently, about the injury nobody is supposed to mention.",
    "A newspaper have offered money for his side of a story.",
    "He is the only player the press office will put up this week.",
    "A clip of him on the bench is being read as a reaction.",
    "Somebody has counted the words he has said publicly this season.",
    "The club's sponsor wants him at a launch, with cameras.",
    "A rival's supporters' podcast have made him a running joke.",
    "He is asked about his father on television, without warning.",
    "A press conference where six of the eight questions are about him.",
    "A magazine wants a photo shoot he finds embarrassing.",
    "He has been asked to keep a diary for a website all season.",
    "A story runs claiming he has fallen out with the captain.",
    "He is doorstepped outside his house on a Sunday morning.",
    "The reporter has the facts right and the tone wrong.",
    "He has been named man of the match and asked only about the defeat.",
    "There is a camera in the tunnel, and he has just been substituted.",
    "A columnist has questioned whether he cares.",
    "A retired player has criticised him and the clip is everywhere.",
    "He is being asked to translate his own words into something safer.",
    "His mother has been contacted for a comment.",
    "The press officer sits in and says nothing, which says plenty.",
    "He is being asked about a transfer he has not been told about.",
  ],
  loyalty: [
    "The club are in administration and asking players to wait for wages.",
    "A testimonial has been mentioned, quietly, for the first time.",
    "His name is on a wall at the training ground and he walks past it daily.",
    "Eleven years at the club, and nothing offered for it.",
    "The supporters' trust have asked him to speak at a meeting.",
    "A rival manager has rung him directly, which is not how it is done.",
    "He is the only one left from the team that went up.",
    "The club that released him at fourteen want him back at twenty-eight.",
    "The chairman who signed him has gone, and the new one is polite.",
    "He could stay and be loved, or go and be paid.",
    "A supporter has named a child after him.",
    "He has been asked to request a transfer, to make it easier for the club.",
    "The badge on his chest has been redesigned and nobody asked anybody.",
    "Staying would mean the third tier, and he has never played in it.",
    "He grew up ten minutes from the ground and lives there still.",
    "The club need to sell somebody, and he is the one worth money.",
    "His agent calls loyalty a word clubs use when they are not paying.",
    "A statue has been discussed, and it is not his.",
    "He is being asked to captain a club he is thinking of leaving.",
    "His brother has a season ticket in the stand he would be leaving.",
    "The supporters have sung his name for eight years and it still works.",
    "A local paper asks him straight out whether he will be here in August.",
    "He has been offered a coaching job for afterwards, which is a kind of chain.",
    "The club have offered less because they think he will not leave.",
    "His son has just started supporting them properly.",
    "A move now would mean never playing here again, and they both know it.",
    "He is being asked to take a wage cut to keep the club going.",
    "He has never played for anybody else and cannot picture it.",
    "The supporters have started a campaign to keep him.",
    "The manager who made him has been sacked by the club he loves.",
    "There is a shirt of his framed in a pub near the ground.",
    "He would be the first in his family to leave the town.",
    "The club have sold three of his closest friends in the squad.",
    "His old academy coach still works there, on half the money.",
    "A rival offers Europe; this club offers a Tuesday in February.",
    "He has been asked to appear in a season-ticket campaign before deciding.",
    "The club want five years, which would be all of it.",
    "Somebody in the boardroom has told a lie about him, and he knows.",
    "He owes the club everything and has paid it back twice.",
    "A supporter stops him at a petrol station and just asks him to stay.",
    "He would be leaving a relegation fight he helped cause.",
    "There is a bench outside the ground with his old coach's name on it.",
    "The offer to leave comes from a club he has spent his life disliking.",
    "His mother has never once said she wants him to stay, until now.",
    "The club have hung a photograph of him in a reception he cannot look at.",
  ],
  role: [
    "He was moved to right-back for one game and it has become a season.",
    "The gaffer wants a false nine and thinks he is one.",
    "He is the substitute brought on to see games out, at twenty-four.",
    "A new formation with one striker, and there are three of them.",
    "He has been asked to mark their best player and do nothing else.",
    "The armband has gone to somebody who has been here six weeks.",
    "He is being played out of position to accommodate a signing.",
    "The coach wants him touching the ball less, not more.",
    "He has been told he will play in cup games only.",
    "His job now is to foul people cynically and take the yellow.",
    "The gaffer has him at left wing-back, which is two jobs at once.",
    "He is expected to run ninety minutes so somebody else does not have to.",
    "A change of system has made his best quality irrelevant.",
    "He has been asked to stop shooting from distance.",
    "The captain has asked him to sit deeper and cover for him.",
    "Fourth choice in one position, second in another he hates.",
    "There is a plan for the season and he is not in the first half of it.",
    "The staff want him to add something he has never had.",
    "He has been dropped for a game he was built for.",
    "His replacement is on loan and cannot play against his parent club.",
    "The gaffer calls him a utility player, approvingly.",
    "He is being asked to play as a target man at five foot eight.",
    "A younger player has been promised his minutes, and he has heard about it.",
    "He has started every game and touched the ball less in each one.",
    "The team's shape means he stands still for long periods.",
    "He is being used as a specialist, which means twenty minutes a week.",
    "The new coach has him doing a role with a foreign name.",
    "He has been asked whether he could play centre-half in an emergency.",
    "He is captain of the reserves, which is not what he wanted to be.",
    "The manager wants him on the left so a better player can have the right.",
    "His position has been given away in a press conference.",
    "He is being asked to be a leader without being given anything to lead.",
    "A tweak has him defending the near post at set-pieces, forever.",
    "He is told he is important, and named on the bench again.",
    "The role would help the team and finish his season.",
    "He would be first choice in a worse side, and he knows which he wants.",
    "Two players ahead of him, and one of them is thirty-four.",
    "The coach has asked him to change how he runs, at twenty-nine.",
    "Emergency option in three positions, first choice in none.",
    "His minutes are being managed, a phrase he has come to dread.",
    "A change of shape means somebody loses out, and it is him.",
    "The gaffer wants him to hold the width and never come inside.",
    "He has been asked to take the corners because nobody else can.",
    "His whole game is built on something the team no longer does.",
    "The staff have him down as a squad player, in a document he was not meant to see.",
  ],
  fallout: [
    "A tackle in training that went well beyond what training allows.",
    "The two of them had to be pulled apart in the tunnel at half-time.",
    "He told a team-mate the truth in front of eighteen other people.",
    "A team-mate accused him of not tracking back, on the pitch, at volume.",
    "He shouted at the goalkeeper, and the goalkeeper has not forgotten.",
    "Somebody has moved his things to a different peg without a word.",
    "They have not spoken since the coach journey home.",
    "He refused to shake a hand and the cameras saw it.",
    "A row about who takes the penalties that has not been resolved.",
    "He was blamed for a goal that was not his and did not take it well.",
    "A younger player has complained about him to the staff.",
    "He made a joke at somebody's expense and it landed badly.",
    "The squad has split over something that started as nothing.",
    "A team-mate has been told what he said, with the worst part emphasised.",
    "He is being asked to apologise for the part he was right about.",
    "Two of the coaching staff are not speaking, and he is caught between them.",
    "He walked out of a team meeting and has not explained why.",
    "Somebody took his substitution personally on his behalf, and made it worse.",
    "The captain has stopped picking him for anything he gets to choose.",
    "He questioned a team-mate's professionalism, and the phrase has spread.",
    "A dressing-room fine has escalated into something nobody meant.",
    "He was defended by somebody he does not like, which complicated everything.",
    "There is a player he cannot look at across the canteen.",
    "The gaffer has told them both to sort it out by Friday.",
    "Six years of friendship, ended by a fifty-fifty in training.",
    "Somebody has repeated a private conversation to the wrong person.",
    "He was the only one who did not join in, and it was noticed.",
    "A team-mate's brother has said something online and it has got back.",
    "He is being asked to pick a side in something nothing to do with him.",
    "They are being kept apart in the warm-up, obviously.",
    "He hit somebody in training, and the club are deciding what to do.",
    "A senior pro has told him to grow up, in front of the group.",
    "He has been left out of a players' meeting he should have been in.",
    "Somebody has been telling the manager things, and it is narrowing down.",
    "He held his hands up and the other one did not.",
    "A row about music has become a row about respect.",
    "He is not being spoken to and nobody will say what he did.",
    "The argument was about football and the words were not.",
    "There is an atmosphere in the room and he is at the centre of it.",
    "He has been asked to stop sitting where he has sat for three years.",
    "A player he fell out with has been made captain.",
    "They scored a goal together on Saturday and it changed nothing.",
    "Somebody has taken his side too loudly and made him look bad.",
    "He was fined by the club after an incident nobody has described publicly.",
    "A team-mate's family have been dragged into it, which changes what happens next.",
  ],
  injury_comeback: [
    "Nine months, two operations, and a first sprint on grass this morning.",
    "The strapping is off, and nobody has told him to stop wearing it.",
    "He can feel the ankle in the cold and has told nobody.",
    "A reserve game on a Tuesday afternoon, forty-five minutes, no more.",
    "The surgeon said six months and it has been ten.",
    "Five weeks of running with a rehab coach and no ball at all.",
    "His first contact session, and the group have been told to be careful.",
    "On the bench for the first time since January.",
    "He is fit, and the team are winning without him.",
    "A specialist has used a word he had to look up.",
    "He has done the rehab twice, because the first time did not take.",
    "Two hundred and eleven days since he last played.",
    "The gym at seven in the morning with the injured group, again.",
    "He tested the knee on his own, at night, on the astro behind the stand.",
    "His shirt number has stayed unused, which somebody meant kindly.",
    "He can run in straight lines and cannot turn without thinking.",
    "The club doctor wants another scan before anything is decided.",
    "A minute into the warm-up, and the whole ground is watching his legs.",
    "He has come back too early once already.",
    "The physio counts something out loud and it has become a rhythm.",
    "Every session ends with ice, and nobody mentions it.",
    "He has missed a promotion, a relegation and a manager.",
    "First start back, away from home, on a pitch he does not like.",
    "The injury was to the other leg, and now that one aches.",
    "He has been told the muscle is stronger than before, which he doubts.",
    "A friendly behind closed doors, twenty minutes, everyone watching one thing.",
    "He is training with the under-twenty-threes to get minutes.",
    "The consultant mentioned the word career and then moved on.",
    "He got through Saturday and cannot get out of the car on Sunday.",
    "The club signed a replacement while he was out.",
    "His body is right and his first touch is a season behind.",
    "He is back in the squad photograph, which he missed in August.",
    "A stress fracture that took four months to find at all.",
    "He knows every physio's name and their children's names.",
    "The first time he has put boots on since the ambulance.",
    "Cleared to train, not cleared to play, and no date given.",
    "So long on the bike that the numbers stopped meaning anything.",
    "He does not want to be the man who talks about his injury.",
    "A tackle came in during training and he did not go into it.",
    "The gaffer wants twenty minutes and the physio wants none.",
    "Nobody has asked how he is for three weeks, and he has noticed.",
    "Second comeback, same injury, and he is twenty-six.",
    "He watched the whole cup run from a treatment table.",
    "The rehab is finished and there is no plan for what happens next.",
    "He is playing again, and a way he used to move has not come back.",
  ],
  transfer_rumour: [
    "A number appeared on a ticker on a Tuesday, and he saw it in a barber's.",
    "Supporters have been counting his posts for clues.",
    "A club with money has been linked, and there is no smoke without an agent.",
    "The manager was asked to guarantee he would stay, and would not.",
    "His shirt has been discounted in the club shop.",
    "A journalist claims a medical is booked, which is news to him.",
    "He has been linked with three clubs this week and spoken to none.",
    "The rumour started with somebody who was in the same restaurant.",
    "Deadline day, and his name is in the crawl at the bottom of the screen.",
    "A rival's supporters have made a graphic of him in their shirt.",
    "He was left out at the weekend, and the internet has decided why.",
    "Somebody photographed his agent in a hotel lobby.",
    "The story says his family have been house-hunting, which they have not.",
    "A bid has come in and the club have not told him the number.",
    "The lads have started calling him by the other club's nickname.",
    "His name is being used to sell newspapers on a slow week.",
    "He has been told to focus on football by people who cannot.",
    "A club he would love to join was mentioned once and never again.",
    "The chairman said he is not for sale, which everybody heard as a price.",
    "A supporter asks him to confirm it, in a supermarket, in front of his kids.",
    "The rumour is that he has already handed in a request.",
    "His release clause has been printed and it is embarrassingly small.",
    "A pundit has said he would be mad not to go.",
    "His parents have been asked about it at their own front door.",
    "The window shuts at eleven and nothing has happened yet.",
    "A team-mate has congratulated him for something that has not happened.",
    "He has been left on the bench, and the story writes itself.",
    "The club have released a statement, which has made it worse.",
    "He is being linked to a club whose manager does not rate him.",
    "Somebody has worked out that he unfollowed the club account.",
    "The story is three weeks old and has been reheated twice.",
    "A move abroad has been mentioned, and his wife heard it on the radio.",
    "He is asked in the tunnel whether this will be his last game here.",
    "His agent has denied it in a way that confirms it.",
    "The fee being quoted is more than the club have paid for anybody, ever.",
    "A rival manager praised him publicly and everybody knows what that is.",
    "He is playing well, and every good game moves the story on.",
    "A club two divisions up have sent scouts to three games running.",
    "The rumour has reached his old primary school.",
    "He has been told a bid was rejected without being told there was one.",
    "A banner asks him to stay, and it is not a friendly one.",
    "Nobody at the club has mentioned it to him in ten days.",
    "He does a press conference and denies everything, truthfully.",
    "The story is wrong now and might be right in a fortnight.",
    "Captain, out of contract, and linked with a rival.",
  ],
  manager_fallout: [
    "A new manager has arrived and named ten players he wants to keep.",
    "The gaffer has started calling him by his surname only.",
    "He was substituted after twenty-eight minutes, having come on at half-time.",
    "The manager has stopped taking his calls.",
    "He has been training with the goalkeepers, which is a message.",
    "The gaffer said he lacks courage, in a room with fourteen people in it.",
    "He is not in the team photograph for the new season.",
    "A meeting was requested six weeks ago and has not happened.",
    "The manager put him on, then shouted at him for the thing he asked for.",
    "He has been given a locker in the away dressing room.",
    "The gaffer told the press he is not injured, which was not the question.",
    "He answered back once, in August, and it has cost him the year.",
    "The manager wants an apology to the group, and he will not give one.",
    "A coach has told him privately that the manager has made his mind up.",
    "He has been left behind for a trip abroad.",
    "The manager praised the man who replaced him for doing less.",
    "He was told to warm up for twenty minutes and then sat back down.",
    "The gaffer looks at him whenever he talks about attitude.",
    "He is being asked to train with the youth team, for his own good.",
    "The assistant does the manager's talking to him now.",
    "He has been fined for breaking a rule he did not know existed.",
    "There is a list of players who can leave, and he has heard he is on it.",
    "The gaffer named the substitutes and left him out entirely.",
    "He played the whole of a friendly and none of the next four games.",
    "A row about a substitution has become a row about respect.",
    "The manager has told him he does not run enough, with numbers.",
    "He has been told the club would like him to find another club.",
    "The gaffer changed the system the week he found form.",
    "He is the only fit senior player not to feature since November.",
    "The manager came from a club he once refused to join.",
    "He has been asked to hand the armband over without an explanation.",
    "The gaffer's son-in-law plays in his position.",
    "He was told he would start, then was not in the squad.",
    "The manager describes him publicly as one for the future, at twenty-eight.",
    "He has stopped being invited to the meetings that matter.",
    "A senior coach has been told to manage him, and he can tell.",
    "The gaffer has three games left and may take him down with him.",
    "He was seen laughing after a defeat and it has been raised.",
    "The manager has decided he is a bad influence on the younger lads.",
    "He is being played somewhere designed to make him ask to leave.",
    "A public row on the touchline that both of them have to explain.",
    "He is told his face fits, which nobody says when it does.",
    "The gaffer has started leaving him out of the walk-throughs.",
    "He has been offered to two clubs without being asked.",
    "The manager who wanted him has been sacked, and the new one did not.",
  ],
  charity: [
    "A hospice have asked for a visit, and asked for no cameras.",
    "A children's ward on Christmas Eve, and a coach trip on Boxing Day.",
    "His old school is closing and wants him at the last assembly.",
    "A team-mate is walking a hundred miles for something and needs company.",
    "The club's foundation want him as the face of a reading scheme.",
    "A homeless charity two streets from the ground has run out of money.",
    "He has been asked to auction the shirt from the best night of his career.",
    "A supporter's funeral, and the family have asked for someone from the club.",
    "A boy who wrote to him has been given weeks.",
    "He is asked to speak about mental health, which means speaking about himself.",
    "The grassroots club he played for at eight needs a new set of goals.",
    "A former team-mate's kit-collection scheme has outgrown his garage.",
    "The club want the whole squad at a fundraiser on a day off.",
    "A cause his mother cares about has asked, through her.",
    "There is a girls' side in the town with no coach and no pitch.",
    "A veterans' group meet at the ground on Wednesdays and want a visit.",
    "He is asked to lend his name to a campaign he has not read properly.",
    "A hospital has asked for him, and it is the ward his father was on.",
    "He could write a cheque and be done, or turn up for a year.",
    "A charity match in the summer break, when he has been told to rest.",
    "A food bank has asked for a photograph rather than money.",
    "The community team are short-staffed and behind on everything.",
    "He has been asked to visit a prison and run a session.",
    "A refugee side train on the council pitches and nobody has helped them.",
    "Somebody has set up a fund in his name without asking.",
    "A young lad from his old estate needs boots and will not ask.",
    "A black-tie dinner where the tickets cost more than he is comfortable with.",
    "A hospital porter who used to watch him play has been made redundant.",
    "There is a defibrillator appeal at a club that lost somebody last year.",
    "A school wants him to hand out prizes and stay for the photographs.",
    "The cause is worthwhile and the person asking has an agenda.",
    "A charity have asked him to become a patron, which is not one afternoon.",
    "He is asked to speak at a memorial for a player who died at nineteen.",
    "A disability side want a session, on a Tuesday, in the rain.",
    "Somebody has asked him to fund a whole season for a junior team.",
    "A hospice nurse recognised him and did not ask for anything.",
    "He is asked to be photographed with a cheque he did not write.",
    "A family who lost a child want to meet him before Saturday.",
    "The club have already announced his involvement in something.",
    "A campaign about racism, and they want players to speak, not pose.",
    "He has been asked to go back to the estate and be seen there.",
    "A sponsored walk that the whole squad has been volunteered for.",
    "A charity single, which is exactly as bad as it sounds.",
    "A children's hospital have asked for an hour and it would take a day.",
    "He has done this quietly for years, and somebody wants to publicise it.",
  ],
  social_storm: [
    "A supporter filmed him in a petrol station and it has two million views.",
    "A gesture towards the away end has been slowed down and studied.",
    "Somebody has made a compilation of everything he has ever posted.",
    "His girlfriend's account has been found and is being picked over.",
    "He followed an account he should not have, and it was spotted in minutes.",
    "A photograph from a stag do has surfaced at the worst possible moment.",
    "He replied to one person and forty thousand replied back.",
    "A misheard word in an interview is being played on a loop.",
    "His brother has been arguing with supporters online, using the family name.",
    "He has been accused of something online with no evidence either way.",
    "A video of him ignoring a child, with the context cut off.",
    "The club posted about him and the replies got out of hand.",
    "Somebody has found a comment he made about the club he now plays for.",
    "He is being told to post an apology written by somebody else.",
    "His account has been hacked and something has gone out.",
    "His name has been trending since lunchtime.",
    "He posted a holiday photograph during a losing run.",
    "A supporter has turned up at his house because of something online.",
    "He has been sent things nobody should be sent, every day this week.",
    "His agent wants everything from before he signed deleted.",
    "A picture of his face has escaped football entirely.",
    "He wrote something true, and the club would prefer he had not.",
    "Somebody recorded him singing on a night out.",
    "He has been drawn into an argument about politics without meaning to.",
    "His silence about something is being read as a statement.",
    "A cause he posted about turns out to be something else.",
    "There is a fake account of his in another country, doing damage.",
    "He liked a post about a rival manager, at one in the morning.",
    "Somebody has been abusing him for a fortnight from a nameless account.",
    "He was tagged in a video from a bar he was not in.",
    "His old teacher has been interviewed about him on a podcast.",
    "A caption he wrote at nineteen has been translated badly.",
    "The club's sponsor has been asked to comment on his account.",
    "He deleted a post, and the deletion is now the story.",
    "A photograph of his new car has become an argument about wages.",
    "A team-mate's post is being read as being about him.",
    "He has been asked to stop posting entirely until further notice.",
    "A fan account has published where he lives.",
    "He said nothing all season, and now nobody believes his statement.",
    "A picture of him at a rival's ground, watching a friend play.",
    "The pile-on has moved from him to his mother.",
    "There is a clip of him not applauding the travelling support.",
    "His response was reasonable, and the screenshot cut off the question.",
    "Somebody has counted how many times he has posted about the club.",
    "A journalist has quoted his replies as though they were an interview.",
  ],
  family_illness: [
    "His father has been unwell since the spring and only said so in August.",
    "A diagnosis that arrived the week the season started.",
    "His mother is having tests and has asked him not to change anything.",
    "A brother in hospital, and a cup tie four hundred miles away.",
    "Six nights sleeping in a chair beside a bed.",
    "The doctors want a decision from the family this week.",
    "His grandmother no longer recognises him and still watches every game.",
    "A phone he cannot bring himself to turn off during team meetings.",
    "His son has been referred to a specialist and nobody will say why yet.",
    "The club gave him a week and he has taken two days.",
    "His sister has carried all of it while he has been away.",
    "He found out at the airport, on the way to a warm-weather camp.",
    "A parent who has never asked him for anything has asked him to come home.",
    "There is an operation on the Saturday of a game he was told he would start.",
    "He has been driving home after every match, arriving at two.",
    "His wife has told him the truth about how bad it is.",
    "A ward, visiting hours, and training at nine tomorrow.",
    "He has stopped telling the club what is happening.",
    "Somebody at home has been hiding the letters from the hospital.",
    "His father wants to come to a game and probably should not.",
    "There is a chance, and it is not a good one.",
    "He is the one who has to tell the rest of the family.",
    "The physio noticed before anybody else that something was wrong with him.",
    "His mother's operation has been postponed twice.",
    "He scored on the first night his family have not been there.",
    "A relative has asked him to pay for private treatment.",
    "A month without proper sleep, and it is starting to show at work.",
    "The manager knows and has told nobody, which is a kindness.",
    "He has to choose between a hospital appointment and a medical of his own.",
    "His father has asked him not to miss games on his account.",
    "The season has ten games left, and so, roughly, does somebody.",
    "He is playing on the day of the funeral and everybody agrees it is right.",
    "A grandparent's house is being sold and nobody told him.",
    "His mother rings after every match and did not ring after this one.",
    "He has been asked to be in two places, and both of them matter.",
    "His brother is unwell and refusing to see anybody, including him.",
    "A hospice, a Thursday afternoon, and a plane to catch.",
    "He has been given the results before the person they are about.",
    "His child is ill, and the club have a game on Wednesday.",
    "He cannot concentrate in the video sessions, and it has been noticed.",
    "There is nobody at home to do what needs doing except him.",
    "The consultant will only speak to family, and he is four hours away.",
    "He was on the pitch when the call came, and it waited.",
    "A ward that smells exactly like the one from when he was ten.",
    "He is being told to take his time by people who need him on Saturday.",
  ],
  romance: [
    "She has been asked to move country for his career and has not answered.",
    "Two years of hotel rooms and phone calls, and a question that has to be asked.",
    "He has met somebody who has never watched a football match.",
    "Her career is going better than his and neither of them mentions it.",
    "A relationship everybody at the club knows about except the club.",
    "She has said she does not want to be a footballer's wife, in those words.",
    "They have been together since school, and he is not the same person.",
    "A wedding date that clashes with the first week of pre-season.",
    "He has been unfaithful and has to decide what to do about it.",
    "She has been offered a job in the city he is about to leave.",
    "Her family have never liked him and are being polite about it.",
    "They want children, and the schedule has an opinion.",
    "He proposed and has not told anybody at the club.",
    "She has asked him to choose between the move and the marriage.",
    "A relationship that started three weeks before the transfer window.",
    "He has been seeing somebody a team-mate used to see.",
    "She wants to know where they will be living in a year, and he cannot say.",
    "Their flat is in boxes for a move that may not happen.",
    "Forty nights at home this season, and she has counted them.",
    "A first meeting with her parents, on a day off, four hours away.",
    "She has stopped coming to games and will not say why.",
    "He is thirty-one and she is asking what happens after football.",
    "They separated in January and she has been at the last three matches.",
    "Somebody has told her something about him that is half true.",
    "She was photographed leaving the ground and hated it.",
    "His agent has opinions about his relationship, which is new.",
    "They have been arguing about the same thing since the summer.",
    "She is pregnant, and the season has six months left.",
    "He met somebody at a club function and cannot stop thinking about it.",
    "Her mother is ill and she wants to go home, permanently.",
    "They have not been alone in a room together for eleven days.",
    "She asked him to miss a game, and meant it.",
    "He has kept the relationship quiet, and she has worked out why.",
    "A ring has been bought and sits in a drawer at the training ground.",
    "She has been offered work abroad and he has been offered a contract here.",
    "He is being asked to make a decision about somebody else's life.",
    "Their child was born on an away trip and he saw a photograph.",
    "She has read something about him online and has not mentioned it.",
    "A relationship that survives on Wednesdays and long summers.",
    "A friend who means well has told him she is too good for him.",
    "They want different lives and are both being very polite about it.",
    "She has never asked him for anything, and has asked him for this.",
    "He is home for a fortnight, the longest stretch they have had.",
    "A quiet register office, no cameras, and a squad who will find out later.",
    "She has held the whole house together for three seasons.",
  ],
  mentor_crossroads: [
    "{mentor} has been ill and wants to see him before the season starts.",
    "The advice from {mentor} is the opposite of what his agent is saying.",
    "{mentor} has been sacked and is asking, indirectly, for help.",
    "Three years without a word, and now {mentor} is ringing.",
    "{mentor} thinks he has stopped working, and says it plainly.",
    "A job has come up at the club where {mentor} started him off.",
    "{mentor} wants him to come back and speak to the current group.",
    "He disagrees with {mentor} for the first time and has to say so.",
    "{mentor} has taken a job at a rival, which changes what they can discuss.",
    "The man who made him is being written out of his story by other people.",
    "{mentor} rings the night before every big game, and did not ring last night.",
    "He has been offered a move {mentor} would never have made.",
    "{mentor} has asked him for money, which has never happened before.",
    "A testimonial for {mentor}, and the date is awkward.",
    "{mentor} has told him to retire, kindly, and he is twenty-nine.",
    "He has outgrown {mentor}'s advice and does not know how to say it.",
    "{mentor} has been criticised publicly and has not defended himself.",
    "The coach who first believed in him is applying to work under him.",
    "{mentor} thinks the club are using him, and has evidence.",
    "He wants {mentor}'s approval for a decision already made.",
    "{mentor} has stopped watching his games, and admitted it.",
    "There is a funeral, and {mentor} would want him at the match instead.",
    "{mentor} has been proved wrong about him and has not acknowledged it.",
    "He is being asked to choose between {mentor} and the man paying him.",
    "{mentor} wants him to take on a young player the way he was taken on.",
    "A letter from {mentor}, on paper, which is not how they do things.",
    "{mentor} was right about the last three decisions, and is warning him again.",
    "He has been avoiding {mentor}'s calls for a fortnight.",
    "{mentor} has moved abroad and wants him to follow.",
    "The advice is good, and comes from a man who never made it himself.",
    "{mentor} has asked him to speak up about something at the club.",
    "He is being asked to replace {mentor} at a club that has moved on.",
    "{mentor} has been offered a role that would put him in charge of him.",
    "He has stopped needing {mentor}, and {mentor} has noticed.",
    "A disagreement about his position that goes back to when he was fifteen.",
    "{mentor} was in the stand and did not come down afterwards.",
    "He is asked to say something about {mentor} in an interview.",
    "{mentor} says the club he is about to join will ruin him.",
    "There is a coaching course, and {mentor} wants him on it now.",
    "{mentor} has fallen out with his agent, and he is stuck between them.",
    "He has been told {mentor} took a fee for him, years ago.",
    "{mentor} would like to be thanked publicly and would never ask.",
    "He has to tell {mentor} he is leaving before anybody else hears.",
    "{mentor} has one piece of advice left and is saving it.",
    "A car park after a defeat, and {mentor} waiting by the gate.",
  ],
  friend_rivalry: [
    "{rival} has been called up, and he has not.",
    "He and {rival} are competing for the same shirt in the same squad.",
    "{rival} scored against him and did not celebrate, which was worse.",
    "A move that would take him to the club {rival} has just left.",
    "{rival} has stopped answering his messages since the transfer talk started.",
    "Their mothers still speak weekly, which complicates every game.",
    "{rival} has been made captain of the side they both came through.",
    "He has been asked, publicly, to compare himself with {rival}.",
    "{rival} is on twice the money for half the games.",
    "They shared a flat at eighteen and now share an agent.",
    "{rival} is injured, and he has taken the shirt.",
    "A tackle from {rival} that was not quite an accident.",
    "They are both up for the same award and only one can win it.",
    "{rival} said something in an interview that was aimed at him.",
    "He was best man at {rival}'s wedding and they have not spoken since March.",
    "{rival} has signed for his club, in his position.",
    "Their fathers played together and keep bringing it up.",
    "{rival} went abroad and has come back better.",
    "He has been dropped for {rival} and has to sit next to him.",
    "{rival} is struggling, and he has not rung.",
    "The two of them are on opposite sides of a dressing-room split.",
    "{rival} has asked him for a favour that would cost him something.",
    "He is playing against {rival} on the day of a family occasion.",
    "{rival}'s career has taken off and his has not moved.",
    "A photograph of them both at fourteen keeps being reposted.",
    "{rival} has been offered work in the media before either has retired.",
    "He would have to mark {rival} for ninety minutes on Saturday.",
    "{rival} has told a journalist a story about him from years ago.",
    "They signed on the same day, and only one of them is starting.",
    "{rival} has been made an example of, and he stayed quiet.",
    "He is asked to talk {rival} out of a move he wants himself.",
    "{rival} has retired and taken a coaching job at his club.",
    "The banter has stopped being funny and neither will say so first.",
    "He was outplayed by {rival} in front of the people who raised them both.",
    "{rival} has been dropped and rung him for the first time in a year.",
    "A promotion decider, and {rival} is in the other dugout's plans.",
    "{rival}'s brother has said something about him online.",
    "He is being asked to captain a side {rival} thinks he should not.",
    "{rival} has been picked for a squad he was told he was in.",
    "They meet in a tunnel and neither knows what the other will do.",
    "{rival} has done everything right, and it still stings.",
    "He has been asked to recommend {rival} to a club he wants himself.",
    "{rival} owes him money from when neither of them had any.",
    "Their old coach has been asked which of the two was better.",
    "Four years without sharing a pitch, and they share one this afternoon.",
  ],
  new_money: [
    "His first car cost more than his mother's house did.",
    "An uncle he has not seen since he was nine has a business idea.",
    "The money has arrived and he has not told anyone at home how much.",
    "A financial adviser recommended by a team-mate who is now broke.",
    "He has been asked to invest in a bar by somebody he trusts.",
    "Three of his friends have stopped letting him pay, and one never does.",
    "He bought his father a car and it has sat on the drive for a month.",
    "A tax bill he did not know was coming.",
    "His old mates have started meeting up without him.",
    "He has been offered a scheme that sounds clever and is not.",
    "The house is too big and most of it is still in boxes.",
    "Somebody has asked him for a loan and used the word deserve.",
    "His weekly wage is more than his father used to earn in a year.",
    "A friend of his agent has an opportunity in property abroad.",
    "He has been paying for nine people's holidays and stopped counting.",
    "His brother has quit a job on the strength of the new contract.",
    "He is being pushed to buy a watch he does not want.",
    "The money is real and he still checks the balance twice a day.",
    "A charity, a scheme and a friend all want a decision this month.",
    "He bought his mother a house and she is unhappy in it.",
    "Everybody in his old town knows the number in his contract.",
    "He has been told to put it in a pension and cannot picture being old.",
    "A team-mate will not stop talking about an investment he has found.",
    "He has been advised to buy a club, at twenty-four.",
    "His accountant has resigned without explaining why.",
    "He has spent nothing, and people have started mentioning it.",
    "A relative has been using his name to get credit.",
    "He signed something at nineteen that he now needs a lawyer to read.",
    "His agent takes a percentage of things he did not know were included.",
    "Somebody has valued his whole career and told him to live below it.",
    "He is being asked to fund a family business he thinks will fail.",
    "The money has changed the way his father speaks to him.",
    "A friend has asked to be his driver, which is really asking for a job.",
    "He has been sold a policy he does not understand by somebody charming.",
    "His girlfriend earns a normal wage and it has started to matter.",
    "He has never budgeted, has never needed to, and it has caught up.",
    "An old team-mate who earned this much is working nights now.",
    "There is a car in the garage he has driven twice.",
    "He has been asked to guarantee a mortgage for somebody else.",
    "His first tax return runs to sixty pages.",
    "He gave a friend money and the friendship ended anyway.",
    "A club dinner where everybody talks about investments and he says nothing.",
    "He has been told this is the peak, and to plan accordingly.",
    "His mother has kept every wage slip from before, in a tin.",
    "Somebody has worked out what he earns per minute played.",
  ],
  move_abroad: [
    "Training starts at ten and finishes at seven, with a gap nobody explained.",
    "He has been given a translator who also works for the club.",
    "The heat at four in the afternoon is a different sport entirely.",
    "His contract is in a language he cannot read, and he has signed it.",
    "A dressing room with five languages and no common one.",
    "Three weeks in the country and he has eaten in the same place nine times.",
    "The league starts in a different month and finishes in another.",
    "His family are staying at home until Christmas, they have decided.",
    "The supporters here expect something he does not know how to give.",
    "A city where nobody recognises him, which is unfamiliar and pleasant.",
    "He has been asked to learn the language by December.",
    "The training methods are different and nobody is explaining why.",
    "His mother has never flown, and the flight is three hours.",
    "He is the only one here from home, and the phone calls are getting shorter.",
    "Winter here means snow and a break he does not know what to do with.",
    "The president speaks to players directly, which nobody warned him about.",
    "He misses a particular kind of bread, which he finds embarrassing.",
    "The referees here give things he has never seen given.",
    "His agent has flown home, and he is on his own with it.",
    "A driving licence, a bank account and a phone contract, all in a fortnight.",
    "He was booed at his own ground for something he did not understand.",
    "The press are at training every day, standing on the touchline.",
    "His flat looks out over a motorway and he has stopped noticing.",
    "A team-mate's family have invited him for lunch and he does not want to go.",
    "The tactical language is different even when the football is not.",
    "A homesickness he had not expected and cannot mention to anybody.",
    "He has been told to stop playing the way he was taught.",
    "The club pay late and everybody treats it as normal.",
    "His children would have to start school in another language.",
    "A cup competition whose rules he does not understand.",
    "He has learned twenty words, and all of them are about football.",
    "He came for the football, and it is the evenings that are hard.",
    "A senior pro has taken him under his wing for reasons he cannot read.",
    "Supporters wait outside the training ground every day, in numbers.",
    "Nobody at home has any idea how well or badly it is going.",
    "He would go back if it could be done without it becoming a story.",
    "The move was {rival}'s idea originally, which he has admitted to nobody.",
    "There is a way of celebrating here that he has been told to adopt.",
    "His wife has learned the language faster and translates for him.",
    "He has not seen a game from home in four months.",
    "The season here breaks in the middle and he has been given a fortnight.",
    "A local derby he did not know existed until the police escort arrived.",
    "He is expected to speak to the supporters after a defeat, in their language.",
    "His mother has sent a parcel that took eleven days to arrive.",
    "The club would like him to take citizenship, eventually, and have said so.",
  ],
};
export const DEMAND_A: Bank = {};
export const FRAME_A: Bank = {};
export const SETTINGS_A: Bank = {};
export const CHILD_SETUP_A: Bank = {};
export const EVENT_PREFIX_A: Bank = {};
export const BIG_SETTINGS_A: string[] = [];
