// Authoring pack L. One author owns this file — nobody else writes to it, so packs never collide.
// Keys must match the bank they extend (see shared/src/prompts/*.ts for the key names and the house voice).
import type { Bank } from "../merge.js";
export const KIND_SETUP_L: Bank = {};
export const DEMAND_L: Bank = {};
export const FRAME_L: Bank = {};
export const SETTINGS_L: Bank = {
  "Youth Team": [
    "on a training-ground pitch with no line markings left by March",
    "with the youth-team kit still damp from Tuesday",
    "before eleven o'clock on a Saturday morning",
    "under a sky that had been threatening rain since the warm-up",
    "against lads two years older and a stone heavier",
    "after a fifty-mile coach trip that left at seven",
    "beside a stack of upturned goal frames",
    "past the point where the floodlights actually helped",
    "through the second half of a game already lost",
    "at the far end of a pitch shared with a rugby club",
    "out on the back field, where the grass never quite recovers",
    "down at the training ground on a Thursday",
    "over at the college pitches, borrowed for the afternoon",
    "alongside three trialists nobody had introduced",
    "the physio watching from a folding chair on the touchline",
    "with a burst ball bag propped against the dugout",
    "in the last twenty minutes of a reserve game nobody was winning",
    "on a surface the groundsman had already given up on",
    "with a linesman in a club tracksuit and no badge",
    "before a crowd of forty, most of them family",
    "under lights that took ten minutes to come up properly",
    "against a team who had travelled up from Devon that morning",
    "after being told at breakfast he was starting",
    "beside the away dugout, close enough to hear every word",
    "past two committee men leaning on the perimeter rail",
    "through a fixture that had already been called off twice",
    "at the wrong end of a five-nil",
    "out on the flank with the wind straight in his face",
    "down the coach at Keele services, half the squad asleep",
    "over the top of a defence that had not trained together",
    "frost still white along the far touchline",
    "with his boots borrowed off a lad who had been released",
    "in a game moved to a Wednesday afternoon for pitch reasons",
    "on the smaller of the two pitches behind the main stand",
    "before the first team had even finished their warm-down",
    "under the eye of a coach who wrote nothing down all game",
    "against the club's own under-eighteens in a practice match",
    "after forty minutes of nothing at all",
    "beside a corner flag someone had pushed in at an angle",
    "past the halfway line for the first time in ten minutes",
    "through a fog that came in off the reservoir at half three",
    "at a ground where the away end was a grass bank",
    "out in the rain at a stadium that seats twelve thousand and held sixty",
    "down at Rosehill on a pitch the council had cut too short",
    "over in the corner where the assistant kept the bibs",
    "the groundsman waiting by the gate with his keys out",
    "with the tannoy playing the same three songs",
    "in a fixture rearranged twice and finally played on a Tuesday",
    "on a bobbled goalmouth churned to mud by December",
    "before an audience of scouts who had come to watch somebody else",
    "under the noise of a nearby dual carriageway",
    "against a lad who had been in the first team squad on Saturday",
    "after his landlady had made him take an umbrella",
    "beside a barrier held together with gaffer tape",
    "past a photographer who left at half time",
    "through the fourth game in eleven days",
    "at eight in the evening on a floodlit midweek",
    "out on a pitch two lads had helped mark that morning",
    "down the road at the university sports ground",
    "over the course of a first half he spent chasing",
    "his digs a bus ride from the training ground",
    "with a first-year apprentice running the line",
    "in a testimonial for a player nobody in the squad remembered",
    "on the day the released list was pinned up",
    "before the reserves had a manager at all",
    "under a caretaker who had taken the team for a fortnight",
    "against a side who kicked everything above knee height",
    "after a warm-up cut short by a burst pipe in the changing rooms",
    "beside the tunnel mouth where the kit man stood with a clipboard",
    "past a wall of six that had no intention of moving",
    "through a spell where the ball spent more time out than in",
    "at the point in the season where the fixtures stop mattering",
    "out on a Monday afternoon in front of nobody",
    "down at a non-league ground the club had hired for the day",
    "over ninety minutes on a surface that took two studs off his boot",
    "the referee an academy coach in a borrowed shirt",
    "with his agent stood at the halfway line in a good coat",
    "in a reserve fixture that clashed with the first team's away trip",
    "on grass that had been sand-dressed the week before",
    "before a scout who had driven from Preston and stayed nine minutes",
    "under a scoreboard stuck on nil-nil from the previous week",
    "against a centre-half who had been playing men's football since sixteen",
    "after signing a two-year deal on the Friday",
    "beside a pile of cones nobody had put away",
    "past the far post twice in five minutes",
    "through the last third of a game with cramp setting in",
    "at a ground where the changing rooms were a portakabin",
    "out on loan for a month at a club four divisions down",
    "down to nine men after two lads went off injured",
    "over an hour of football in a stiff crosswind",
    "his name spelt wrong on the team sheet",
    "with a crowd small enough that he could hear his own touch",
    "in a match where both sides had lost their goalkeeper",
    "on a Tuesday night when the first team were in Europe",
    "before the youth cup tie that everyone had been talking about for a fortnight",
    "under a manager who had watched him twice and said nothing",
    "against a team who arrived with fifteen players and no substitutes",
    "after being pulled out of school football two years earlier",
    "beside a father who had come straight from a shift",
    "past the age where being small was an excuse",
    "through a half in which he touched the ball nine times",
    "at a training ground with one working shower",
    "out in Cheshire at a facility the club rented on Wednesdays",
    "down at the old ground, still used for reserve fixtures",
    "over at the far pitch, where the under-sixteens were finishing",
    "the away side warming up in coats",
    "with the wind carrying the coach's voice away from him",
    "in an afternoon fixture with an eight-thirty kick-off changed at short notice",
    "on a pitch cut into a public park with dog walkers on the touchline",
    "before a director who had come down for a look",
    "under a sky going dark by half past three",
    "against a reserve side full of first-teamers coming back from injury",
    "after three weeks on the treatment table",
    "beside a stretcher nobody had needed all season",
    "past a linesman who had given him offside twice already",
    "through a run of games where the results stopped being mentioned",
    "at the end of a week where two lads had been let go",
    "out on the pitch fifteen minutes before anyone else",
    "with the ball skidding on wet paint",
    "in front of a stand that had been closed for safety",
    "on a January afternoon with the pitch frozen at both ends",
    "before a fixture that would decide nothing at all",
    "under a coach who had played four hundred games in the lower leagues",
    "against the first team in an eleven-a-side on a Friday",
    "after the gaffer had named the squad and read his name out ninth",
    "beside a substitutes' bench of four plastic seats",
    "past the second-year lads who had already signed",
    "through a match played with a size-four ball by mistake",
    "at the wrong end of a heavy pitch, forty minutes gone",
    "out in front of a group of primary-school kids on a visit",
    "down at a ground where the dressing room had no hot water",
    "over a game that lasted a hundred and one minutes",
    "a schoolboy trialist filling in at right-back",
    "with the manager's assistant on the far side, arms folded",
    "in a match that finished in near-darkness",
    "on a Saturday when the youth team had no game",
    "before a scout from a club in the division above",
    "under a barrage of long balls into the channel",
    "against a side third from bottom of the reserve league",
    "after a fortnight of doing nothing but running",
    "beside a touchline rope that kept falling down",
    "past two lads warming up who had been told they were on next",
    "through a game he had been told to treat as a trial",
    "at nine on a Sunday morning in a mid-season friendly",
    "out on the pitch with a shirt two sizes too big",
    "down at the club's other site, twenty minutes from the stadium",
    "over on the far touchline where the coaching staff stood",
    "the kit man counting shirts back in at the whistle",
    "with sleet coming across the pitch at an angle",
    "in a game where the referee kept apologising",
    "on a pitch with a slope you could see from the halfway line",
    "before an under-strength side who had lost four to the first team",
    "under the eye of two men in club coats who never sat down",
    "against a goalkeeper who came for everything",
    "after an argument in the changing room at half time",
    "beside the goal his own reserves had conceded four in",
    "past a defender who had already been booked",
    "through the middle of a squad rotation nobody explained",
    "at a fixture the club had put on their website as cancelled",
    "out on a Wednesday with the first team training on the next pitch",
    "down at a ground with a scoreboard that had not worked since 1997",
    "over a first half where the wind did most of the work",
    "his second full game in nine months",
    "with the first-team physio taking the reserves' warm-up",
    "in a pre-season game against a works side",
    "before a manager who had already decided",
    "under the roof of an indoor pitch, the game moved inside",
    "against a former team-mate released the previous May",
    "after being moved to a position he had never played",
    "beside a corner of the ground where the ivy had come through the fence",
    "past the point where the score mattered to anyone",
    "through the tail end of a game he had come on in the seventy-eighth minute of",
    "at the second attempt, the first game abandoned at half time",
    "out on a pitch marked out with two sets of lines",
    "down the far end where the goal net had a hole in it",
    "over the shoulder of a full-back who kept losing him",
    "with the reserves playing in last season's away kit",
    "in a match where a supporter kept shouting the same thing",
    "on a ground shared with the local cricket club, the square roped off",
    "before the youth-team coach who had brought him from schoolboy football",
    "under floodlights borrowed from the training ground next door",
    "against a side who had been beaten seven-nil the week before",
    "after the club had told him a loan was being discussed",
    "beside the tunnel, waiting for a substitution that took eight minutes",
    "past three lads in tracksuits watching from behind the goal",
    "through a period where he played four games in four different positions",
    "at a fixture nobody had put on the fixture list",
    "out in the middle in the last five minutes of a training game",
    "down at a training ground where the pitches were numbered on the gate",
    "over at the medical room, the game finishing without him",
    "his mother watching from the car",
    "with a coach shouting one instruction at him for the entire half",
    "in a game played on the day of a first-team cup tie",
    "on a pitch that had taken two games already that week",
    "before a crowd made up mostly of the opposition's youth team",
    "under the assumption he was being watched, which he was not",
    "against a team who played five at the back and did not cross the halfway line",
    "after being told to shower and get changed at half time",
    "beside the boot room where the apprentices still cleaned the first team's boots",
    "past a hoarding advertising a company that had gone out of business",
    "through a run of six games as a substitute",
    "at a stage of the season where the pitches had all gone",
    "out on the training pitch after everyone else had gone in",
    "down at a pitch with cows in the field the other side of the hedge",
    "over the course of a fixture nobody had bothered to referee properly",
    "the game restarted after a dog got on",
    "with two first-year lads on the bench who had never played a reserve game",
    "in a match played with the same three balls all afternoon",
    "on a Thursday afternoon with a cross-country wind",
    "before the reserve-team coach who had been a full-back at the club himself",
    "under a coaching staff who had been at the club longer than he had been alive",
    "against a side who had all played in the Football League",
    "after a train journey with the squad in club tracksuits",
    "beside a pitch where the under-fourteens were playing at the same time",
    "past a corner flag that had been snapped and taped",
    "through a game in which nobody spoke to him",
    "at a stadium the club used twice a season for reserve fixtures",
    "out on a surface that had been laid four months earlier",
    "down the tunnel afterwards past a first-team coach who said nothing",
    "over a fixture rescheduled to a Monday because of a funeral",
  
    "with a scout he did not know was a scout",
    "in a game where both teams wore black armbands",
    "on a pitch with a penalty spot painted twice",
    "before the release list came out, three days before",
    "under the shadow of the main stand for the whole first half",
    "against a side who had beaten them twice already that season",
    "after a summer of being told he had grown",
    "beside a lad on the bench who had been at the club since nine",
    "past the second-choice keeper, up for a corner in stoppage time",
    "through a match in which the ball went out of the ground four times",
    "at a ground where the goal nets were tied on with string",
    "out on the pitch in a squad number in the forties",
    "down at the reserve fixture with the first team at home the same day",
    "over the top of a back four playing an offside trap badly",
    "with the referee's assistant taking the second half on his own",
    "in a game where a goal was disallowed and nobody argued",
    "on an evening when the training ground gates were locked at nine",
    "before a first-team midfielder coming back from a hamstring",
    "under a coach who kept calling him by another lad's name",
    "against a team who turned up in the wrong colour shirts",
    "after being told at nine that morning he was in the squad",
    "beside a goalmouth that had been re-turfed in squares",
    "past the twenty-minute mark with the score still level",
    "through the middle of a season where he was neither in nor out",
    "at the request of a manager who wanted to see him at left-back",
    "out on a rutted surface at a ground with a running track around it",
    "down a slope towards the away goal with the wind behind him",
    "over ninety minutes in which nothing was decided",
    "the far goal in front of an empty terrace with weeds through it",
    "with a coach counting bibs at the side of the pitch",
    "in a game his father drove ninety miles for",
    "on a Tuesday nobody outside the club knew about",
    "before an audience of two apprentices and a man walking a dog",
    "under the eye of a director of football who left after twenty minutes",
    "against a side who had a professional trialist at centre-forward",
    "after a night in digs with a broken radiator",
    "beside a coach who had already turned to talk to somebody else",
    "past a defender who had shaken his hand in the tunnel",
    "through the last month of a season with nothing on it",
    "at a fixture where both teams changed in the same room",
    "out on a pitch that had hosted a school sports day the day before",
    "down at a ground where the entrance was through a scrapyard",
    "over the head of a keeper who had come out too far",
    "his shirt tucked into shorts a size too small",
    "with the number nine given to a lad on trial",
    "in the fourth reserve fixture in eighteen days",
    "on a corner of a pitch that had been sanded twice",
    "before the youth team travelled to Belgium the following week",
    "under a caretaker manager taking his last game",
    "against opposition who had been in a coach crash on the way and arrived late",
    "after the club had moved training to the morning for the winter",
    "beside a linesman who spent the whole game looking at his watch",
    "past the moment when the substitutes were told to warm up",
    "through a game he had been left out of and then put in",
    "at a training ground that backed onto a canal",
    "out in a reserve fixture with a first-team squad number on the back",
    "down at a pitch where the halfway line was still visible from the last game",
    "over the winter break the club did not really have",
  ],
};
export const CHILD_SETUP_L: Bank = {};
export const EVENT_PREFIX_L: Bank = {};
export const BIG_SETTINGS_L: string[] = [];
