// Authoring pack M. One author owns this file — nobody else writes to it, so packs never collide.
import type { Bank } from '../merge.js';
export const KIND_SETUP_M: Bank = {};
export const DEMAND_M: Bank = {};
export const FRAME_M: Bank = {};
export const SETTINGS_M: Bank = {
  'First Team': [
    'in front of a full house on a cold Saturday',
    'at a ground where the away end hangs right over the tunnel',
    'under a stand still half-empty at kick-off, the motorway to blame',
    'away at a place with a running track between the crowd and the grass',
    'before a sell-out that had queued down the side street since eleven',
    'out on a pitch that had cut up badly after Thursday\'s rain',
    'down at a ground with scaffolding across the far corner',
    'past the lad with the drum in the corner of the away end',
    'with a sponsor\'s board hanging loose behind the near goal',
    'through eighty minutes of rain coming in sideways',
    'a Monday night kick-off, moved for the cameras',
    'kick-off pushed back twenty minutes for a crash on the ring road',
    'against a centre-half who had been doing this since before he was at school',
    'after a five-hour coach journey up the A1',
    'beside a linesman who had already been booed for forty minutes',
    'alongside two lads who would be sold before February',
    'on a Tuesday night with the gate barely at nine thousand',
    'in the second half of a season that had stopped being fun',
    'as the away end sang all the way through the goalkeeper\'s run-up',
    'the manager\'s name on the front of two papers that morning',
    'in a ground where the floodlights buzz',
    'under lights that had been on since half two',
    'at a stadium built in the eighties and not touched since',
    'in front of an away end that never sat down',
    'on grass worn bare in both goalmouths by November',
    'with the pitch frozen along the shaded touchline',
    'away in a corner of the country he had never been to before',
    'before the international break, everyone half-thinking about the flight',
    'after the third game in eight days',
    'in the seventy-eighth minute of a game already won',
    'the fourth official holding up six',
    'down the far end, where the ball boys had gone quiet',
    'past the halfway line for what felt like the first time all half',
    'against a side who had not lost at home since August',
    'in the rain, in the north, in February',
    'at half four on a Sunday for a broadcaster in Singapore',
    'with two thousand travelling and every one of them standing',
    'in front of a stand named after a man nobody under thirty remembered',
    'on a surface that had hosted a rugby match six days earlier',
    'with the tannoy cutting out mid-announcement',
    'before a crowd that had paid forty quid to be there',
    'as the stewards turned to face the away end',
    'under a roof low enough to keep the noise in',
    'in a stadium where the corners are open and the wind comes through',
    'with his contract situation printed in a column that morning',
    'after a week of being asked about the manager',
    'against a full-back who had already been booked',
    'out wide, in front of the dugouts',
    'alongside a captain playing through an injection',
    'at a club still paying for a stand they never filled',
    'with the home end emptying from the seventy-fifth minute',
    'in a game shown live because two other games had been called off',
    'through a fixture that had been rearranged twice',
    'on a Wednesday, on a screen, in front of no one he knew',
    'with sleet coming across the open corner',
    'in front of the same three photographers as every week',
    'after being marked out of the game for a half',
    'with the wind holding the ball up over the top',
    'at a ground where the tunnel comes out at the corner flag',
    'before an away end that had been on the road since six',
    'on a pitch with the lines still faintly showing from two games before',
    'in the smell of frying onions blowing off the vans behind the stand',
    'a goalkeeper shouting at him from forty yards away',
    'away at a side who had beaten them twice the season before',
    'against men who had families and mortgages and no interest in his reputation',
    'at a ground with a single tier down one whole side',
    'after a goal that had been checked for two minutes',
    'in front of a bench with three unused substitutes and no answers',
    'with the assistant referee\'s flag up and the crowd already appealing',
    'down at the far corner where the terracing used to be',
    'as the ninety-third minute came up on the board',
    'in a match that had gone to pieces in the last ten minutes',
    'under a caretaker manager taking his first session on the Tuesday',
    'with the coach parked behind the away end and the engine still running',
    'through a spell where nobody could keep the ball',
    'before a kick-off delayed while a stretcher came off',
    'at a stadium where the dressing rooms are still down a corridor of tile',
    'alongside a lad on loan who would not speak to anyone',
    'with two hundred miles of dark motorway to come afterwards',
    'on a night when the away end had brought a hundred flags',
    'in front of a crowd who had watched this team lose four on the spin',
    'after a warm-up cut short by a hailstorm',
    'with the referee\'s watch going off in the eightieth minute',
    'against a marker who talked at him for the whole first half',
    'out on the left, hard against the advertising boards',
    'at a place where the pitch sits below the level of the streets',
    'before eleven thousand and an empty away section',
    'under a manager who had four games to save his job',
    'in the last twenty minutes with three at the back',
    'the physio already on twice',
    'past a defender who had booted him in the first minute and got away with it',
    'in the middle of a run of five away games in six',
    'as the home crowd started whistling for the end',
    'with the low away-end roof throwing the noise back down',
    'on a Saturday when half the league was off with the weather',
    'at a ground reached down a lane between two rows of houses',
    'after a team meeting that ran an hour long',
    'with his boots wrong for the surface and no time to change',
    'in a fixture the fans had circled in July',
    'before the cameras had even settled',
    'in a stadium half-covered in tarpaulin where the new stand was going up',
    'against a side who had not conceded in five',
    'with the goalkeeper\'s kicking going straight into the wind all half',
    'down at a seaside ground with gulls on the roof',
    'after a first half nobody would want to watch again',
    'on the same pitch he had played on at seventeen for the youth team',
    'with a former team-mate now wearing the other shirt',
    'through a period where the game had gone completely flat',
    'at a Friday kick-off moved for engineering works on the line',
    'before an away end packed in behind a fence of stewards',
    'as a plastic bag went across the box in the wind',
    'under the eye of a scout sat two rows behind the dugout',
    'the same tannoy song they had played for thirty years',
    'in front of a stand where the season-ticket holders had sat in the same seats since the seventies',
    'out in the cold with the game stretched and legs gone',
    'alongside a striker who had not scored since September',
    'after being switched to the right at half-time',
    'with the crowd\'s mood turning somewhere around the hour',
    'on a heavy pitch that took a yard off everyone',
    'at the end where the away supporters had a full view of it',
    'in a match played out to a soundtrack of one drum',
    'against a captain who had won two league titles',
    'before a crowd who had come mostly to watch the other lot',
    'with a groundsman still forking a divot at half-time',
    'under a sky that had not got light all afternoon',
    'in a game that had been a six-pointer in every preview',
    'after twenty-two minutes of nothing at all',
    'on a night the club had put tickets at a tenner and filled the place',
    'with the referee having a quiet word between every free-kick',
    'at a ground where the away dressing room has no windows',
    'through a substitution he had not seen coming',
    'past a full-back who had shoved him twice already',
    'beside a corner flag bent in the wind',
    'with the team-sheet handed in an hour before and one name missing',
    'in the first game after a player had been sold',
    'as the numbers went up for four added minutes',
    'nothing each, and no sign of that changing',
    'on a Boxing Day pitch already frozen at the edges',
    'before an away following of six hundred and a lot of empty seats',
    'in front of the family stand, of all places',
    'out on a training pitch on the coldest morning of the year',
    'at a stadium where the club shop backs onto the tunnel',
    'after a night in a hotel by a roundabout',
    'with the manager watching from the stand for a touchline ban',
    'against a team playing their eighth game in a month',
    'in the away leg of a tie already half-lost',
    'under a floodlight pylon that had a bulb out',
    'with a fan on the pitch and the game stopped for a minute',
    'down the tunnel end where the noise doubles',
    'through a half of pure attrition',
    'on a surface that had gone greasy on top and hard underneath',
    'at a ground with a supermarket where the old terrace was',
    'alongside a keeper who kicked everything long all afternoon',
    'before the second half, with new instructions and a changed shape',
    'with the away end still coming in at ten past three',
    'in a match rescheduled to a Sunday teatime for the league\'s overseas deal',
    'against a marker eight years older and half a yard slower',
    'after a week of double sessions',
    'with the crowd on the referee from the first whistle',
    'at a place where the seats spell out the town\'s name',
    'in the twelfth minute of a game already gone',
    'on a pitch shared with a rugby league side',
    'steam coming off them at the break',
    'before a crowd of nineteen thousand, most of them wanting a change',
    'as the wind got up in the second half',
    'under a scoreline that had not moved since the fourteenth minute',
    'away in a stadium three sizes too big for the club inside it',
    'with the reserves\' game called off and everyone watching this one',
    'through a stoppage while a floodlight came back on',
    'after a corner routine they had done all week and never once got right',
    'at a ground where the pitch slopes about a yard corner to corner',
    'in front of the directors\' box, with the chairman not in it',
    'with the pitch flooded down one flank',
    'against a side who had gone two down and did not care',
    'forty-eight hours since the last whistle',
    'on the day the club announced a new sponsor',
    'beside a dugout where somebody was shouting at a coach',
    'at half past twelve on a Saturday, for the cameras',
    'in a first half of nothing but throw-ins',
    'before a crowd who had seen better and said so',
    'out on the far side, where the manager could not reach him with his voice',
    'with a new signing sat in a suit in the stand',
    'in a run of three games in seven days over Christmas',
    'on grass still white in the corners at kick-off',
    'at a ground where the away fans get the whole side, not the corner',
    'after being told an hour before that he was starting',
    'through the last quarter of an hour with a dead leg',
    'against a side who dropped eleven behind the ball',
    'with the fourth official\'s board glowing in the drizzle',
    'before an away end who had been singing the manager\'s name since they arrived',
    'in a stadium with two ends closed for building work',
    'under the sort of rain that empties a stand by the hour mark',
    'at a kick-off that had already been moved twice',
    'with a ball boy taking his time on the far side',
    'on the anniversary of something the club had put on the shirts',
    'alongside a lad making his debut at eighteen',
    'as the home side made a triple change on the hour',
    'with the game on in a hundred countries and eleven thousand in the ground',
    'in a season that had turned into a fight',
    'down at the bottom end, where the roof leaks',
    'after a goal disallowed by an armpit',
    'with the away coach given a police escort out',
    'in front of a crowd told that week the season ticket was going up',
    'at a training ground where the pitches had gone to mud by December',
    'against a defender who had done him three seasons running',
    'through a passage of play that lasted a minute and a half without a break',
    'on a Thursday, in a competition nobody had wanted to be in',
    'with the manager\'s assistant taking the warm-up alone',
    'before a crowd that had thinned out by twenty past four',
    'under a roof full of pigeons',
    'out in front of eight hundred who had travelled on a night bus',
    'beside a touchline with no room to run down',
    'at a ground where the noise comes back off the flats behind the stand',
    'with two of them off with hamstrings inside half an hour',
    'in the fourteenth game of a run without a rest',
    'after the whistle for offside that never came',
    'with a defender\'s arm across his chest for the whole set-piece',
    'on a night when the announcer got his name wrong',
    'in a fixture that had filled the ground every year since he was born',
    'as the board went up with his number on it',
    'an hour gone, the crowd very quiet',
    'against a keeper who had been at the club sixteen years',
    'in a corner of the pitch nobody could get out of',
    'before kick-off, boots on, in a tunnel with a low ceiling',
    'at a stadium where they still ring a bell before kick-off',
    'through the first twenty minutes of a game they had to win',
    'on a pitch that had been under covers for three days',
    'with the sun low enough to blind one goalkeeper for a half',
    'down at a ground where the away end faces west into it',
    'after a booking he could not argue with',
    'in the league\'s coldest week in a decade',
    'alongside a midfielder who had asked to leave in the summer',
    'with a stand of school kids on free tickets',
    'before a cup tie against a side four divisions below',
    'out on grass cut short and watered twenty minutes before',
    'at the end of a week when three players had been left out',
    'the physio\'s bag open on the touchline',
    'in a game the club needed for the gate money as much as the points',
    'against a side who had a man sent off and got better for it',
    'as the second half went the way of the first',
    'on a Sunday morning nobody thought the pitch inspection would pass',
    'with the assistant limping and a fourth official warming up',
    'in front of a crowd two thousand down on last season',
    'at a place where the away seats have a pillar in front of them',
    'under a caretaker\'s first team talk',
    'through a half where the ball spent most of its time in the air',
    'before a game billed all week as the manager\'s last',
    'with an away end that had not stopped for eighty minutes',
    'on a pitch the referee had walked twice before nine',
    'beside a corner flag with a photographer\'s lens two feet away',
    'after eleven days without a fixture',
    'against a team who had signed four players in January',
    'in the last home game before a run of four on the road',
    'with a hole in the netting and somebody\'s ball out in the car park',
    'at a kick-off moved to Monday and half the away end unable to come',
    'down the side where the coaching staff pace the whole ninety',
    'as the floodlights came on at twenty past three',
    'the trainer counting them back in at the whistle',
    'in a stadium where the announcer reads the team out one name at a time',
    'on a surface relaid in the summer and still not right',
    'after the coach got in at four in the morning',
    'with a whole back four he had not played in front of before',
    'against a midfielder who had been capped nineteen times',
    'at a ground with a gate of six thousand and a stand built for twenty',
    'before the biggest away following the club had taken in years',
    'in weather that turned the ball into something else entirely',
    'through a scrappy, ugly November of one-nils',
    'on the day the club sold its top scorer',
    'with the pitch still marked from an under-21 game the night before',
    'at a ground where the away fans can hear the home dugout',
    'alongside a substitute told to warm up and then sat back down',
    'as the crowd turned on the substitution',
    'out in a warm-up under a sky about to break',
    'with the badge repainted on the halfway line that morning',
    'in front of a stand that had been closed for two years',
    'against men who had been marking his sort for a decade',
    'after a first touch that went ten yards and the groan that followed',
    'with the bus stuck in traffic and the warm-up cut to fifteen minutes',
    'on a night when nothing about it was pretty',
    'before an empty seat where his dad usually sat',
  ],
};
export const CHILD_SETUP_M: Bank = {};
export const EVENT_PREFIX_M: Bank = {};
export const BIG_SETTINGS_M: string[] = [];
