// Authoring pack B. One author owns this file — nobody else writes to it, so packs never collide.
// Keys must match the bank they extend (see shared/src/prompts/*.ts for the key names and the house voice).
import type { Bank } from '../merge.js';
export const KIND_SETUP_B: Bank = {};
export const DEMAND_B: Bank = {
  aggression: [
    'Teeth, not manners.',
    'A tackle is due.',
    'Steel, and plenty of it.',
    'Somebody has to answer this.',
    'Boots first, apologies afterwards.',
    'Two men, one ball.',
    'Grit, not gloss.',
    'The duel decides everything.',
    'Front foot or nothing.',
    'Menace would help here.',
    'A fifty-fifty is coming.',
    'Nobody has gone in yet.',
    'Ugly work, and quickly.',
    'Whoever wants it most.',
    'The soft option is available.',
    'Somebody must plant a flag.',
    'Appetite, plainly measured.',
    'No polite way through.',
    'A tackle waiting to be won.',
    'The first challenge sets the price.',
    'Half a yard, taken by force.',
    'His marker has had it easy.',
    'The loose ball belongs to somebody.',
    'Courage, of the entirely unglamorous sort.',
    'A pitch that has gone quiet.',
    'They want an edge from him.',
    'The braver man keeps the ground.',
    'Somebody has taken liberties tonight.',
    'A body between ball and opponent.',
    'Territory, rather than football, is at stake.',
    'The physical exchange has been entirely one-sided.',
    'A challenge that will hurt somebody.',
    'Shoulder against shoulder, and no referee nearby.',
    'It asks whether he fancies the fight.',
    'Nobody wins a header by hoping for it.',
    'The moment wants weight behind the shoulder.',
    'A duel with a man who never loses one.',
    'They need to see him dish it out.',
    'Somebody is being bullied and nobody has noticed.',
    'It calls for a proper challenge, timed and honest.',
    'The next contact has to carry a message.',
    'A statement is overdue, and it will not be verbal.',
    'Standing off has achieved nothing for half an hour.',
    'It wants him first, hard, and entirely unbothered.',
    'The gaffer is looking for somebody to set a tone.',
    'A game that belongs to whoever refuses to be moved.',
    'Retaliation is easy; doing it legally is the hard part.',
    'His team have gone soft and everybody can see it.',
    'It asks him to stop being the smaller man.',
    'A yard of ground that neither man wants to give up.',
    'The moment rewards the man who does not check his stride.',
    'Somebody has to stop admiring the ball and go and win it.',
    'It asks for the sort of challenge that makes a bench stand up.',
    'The opposition have decided he is the one to lean on.',
    'A hard afternoon is available if he wants to make one.',
    'Being reasonable has not worked and is not going to.',
    'It wants an appetite for the collision, not a plan to avoid it.',
    'The referee will sort it out later; the ball needs winning now.',
    'A contest that is physical long before it is anything else.',
    'Nobody remembers a tackle that was never actually made.',
    'It asks whether he can stay unpleasant for the full ninety minutes.',
    'The middle of the pitch is unclaimed and somebody is going to take it.',
    'A moment that measures how badly he actually wants the ball.',
    'Being second to everything is a decision rather than bad luck.',
    'It wants him wound up, and pointed in roughly the right direction.',
    'The lads have watched somebody take liberties and are waiting for a reply.',
    'A challenge somewhere between brave and reckless, with no time to work out which.',
    'It asks for the stubbornness that irritates opponents into mistakes.',
    'Half-hearted is how people get hurt in situations exactly like this.',
    'The next fifty-fifty will tell both sides what the rest of the afternoon looks like.',
    'A moment where backing out is available and would be noticed by everyone.',
    'It comes down to which of them is prepared to get hurt.',
    'Somebody has to make the next twenty minutes thoroughly uncomfortable for the other lot.',
    'The physio will hear about this one whichever way it goes.',
    'A question of whether he will put his head where the boots are going.',
    'It wants the kind of edge that no coach has ever managed to teach.',
    'Nothing about the situation can be solved by being polite about it.',
    'The other side have not been asked to earn a single thing yet.',
    'A marker needs laying down before the half is out, and nobody has laid it.',
    'It asks him to arrive with intent rather than merely arrive on time.',
    'Somebody must be prepared to be disliked for the next ten minutes.',
    'The ball is fifty-fifty; the willingness to go and get it is not.',
    'A tempo that will be set by force rather than by football.',
    'It rewards whoever is still going in when the ground is hard and the legs are sore.',
    'His man has been given far too much room for far too long.',
    'A duel he has lost twice already, with a third one coming.',
    'It wants him to look like a problem the other lot have not solved.',
    'The dressing room will notice who put a body in and who did not.',
    'Somebody has to want the collision more than the other man does.',
    'It asks for controlled aggression, which is a great deal harder than the other sort.',
    'A moment that will belong to the braver of the two men involved.',
    'The game has been played at arm’s length and somebody has to close the gap.',
    'It wants a challenge that leaves the opponent thinking about the next one.',
    'Nobody is going to hand him anything in the next thirty seconds.',
    'A physical question, and there is no clever answer available to it.',
    'It asks for the work nobody volunteers for and nobody thanks him for.',
    'The moment favours appetite, and appetite is not a thing he can fake.',
    'Somebody must decide that being liked matters less than winning the ball.',
    'A challenge is coming whether he wants it or not.',
    'It wants steel in the tackle and nothing at all in the words afterwards.',
  ],
  creativity: [
    'Invention, or nothing.',
    'The obvious ball is covered.',
    'A locked door somewhere.',
    'Nobody has seen it yet.',
    'One idea would do.',
    'Geometry, not effort.',
    'Something has to be invented.',
    'The pattern needs breaking.',
    'A puzzle, not a fight.',
    'Craft, rather than force.',
    'Two banks of four.',
    'Somebody must think of something.',
    'The safe pass keeps failing.',
    'A seam, if anybody finds it.',
    'Everything sensible has been tried.',
    'Half a thought ahead.',
    'Imagination is the missing item.',
    'A crowded box and no width.',
    'The gap exists; finding it is the work.',
    'Nobody has taken a risk all half.',
    'A picture only one player can see.',
    'It asks for vision rather than legs.',
    'The runner is there if anybody spots him.',
    'A defence that has solved everything so far.',
    'It rewards the eye more than the boot.',
    'The angle is wrong for the ordinary solution.',
    'Space has to be manufactured out of nothing at all.',
    'It calls for a pass that has occurred to nobody.',
    'A first touch that would solve three problems at once.',
    'Nothing rehearsed on the training ground is going to unlock this.',
    'The percentages say sideways; the picture says something else entirely.',
    'It wants the ball played where the defender is not looking.',
    'A moment for a lock-picker rather than a battering ram.',
    'Somebody has to change the shape of the problem itself.',
    'It asks him to think in a direction nobody has considered.',
    'The clever ball is on if anybody dares to play it.',
    'A defence set up precisely for what the team keeps doing.',
    'It wants an idea more than it wants a technique.',
    'Twenty players on the pitch and one thought missing from all of it.',
    'The team have run out of ways to ask the same question.',
    'It rewards whoever plays what he sees rather than what he was told.',
    'A gap that opens for a second and then closes again for good.',
    'It asks for improvisation, without tipping over into recklessness.',
    'Nobody expects the ball to go backwards in order to go forwards.',
    'The training-ground moves have all been read and dealt with.',
    'A congested pitch with one sliver of daylight somewhere in it.',
    'It wants the sort of pass that is only obvious afterwards.',
    'Somebody must see the third man run before the third man does.',
    'A moment that punishes the obvious and forgives almost nothing else.',
    'It calls for the answer nobody in the ground has thought of yet.',
    'The straightforward option keeps leading precisely nowhere at all.',
    'A stubborn defence, a tight pitch, and one solution hidden inside both.',
    'It asks whether he can hold three moves in his head at once.',
    'Everybody is watching the ball, which is exactly where the answer is not.',
    'It wants a disguise put on an otherwise ordinary pass.',
    'A defence organised well enough that it will have to be outwitted.',
    'The picture keeps rearranging itself and somebody has to keep up with it.',
    'It asks for thought at full pace, which is the genuinely difficult part.',
    'One clever ball would change an afternoon that has been going nowhere.',
    'A moment for the kind of intelligence that does not show up in fitness data.',
    'It wants him to break the rhythm deliberately rather than by accident.',
    'Nobody has tried the difficult side of the pitch for twenty minutes.',
    'A pass exists somewhere that would settle the entire argument in one movement.',
    'It rewards a strange idea taken confidently rather than a safe one taken well.',
    'The route forward is not remotely where anybody is currently looking.',
    'It asks him to notice the thing everyone else has stopped noticing.',
    'A problem that will not yield to effort, however much effort is applied.',
    'It wants the ball delivered into a space that is still being made.',
    'Somebody has to see what is not there yet and act as though it is.',
    'The plan has been read from the first minute and something else is needed.',
    'It calls for a solution that will look extremely silly if it does not work.',
    'A moment where the coaching manual has run out of useful pages.',
    'It asks for the touch that buys a yard out of absolutely nowhere.',
    'Everything the side has attempted has been dealt with comfortably.',
    'It wants him to invent rather than repeat what worked last week.',
    'A crowded middle of the pitch and an empty flank nobody has used.',
    'It rewards the player who is thinking while everybody else is running.',
    'The defenders are comfortable, which is the whole of the problem.',
    'A moment that wants the ball moved before anybody expects it moved.',
    'It asks for an answer with a bit of nerve buried inside it.',
    'One line drawn across the pitch that nobody has drawn before.',
    'It wants a first-time ball that not one player has considered.',
    'A defence flat and organised, waiting for exactly the pass they expect.',
    'It asks him to look up and find something genuinely odd.',
    'The obvious option is available, and it has failed eleven times already.',
    'A moment that will only work if he sees it before the defender turns.',
    'It rewards the idea, and the execution can be scruffy if it has to be.',
    'Somebody must ask the defence a question they have not been asked yet.',
    'A tight corner with no straight line out of it in any direction.',
    'It wants the weighted ball that makes somebody else’s run look easy.',
    'The moment belongs to whoever sees it first, and there is not long.',
    'It asks for a mind quicker than the situation unfolding around it.',
    'A packed penalty area asking for cunning rather than power.',
    'It wants something original, and it wants it in the next two seconds.',
    'Nobody would blame him for the simple ball, and that is the trouble with it.',
    'A moment where the picture matters far more than the technique.',
    'It calls for the pass that makes people in the stand sit forward.',
    'The defence have been given nothing to worry about all afternoon.',
    'It asks him to solve it with his head rather than his lungs.',
    'A thought arriving half a second before the defender does is the entire margin.',
  ],
  composure: [
    'A cool head, basically.',
    'The noise is the test.',
    'Panic is the opponent.',
    'Nerve, nothing else.',
    'Heart rate, mostly.',
    'One decision, made calmly.',
    'The moment punishes hurry.',
    'A still head required.',
    'Everybody around him is rushing.',
    'Stillness in a loud place.',
    'The occasion has grown teeth.',
    'A quiet second, found somewhere.',
    'Slow it down.',
    'Control first, football second.',
    'A hostile ground and one touch.',
    'The clock says hurry.',
    'Nothing here is technically difficult.',
    'Breathe, then decide.',
    'A calm decision in an uncalm minute.',
    'It asks for the extra half-second.',
    'The ground has gone very loud.',
    'A test of temperament with nowhere to hide.',
    'Everyone is shouting a different instruction at him.',
    'It wants routine where there is nothing routine.',
    'The right choice is easy; making it now is not.',
    'A moment that gets bigger the longer it lasts.',
    'It rewards the man whose hands stay dry.',
    'Rushing has already cost his team twice tonight.',
    'A decision that will be replayed whichever way it goes.',
    'It wants the same technique under twice the usual pressure.',
    'The pressure is the whole test; the football part is simple.',
    'A moment that has undone considerably better players than him.',
    'It asks him to treat this like any other ball.',
    'Ten thousand people would very much like him to hurry.',
    'It wants him to act as though nothing unusual is happening.',
    'The last man who faced this got it badly and publicly wrong.',
    'A situation designed from top to bottom to make somebody rush.',
    'It asks whether the size of the occasion has shrunk him.',
    'Everything depends on him not thinking about everything at once.',
    'It calls for the boring, correct thing, done properly and without fuss.',
    'The temptation is to do it a good deal faster than necessary.',
    'A wall of sound, and one small decision to be made inside it.',
    'It wants judgement, arrived at calmly, with the ground screaming.',
    'Nobody is going to give him time, so he will have to take it.',
    'A cold assessment made at speed, which is the difficult combination.',
    'It asks him to hold his nerve for three seconds longer than feels natural.',
    'The scoreline has made every single touch feel considerably heavier.',
    'A moment where composure is genuinely the only skill required.',
    'It rewards the player who flatly refuses to be hustled into anything.',
    'Everything about the situation is quietly inviting him to make a mistake.',
    'It wants a settled first touch and absolutely nothing dramatic afterwards.',
    'The crowd will remember this one whichever way it happens to go.',
    'A test of nerve that has been dressed up as a test of skill.',
    'It asks for restraint at the exact moment instinct is saying otherwise.',
    'Two team-mates have already been broken by the pressure tonight.',
    'It wants him looking like the calmest man anywhere on the pitch.',
    'The game has gone frantic and somebody has to decline to join in.',
    'A situation with one right answer and no time at all to enjoy finding it.',
    'It asks him to stop the game speeding up inside his own head.',
    'Nerves are entirely normal; being governed by them is the failure.',
    'It wants the decision made once rather than made and remade three times.',
    'The whistle is close and the temptation to force something is closer.',
    'A quiet mind would be worth more than a goal in this situation.',
    'It asks him to keep his shape while everything around it tilts.',
    'Everything gets a good deal easier the moment he refuses to panic.',
    'It rewards the head that stays above the moment rather than inside it.',
    'A crowd that has spent ten minutes trying to unsettle exactly this.',
    'It wants him to take the sting out of a situation that is full of it.',
    'The moment does not care in the slightest how much it happens to matter.',
    'A pair of calm feet here would settle the entire side around him.',
    'It asks for the same swing he has made a thousand times in training.',
    'Nothing about this is hard except every single circumstance around it.',
    'It wants him to hold his own tempo while the game insists on another.',
    'The hands are shaking and the pass still has to be properly weighted.',
    'A moment that rewards patience and punishes fear in roughly equal measure.',
    'It asks whether he can be trusted when the game has gone tight.',
    'Everyone else out there has quietly stopped thinking clearly.',
    'It wants him unbothered, or failing that, convincingly pretending to be.',
    'The occasion is considerably bigger than the football being asked of him.',
    'A decision made under a noise he has never played in before.',
    'It asks him to slow his own game down while everybody speeds theirs up.',
    'It rewards whoever can still think properly at a full sprint.',
    'A moment where the mistake would be remembered a great deal longer than the success.',
    'It wants control of himself first, and control of the ball immediately afterwards.',
    'The panic around him is louder than any instruction he is being given.',
    'It asks for a level head and an unhurried touch, in that order.',
    'A test of what happens to him when a crowd genuinely turns.',
    'It wants the technique to survive an occasion designed to destroy it.',
    'Nobody would be surprised if he rushed it, and that is the danger.',
    'It asks for the discipline to wait one beat longer than anybody wants.',
    'A moment where looking calm matters almost as much as being calm.',
    'It wants him to treat the pressure as background rather than as the subject.',
    'The situation is simple and every single thing around it is difficult.',
    'It asks him to be the last man on the pitch to lose his head.',
    'A steady heartbeat would be worth more here than a clever touch.',
    'It rewards stillness, in an extremely busy corner of a very loud ground.',
    'Everything hinges on him not overplaying a situation that plays itself.',
    'It wants him to look up at the exact moment everyone is screaming at him.',
    'A cool decision, taken once, and then lived with either way.',
  ],
  teamwork: [
    'The answer involves somebody else.',
    'Shape, not brilliance.',
    'Somebody has to cover.',
    'The unselfish option, obviously.',
    'A run nobody will notice.',
    'Trust, given and returned.',
    'Give it and go.',
    'The boring pass is correct.',
    'Eleven players, one shape.',
    'Somebody must fill that gap.',
    'Useful beats impressive.',
    'The free man is calling.',
    'A decoy, essentially.',
    'Work, not headlines.',
    'His mate is drowning quietly.',
    'The overlap is on.',
    'Somebody has to press first.',
    'A square ball, unapplauded.',
    'A team-mate has made the run.',
    'It asks him to trust the man outside him.',
    'The full-back is exposed and needs help immediately.',
    'Somebody has to take the ball off the struggling lad.',
    'It wants the pass that makes the next pass possible.',
    'A partnership is quietly being built or broken here.',
    'It rewards the player who tracks back without being asked.',
    'The team need the ball kept, not the crowd entertained.',
    'A simple ball to feet would achieve more than a spectacular one.',
    'It asks him to fill a gap that is not really his to fill.',
    'Somebody is out of position and somebody else has to fix it.',
    'It calls for the run that drags a defender out of the way.',
    'The unit is only ever as good as its slowest bit of cover.',
    'A moment that works only if two of them read it the same way.',
    'It wants him to make the easy option available to somebody else.',
    'The clever ball is on, and the sensible one is better.',
    'It asks for the kind of work that shows up in nobody’s figures.',
    'A young lad beside him badly needs bringing into the game.',
    'It rewards the pass that quietly costs him all of the credit.',
    'The move needs a fourth man and he happens to be nearest.',
    'It wants him to hold the ball until somebody arrives to help.',
    'A team-mate has been given a torrid time and needs somebody near him.',
    'It asks him to give the ball to whichever of them is in form.',
    'Somebody has to take the unglamorous corner of the pitch tonight.',
    'It calls for a lay-off and a run past, and nothing more complicated.',
    'The gaffer has spent all week asking two players to think as one.',
    'A collective effort with one obvious weak link that needs covering.',
    'It wants an extra ten yards run entirely on somebody else’s behalf.',
    'The pass is not remotely spectacular, and it is exactly right.',
    'It asks him to close the door his mate left standing open.',
    'A pattern the whole side has drilled that needs all of them to work.',
    'It rewards trust, given rather than demanded, and given first.',
    'Somebody needs to stand in the way of a counter nobody else has seen.',
    'It wants him to run the channel so that somebody else gets the space.',
    'The dressing room is watching closely to see who does the dirty work.',
    'A team-mate has apologised twice already and needs an arm round him.',
    'It asks him to give up a decent shot in exchange for a better one.',
    'Somebody has to be the outlet that nobody ever thanks anybody for being.',
    'The move dies unless somebody supports the ball inside the next second.',
    'It wants a quiet word in an ear rather than a gesture for the crowd.',
    'A moment in which the selfish thing is also very clearly the losing thing.',
    'It rewards the player who plays for the shirt standing next to him.',
    'The lad ahead of him has not had a touch in ten long minutes.',
    'It asks him to take the ball into a bad area because the team needs it there.',
    'Somebody has to be brave enough to be completely predictable.',
    'A back four holding firm depends entirely on all four of them holding.',
    'It wants the ball recycled patiently rather than forced through the middle.',
    'The keeper needs a body in front of him and nobody has offered one.',
    'It asks him to be useful long before he tries to be impressive.',
    'A debutant beside him is having a nightmare and saying nothing about it.',
    'It wants the pass across, not the shot from an impossible angle.',
    'Somebody needs to take some of the load off the man carrying all of it.',
    'It rewards the honest ten yards that nobody in the ground will remember.',
    'A group only holds together if one of them is prepared to do this.',
    'It asks him to be the player the team needs, not the one he wants.',
    'The whole afternoon turns on somebody being unselfish for four seconds.',
    'It wants him to defend from the front, which is nobody’s favourite job.',
    'A team-mate is calling for it and, irritatingly, is completely right.',
    'It asks him to hold the line with the rest of them, exactly.',
    'Somebody must sacrifice their own afternoon for the sake of the plan.',
    'It wants the tidy five yards, repeated all afternoon without complaint.',
    'A moment made for a workhorse rather than for a showman.',
    'It asks him to keep the ball simply because the team need a breather.',
    'The winger has been isolated for an hour and needs somebody alongside him.',
    'It rewards the man who makes room for other people to play in.',
    'A system that only works when the least glamorous job is done properly.',
    'It wants him to set the screen and let another man take the applause.',
    'Somebody is screaming for it and, on the evidence, deserves it.',
    'It asks for the block rather than the interception, which is less fun.',
    'The shape holds only as long as everybody agrees to hold it.',
    'It wants him to look for the free man first, and every time.',
    'A moment measured entirely in what the team gains, not what he does.',
    'It asks him to make somebody else the story of the afternoon.',
    'Somebody has to do the running that lets the whole plan breathe.',
    'It wants him where he is supposed to be rather than where the ball is.',
    'A team-mate has taken a knock and the shape needs shuffling round him.',
    'It rewards whoever covers the ground somebody else could not manage.',
    'The right pass here will be forgotten by everybody within a minute.',
    'It asks him to talk, and rather harder, to listen.',
    'A moment that only counts if he makes it belong to somebody else.',
    'It wants the ball moved on first time, before the pressure arrives.',
    'Somebody has to do the thing that keeps ten other people in the game.',
  ],
  leadership: [
    'Ten men are waiting.',
    'Somebody has to speak.',
    'The room has gone quiet.',
    'An example, not a speech.',
    'Heads are dropping.',
    'A standard needs setting.',
    'Nobody has taken charge.',
    'Responsibility, willingly taken.',
    'The armband is loose.',
    'Somebody must decide.',
    'A voice is missing.',
    'Presence, more than volume.',
    'The group is drifting.',
    'Standards have quietly slipped.',
    'Somebody has to front up.',
    'A team looking for somebody.',
    'The silence needs breaking.',
    'Accountability, and no excuses.',
    'A young lad needs telling, kindly.',
    'It asks him to demand better from people.',
    'The gaffer has said his piece; the players have not.',
    'Somebody has to be honest with a team-mate who will hate it.',
    'It wants him to carry the responsibility that nobody else wants.',
    'A dressing room quietly deciding what it is prepared to tolerate.',
    'It rewards the man who steps forward when it is unpopular.',
    'The captain is off and the job has landed somewhere unclaimed.',
    'A moment that decides who this group of players actually listens to.',
    'It asks for authority that nobody has yet got round to giving him.',
    'Somebody must stop the argument before it turns into a proper split.',
    'It wants him to lift a side that has visibly stopped believing.',
    'The half-time silence has gone on too long and needs breaking.',
    'A squad that will take its temperature from whoever speaks first.',
    'It asks him to take responsibility for a mistake that was not his.',
    'Standards have slipped, everybody has noticed, and nobody has said anything.',
    'It calls for the unpopular truth, said plainly, to people who outrank him.',
    'A younger player is looking directly at him and waiting to see what happens.',
    'It wants the sort of leadership that gets done rather than announced.',
    'Somebody needs to reorganise this shambles before the next attack arrives.',
    'It asks him to protect a team-mate who is being deliberately targeted.',
    'The senior men have said nothing at all, and the silence is telling.',
    'A moment that will be remembered by the lads rather than by the crowd.',
    'It wants him to demand the ball at nought-nil in a hostile ground.',
    'Somebody must make a decision and be publicly wrong if it comes to that.',
    'It rewards whoever takes charge of a situation that has turned ugly.',
    'A group of exhausted men needing one of them to insist on more.',
    'It asks whether the others would genuinely follow him anywhere.',
    'The mistake has already been made; the reaction to it is the real issue.',
    'It wants a hand on a shoulder and one very clear instruction.',
    'Somebody has to be the adult in a distinctly childish moment.',
    'A team-mate is losing his head and needs pulling back before the referee acts.',
    'It calls for a standard set by behaviour rather than announced in words.',
    'The dressing room is looking for somebody either to blame or to follow.',
    'It asks him to hold other people to exactly what he asks of himself.',
    'A defeat that needs owning by somebody, in front of everybody.',
    'It wants him to set the tone for the last twenty minutes of this.',
    'Somebody has to insist the shape holds when everybody wants to chase.',
    'It asks him to be counted at the precise moment it costs him something.',
    'The younger players have nobody at all to copy tonight.',
    'A team-talk that needs to come from a player rather than a coach.',
    'It wants him to keep the group together when it would be far easier not to.',
    'It asks him to drag eleven tired men through another ten minutes.',
    'Somebody must speak to the referee before the situation gets any worse.',
    'A moment in which staying silent would be very clearly the wrong answer.',
    'It rewards the man who does not stand about waiting for permission.',
    'The plan has collapsed and somebody has to improvise on behalf of everybody.',
    'It asks for the courage to be responsible for how this turns out.',
    'A group with a great many talkers in it and no leaders at all.',
    'It wants him to take the criticism and decline to pass any of it on.',
    'Somebody needs to make a decision that the rest of them can trust.',
    'It asks him to show the way rather than stand and point at it.',
    'A team that will remember exactly who spoke and who looked at the floor.',
    'It wants the standard held even though the result has already gone.',
    'Somebody has to be the reason this does not fall apart entirely.',
    'It asks him to look after the group before he looks after himself.',
    'A moment that quietly separates the loud players from the trusted ones.',
    'It wants him to take the free-kick that nobody else is volunteering for.',
    'The gaffer is watching the room to see which of them reacts.',
    'It asks him to lead men who were at this club long before he arrived.',
    'A club under pressure and a dressing room short of anybody willing to own it.',
    'It wants somebody to take the weight off the youngest man out there.',
    'The team have stopped organising themselves and are waiting to be organised.',
    'It rewards calm authority far more than it rewards shouting.',
    'Somebody has to take charge of a decision that is going badly wrong.',
    'It asks him to raise a standard rather than merely meet the existing one.',
    'A captaincy question that is being answered right now, by somebody.',
    'It wants him to take on the hard conversation that everyone is avoiding.',
    'The room needs somebody to say plainly what happens from here.',
    'It asks for a decision, taken publicly, and owned publicly afterwards.',
    'A moment where standing back would be noticed by every man in the room.',
    'It wants him to demand more from men who have already given plenty.',
    'Somebody must be the one who simply refuses to accept how this is going.',
    'It rewards whoever holds his nerve on behalf of ten other people.',
    'A group that will follow whichever of them moves first, for good or bad.',
    'It asks him to take charge of a set-piece that nobody has claimed.',
    'The armband is not on his sleeve, and the job is his anyway.',
    'It wants an example set in the next thirty seconds, by somebody.',
    'A side that has stopped believing, and one man who could change that.',
    'It asks him to front up to the supporters afterwards, whatever happens.',
    'Somebody has to steady a team that is visibly coming apart at the seams.',
    'It wants him to be the one who demands better, out loud, right now.',
  ],
  stamina: [
    'Legs, and nothing else.',
  
    'One more run.',
    'Everybody is finished.',
    'Work, plain and boring.',
    'The tank is empty.',
    'Who lasts longest.',
    'Cramp is coming.',
    'A heavy pitch.',
    'Nothing clever left.',
    'Lungs first, football second.',
    'The pitch has got longer.',
    'Somebody has to keep running.',
    'A body asking to come off.',
    'Ninety minutes and counting.',
    'Fatigue is deciding things.',
    'Another sprint, unrewarded.',
    'The last twenty minutes.',
    'A run that has to be made again.',
    'It asks for work that has stopped being enjoyable.',
    'The recovery run is forty yards and uphill in his head.',
    'A test of exactly what he did during the summer.',
    'It wants him still moving when everybody else has stopped.',
    'Everybody is spent; the difference is what they do about it.',
    'A schedule of three matches in a week and no rest anywhere in it.',
    'It asks for one more sprint that nobody would notice him missing.',
    'The game is being decided by whichever of them is still genuinely fit.',
    'A body that has already done ninety minutes and is being asked for more.',
    'It rewards whoever spent July preparing for exactly this ten minutes.',
    'Legs full of concrete and a full-back who has not stopped running.',
    'It wants the same intensity in the last minute as in the first.',
    'A match that has quietly turned into a straightforward fitness test.',
    'It asks him to go again with absolutely nothing left to go with.',
    'The forward ahead of him has been running all night and has not slowed.',
    'A pitch cutting up badly and twenty minutes still to be played.',
    'It wants him pressing at a point where pressing feels entirely pointless.',
    'Extra time, no substitutions left, and two sets of ruined legs.',
    'It asks for the third full sprint inside ninety seconds.',
    'A long season is showing in every set of legs on the pitch.',
    'It rewards relentlessness, and there is nothing else on offer here.',
    'Somebody has to keep covering that entire flank on his own.',
    'It wants him upright while the rest of them are on their haunches.',
    'A test of conditioning that has been dressed up as a test of will.',
    'It asks him to run himself into the ground without making a fuss about it.',
    'The heavy ground is quietly punishing everybody who has stopped working.',
    'A game in which the substitutes will decide things unless he lasts.',
    'It wants one more lung-busting run into a corner that may come to nothing.',
    'It asks whether he can do all of this again in four days.',
    'Every yard now costs him roughly twice what it cost him an hour ago.',
    'A midfield battle that has stopped being football and become attrition.',
    'It rewards the player whose head does not go the moment his legs do.',
    'The tempo has been brutal for an hour and it is not slowing down.',
    'It wants him to make a recovery run that nobody at all expects.',
    'A tired side, and one man who is not allowed to be tired yet.',
    'It asks for the endless, boring, unwatched work of a full ninety minutes.',
    'Muscles are burning and the ball keeps coming straight back at him.',
    'It wants persistence long after the point of the persistence has gone.',
    'A hard week behind him and a considerably harder afternoon in front.',
    'It asks him to outlast a man who is every bit as finished as he is.',
    'The whole side are hanging on and one of them has to refuse to.',
    'It rewards whoever runs at the exact moment the game says walk.',
    'Nobody in the ground would criticise him for jogging that particular one.',
    'It wants him working hard with the score already comfortably settled.',
    'A match where simply staying on the pitch counts as an achievement.',
    'It asks him to close a gap he has already closed twelve times tonight.',
    'The last twenty minutes of this have become a completely different sport.',
    'It wants him holding his running at the point where it stops mattering to him.',
    'A test of appetite for running rather than any appetite for football.',
    'It asks him to do it all again after a very bad night’s sleep.',
    'The opposition are looking hard for whoever has stopped tracking runners.',
    'It rewards the man who trained through the parts of pre-season he hated.',
    'A body at the end of a long month with no gaps left in it.',
    'It wants him covering ground that not one person in the stand is watching.',
    'The touchline is shouting for one more push out of men who have none.',
    'It asks for effort at the very end of an extremely long season.',
    'A tie that is going to be settled by legs rather than by skill.',
    'It wants the same work rate at nil-three as there was at nil-nil.',
    'His marker has stopped running, which is more or less an invitation.',
    'It asks him to keep going long after the moment has actually passed.',
    'A pitch, a clock, and twenty-two players with nothing much left.',
    'It rewards whoever finds something after everything has already gone.',
    'Somebody must keep offering for the ball even though it hurts to.',
    'It wants him still running in the ninety-fourth minute of a lost game.',
    'A game stretched long and thin, with the interesting part gone.',
    'It asks how deep he is actually prepared to dig for this.',
    'The heat has taken something out of every man on the pitch.',
    'It wants him chasing what is almost certainly a lost cause anyway.',
    'A body that will feel this for three days and does not get a say.',
    'It asks for the fortieth press of the afternoon to look like the first.',
    'Everybody slows down eventually; the only question is who slows least.',
    'It wants him to keep the option available for a team that keeps missing it.',
    'A run that arrives two seconds after everybody else quietly gave up.',
    'It asks whether the fitness work was actually done or merely attended.',
    'The game will be won or lost in the final quarter of an hour.',
    'It rewards the man who declines to hide when hiding is entirely possible.',
    'Somebody has to keep the pressing going on his own if it comes to that.',
    'It wants him sprinting back immediately after sprinting all the way forward.',
    'A tired team, a loud crowd, and fifteen minutes that will decide everything.',
    'It asks for stubborn legs, a short memory and absolutely no complaints.',
  ],
  flair: [
    'The safe pass is dull.',
    'Something bold, ideally.',
    'A crowd is waiting.',
    'Nerve over sense.',
    'The trick is on.',
    'Boldness, or nothing.',
    'One touch could do it.',
    'A quiet game needs something.',
    'Instinct, not instruction.',
    'The defender has committed.',
    'Somebody should try something.',
    'A moment for theatre.',
    'The obvious option is forgettable.',
    'Brilliant or foolish, nothing between.',
    'His feet, or nobody’s.',
    'A chance to be ruthless.',
    'The bench is leaning forward.',
    'Something outrageous is available.',
    'A stage, a ball, a decision.',
    'It asks whether he trusts his own feet.',
    'The percentages absolutely hate what is currently available.',
    'A defender standing off him and practically inviting it.',
    'It wants the audacious option taken without any hesitation at all.',
    'One-on-one, an open pitch, and a crowd already on its feet.',
    'It rewards the player who is not remotely afraid of looking stupid.',
    'The ball has sat up perfectly and the goal is a very long way off.',
    'A moment that separates the entertainers from the merely professional.',
    'It asks for the flourish that the situation does not remotely require.',
    'Somebody could do something extremely silly here, in the very best sense.',
    'It wants him taking the defender on rather than passing it sideways.',
    'A tight angle, an unlikely idea, and about a second to decide.',
    'It asks for something the coaching staff will visibly wince at.',
    'The chance to embarrass a defender who has been talking all afternoon.',
    'It wants the first touch to be a statement rather than a control.',
    'A situation begging for somebody with no fear of failure whatsoever.',
    'It rewards the man who dares to try it in front of a full ground.',
    'Everybody has settled for sideways passes for twenty long minutes.',
    'It asks him to try the thing he practises alone after training.',
    'A chance to do something that people will still be talking about tomorrow.',
    'It wants the ball flicked somewhere that nobody has thought to defend.',
    'The gaffer would much prefer the simple ball; the moment would not.',
    'It asks for expression at a point where obedience would be safer.',
    'A ball dropping over his shoulder with the goal somewhere behind him.',
    'It wants him to gamble everything on his own ability, publicly.',
    'The moment forgives ambition completely and punishes hesitation entirely.',
    'A quiet ground, a flat afternoon, and one player who could change both.',
    'It asks for the trick that either works beautifully or costs a goal.',
    'It wants the sort of touch that gets several thousand people out of their seats.',
    'Nobody in the entire ground expects what is genuinely on here.',
    'A defence flat-footed for a second, and one player who has noticed.',
    'It asks him to be bold in a game that has been careful all afternoon.',
    'It rewards flair, provided of course that the flair actually comes off.',
    'The full-back has been beaten twice already and is visibly nervous.',
    'It wants him to try it now, while the defender is still unbalanced.',
    'A chance to do exactly the thing the academy spent years discouraging.',
    'It asks for something instinctive, before the brain gets involved and ruins it.',
    'The ball, the space, and a genuinely bad idea that is worth having.',
    'It wants him to entertain and to win, in the same movement.',
    'A moment in which being cautious would itself be the mistake.',
    'It asks him to shoot from somewhere that nobody sensible shoots from.',
    'Something extravagant is on and there is very little time to consider it.',
    'It rewards the man who plays with his head up and his eyes wide open.',
    'A crowd whose entire mood could turn on one piece of skill.',
    'It wants the outside of the boot where the inside would do the job.',
    'The defender is expecting the pass, which is the whole of the opportunity.',
    'It asks for a bit of the impossible, and asks for it immediately.',
    'A defence that has never once seen him do the thing he is about to try.',
    'It wants him to try the finish that has been on his mind for ten minutes.',
    'It asks him to play as though nobody has told him what the score is.',
    'A moment made for somebody with absolutely no sense of danger.',
    'It rewards confidence that borders uncomfortably on arrogance.',
    'The ball has dropped kindly and the angle remains completely horrible.',
    'It wants a chip, a dink, or something considerably worse than either.',
    'A chance to remind an entire stadium why he is on the pitch.',
    'It asks him to take a risk that the situation cannot possibly justify.',
    'One clever touch and a game that has gone nowhere opens up completely.',
    'It wants him doing what he did against a garage door as a boy.',
    'A moment that would be talked about in that stand for years afterwards.',
    'It asks for skill under no obligation whatsoever to be sensible.',
    'It wants the first-time volley rather than the safe, tidy header.',
    'A situation where the ordinary answer is fine and utterly forgettable.',
    'It rewards whoever is genuinely unafraid of the consequences of failing.',
    'Nothing at all requires him to try this, which is the whole appeal.',
    'It asks him to make a decision that no coach would ever have taught.',
    'A defender has given him a yard that he will not be given twice.',
    'It wants the extravagant finish in preference to the tidy one.',
    'It asks for boldness at more or less exactly the wrong moment.',
    'Something worth trying, and a very good chance of looking daft doing it.',
    'It wants him to do the difficult thing purely because it is there.',
    'A moment for the player he was before anybody got round to coaching him.',
    'It asks him to make the genuinely difficult look completely effortless.',
    'A stadium half expecting him to try it, and half hoping he will not.',
    'It wants imagination taken at full speed rather than at walking pace.',
    'The safe option is available, entirely sensible, and completely dull.',
    'It asks him to back the one thing he can do better than anybody.',
    'A moment that only works at all if he commits to it completely.',
    'It rewards the player who wants the ball at the very worst moment.',
    'Something that would end up on a Sunday roundup, if it comes off.',
    'It wants a touch that changes the temperature of the entire ground.',
  ],
  keeping: [
    'The box is his.',
    'Hands, and nerve.',
    'Nobody behind him.',
    'A cross is coming.',
    'Everything behind him is net.',
    'Come, or stay.',
  
    'A clean take, no fuss.',
    'The wall needs setting.',
    'Bodies everywhere.',
    'Position, then reflexes.',
    'Somebody has to be certain.',
    'A one-on-one, unavoidable.',
    'The angle is closing.',
    'Loud, early, unmistakable.',
    'A greasy ball tonight.',
    'The penalty spot, pointed at.',
    'Big, for one more second.',
    'A shot from distance in poor light.',
    'It asks for a clean catch and no rebound at all.',
    'The back four have left him badly exposed again.',
    'A ball spinning in awkwardly from a very bad angle.',
    'It rewards positioning a long time before it rewards reflexes.',
    'The defenders in front of him need telling exactly where to stand.',
    'A deflection has taken it entirely the other way in mid-air.',
    'It wants a decision on whether to come, made in a fraction of a second.',
    'The forward is through on goal and the angle is closing quickly.',
    'It asks for hands that do not spill anything on a very wet night.',
    'A corner, a shove in his back, and no whistle coming from anywhere.',
    'It rewards patience — staying up on his feet as long as possible.',
    'The last touch he had was roughly forty minutes ago.',
    'It wants him to punch it clear rather than attempt a half-catch.',
    'A free-kick from the edge and a wall he does not entirely trust.',
    'It asks him to sweep up behind a high line that keeps getting caught.',
    'The striker has been waiting the whole night for exactly this chance.',
    'A cross whipped under his own bar in a strong and awkward wind.',
    'It wants a save first and a calm bit of distribution immediately afterwards.',
    'It asks for footwork long before it asks for anything from his hands.',
    'A shot he really should save, and every single person there knows it.',
    'It rewards concentration after an hour in which nothing has happened at all.',
    'The tie, and possibly the season, hangs on the next thing he does.',
    'A backpass under pressure with a striker already charging at him.',
    'It wants him to claim the ball cleanly and end the argument entirely.',
    'The centre-halves are ball-watching again and somebody has to cover it.',
    'It asks him to be completely certain in six seconds of total chaos.',
    'A poor clearance has handed the other lot a second bite at it.',
    'It rewards the keeper who has spent the week reading the striker’s habits.',
    'A shot arriving late through a forest of legs he cannot see past.',
    'It wants him off his line early enough for it to actually matter.',
    'The header is looping awkwardly and the goal is somewhere behind him.',
    'It asks for the stop that nobody in the ground expects him to make.',
    'A save is needed and there is not a single team-mate who can help.',
    'It wants him to make the goal behind him look considerably smaller.',
    'The ball is loose in his six-yard box and boots are flying everywhere.',
    'It asks for the routine take, done properly and without any drama.',
    'A shot rising hard towards the top corner from twenty-five yards.',
    'It wants him to hold onto it rather than push it back into danger.',
    'The counter is on and his entire penalty area is empty behind him.',
    'It asks him to start the attack as well as finish off the last one.',
    'A penalty given, and a very long walk back to the line.',
    'It rewards whichever of the two of them stays on his feet longest.',
    'The ball is in the air and three men are going up for it.',
    'It wants strong hands on a night when the ball will not sit still.',
    'A shot he has seen extremely late through a crowd of bodies.',
    'It asks him to guess well, or better still, not to guess at all.',
    'The whole ground has gone quiet to watch what the goalkeeper does.',
    'A rebound that has to be smothered before anybody else reacts to it.',
    'It wants him decisive, and being right about it is almost secondary.',
    'A corner delivered into the awkward space directly in front of him.',
    'It asks for command of an area filled with considerably bigger men.',
    'The defence have conceded a cheap free-kick in a genuinely bad place.',
    'It rewards a keeper who trusts what he has seen and acts on it.',
    'A shot that will beat him comfortably if he commits a moment too early.',
    'It wants him to stand up and force the forward into the finish.',
    'The clean sheet still has an hour of this to survive intact.',
    'It asks him to talk the whole back line into a better position.',
    'A drive dipping viciously and late a couple of yards in front of him.',
    'It wants him to make sure of it and take absolutely no risks.',
    'It asks for reflexes that he has no time at all to think his way to.',
    'A cross whipped in with real pace and no obvious man attacking it.',
    'It rewards whoever is bravest in a box that has become dangerous.',
    'The forward has already put one past him earlier in the evening.',
    'It wants a save, and then it wants him to say nothing whatsoever about it.',
    'A ball squirming loose after a completely routine take went wrong.',
    'It asks him to be the last line and, more importantly, to look like it.',
    'Everything the side has done for an hour now rests entirely in his hands.',
    'A low shot skidding towards his weaker side off a wet surface.',
    'It wants him to trust himself enough to come for the difficult one.',
    'The forward is quicker than him and the ball sits between the two of them.',
    'It asks for clean handling in front of an away end that has been waiting.',
    'A save here would keep a scoreline respectable that is drifting away.',
    'It rewards the man who stays switched on for the entire ninety minutes.',
    'It wants him commanding a six-yard box with eight players standing in it.',
    'One save would change what an entire crowd currently believes.',
    'It asks him to make a habit of his look something close to a miracle.',
    'A shot through bodies that he will pick up perhaps ten yards out.',
    'It wants the ball dealt with, however scruffy it happens to look.',
    'The goalmouth behind him has genuinely never felt bigger than it does now.',
    'It asks him to hold his line and not be tempted by the near post.',
    'A moment in which nobody on the pitch can cover for his mistake.',
  ],
};
export const FRAME_B: Bank = {
  Grassroots: [
    'Boots, mud, and a Sunday morning, ',
    'Frost on the pitch, ',
    'Coats down for goalposts, ',
    'Squash at half-time, ',
    'Muddy knees and a dripping nose, ',
    'Still the smallest in his class, ',
    'A borrowed shirt, far too big, ',
    'Nets tied on with baler twine, ',
    'Shin pads that keep sliding down, ',
    'Bruises on both shins, ',
    'A ball scuffed grey from the garage wall, ',
    'Chips on the way home, win or lose, ',
    'Snow on the ground and gloves that do not fit, ',
    'Boots two sizes too big with three pairs of socks, ',
    'Told off at school for kicking a tennis ball indoors, ',
    'Playing up an age group and looking every bit as small, ',
    'His dad shouting instructions the coach has already given, ',
    'Last week he scored four and has heard nothing else since, ',
    'Kick-off delayed while somebody goes and finds a referee, ',
    'The one boy who stays behind after everybody has gone home, ',
    'A hand-me-down kit that still smells faintly of his cousin, ',
    'Half the team have not turned up and nobody knows why, ',
    'Wind straight off the fields and a ball that will not sit still, ',
    'His mum on the touchline with a flask and a folding chair, ',
    'A pitch shared with a rugby club, lines running everywhere, ',
    'The teacher has said football depends on his spellings improving first, ',
    'Last picked at breaktime again, and it still stings badly, ',
    'A trial for the district side that everybody has been talking about, ',
    'Boots caked so thickly that the studs have entirely disappeared, ',
    'Moved to defence this week, and thoroughly unhappy about it, ',
    'A grandfather who has never missed a game, whatever the weather, ',
    'Playing in the rain with both hands pulled up inside his sleeves, ',
    'The coach has started using his surname and it feels oddly serious, ',
    'A team of eleven friends who only half know the actual rules, ',
    'His first pair of proper boots, kept in the box overnight, ',
    'A cup tie against the school everybody insists cannot be beaten, ',
    'Told to stop trying tricks and simply pass the ball, ',
    'A packed lunch in the car and a fixture two towns away, ',
    'Nobody in his family has ever been much of a footballer, ',
    'Kicking a ball against the garage door until the light finally goes, ',
    'A stitch already, and something like half an hour still left, ',
    'A referee who is, in truth, somebody’s dad in a tracksuit, ',
    'Small for his year, and quicker than everybody in it, ',
    'The league table pinned in the clubhouse with his team near the bottom, ',
    'His name on the team sheet for the first time all season, ',
    'A schoolbag full of homework and a head entirely full of Saturday, ',
    'Not allowed out of the house until the washing-up is done, ',
    'A coach who shouts a great deal and means extremely well, ',
    'The pitch is frozen solid and nobody is calling anything off, ',
    'Grown out of last season’s shorts and nobody has mentioned new ones, ',
    'A cousin at a proper club who never lets him forget about it, ',
    'Twenty minutes of keepy-uppies in the back garden every single night, ',
    'First game since the school holidays and everybody is thoroughly rusty, ',
    'A team-mate crying after a telling-off, and nobody quite sure what to do, ',
    'On a full-size pitch for the first time, and it looks enormous, ',
    'A fixture moved to a pitch that nobody in the car can find, ',
    'The chance to take a penalty with every single person watching, ',
    'Practising with his left foot in secret, where nobody can see, ',
    'A whole term of school football spent being told he is good at this, ',
    'Six-nil down at half-time and still desperate to play the second half, ',
    'A scout, apparently, standing somewhere near the corner flag, ',
    'The manager’s son plays in his position and starts every week, ',
    'Dragged out of bed at eight on a Sunday, complaining the entire way, ',
    'His best friend has moved to another team and it genuinely hurt, ',
    'A hat-trick last month that he still finds ways to mention, ',
    'A long walk to the pitch with a bag over one shoulder, ',
    'Asked to captain the side for a week while somebody is away, ',
    'He has watched the same goal on the telly roughly forty times, ',
    'A pitch with a great deal more mud on it than grass, ',
    'Told he is too greedy, and not entirely sure what that means yet, ',
    'A tournament in a field somewhere, six short games in a single day, ',
    'His shirt hangs down well past his knees and nobody has a smaller one, ',
    'The whole family crammed into one car with nobody wanting to drive, ',
    'A goalkeeper on his team who is visibly frightened of the ball, ',
    'Everybody in his year has grown a foot and he has not, ',
    'A new lad has joined this week and is apparently very good indeed, ',
    'Told to stop diving in, and doing exactly that again immediately, ',
    'The trophy cabinet in the clubhouse has precisely one cup in it, ',
    'A whole week of looking forward to a single ninety minutes, ',
    'Last game of the season and the pitch already booked for cricket, ',
  ],
  Academy: [
    'Two trains and a bus after school, ',
    'A kit bag heavier than his schoolbag, ',
    'Boots provided by the club, ',
    'Homework done badly in the dark, ',
    'A nutritionist, at fourteen, ',
    'The squad gets cut in the spring, ',
    'Growing pains in both knees, ',
    'A body he does not recognise, ',
    'Reports posted home in sealed envelopes, ',
    'Sunday afternoons gone entirely, ',
    'A new coach, new certainties, ',
    'The badge still feels borrowed, ',
    'Tuesday and Thursday under the lights, ',
    'His mum drives, always, ',
    'A rival in his own year group, ',
    'Told to be louder, somehow, ',
    'Exams in the summer, ',
    'A first flight, for a tournament, ',
    'The coaches film every session now, ',
    'A year group of twenty, and the numbers always thin out, ',
    'Switched to a position he has genuinely never played before, ',
    'The lad he arrived with was released back in March, ',
    'Told his first touch is the single thing holding him back, ',
    'School mates think it is all glamorous and it mostly is not, ',
    'The academy gym has him lifting nothing heavier than an empty bar, ',
    'A new boy has come in for his position and looks quick, ',
    'His parents drive something like two hundred miles a week for this, ',
    'A physio who says the knees will settle down eventually, ',
    'The coach barely speaks to him and he cannot tell whether that is good, ',
    'A school report noting, politely, that he is tired in lessons, ',
    'Told to stop copying whatever he has seen on the television, ',
    'His year group play their matches in front of maybe thirty people, ',
    'A trial game against another academy with staff watching from a window, ',
    'He can beat anybody in his age group one-on-one and knows it perfectly well, ',
    'A knock that has kept him out of everything for three weeks, ',
    'His mates from school have started making plans without him in them, ',
    'The under-sixteens trained beside them today and looked like grown men, ',
    'A schedule of school, training, and very little else at all, ',
    'Moved up a year for a fortnight and thoroughly out of his depth, ',
    'A coach who was once a professional and has never once mentioned it, ',
    'His mum asks how it went and the answer is always fine, ',
    'The release conversations happen in a small room just off the corridor, ',
    'A growth spurt that has cost him most of his balance, ',
    'Ninety minutes on a coach each way for a fixture nobody watches, ',
    'The only one from his primary school still involved in any of it, ',
    'Told his attitude is comfortably the best thing about him, ',
    'The first time an older player has spoken to him by name, ',
    'His height and weight recorded on a chart every single month, ',
    'A session cancelled because of the pitch, and nobody happy about it, ',
    'Told to work on his weaker foot until it stops being the weaker one, ',
    'Exam season, and nobody at home mentioning football at all, ',
    'A team-mate who is already being talked about by complete strangers, ',
    'The changing room has a hierarchy that nobody bothered to explain, ',
    'His old Sunday side still ring up asking him to come back and play, ',
    'A minibus, a service station, and a game three counties away, ',
    'Told, flatly, that he is a year behind everybody else physically, ',
    'The academy manager knows his name, which still feels enormous, ',
    'A whole season of playing well without ever quite getting picked, ',
    'Told to enjoy it, by adults who all look slightly worried, ',
    'His first proper injury, and the first thing he has ever missed, ',
    'A lad in his year group who has apparently never had a bad day, ',
    'The fixture list for his age group, pinned up in the corridor, ',
    'He no longer plays in the street because of what it might cost, ',
    'A coach who praises absolutely nobody and has now praised him twice, ',
    'Two hours of stretching and video analysis for every hour with a ball, ',
    'His school has quietly stopped asking him to play for the year team, ',
    'A shirt with a squad number that he certainly did not choose, ',
    'Told he thinks too slowly, which stings rather more than being called slow, ',
    'A summer break spent worrying about coming back behind everybody else, ',
    'Quicker than everyone around him, and has been since he was ten, ',
    'The parents on the touchline have become competitive with each other, ',
    'A session where the staff had somebody else entirely in mind, ',
    'His name spelled wrong on the team sheet for the third time, ',
    'Told, repeatedly, that this is the year in which players get released, ',
    'Proper lines, proper nets, and staff standing about taking notes, ',
    'Stretching at home in the evenings now, without anybody asking him to, ',
    'The lad ahead of him in his position has been injured for a month, ',
    'A double session in the school holidays, and not one complaint about it, ',
    'His whole family have rearranged their lives around this, quietly, ',
    'Told he has a chance, and nothing whatsoever more definite than that, ',
  ],
  Scholar: [
    'Digs, and a landlady who cooks too much, ',
    'Boots to clean, every morning, ',
    'Homesick, and admitting it to nobody, ',
    'Two years to prove it, ',
    'A shared room, a long way from home, ',
    'College one day a week, ',
    'Sweeping the tunnel, in rotation, ',
    'A first wage packet, ',
    'Reserve football against grown men, ',
    'A washing machine he cannot work, ',
    'His mum rings every evening, ',
    'A curfew, broken twice, ',
    'Four meals he can cook, ',
    'The decision comes in April, ',
    'A hill he runs on Sundays, ',
    'Released lads, gone by lunchtime, ',
    'A holdall, and somebody else’s house, ',
    'Told to grow up quickly, ',
    'A rota that nobody in his year escapes, ',
    'The scholarship signed in an office with his parents beside him, ',
    'A lad in his exact position who signed a full year earlier, ',
    'Cleaning changing rooms after training, like everybody else in his year, ',
    'A first-team pro whose boots he cleans and who barely acknowledges him, ',
    'The youth-team coach who shouts, and the one who never does, ',
    'His first wage packet, which is both tiny and enormous, ',
    'Training with adults who tackle each other like they mean it, ',
    'A body that has finally begun catching up with his ability, ',
    'Told he is close to something, without ever being told to what, ',
    'The youth cup run has the whole club paying unusual attention, ',
    'A weights programme that has visibly changed the shape of him, ',
    'His old school friends are choosing sixth-form subjects this month, ',
    'The first-team manager walked through the middle of the session today, ',
    'A knee that swells after every match and nobody can quite explain why, ',
    'Told his year group is the strongest the club has had in a decade, ',
    'Six weeks since he was last at home, and nobody has mentioned it, ',
    'A coach who has been here thirty years and misses absolutely nothing, ',
    'The scholar he came in alongside has already been quietly let go, ',
    'A minibus back from a heavy defeat with nobody saying anything, ',
    'His first proper hamstring injury, and all the fear that comes with it, ',
    'A trial period out on loan at a non-league side up the road, ',
    'Studying a course he has absolutely no intention of finishing, ',
    'The corridor is lined with photographs of everybody who made it, ',
    'A dressing room in which he is, for once, no longer the youngest, ',
    'Being picked ahead of older lads, which has changed how they speak to him, ',
    'A youth-team fixture with three first-team staff sitting in the stand, ',
    'His landlady leaves a dinner out for him when he is back late, ',
    'Six in the morning, and a bus that has never once been on time, ',
    'A room with one poster in it and nothing else that belongs to him, ',
    'Told he has the ability and needs the other thing, whatever that is, ',
    'The first agent to ask for his number was politely turned away, ',
    'A team-mate has signed professional terms and the whole building knows, ',
    'The first-team squad train on the far pitch, visible and completely unreachable, ',
    'A season of playing every single week and improving extremely slowly, ',
    'Told the gaffer asked about him, and nothing has felt the same since, ',
    'His parents have not seen him play a match since September, ',
    'A long January of mud, running, and reserve fixtures nobody watches, ',
    'Told his weakness is between the ears rather than in the boots, ',
    'A youth-team captaincy handed over without any ceremony whatsoever, ',
    'The senior professionals have started to learn his name, slowly, ',
    'He rings home a good deal less about the bad days now, ',
    'A physio who knows considerably more about his body than he does, ',
    'Told to put a stone of muscle on before pre-season starts, ',
    'The lad above him in the pecking order has picked up a bad injury, ',
    'A youth-team dressing room containing perhaps two lads who will make it, ',
    'Playing through something for a fortnight that he has not reported, ',
    'A trip to a first-team match, sitting up in the stand in a club tie, ',
    'His younger brother has just started at the same academy, ',
    'A schedule that leaves him one free afternoon a fortnight, ',
    'Asked to train with the reserves twice this month, and told nothing after, ',
    'The kit man treats him like a piece of furniture and always will, ',
    'A defeat after which he was singled out in front of everybody, ',
    'Told the club has a decision to make about him, and no date for it, ',
    'His digs sit above a shop on a road with buses running all night, ',
    'A February containing nothing at all except rain and running, ',
    'He has learned to keep his head down walking through the tunnel, ',
    'Told he is the best in his year, and to forget he ever heard it, ',
    'A first booking, and a considerable lecture about it afterwards, ',
    'The youth-team results are printed and pinned up every Monday morning, ',
    'Given the squad number he actually wanted, for once in his life, ',
    'His mum has kept every single programme with his name printed in it, ',
    'Told to be ready, without ever being told what he should be ready for, ',
  ],
  Breakthrough: [
    'A squad number somewhere in the twenties, ',
    'A locker at the far end, ',
    'Four minutes of first-team football, ',
    'His first flat, and very quiet, ',
    'A debut, watched back twice, ',
    'The physio knows him well, ',
    'Nine times on the bench, ',
    'An agent answering differently now, ',
    'A goal drought, eleven matches, ',
    'Told to keep his head down, ',
    'The reserves feel like a demotion, ',
    'A hamstring, badly timed, ',
    'Youngest in the room by four years, ',
    'New terms offered, and unsigned, ',
    'A hostile away end, ',
    'Boots, and now a boot deal, ',
    'The captain has noticed him, ',
    'Three starts, and no promises, ',
    'A first red card, and a long week, ',
    'The senior pros have started including him in the card school, ',
    'His first away trip with the first team, sitting quietly at the front, ',
    'Told he will be involved on Saturday and absolutely nothing more, ',
    'The gaffer used his name in a press conference and it felt strange, ',
    'A local paper has run a piece calling him one to watch, ',
    'His contract runs out in eighteen months and everybody in the building knows, ',
    'Training every day alongside men who have played hundreds of games, ',
    'A loan move discussed at length and then very quietly shelved, ',
    'The captain has taken him aside twice in the last month, ',
    'A first goal that has changed the way people say his name, ',
    'His family have started getting asked about him in local shops, ',
    'Told he is not far away, by people who tell everybody that, ',
    'A senior pro in his position with two years left on a big contract, ',
    'A body that finally holds up against men who tackle properly, ',
    'Told to be patient, by a manager who is under a good deal of pressure himself, ',
    'His first proper interview, in which he said almost nothing at all, ',
    'The training-ground staff have begun tailoring sessions specifically to him, ',
    'Told the shirt is his to lose, which is not remotely comforting, ',
    'A cup tie against lower-league opposition, and a genuine chance of starting, ',
    'The manager who gave him his debut is one defeat away from trouble, ',
    'A season of nearly starting and nearly being dropped, week after week, ',
    'He still travels to the ground with the same bag he had at sixteen, ',
    'A first taste of being booed at somebody else’s ground, ',
    'The senior players test him in small ways more or less every day, ',
    'A first-team dressing room with a set of unwritten rules nobody explains, ',
    'Given the number seven and told, firmly, not to read anything into it, ',
    'Told the club have turned down an offer for him and said nothing since, ',
    'A camera crew at the training ground for the first time in his life, ',
    'His debut season is being written about before it has even finished, ',
    'A month out injured, watching somebody else settle into his place, ',
    'He earns more in a week than his father ever earned in a year, ',
    'The crowd have started singing something with his name in it, ',
    'A pre-season tour on which he played every available minute, ',
    'Told to add goals to his game, and to add them fairly quickly, ',
    'A senior professional who has decided, unasked, to look after him, ',
    'The gaffer has changed the system, apparently in order to suit him, ',
    'A first international call-up, at under-twenty-one level, ',
    'Photographed leaving the training ground, which has never happened before, ',
    'Told the next six months will decide the next ten years of his life, ',
    'A dressing room split about the manager, and he is staying well out of it, ',
    'His old academy coaches still text him after every single game, ',
    'The club have offered new terms and his agent has told him to wait, ',
    'Marked properly now by full-backs who have watched footage of him, ',
    'Told he is too easily knocked off the ball, again, by a different coach, ',
    'A first start in front of a full house, and his family somewhere in it, ',
    'His name on the back of shirts hanging in the club shop, ',
    'A run of games that has quietly changed his standing in the room, ',
    'The manager has stopped bothering to explain his team selections to him, ',
    'Told the fans have taken to him, which cuts both ways and everybody knows it, ',
    'A quiet Christmas containing three fixtures in eight days, ',
    'His first proper argument with a coach, and the silence afterwards, ',
    'A move away is being suggested by people who are close to him, ',
    'No longer surprised to find his own name on the team sheet, ',
    'Told the step from talented to reliable is the difficult one, ',
    'The captain has asked him to start taking the set-pieces, ',
    'A season in which he has played every position across the front line, ',
    'Dropped once, with no explanation offered and none requested, ',
    'Told to stop trying to impress people and start being genuinely effective, ',
    'A club record signing has just arrived in his position, ',
    'A manager change, and a new man with no particular reason to trust him, ',
    'Told his best position is not the one he has always believed it was, ',
  ],
  Establishing: [
    'A hundred league appearances, ',
    'The younger lads ask him things, ',
    'A contract that settles everything, ',
    'A bad ankle, managed rather than fixed, ',
    'Two managers, and a third coming, ',
    'The armband, more often than not, ',
    'A young family at home, ',
    'Coaching badges, thought about quietly, ',
    'His routine has not changed in years, ',
    'A summer of interest, and no move, ',
    'Reputation arrives before he does, ',
    'The window shut, and he stayed, ',
    'A testimonial, mentioned far too early, ',
    'Fewer games, more responsibility, ',
    'A rival who stopped being one, ',
    'The body needs an extra day now, ',
    'A derby, and he is the danger, ',
    'Awards lists, for the first time, ',
    'A vice-captaincy, and the work behind it, ',
    'He knows every referee in the division by temperament, ',
    'Told he is the first name on the team sheet, and quietly believing it, ',
    'His body has learned exactly what it can and cannot do in a week, ',
    'The gaffer asks his opinion before making changes to the side, ',
    'A young lad has arrived in his position and is genuinely very good, ',
    'Told his best years are only starting, by people who appear to mean it, ',
    'A hundred games in three seasons and an ankle that reminds him nightly, ',
    'His name read out to a roar that he has entirely stopped noticing, ',
    'He has become the one who speaks to the press after a bad defeat, ',
    'A pre-season in which he is expected to set the standard for everybody, ',
    'His agent talks about the next move as though it has already been decided, ',
    'A dressing room that has quietly come to rely on him for most things, ',
    'Told he is playing the best football of his life, and agreeing, ',
    'He stopped reading anything written about him two seasons ago, ',
    'The club have built the whole side around what he happens to do well, ',
    'A young family at home that has changed what a bad result feels like, ',
    'He knows precisely what an opponent will do a moment before they do it, ',
    'Told to lead, by a manager who does not lead especially well himself, ',
    'A season in which his numbers have never been anywhere near this good, ',
    'His old academy year group has thinned out to roughly two survivors, ',
    'A run of games that has him being talked about at international level, ',
    'He has learned to keep something back for the last month of a season, ',
    'Told he is worth twice what the club actually paid for him, ',
    'A relegation fight, with his name in every single preview of it, ',
    'The captain is out for the season and the armband is sitting unclaimed, ',
    'He trains the way the senior pros used to, and the kids have noticed, ',
    'A move abroad has been raised, seriously, for the first time, ',
    'Told the club will listen to offers in the summer, and nothing more, ',
    'A promotion push with him as the man expected to carry most of it, ',
    'Somebody the referee will actually listen to, which took years, ',
    'Told his ceiling is a good deal higher than the club he currently plays for, ',
    'His parents come to fewer games now, and he entirely understands why, ',
    'A cup semi-final, and comfortably the biggest week of his career so far, ',
    'A manager who trusts him with the plan before the team ever hears it, ',
    'His name sits on the list of players that other clubs enquire about, ',
    'Told he has ten years left in him, provided he looks after himself, ',
    'A dressing room in which his mood quietly sets everybody else’s, ',
    'He has played in front of eighty thousand people and slept perfectly well after, ',
    'A season interrupted by an injury that he genuinely did not see coming, ',
    'The club captain has told him, privately, that the armband is coming, ',
    'Earning enough now to have stopped thinking about earning at all, ',
    'Told his consistency is worth considerably more than anybody else’s flair, ',
    'A summer spent working on something that nobody asked him to fix, ',
    'His first serious operation, and a long and tedious road back from it, ',
    'A younger version of himself has been signed from another club, ',
    'He has stopped being the story and started being the standard, ',
    'Told the side plays noticeably worse without him, and it is true, ',
    'A run of poor form that the crowd have very much noticed, ',
    'His international career has begun and complicated absolutely everything, ',
    'He speaks in team meetings now, without waiting to be asked, ',
    'A club in transition, with him as one of the very few constants, ',
    'A house bought outright, and a life that finally feels settled, ',
    'A derby in which he is the man the other side have spent the week worrying about, ',
    'He has learned to be useful on the days when he is playing badly, ',
    'Told the club’s ambition may not entirely match his own any more, ',
    'A season in which every opponent turns up with a plan for him specifically, ',
    'A young professional has begun copying his warm-up, badly, ',
    'Long enough at the club to have seen three completely different eras, ',
    'Told to think seriously about what he wants to be remembered for, ',
    'A midweek fixture list that has flattened the entire squad, ',
    'His performances have quietly outgrown the table his team sit in, ',
    'A manager sacked whom he genuinely liked and will genuinely miss, ',
    'He has become the player the gaffer points at during team meetings, ',
    'A career that has settled into something solid, and plainly unfinished, ',
  ],
};
export const SETTINGS_B: Bank = {};
export const CHILD_SETUP_B: Bank = {};
export const EVENT_PREFIX_B: Bank = {};
export const BIG_SETTINGS_B: string[] = [];
