// Authoring pack P. One author owns this file — nobody else writes to it, so packs never collide.
import type { Bank } from '../merge.js';
export const KIND_SETUP_P: Bank = {};
export const DEMAND_P: Bank = {};
export const FRAME_P: Bank = {
  'Youth Team': [
    "Two stone heavier than the boy who signed here at fifteen, ",
    "Eight in the morning on the physio table, one ankle in a bucket of iced water, ",
    "Growing stopped somewhere last winter and the building started, ",
    "The strength coach writes his numbers on a whiteboard nobody rubs off, ",
    "Shins that ache on the cold mornings, and nobody wants to hear about it, ",
    "Weighed every Monday, and the number read out, ",
    "Squat, bench, chin-ups — a chart on the gym wall with his name low on it, ",
    "Skin has broken out across his back since the new protein, ",
    "Hamstring tightness that comes and goes, logged in a book he never sees, ",
    "Eating six times a day because a man with a clipboard says so, ",
    "Boots a size bigger than they were at Christmas, ",
    "Ice baths at half seven, four lads to a tub, ",
    "A knock on the hip that has not gone in eleven days, ",
    "They have taught him how to fall properly, which nobody had warned him about, ",
    "Stretching on a corridor floor because the gym is booked, ",
    "Rest is a thing prescribed now, not chosen, ",
    "The doctor pressed his knee and said nothing for a long moment, ",
    "Cramp in both calves on the coach back from Doncaster, ",
    "Big enough now to be put on the biggest lad in the box, ",
    "A scar on his shin from a February pitch frozen at one end, ",
    "Shoulders that have arrived from somewhere in the last six months, ",
    "Told to put on four kilos by March, and no advice on how, ",
    "A dead leg carried through a full session without mentioning it, ",
    "Bloods taken on a Tuesday and nobody says what for, ",
    "Two hundred and ten pounds a week, and forty of it goes home, ",
    "His first payslip is folded in his wallet, unspent, ",
    "Boot money from a rep who calls him by the wrong name, ",
    "His mum has stopped taking the twenty he offers on a Sunday, ",
    "Contract talk happens in a room with a plastic plant in the corner, ",
    "A secondhand car he cannot legally drive yet, bought by his brother, ",
    "Learning what a P45 is from a lad who has just been handed one, ",
    "Paid monthly now, and it runs out on the twenty-third, ",
    "The club takes his digs money before he ever sees it, ",
    "A signing-on fee in three instalments, the first one due in April, ",
    "Nobody told him about tax, ",
    "Bus fares, boots, and a phone bill his dad still quietly covers, ",
    "Somebody has offered to sort his money out for him, ",
    "A pair of boots handed over free, which feels like being paid twice, ",
    "His wages are less than his mate earns fitting kitchens, ",
    "Twelve months — that is all the paper actually says, ",
    "The offer sits on the table for a fortnight and then it does not, ",
    "A bonus for every reserve appearance, and he counts them, ",
    "Saving for nothing in particular, in a building society account his nan opened, ",
    "The lads who have signed pro get a different coloured kit bag, ",
    "Insurance forms, a pension, and a box asking for next of kin, ",
    "Two years offered to the left-back and one to him, ",
    "A club fine of a tenner for turning up late, paid without argument, ",
    "A bank card with his own name embossed across it, ",
    "The kitman charges a quid for a lost sock and he means it, ",
    "Everything he has ever earned would fit in one envelope, ",
    "His mum keeps his old room exactly as it was, ",
    "Sunday dinner at two, and he is back on the bus by six, ",
    "His dad rings after every game and asks about the pitch first, ",
    "A younger sister who has started playing and is better than he was, ",
    "Home is ninety minutes on the train and he goes less than he says he does, ",
    "His nan cuts every mention of him out of the local paper, ",
    "Nobody at home understands why he cannot just come back for a weekend, ",
    "The neighbours ask his mother how he is getting on and she never knows what to say, ",
    "His brother has a job, a van, and an opinion about all of it, ",
    "A phone call home he lets ring out, because there is nothing new to report, ",
    "His father drove four hours to watch forty minutes of reserve football, ",
    "Christmas morning training, and the family eat at four without him, ",
    "Photographs of him at eight, in a kit two sizes too big, still up the stairs at home, ",
    "His mum has never once asked whether he misses the house, ",
    "Post still arrives at his parents' address, most of it from the club, ",
    "A grandad who watched him in the under-elevens and died in March, ",
    "Nobody in his family has ever had a contract of any kind, ",
    "His old school friends are all on college courses and he is not, ",
    "Two brothers, one van, and a Saturday spent driving to Crewe, ",
    "He is missing from three of the last four family Christmas photographs, ",
    "His mother irons his training kit when he brings it home, and he lets her, ",
    "A cousin who tells everyone in the pub that he plays for the first team, ",
    "Home is a place he visits now, ",
    "His dad has stopped giving him advice at half-time, ",
    "That kitchen-table conversation about what happens if it does not work out, ",
    "An aunt who asks, every single time, whether he has met anyone famous, ",
    "Mrs Docherty leaves a plate in the oven for him when the bus is late, ",
    "Two lads to a room and one plug socket between them, ",
    "A landlady who has housed thirty-one apprentices and remembers four of them, ",
    "Curfew is ten, and the fourth stair up creaks, ",
    "The digs telephone sits in the hall and there is always a queue for it, ",
    "Toast and tea at half six in a kitchen with the radio on, ",
    "A shared bathroom, a rota on the door, and a boiler that gives up by seven, ",
    "His landlady watches the racing and asks him nothing about football, ",
    "Somebody else's boots are drying on the same radiator as his, ",
    "The room smells of Deep Heat and damp towels, ",
    "Rent taken at source, and a receipt he never asked for, ",
    "A bed that is too short for him now, ",
    "A fruit bowl on the sideboard that has never once had fruit in it, ",
    "Wednesday is fish, and he has learned not to say anything, ",
    "The landlady's husband drives him to the ground when it snows, ",
    "Sharing with a Scottish lad who phones home every night at nine o'clock, ",
    "His name written on his own milk in the digs fridge, ",
    "Moved to different digs in November, and no reason given, ",
    "A back garden with a wall he has been kicking a ball against since he arrived, ",
    "The house goes very quiet on the afternoons the others are away, ",
    "A key of his own, finally, after fourteen months, ",
    "Ironing his own shirt badly on a board with a burn mark down it, ",
    "Learning to cook one thing properly, and that thing is pasta, ",
    "Notes left on the microwave in handwriting he does not recognise, ",
    "Rain on the skylight of an attic room in a town he did not choose, ",
    "The other lodger works nights and they have met twice, ",
    "A kit bag by the front door, and nobody saying whose it is, ",
    "Twelve signed at fifteen, three still here, ",
    "They tell them on a Friday, one at a time, in alphabetical order, ",
    "The lad who was better than him at fourteen is fitting windows now, ",
    "Watching another boy carry his boots out to a car, ",
    "Nobody says released — they say not being kept on, ",
    "A half-finished sticker album left behind in the digs, ",
    "The peg with somebody else's name still taped above it, ",
    "His roommate went home on a Tuesday and did not say goodbye, ",
    "Six lads waiting outside an office, and none of them talking, ",
    "Two boys let go, and one of them was still in the car park an hour later, ",
    "The manager shakes their hands and gets all the names right, at least, ",
    "A phone number swapped at the gate that neither of them will ever ring, ",
    "They take the tracksuits back, ",
    "A trial arranged at Rochdale for a lad who deserved better than that, ",
    "The intake photograph on the corridor wall, half of them gone, ",
    "Somebody's mother waiting outside in a Vauxhall with the engine running, ",
    "One of them is off to university and everyone pretends that was always the plan, ",
    "Being kept on while the lad next to him is not, ",
    "The list goes up on the Friday and there is a crowd around it, ",
    "A goalkeeper released after four years and a broken wrist, ",
    "Names quietly taken off the training-ground board over the summer, ",
    "His best mate in the intake has gone to Ireland to try again, ",
    "They cleared out the lockers before the lads had even left the building, ",
    "The lad who scored twenty-two is gone and he is not, ",
    "Word gets round the dressing room before the meeting does, ",
    "A lad from his own intake now works at the ground on matchdays, ",
    "Everyone is talking about him in the past tense within a week, ",
    "The seat next to his on the bus stays empty for a month, ",
    "Nine of them started, ",
    "The youth coach carries a clipboard and a memory for mistakes, ",
    "A man in a woolly hat who has said fourteen words to him since August, ",
    "The reserve manager played four hundred games and never once mentions it, ",
    "Being shouted at by name is better than not being shouted at, ",
    "The fitness coach counts out loud and does not stop for anybody, ",
    "A coach who was released himself at eighteen and has never said so, ",
    "Two members of staff who disagree about him, openly, in front of everyone, ",
    "The kitman is the only one in the building who tells him the truth, ",
    "Video sessions in a portakabin with a screen and a broken blind, ",
    "The manager walked past and said his surname, and nothing else, ",
    "A coach who calls every player son because he cannot remember, ",
    "Being taken aside after training with no explanation offered first, ",
    "The first-team assistant has started standing on his side of the pitch, ",
    "A clipboard with a grudge behind it, ",
    "Somebody has written a number beside his name and folded the sheet over, ",
    "The academy manager knows both his parents' first names, ",
    "Told that he tries too hard, which he does not understand, ",
    "A coaching course means his usual coach is away for a fortnight, ",
    "The physio talks to him more than any of the coaches do, ",
    "Extra finishing after training, alone, with a coach who volunteered for it, ",
    "The chief scout who signed him has left for another club, ",
    "A new coach arrives in January with different ideas about his position, ",
    "Bibs, cones, and a session that overruns by forty minutes, ",
    "They moved him to right-back for six weeks and never said why, ",
    "The head of youth has a son in the same age group, ",
    "Praise arrives once, and is never repeated, ",
    "A coach who eats his lunch standing up and watches everything, ",
    "The gaffer's door is open, which does not mean he can walk through it, ",
    "Asked, in front of the whole group, to explain exactly what he was thinking, ",
    "Somebody in the office keeps a file on him with his school reports in it, ",
    "The bus leaves at six and it does not wait, ",
    "Four hours to Carlisle on a coach with one working heater, ",
    "Cards at the back, headphones at the front, nobody in the middle, ",
    "A service station on the M6 at half eleven at night, ",
    "Sandwiches in foil, handed down the aisle in a plastic crate, ",
    "Sleeping against a window that vibrates the whole way, ",
    "The same seat every week, and nobody ever decided it, ",
    "Back at the ground at two in the morning and training at ten, ",
    "Reserve football at Gateshead on a Wednesday in front of forty people, ",
    "The driver is called Ray and he has done this run for eleven years, ",
    "A minibus, not a coach, because the reserves do not get a coach, ",
    "Roadworks outside Birmingham and a kick-off they are not going to make, ",
    "Nobody talks on the way home when they have lost, ",
    "His kit still wet from the last game, in a bag under the seat, ",
    "Chips eaten standing in a car park because the kitchen had shut, ",
    "The heating packs in somewhere around Preston, ",
    "A window seat, a motorway, and two hundred miles of nothing, ",
    "Two changes of train, because the club would not put a coach on, ",
    "Dropped at a roundabout near his digs at one in the morning, ",
    "The younger lads sit at the front, and nobody wrote that down anywhere, ",
    "Away at Barnsley reserves, seven o'clock kick-off, pitch like a beach, ",
    "Sixty miles each way, twice a week, for eleven months, ",
    "A team-sheet read out on a moving bus, ",
    "His name last on the list of substitutes again, ",
    "The coach breaks down and they sit on a verge for an hour, ",
    "Motorway lights going past a window at a speed he has stopped noticing, ",
    "A packed lunch and a two o'clock kick-off in Chesterfield, ",
    "Nobody claps them off at away reserve games, ",
    "Somebody drew on the condensation weeks ago and it is still there, ",
    "Home by nine, in bed by ten, up at six, ",
    "Frost on the training pitches until eleven o'clock, ",
    "Sweeping snow off a pitch with a yard brush before anyone kicks a ball, ",
    "January, and the floodlights are on before the session even starts, ",
    "Boots that do not dry out between Tuesday and Thursday, ",
    "The pitch has been frozen solid for nine days, ",
    "Gloves are not allowed, apparently, ",
    "A cross-country run in December because the pitches have gone, ",
    "Playing through a hailstorm at Burnley with two subs and no shelter, ",
    "Mud to the ankle on the bottom pitch, which is where the youth team train, ",
    "The sand-based pitch is for the first team and always has been, ",
    "Dark by four, and the last twenty minutes played half blind, ",
    "One shower for eighteen lads and no hot water left by the end, ",
    "Chilblains, and a physio who laughs at the word, ",
    "Fixtures called off three weekends running and nothing to show for any of it, ",
    "The bottom pitch has a slope and a puddle that never leaves, ",
    "Rain coming sideways off the Irish Sea and a coach who will not go in, ",
    "February arrives and the intake looks thinner than it did, ",
    "Three layers to warm up in and one to play in, ",
    "Christmas fixtures — four games in eleven days, ",
    "Ice on the inside of the digs window in the morning, ",
    "The kit comes back stiff out of the drying room, ",
    "A ball that weighs twice as much once it is wet, ",
    "Digging out the goalmouths at half eight on a Saturday morning, ",
    "Nobody watches reserve football in January, ",
    "Cold hands, a warm bus, and the same twelve songs, ",
    "Snow on the terraces, a hundred people in, and the match played anyway, ",
    "The groundsman shouts at them about the state of the six-yard box, ",
    "A season that started in August is now a thing to be got through, ",
    "Steam coming off the backs of the lads down the far end, ",
    "Boots cleaned in an outdoor sink with cold water, in December, ",
    "The boot-room rota has his name down for Tuesdays and Fridays, ",
    "Cleaning nineteen pairs of boots that are not his own, ",
    "The pros leave their boots caked deliberately and everybody knows it, ",
    "Sweeping out the away dressing room after a reserve game, ",
    "Balls pumped, bibs washed, cones counted, before anyone else arrives, ",
    "A senior pro who checks his own boots and says nothing either way, ",
    "Toilets, on a rota, and no exceptions for anyone who has signed pro, ",
    "The boot room smells of dubbin and wet leather and always will, ",
    "Made to do a job again at six in the evening, ",
    "Scrubbing the treatment-room floor while the physio works around him, ",
    "A brush, a bucket, and forty minutes after everyone else has gone, ",
    "The kit skip is his to carry, both ways, ",
    "The youngest carries the balls, and that is simply how it is, ",
    "His last year of doing jobs, if things go the right way, ",
    "Marking a first-team striker on his way back from injury, ",
    "Twenty-three reserve appearances and four goals, ",
    "A trialist arrives on the Monday and plays in his position on the Tuesday, ",
    "Playing against men with mortgages, ",
    "A thirty-four-year-old centre-half showed him what a forearm is for, ",
    "Sent off at Wrexham for something he did not do, ",
    "Nine hundred in for a reserve derby, and it changed the way he played, ",
    "Taken off at half-time with no reason given at the time, ",
    "Two good months, then five games on the bench, ",
    "Scoring in front of an empty stand, ",
    "The youth cup run ended in a quarter-final at somebody else's ground, ",
    "Captain for one game, because the captain was ill, ",
    "Given the number four shirt and told not to get attached to it, ",
    "A pass he still thinks about, from a Tuesday in October, ",
    "They have started playing him out of position and calling it versatility, ",
    "Beaten in the air three times by the same lad, ",
    "A goal-line clearance nobody saw and nobody mentioned, ",
    "Training with the first team on the Thursday and back with the kids on the Friday, ",
    "Beaten six-nil at Blackburn, and the coach said nothing at all afterwards, ",
    "His first booking, for talking, ",
    "The referee at reserve level is somebody's dad, most weeks, ",
    "Forty minutes played, and told afterwards it was his best forty, ",
    "A hat-trick against a side that folded a month later, ",
    "Nutmegged by a fifteen-year-old on the top pitch, ",
    "The senior pros pass it and move and he is always half a yard behind, ",
    "A striker who has done it in the league is on the same pitch as him, ",
    "Told to mark the good one, ",
    "Two touches in a first-team practice match, and both of them fine, ",
    "Corner routines rehearsed for two hours on a Thursday afternoon, ",
    "The reserve league table pinned up, and nobody looking at it, ",
    "A friendly against a non-league side who kicked everything that moved, ",
    "Eleven versus eleven on a Friday and the losers run, ",
    "A club in the third division has been on the phone about him, ",
    "His agent has a Nokia and a habit of ringing at odd hours, ",
    "Somebody in a suit at the training ground who is not staff, ",
    "Being discussed at length in a meeting he was not in, ",
    "A month at Halifax, if the paperwork gets done in time, ",
    "The word potential, used about him, twice, in the same week, ",
    "A scout from Norwich stood behind the goal in the rain, ",
    "His father does not trust the agent and says so at every dinner, ",
    "Three clubs asked, one of them seriously, ",
    "The offer of a trial abroad that came to nothing at all, ",
    "Signing forms at a desk with a club secretary and a cup of tea going cold, ",
    "Contract renewal is due in May and it is only November, ",
    "A lad from the local paper asked him a question after a youth game, ",
    "Nothing to fall back on but a bricklaying course he never started, ",
    "School finished in June and this is all there is now, ",
    "Five GCSEs in a drawer at his mother's house, ",
    "A form asking what he would do otherwise, left blank, ",
    "Eighteen in a fortnight, and a decision due before then, ",
    "The first-team squad list goes up in July and he reads it twice, ",
    "Everything he owns still fits into two bags, ",
  ],
};
export const SETTINGS_P: Bank = {};
export const CHILD_SETUP_P: Bank = {};
export const EVENT_PREFIX_P: Bank = {};
export const BIG_SETTINGS_P: string[] = [];
