// Authoring pack O. One author owns this file — nobody else writes to it, so packs never collide.
import type { Bank } from '../merge.js';
export const KIND_SETUP_O: Bank = {};
export const DEMAND_O: Bank = {};
export const FRAME_O: Bank = {
  'Youth Team': [
    "Boot-room rota has him on the first team's studs every Thursday, ",
    "Nobody has said the word contract to him yet, ",
    "Two lads from his intake had their kit bags by the door on Friday, ",
    "Half seven on the physio's table, before anyone else is in the building, ",
    "The landlady keeps a plate warm for him on Sundays, ",
    "Reserve games kick off at two on a Tuesday in front of forty people, ",
    "Since school finished there is nothing else on the list, ",
    "A coach with a clipboard and a long memory has him marked, ",
    "Training with the seniors on Monday, back with the kids on Wednesday, ",
    "'You'll know in April,' is all the youth-team manager will say, ",
    "Weighed and measured every Monday morning now, ",
    "Rain on the far pitch, the one with no stand and a sloping goalmouth, ",
    "Everything he owns fits in one holdall and a boot bag, ",
    "Up at six for the bus, ",
    "Growing has stopped and the gym work has started, ",
    "His room-mate went home to Wexford in March and has not been replaced, ",
    "Twenty-two lads signed at fourteen and nine are left, ",
    "Sweeping the away dressing room after a reserve defeat, ",
    "An agent rang the house phone twice before anyone answered, ",
    "Digs on a road where the buses stop at eleven, ",
    "Cones out at half eight, cones in at four, ",
    "The senior keeper learned his name last week, ",
    "There is a loan club in League Two who have watched him three times, ",
    "Nothing to fall back on but a maths GCSE and a driving theory pass, ",
    "Being asked to make up the numbers in a first-team five-a-side, ",
    "Somebody has moved his peg down the corridor with the pros, ",
    "Meat and two veg at half twelve, every day, in a room with a serving hatch, ",
    "He has learned to tape his own ankles, ",
    "Getting a boot in the calf off a thirty-four-year-old who did not apologise, ",
    "Forms went home for his mum to sign and came back without a word, ",
    "The youth cup run ended in the fourth round on a plastic pitch in Salford, ",
    "Kit man calls everyone son and knows exactly who is going, ",
    "Told to stay behind and do finishing, then left alone with a bag of balls, ",
    "First wage packet went on a phone contract and a hoodie, ",
    "And now there is a scout in the car park who never gets out of the car, ",
    "One shirt, two of them — and the manager likes the other one's left foot, ",
    "Learning what a lactate test does to a person, ",
    "Down at the training ground on Boxing Day while the school lot were still in bed, ",
    "A physio who says nothing for six weeks and then says four months, ",
    "His mother asks about a back-up plan every time he rings, ",
    "The under-18s coach has stopped shouting at him, which could mean anything, ",
    "Bus to Middlesbrough leaves at five in the morning for a ten-thirty kick-off, ",
    "Contract talks are happening in a room he is not in, ",
    "Watching the released lads clear their pegs without looking up, ",
    "Eighteen in September, and the club decides before then, ",
    "Some of the seniors nod now, some still don't, ",
    "Landlady's husband drives him in when the rain is bad, ",
    "Running the sand dunes at Formby in November, ",
    "A first-team squad number pinned up with his name spelled wrong, ",
    "Nobody tells him anything — and everybody knows something, ",
    "Same eleven pairs of boots since he was sixteen, ",
    "The strength coach has him on a programme with his name at the top, ",
    "Loan talk again, then nothing, ",
    "Sat in a hotel lobby in Norwich waiting for a bus that is late, ",
    "He signed something in a portacabin with a kettle in it, ",
    "Home once a month, and it feels smaller each time, ",
    "Four of the lads he came in with are now at colleges in America, ",
    "The reserve team has three trialists in it this week, ",
    "Ice bath at ten past four, twelve minutes, no talking, ",
    "Learning that the first team train on the good grass, ",
    "An agent who wears a coat indoors met him after training, ",
    "Older pros use him as the man in the middle in the rondo and enjoy it, ",
    "Nine miles from the digs to the training ground, no car, ",
    "The lad in the next room got a year and he got nothing yet, ",
    "Every session is watched by somebody with a laptop, and the numbers end up in a document he will never see, ",
    "Told his body fat percentage in front of six other people, ",
    "Sunday dinner kept warm in the oven under a plate, ",
    "Playing forty-five minutes for the reserves and forty-five for the eighteens, ",
    "Somebody left a first-team tracksuit in his locker by mistake, ",
    "Because the club sold the last one, there is room for one this year, ",
    "The gaffer's assistant asked him his name and then forgot it, ",
    "Three trials, two rejections and a phone that does not ring, ",
    "Waiting outside an office at ten to nine with two other lads, ",
    "His dad drives up for reserve games and stands on his own, ",
    "Being told to put weight on, then told he is carrying weight, ",
    "One end of the season to prove eight years were not wasted, ",
    "The bibs are washed by whoever came last in the running, ",
    "A press officer has taken a photograph of him against a white wall, ",
    "Half the intake has already gone and the year is not finished, ",
    "Learning to fill in his own expenses form, badly, ",
    "There is a lad from Leeds in the digs who cries quietly and thinks nobody hears, ",
    "The Under-21s manager keeps calling him by his surname, ",
    "Handed a squad number for a friendly in Dundee, ",
    "Nine o'clock curfew at the digs, and nobody enforces it any more, ",
    "Someone has written his name on the whiteboard under 'available', ",
    "Boots that are his own now, not handed down, ",
    "Six weeks off a broken metatarsal, sat at the side with a ball under his foot, ",
    "The medical staff know more about his future than he does, ",
    "First-team warm-up, standing at the end of the line, ",
    "Free on a Wednesday afternoon and nothing to do with it, ",
    "A club car came for him at seven and the driver said nothing the whole way, ",
    "Two years scholarship done, and the rest is a phone call, ",
    "Watching the lads he sat next to in year eleven go off to university with three years mapped out in front of them, ",
    "The captain shook his hand in the tunnel and it lasted a second, ",
    "Every touch in training feels like it counts for something now, ",
    "A youth coach who never played and never lets that go, ",
    "Told to bring boots and a passport, no other details, ",
    "Heating off at eleven, ",
    "His name on a team sheet pinned to a corridor wall, ",
    "Sent to warm up in the eightieth minute and not brought on, ",
    "A midweek game at a non-league ground with a burger van behind the goal, ",
    "Cutting his own hair in the digs bathroom to save the money, ",
    "'Don't get comfortable,' the coach said, and walked off, ",
    "Second season of the scholarship, and the pretending is over, ",
    "There is a hole by the corner flag that the groundsman has been promising to fill since October, and nobody has chased him about it, ",
    "Fifteen minutes off the bench against a team of men, ",
    "Being measured for a suit for the end-of-season do, ",
    "An offer from Scotland, of sorts, through a third party, ",
    "Lifting more than he weighs, three mornings a week, ",
    "Nobody in his family has ever earned money from a game, ",
    "A senior pro asked him to fetch a coffee and then talked to him for an hour, ",
    "Reserve fixtures get moved for the weather and nobody tells the parents, ",
    "No wifi on the bus past Birmingham, ",
    "Eight months to a decision that will be made in a ten-minute meeting, ",
    "Left out of the youth cup squad without an explanation, ",
    "Playing right-back for the first time in his life because someone was ill, ",
    "The landlady's dog sleeps in his room now, ",
    "Signing on the dotted line while his mum wipes her hands on a tea towel, ",
    "There is a lad two years younger who is quicker than him, ",
    "Told the club has him down as a midfielder now, ",
    "Winter mornings when the pitches are frozen and they run the car park, ",
    "His agent has a list and he is not the top name on it, ",
    "A trial game arranged for a Tuesday and cancelled on the Monday, ",
    "Twelve of them in a minibus to a training camp in Cheshire, ",
    "Nothing about the last two years has been his decision, ",
    "The academy manager has a way of saying 'we'll see', ",
    "Beaten to a place by a lad the club paid money for, ",
    "Video analysis on a Friday, his mistakes on a big screen, ",
    "Home for Christmas Day and back on the twenty-seventh, ",
    "Somebody's dad shouts things at him from behind the fence, ",
    "The first team lost on Saturday — Monday is going to be quiet, ",
    "A national newspaper mentioned him in a list of eleven names, ",
    "Getting used to being the youngest in the room again, ",
    "One phone call away from a season in the fourth division, ",
    "Sharing a bathroom with three lads and a rota nobody follows, ",
    "The tunnel at the reserve ground smells of paint and liniment, ",
    "Told he'd be looked at in pre-season, which is eleven weeks away, ",
    "Rent, food and a bus pass out of four hundred a month, ",
    "An old coach from his junior club sends him a message after every game, ",
    "Passed fit on the Thursday, ",
    "Learning that the seniors' laundry basket is not his to use, ",
    "A scout from Belgium was at the game and left at half-time, ",
    "Being handed a first-team shirt to hang up, not to wear, ",
    "The lad who was captain of the intake got released in January, ",
    "Six in the morning, dark, and the boots are still wet from yesterday, ",
    "Told to stop copying a player he has never watched properly, ",
    "His body is a project other people have plans for, ",
    "Free boots came in a box with somebody else's size on the label, ",
    "The reserves play behind closed doors on a Tuesday in the rain, ",
    "A club welfare officer asks him twice a term how he is finding it, ",
    "Working the turnstiles at a first-team game to earn his keep, ",
    "Never been abroad and now there is a tournament in Portugal, ",
    "Speaking to a first-team coach for ninety seconds in a corridor, ",
    "The best player in his intake now works in his dad's garage, ",
    "Two years of scholarship money, then nothing guaranteed, ",
    "Chasing a man on the wing who has played two hundred league games, ",
    "Sat in the stand for a home game in a club tracksuit, ",
    "There is a folder somewhere — a number, a grade, a date — with his name on it, ",
    "Studs, laces, polish, and forty minutes on his own in the boot room, ",
    "The under-18s got beaten seven-one and nobody spoke on the bus, ",
    "Handed a letter in an envelope at the end of a Friday session, ",
    "A month of training with the first team and then straight back down, ",
    "Nobody at the digs cooks, so the landlady does, ",
    "Late back on the bus, and a Thursday session at half eight regardless, ",
    "The sports scientist calls his sprints 'outputs', ",
    "One good game in October is still being talked about in March, ",
    "Missing his sister's birthday for a game in Yeovil, ",
    "A goalkeeper who has not played since Christmas shares the digs with him, and the pair of them watch the reserves back on a laptop, ",
    "Ten weeks, no start, ",
    "Being taught to wrap his own hamstring by a physio who is late for lunch, ",
    "The kit for the reserve game is the first team's old away strip, ",
    "Wages that go up by fifty pounds if he plays twenty games, ",
    "Someone from the club rang his mother and not him, ",
    "Standing in a queue behind eleven senior pros at the food counter, ",
    "Told he needs to be nastier, by a man in a fleece with a whistle, ",
    "The one coach who ever explained anything to him has gone to another club, and the man who replaced him has not learned the names yet, ",
    "There is a first-team injury and everyone in the reserves knows what that means, ",
    "Growing into a body that was not there in April, ",
    "The reserve manager writes his teams on the back of a cigarette packet, ",
    "Been at the club since he was eight and it might end in June, ",
    "Quick is not the same as early, ",
    "A trialist from Sweden has been given his position for a fortnight, ",
    "Half the year group has already signed and he is still waiting, ",
    "Somebody left the floodlights on and the groundsman blamed the youth team, ",
    "Boots off in the car park because the coach has waxed the corridor, ",
    "Told his ceiling by a man who has never seen him play a full game, ",
    "The digs have a rule about the front door and a rule about the bath, ",
    "Playing against grown men who get paid to stop him, ",
    "First professional contract, two years, and a signing-on fee that pays for a car, ",
    "Fifty-three appearances for the youth team and one for the reserves, ",
    "A photograph of him with the chairman is on the club website, ",
    "Being the one who carries the bibs and balls back in, ",
    "The dressing room has a stereo and he is not allowed near it, ",
    "Nobody warns you that the biggest day is a Tuesday morning, ",
    "Told to go and get some games somewhere, anywhere, ",
    "Two months in the gym and none of it on the pitch, ",
    "An old pro takes the youth session on Fridays and it is the best hour of the week, ",
    "The coach has a new whistle, ",
    "Afternoons off from one o'clock until the next morning, a games console, a sofa, and a landlady hoovering round his feet, ",
    "A first-team debut is a sentence other people say about other people, ",
    "Half the squad has an agent and the other half pretends to, ",
    "Sent to play a bounce game at a prison ground on a Wednesday, ",
    "The bloke who cuts the grass has been there forty years and remembers everyone, ",
    "Getting changed in a corridor because the away room is being painted, ",
    "There is a lad on trial sleeping in the room next to his, ",
    "Told to stop nutmegging people, ",
    "A pre-season friendly in Ireland, forty minutes, one assist, ",
    "The physio's table at eight in the morning has a queue, ",
    "Nineteen years old is a long way off and it decides everything, ",
    "Collar and tie on the coach now, ",
    "Someone stole his shin pads and he has not said anything, ",
    "The under-18s dressing room is a portakabin with a bad door, ",
    "Two of the lads released in January still come on Saturdays and watch from the far side with their hands in their pockets, ",
    "Signed for two years with an option the club holds, ",
    "Being asked to do the warm-down while the seniors go in, ",
    "A left-back from the academy has been sold for money nobody expected, ",
    "Told, in passing, that he is on a list of six — six for two places, ",
    "Chips and a bottle of water on the way home from Rotherham, ",
    "The bloke on the gate calls him by the name of a player who left in 2019, ",
    "Ninety minutes for the reserves against a team of trialists and comeback men, ",
    "His old school teacher sends a message asking how it's going, ",
    "Playing in front of scouts who are watching somebody else, ",
    "A hamstring, twice, in six weeks, ",
    "Nine new fifteen-year-olds arrived in July, and one of them is already ahead of a lad from his own intake, ",
    "Told to keep his phone off during team meetings, and he does, ",
    "Boots in the tumble dryer again, ",
    "Being taken off at half-time and not told why until Monday, ",
    "There is a loan offer from a club three hundred miles north, ",
    "Nobody in the digs has a car and the last bus goes at ten past, ",
    "Waiting for a decision that four men will make over sandwiches, ",
    "Learning the seniors' nicknames without ever being given one, ",
    "The kit man swore at him for putting whites in with the reds, ",
    "A goal nobody filmed, ",
    "First flight for a game, and he sat by the window, ",
    "Told he needs a season of men's football, ",
    "The strength coach measures his jump on a mat every fortnight, ",
    "Somebody at the club calls him 'the young lad' and it might stick, ",
    "Been asked to train with the first team on Thursday, no other information, ",
    "Twenty-five pounds a week for cleaning boots, ",
    "A trial at a bigger club that his own club does not know about, ",
    "The pitches flood by the far corner and they play on it anyway, ",
    "Handed the number nine shirt for the eighteens because the other lad is injured, ",
    "Being taught how to speak to a local reporter, in a room, by a woman with a folder, ",
    "Four lads released on a Wednesday and training as normal on the Thursday, ",
    "Nothing in his life has a date on it after June, ",
    "The landlady wants to know if he's staying next season, ",
    "Standing at the back of a first-team meeting with his hands behind his back, understanding about a third of what is being said, ",
    "A senior midfielder gave him a pair of boots he had never worn, ",
    "Reserve football, a fifteen-hundred capacity ground, and one photographer, ",
    "Told he has a good attitude — which can mean two things, ",
    "Rooming with a lad who talks in his sleep in Portuguese, ",
    "First contract negotiations conducted mostly in a car park, ",
    "The academy has a sign about standards that nobody reads any more, ",
    "Timed over ten metres, twice, ",
    "His agent talks about clubs he has never been to, ",
    "A cold Tuesday, a wet ball and a coach who counts every mistake, ",
    "Named on the bench for a cup tie on a Tuesday, and he was still on it when the fourth official put the board up, ",
    "Given a locker in the main building for the first time, ",
    "Two years older than the boy who arrived and it does not feel like it, ",
    "Playing catch-up with a body that changed shape over one summer, ",
    "The doctor knows his knees better than his mum does, ",
    "Told to lose the earrings before he trains with the seniors, ",
    "Watching from the tunnel, ",
    "A reserve game abandoned at half-time for a floodlight failure, ",
    "Eight lads in the intake, three cars between them, ",
    "Signing a form that mentions image rights and not understanding a word, ",
    "The chief scout stands with his hands behind his back — never a word, never a nod, ",
    "Getting spoken to about his diet, at length and in front of others, by a man holding a bacon roll, ",
    "There is a photo of the last intake on the wall and four of them made it, ",
    "Learning to lose the ball and not disappear for ten minutes after, ",
    "A youth team manager who has seen four hundred boys come through, ",
    "Told the loan is off, on the morning it was meant to happen, ",
    "The training kit gets handed in every night and comes back tighter, ",
    "Nobody has explained what happens if the answer is no, ",
    "Sat on a bench outside the manager's office with his hands between his knees, ",
    "Playing a bounce game against the first team and told not to embarrass anyone, ",
    "One year left, one shirt, and a lad from Nigeria who is better than him at everything but heading, ",
    "The scholarship ends on the thirtieth of June, ",
    "His mum has kept every programme with his name in it, ",
    "Back in the digs by six with the whole evening in front of him, ",
  ],
};
export const SETTINGS_O: Bank = {};
export const CHILD_SETUP_O: Bank = {};
export const EVENT_PREFIX_O: Bank = {};
export const BIG_SETTINGS_O: string[] = [];
