import type { CommentaryBank } from './extra.js';

// ── PACK 7 — the second yellow ─────────────────────────────────────────────────────────────────────
// A dismissal for two bookings is not the same beat as a straight red, so it no longer draws from the
// same bank. A straight red is violence or a last-man foul: shock, outrage, a moment of madness. This
// is the opposite — it is CARELESS. The referee is reluctant, the offence is often trivial, and the
// player's own first booking is what convicts him. The lines below lean on that: the needlessness, the
// referee's slow reach for the pocket, the head in the hands, the bench that saw it coming.
export const CM_EXTRA_7: CommentaryBank = {
  red_card_second: [
    'A second booking, and {p} has to go — {team} are down to ten.',
    'That is his second yellow, and there is no argument to be had.',
    'The referee reaches for the yellow, then remembers the first one. {p} is off.',
    'Needless. Utterly needless. {p} collects a second booking and leaves {team} short.',
    'He was already on a card, and {p} has thrown it away.',
    'Two yellows make a red, and {p} knows exactly what he has done.',
    'The referee had warned him. {p} did not listen, and now he walks.',
    '{p} was booked inside the first half hour, and he has just gone in again.',
    'A silly, tired challenge, and it costs {p} his afternoon.',
    'He hauls him back, and the referee has no choice — second yellow for {p}.',
    'Booked, and booked again. {p} is dismissed and {team} must reorganise.',
    'The card comes out, and {p} is already walking. He knew.',
    'One rash moment on a yellow card, and {team} are a man light.',
    '{p} drags him down and immediately puts his hands on his head.',
    'That is a caution — his second — and the game is over for {p}.',
    'The referee holds the yellow up, then the red. {p} trudges off.',
    'A second yellow, and the {team} bench are furious with their own man.',
    'Careless from {p}, who was walking a tightrope from the twentieth minute.',
    'He steps across his man, and that is a second booking. {p} is gone.',
    'The dissent finishes him. {p} talks his way to a second yellow.',
    'A cheap foul in a harmless area, and {p} has been sent off for it.',
    '{p} goes into the book for the second time, and off he goes.',
    'That is the softest of second yellows, but it is a second yellow all the same.',
    'The referee did not want to give it. He had to. {p} is off.',
    '{p} kicks the ball away, and the referee has been left with no option.',
    'A second caution for time-wasting, of all things. {p} cannot believe it.',
    'He was a booking waiting to happen, and {p} has finally found it.',
    'Two yellows in eleven minutes. {p} has had a spectacular collapse.',
    'The captain is pleading, but the referee is pointing at the tunnel.',
    '{p} slides in on a card, and that is the end of him.',
    'A trailing arm, a second yellow, and {team} play out the rest with ten.',
    'He had been booked for exactly this. {p} has done it again.',
    'The manager saw it coming and could not get the substitution done in time.',
    '{p} is dismissed for two bookings, and {team} have a serious problem.',
    'A second yellow, and you can see the apology in his walk.',
    'He handles it deliberately, and that is his second card of the afternoon.',
    'The referee reaches into his pocket, and the {team} bench slumps as one.',
    '{p} is off for two yellows, and the away end are jeering him down the tunnel.',
    'A frustrated swipe from {p}, already booked, and it is a red.',
    'That is a dismissal, and {p} will not sleep well tonight.',
    'Two cautions and an early bath for {p}. {team} regroup.',
    'He pulls the shirt, the referee sees it, and the second yellow follows.',
    '{p} was one bad decision from this, and he has just made it.',
    'A second booking. Nothing malicious in it — just tired legs and a tired brain.',
    'Off he goes. {p} takes the long walk, and {team} shuffle their shape.',
    'The referee books him, checks his notebook, and reaches for red.',
    '{p} squares up to his man and that is enough for a second yellow.',
    'It is a foul, it is a caution, and it is his second. {p} is dismissed.',
    'The {team} supporters are screaming at the referee, but the card is right.',
    'A second yellow for a challenge he did not need to make.',
    'He is walking before the red is even shown. {p} knows.',
    'Two bookings, thirty seconds of madness, and {team} are down to ten.',
    'The referee shows {p} a second yellow, and the substitution board goes back in the bag.',
    '{p} appeals, but he was booked in the first half and he knows the answer.',
    'A stray boot, a second card, and {team} face the rest of this a man short.',
    'He argues, and the referee simply points to the pocket where the first one came from.',
    'A second yellow for {p}, and the shape of this game has just changed.',
    'That is his afternoon over — two bookings, and {team} must dig in.',
    '{p} lunges when he only had to stand up, and it costs him everything.',
    'The referee finishes the job he started in the first half. {p} is off.',
  ],
};
