// Match-commentary authoring pack 2. One author owns this file.
// Keys are match event types; use {p} {team} {opp} {zone} {off} {name} placeholders.
import type { CommentaryBank } from './extra.js';
export const CM_EXTRA_2: CommentaryBank = {
  // ── loose_ball (250) — the heaviest bank in a match ─────────────────────────
  loose_ball: [
    // ricochets and deflections
    "Deflected up into the air {zone} — everyone waits for it to drop.",
    "A wicked ricochet {zone}, and nobody has a clue where it is going.",
    "{p} strikes a defender and the ball loops away {zone}.",
    "Off the back of a heel, and it trickles loose {zone}.",
    "Pinball {zone}. Three touches, none of them deliberate.",
    "It clips a boot and changes direction completely {zone}.",
    "The ball rebounds off two bodies and sits up {zone}.",
    "{p} has it charged down and it spins back at him {zone}.",
    "Blocked, and the ball loops over the top {zone}.",
    "A deflection sends it looping behind {p} {zone}.",
    "It ricochets off the referee {zone} — he holds a hand up in apology.",
    "Cannoned away {zone}, and the loose ball is anyone's.",
    "Charged down by a sliding body, and it breaks square {zone}.",
    "{p} gets a boot to it and it flies off at an angle {zone}.",
    "Half a block, and the ball dribbles away {zone}.",
    "It comes back off a knee and drops {zone}.",
    "Two deflections in a second and the ball ends up {zone}.",
    "Spinning viciously {zone} — no fun to deal with, that.",
    "The ball squirts sideways out of the challenge {zone}.",
    "It rears up off a divot and beats everybody {zone}.",
    "Struck straight into the man in front, and it breaks {zone}.",
    "Off a shoulder, up in the air, and down {zone}.",
    "A wild ricochet {zone}, and the crowd rises with it.",
    "That has come off somebody, and it is loose {zone}.",
    // heavy touches and mis-control
    "{p} takes a heavy touch and it gets away from him {zone}.",
    "Far too heavy from {p} — the ball runs on {zone}.",
    "{p} lets it bounce off his shin {zone}.",
    "A poor first touch from {p}, and the moment is gone {zone}.",
    "{p} tries to take it on the turn and loses it {zone}.",
    "It bounces off {p}'s knee and away {zone}.",
    "{p} reaches for it and only knocks it further away {zone}.",
    "The ball skids under {p}'s boot {zone}.",
    "{p} traps it straight into the shins of his marker {zone}.",
    "Chest control gone wrong — {p} pushes it too far {zone}.",
    "{p} takes his eye off it and the ball is gone {zone}.",
    "He tries to be clever, and {p} loses it {zone}.",
    "{p} dawdles, and it is nicked off his toe {zone}.",
    "One touch too many from {p} {zone}.",
    "{p} cannot get it out of his feet {zone}.",
    "Awkward height for {p}, and it bounces away {zone}.",
    "{p} stretches, gets a toe on it, and it is gone {zone}.",
    "The bounce beats {p} completely {zone}.",
    "{p} goes to hook it down and shanks it {zone}.",
    "A dreadful touch from {p} {zone} — and he knows it.",
    "{p} is caught in two minds and the ball trickles loose {zone}.",
    "That is a shocking first touch from {p} {zone}.",
    "{p} lets the ball run across him and it is away {zone}.",
    "He gets right under it — {p} skies his own control {zone}.",
    "The ball hits {p}'s standing leg and spins clear {zone}.",
    // blocks and half-clearances
    "{p} hammers it into a body and the ball drops {zone}.",
    "Only half cleared, and it sits up invitingly {zone}.",
    "The clearance is charged down and the ball stays {zone}.",
    "{p} thumps it away, but only as far as {zone}.",
    "Hooked clear, and it comes straight back {zone}.",
    "A weak header away, and the ball drops {zone}.",
    "They cannot get it out of their half — back it comes {zone}.",
    "Cleared to the edge, and the ball sits {zone}.",
    "The ball is hacked away and lands {zone}.",
    "{p} gets his head to it but only nudges it {zone}.",
    "Half a clearance from {p}, and it is still live {zone}.",
    "He swings at it and misses; the ball rolls {zone}.",
    "The block is brave, but the ball stays {zone}.",
    "{p} slices his clearance horribly {zone}.",
    "A panicked hoof from {p}, straight to nobody {zone}.",
    "Cleared as far as the first man, and back it comes {zone}.",
    "{p} lunges to block and it deflects up {zone}.",
    "They get bodies in the way, and the ball spills {zone}.",
    "An air shot from {p}! The ball runs on {zone}.",
    "{p} hacks at it and the ball squirts away {zone}.",
    "The defender's boot gets there first, but it goes nowhere {zone}.",
    "Headed clear, but straight up in the air {zone}.",
    "Cleared into the back of a teammate, and it rebounds {zone}.",
    "Hoofed away, and the ball comes back down {zone}.",
    // scrambles and two men on it
    "Both of them go for it and neither gets it {zone}.",
    "Two men slide in and the ball pops out {zone}.",
    "They arrive at once and the ball squeezes free {zone}.",
    "A tangle of legs {zone}, and it comes loose.",
    "Four players in a heap {zone}, and none of them has it.",
    "A fifty-fifty {zone}, and the ball wins it.",
    "{p} and his man collide, and it breaks between them {zone}.",
    "Shoulder to shoulder {zone}, and the ball runs on.",
    "A wrestling match {zone}, and neither of them will give in.",
    "Everybody piles in {zone} and it comes out the other side.",
    "It is a lottery {zone} — the ball pings between three of them.",
    "Nobody claims it {zone}. Scruffy stuff.",
    "{p} gets a foot in, so does his marker, and it flies loose {zone}.",
    "Chaos {zone} — the ball is bouncing about like a pinball.",
    "They both jump, they both miss, and it drops {zone}.",
    "A scruffy passage {zone}. Not one for the purists.",
    "Legs and elbows {zone}, and the ball squirms free.",
    "Three shirts all on the same ball {zone}.",
    "There is a queue for that one {zone}, and nobody gets it.",
    "A right old scramble {zone} before it breaks clear.",
    "Bodies on the deck {zone}, and the ball rolls away from all of them.",
    "It gets stuck under {p}'s feet {zone} and he loses it.",
    "The pair of them go up and it drops between them {zone}.",
    "A real scrap for that one {zone}.",
    // keeper spills and goalkeeping
    "The keeper cannot hold it! The ball spills {zone}.",
    "Parried out, and it is loose {zone}.",
    "Punched clear, and the ball drops {zone}.",
    "The keeper flaps at it and the ball skips away {zone}.",
    "He comes and gets nowhere near it — loose {zone}.",
    "Palmed away, but only into trouble {zone}.",
    "The ball squirms out of the keeper's grasp {zone}.",
    "A wet ball, and it slips straight through the gloves {zone}.",
    "He beats it away rather than catching it, and it drops {zone}.",
    "The keeper comes to punch and misses everything {zone}.",
    "Spilled at the second attempt, and the ball is live {zone}.",
    "He can only push it out {zone}, and the strikers gamble.",
    "The keeper claims it, drops it, and it rolls loose {zone}.",
    "He goes down on it, and the ball squeezes under him {zone}.",
    "A big punch, and the ball loops away {zone}.",
    "He tries to gather it with his feet and knocks it clear {zone}.",
    "The keeper's throw-out is intercepted {zone}.",
    "He rushes the kick and it is charged down {zone}.",
    "The keeper hesitates, and the ball is loose {zone}.",
    "Off the keeper's chest and out {zone}.",
    "A strong hand on it, and the ball flies {zone}.",
    "The catch is fumbled, and it drops kindly {zone}.",
    "He is caught in no man's land and the ball runs on {zone}.",
    "A hurried clearance off the keeper's boot, straight {zone}.",
    "The keeper waves for it, claims nothing, and it drops {zone}.",
    // misplaced passes and interceptions
    "{p}'s pass is a yard behind his man {zone}.",
    "Overhit by {p} — the ball runs harmlessly away {zone}.",
    "Underhit! {p} gives it straight to the opposition {zone}.",
    "A sloppy ball from {p}, cut out {zone}.",
    "{p} tries the clever pass and it is read {zone}.",
    "Intercepted! {p} telegraphed that one {zone}.",
    "{p} plays it into an empty space {zone}.",
    "There is no weight at all on that pass from {p} {zone}.",
    "{p} goes for the switch and slices it out of play.",
    "A blind pass from {p}, and it is picked off {zone}.",
    "{p} looks for the one-two and there is nobody there {zone}.",
    "The ball is behind him, and {p} cannot dig it out {zone}.",
    "{p} aims for the near post and finds a shin {zone}.",
    "Cut out easily — {p} gave that away {zone}.",
    "{p}'s ball into the channel is far too strong.",
    "He picks out the wrong shirt; {p} will not enjoy that {zone}.",
    "A hospital pass from {p} {zone}, and his teammate is clattered.",
    "{p} rolls it straight into the press {zone}.",
    "Ambitious from {p}, and it does not come off {zone}.",
    "That is a lazy ball from {p} {zone}.",
    "{p} tries to thread it through and it is blocked {zone}.",
    "The pass never had a chance — cut out {zone}.",
    "{p} takes too long, and the lane closes {zone}.",
    "Misjudged by {p}, and it runs out for a throw.",
    "{p} floats it to nobody in particular {zone}.",
    // the ball running out of play
    "It trickles out for a throw {zone}.",
    "Out of play, and the officials have a decision to make.",
    "It runs out with nobody chasing it.",
    "That is a goal kick — an opportunity wasted.",
    "Straight into touch. Sloppy {zone}.",
    "The ball drifts out and the crowd groans.",
    "Nobody gambles, and it dribbles over the line.",
    "{p} chases it down and cannot keep it in.",
    "Out for a throw-in, and both sides claim it.",
    "It rolls out and the referee points the other way; {p} is furious.",
    "A stray boot puts it into touch {zone}.",
    "That has come off the last man — a throw deep {zone}.",
    "The ball beats {p} and skips out of play.",
    "He tries to keep it alive and cannot — out it goes.",
    "Ball out. A moment for everyone to breathe.",
    "A long punt, straight out on the full.",
    "A poor way to lose it — straight out {zone}.",
    "{p} slides to keep it in and the linesman disagrees.",
    "It runs through to the keeper and the move dies.",
    "The ball dies on the touchline {zone}.",
    "Wasted. It goes out with three men in support.",
    "A hopeful flick, and the ball is out of play.",
    "{p} stretches at full length and it still goes out.",
    "The ball is stuck under the advertising boards.",
    "It squeezes out for a throw with everybody appealing.",
    // bobbles, surface and conditions
    "The ball bobbles horribly {zone}.",
    "A bad bounce {zone}, and everybody has been fooled.",
    "The surface is cutting up — it skids on {zone}.",
    "The pitch takes a divot out of it {zone}.",
    "It sits up nastily and {p} cannot deal with it {zone}.",
    "The ball skims off the wet grass and away {zone}.",
    "A gust catches it {zone} and it drops short.",
    "It keeps low, and {p} is left swiping at fresh air {zone}.",
    "Hard to control on this surface — it gets away {zone}.",
    "The ball hits a rut and jumps up {zone}.",
    "Greasy underfoot, and {p} slips as it runs away {zone}.",
    "{p} loses his footing and the ball rolls free {zone}.",
    "He slips at the worst possible moment {zone} — the ball is gone.",
    "The ball holds up in the grass and the run is wasted {zone}.",
    "It skids off the paint of the line {zone}.",
    "A horrible bounce beats two players {zone}.",
    "The ball dies in a puddle {zone}.",
    "It hops clean over {p}'s boot {zone}.",
    "The wind takes it, and the ball drifts {zone}.",
    "Bouncing awkwardly {zone}, and nobody fancies it.",
    "A knee-high ball {zone} — the worst height there is.",
    "It comes up off the deck and hits {p} on the hip {zone}.",
    "{p} goes to knock it down and gets nothing on it {zone}.",
    "The ball is greasy and it slides through the challenge {zone}.",
    "He plants his foot, the turf gives way, and it is loose {zone}.",
    // aerial duels and second balls
    "Up they go, and the header drops loose {zone}.",
    "A flick-on goes over everybody {zone}.",
    "{p} wins the header but the ball goes nowhere {zone}.",
    "They both climb, and it skims off the top of a head {zone}.",
    "Nobody attacks it, and the ball bounces through {zone}.",
    "The knock-down is not clean, and it rolls away {zone}.",
    "{p} climbs highest and the ball loops off him {zone}.",
    "A duel in the air {zone}, and it comes down between them.",
    "The header is aimless — it drops {zone}.",
    "He nods it straight back into trouble {zone}.",
    "A cushioned header gone wrong, and the ball is stolen {zone}.",
    "The flick-on beats his own man and runs away {zone}.",
    "Up for the long ball, and neither gets a touch on it {zone}.",
    "{p} loses the aerial duel and the ball drops {zone}.",
    "Headed into the ground, and it bounces up over everyone {zone}.",
    "The second ball drops {zone} and nobody reacts.",
    "{p} is out-jumped and the ball spins away {zone}.",
    "A tame header, easily read {zone}.",
    "They challenge in the air and both come away holding a head.",
    "The knock-down is behind the runner {zone}.",
    "He heads it straight up {zone}, and waits for it to come down.",
    "The long ball is nodded back the way it came {zone}.",
    "A defensive header that goes almost nowhere {zone}.",
    "{p} times his leap badly and misses it altogether {zone}.",
    "The ball glances off a head and away {zone}.",
    // texture and tempo
    "Untidy, that {zone}.",
    "Scrappy fare {zone}.",
    "Nobody in control here {zone}.",
    "The ball is up for grabs {zone}.",
    "End to end, and neither side can keep hold of it {zone}.",
    "Loose again {zone}. A mess of a passage, this.",
    "Possession changes hands three times in ten seconds {zone}.",
    "{p} gives it away, wins it back, and gives it away again {zone}.",
    "The ball simply will not settle {zone}.",
    "A broken phase of play {zone}.",
    "Nothing is sticking {zone}.",
    "That is the fourth turnover in a minute {zone}.",
    "{p} dribbles into trouble and it is gone {zone}.",
    "He runs into a wall of shirts and loses it {zone}.",
    "Too many touches, and {p} is crowded out {zone}.",
    "They swarm him and the ball comes free {zone}.",
    "{p} tries to shield it and is bundled off it {zone}.",
    "He is nudged off the ball {zone} and looks for a whistle that never comes.",
    "{p} shapes to cross and gets it stuck under his feet.",
    "The ball squeezes through a forest of legs {zone}.",
    "A wild swing, and it goes anywhere but forward {zone}.",
    "{p} attempts the nutmeg and is left with nothing {zone}.",
    "Overplaying it {zone}, and they are punished.",
    "He tries to walk it out from the back and pays for it {zone}.",
    "The ball stops dead in the grass {zone}.",
  ],
  // ── tackle_won (200) — ⚡ high presses and 🦵 ordinary tackles ──────────────
  tackle_won: [
    "⚡ Snapped up! {p} takes it off his toe and {team} are away.",
    "⚡ {p} times the press to perfection and {team} have it.",
    "⚡ Never a moment's peace — {p} takes it off him.",
    "⚡ Robbed! {p} makes that look far too easy for {team}.",
    "⚡ {team} squeeze right up, and {p} pinches it.",
    "⚡ Ambushed. {p} arrives from nowhere.",
    "⚡ {p} sniffs the loose touch and pounces.",
    "⚡ The pressure told — {p} has it back for {team}.",
    "⚡ Two of them close him down and {p} takes the ball.",
    "⚡ {p} shows him inside, then takes it clean off him.",
    "⚡ A trap sprung by {team}, and {p} is the one who profits.",
    "⚡ Punished! One loose touch and {p} is on it.",
    "⚡ {p} bares his teeth in the challenge and wins it.",
    "⚡ {team} will not let him breathe; {p} takes possession.",
    "⚡ Straight back at them — {p} wins it and {team} go again.",
    "⚡ He should have played it earlier; {p} makes him pay.",
    "⚡ {p} charges the pass down and collects.",
    "⚡ Sharp from {p} — in, out, and away with the ball.",
    "⚡ {p} stings him with the tackle and comes out on top.",
    "⚡ Won back inside three seconds. {team} are relentless.",
    "⚡ {p} nicks it and the crowd are on their feet.",
    "⚡ {team} counter-press, and {p} is the beneficiary.",
    "⚡ He is smothered, and {p} does the smothering.",
    "⚡ Nowhere to go, and {p} helps himself.",
    "⚡ {p} anticipates it and jumps the pass.",
    "⚡ A brilliant read from {p} — {team} have it back.",
    "⚡ {p} rushes him into an error and takes the ball.",
    "⚡ {team} pull the trigger on the press and {p} wins it.",
    "⚡ {p} shoves him off it and it belongs to {team}.",
    "⚡ Turnover! {p} strips him with a nudge of the shoulder.",
    "⚡ {p} hunts him down and gets there.",
    "⚡ The tackle is timed to the split second by {p}.",
    "⚡ {p} takes ball and man, and only the ball counts.",
    "⚡ A cheap concession, and {p} has {team} moving forward.",
    "⚡ He dithers. {p} does not.",
    "⚡ Under real pressure from {p}, and the ball is surrendered.",
    "⚡ {p} simply bullies him off it.",
    "⚡ Poked away by {p}, and {team} can break.",
    "⚡ A greedy dribble, and {p} punishes it.",
    "⚡ {p} throws himself in and comes up with the ball.",
    "⚡ Turned inside out and robbed — {p} has done him there.",
    "⚡ {team} swarm forward and {p} wins it back.",
    "⚡ {p} steps across him and takes it.",
    "⚡ The pass is cut out by {p} and {team} pour forward.",
    "⚡ {p} times his run at the ball and wins it clean.",
    "⚡ Won by {p} in the sort of area that really hurts.",
    "⚡ Reckless in possession, and {p} makes it count.",
    "⚡ Not a chance — {p} is straight on top of him.",
    "⚡ Squeezed out of it, and {p} takes over.",
    "⚡ {p} scuttles across and takes it off his laces.",
    "⚡ He is hemmed in, and {p} finishes the job.",
    "⚡ {p} sprints thirty yards to make that one.",
    "⚡ A sensational press by {team}, finished by {p}.",
    "⚡ Nicked! {p} does not even break stride.",
    "⚡ {p} wins it and {team} have bodies streaming forward.",
    "⚡ That is high-class pressing from {p}.",
    "⚡ Wrong-footed and robbed — {p} has the ball.",
    "⚡ The touch is a foot too long, and {p} is there.",
    "⚡ Suffocating stuff from {team}. {p} takes the ball.",
    "⚡ {p} makes the ground up and wins the duel.",
    "⚡ A poor decision under pressure, and {p} takes full advantage.",
    "⚡ {p} snarls into the challenge and comes away clean.",
    "⚡ Taken off him by {p}, and the crowd sense something.",
    "⚡ {team} do not give him a yard, and {p} takes it.",
    "⚡ Trapped on the touchline, and {p} pinches it.",
    "⚡ {p} bends his run and cuts the pass out.",
    "⚡ A dreadful moment to lose it, and {p} says thank you.",
    "⚡ The press is on, and {p} finishes it.",
    "⚡ {p} takes it with a toe-poke and skips away.",
    "⚡ Won by {p} in a horrible area for them.",
    "⚡ Under the cosh, and now they have lost the ball as well.",
    "⚡ {p} times the shoulder charge beautifully.",
    "⚡ Stripped of it! {p} is a nuisance in the best way.",
    "⚡ A moment of carelessness, seized upon by {p}.",
    "⚡ Straight into him — {p} wins the ball with the challenge.",
    "⚡ {p} reads the touch before it even happens.",
    "⚡ The ball is turned over and {p} is up and running.",
    "⚡ Nipped away by {p} with the outside of his boot.",
    "⚡ He hesitates for half a second and {p} is on him.",
    "⚡ A brave challenge from {p}, and it comes off.",
    "⚡ {team} choke the space and {p} wins it back.",
    "⚡ {p} chases a lost cause and wins the ball.",
    "⚡ Pinched by {p}, and {team} smell blood.",
    "⚡ Textbook pressing — {p} forces it and takes it.",
    "⚡ {p} slides in front of him and steals possession.",
    "⚡ No escape. {p} takes it and turns.",
    "⚡ He tries to spin out of it, and {p} will not allow it.",
    "⚡ {p} pinches it and immediately looks up.",
    "⚡ Like a swarm of bees, and {p} emerges with the ball.",
    "⚡ Won and kept by {p} — that is the hard part done.",
    "⚡ A tigerish challenge from {p}.",
    "⚡ The turnover is {team}'s, courtesy of {p}.",
    "⚡ {p} makes the tackle and stays on his feet.",
    "⚡ Muscled off it, and {p} has it.",
    "⚡ {p} times it late and still takes a clean ball.",
    "⚡ This is what the pressing is for — {p} has it.",
    "⚡ He is caught stone cold by {p}.",
    "⚡ {p} bites at his heels until the ball is his.",
    "🦵 {p} gets his body across and shields it away {zone}.",
    "🦵 A clean take from {p} {zone}.",
    "🦵 {p} times the sliding challenge perfectly {zone}.",
    "🦵 Out of nowhere, {p} pokes it clear {zone}.",
    "🦵 {p} stands firm and the attacker bounces off him {zone}.",
    "🦵 {p} sees it coming and steps into the pass {zone}.",
    "🦵 Won by {p} without a foul in sight {zone}.",
    "🦵 {p} shepherds him away and takes it {zone}.",
    "🦵 A neat toe-poke from {p} {zone}, and {team} have it.",
    "🦵 The tackle is firm but fair from {p} {zone}.",
    "🦵 {p} backs off, backs off, and then pounces {zone}.",
    "🦵 Good defending — {p} shows him the line and wins it {zone}.",
    "🦵 {p} throws a leg out and hooks it clear {zone}.",
    "🦵 That is a proper tackle from {p} {zone}.",
    "🦵 {p} gets there first, and the crowd appreciate it {zone}.",
    "🦵 A well-judged interception by {p} {zone}.",
    "🦵 {p} rises and takes it off his head {zone}.",
    "🦵 The dribble ends there — {p} takes the ball {zone}.",
    "🦵 {p} stretches out a leg and diverts it to safety {zone}.",
    "🦵 Bravery from {p} — head in where the boots are {zone}.",
    "🦵 A clean sweep of the ball by {p} {zone}.",
    "🦵 {p} does not dive in; he waits, and he wins it {zone}.",
    "🦵 The pass is cut out by {p} {zone}, read the whole way.",
    "🦵 {p} outmuscles him {zone} and comes away with it.",
    "🦵 Simple, effective defending from {p} {zone}.",
    "🦵 {p} nicks it away and finds a shirt {zone}.",
    "🦵 A last-ditch challenge from {p} {zone}.",
    "🦵 {p} slides across the surface and takes ball only {zone}.",
    "🦵 He runs straight into {p} {zone}, and comes off worse.",
    "🦵 {p} wins the duel through sheer stubbornness {zone}.",
    "🦵 Composed from {p} — he waits and takes it {zone}.",
    "🦵 A crunching but perfectly legal challenge {zone} from {p}.",
    "🦵 {p} plants a foot on it and the danger is gone {zone}.",
    "🦵 Bundled off the ball by {p} {zone}.",
    "🦵 {p} arrives just in the nick of time {zone}.",
    "🦵 Cover defending at its best — {p} sweeps up {zone}.",
    "🦵 {p} tracks him for forty yards and then takes it {zone}.",
    "🦵 That is a captain's tackle from {p} {zone}.",
    "🦵 {p} keeps his feet and wins the ball {zone}.",
    "🦵 Everything about that challenge from {p} is right {zone}.",
    "🦵 He tries the step-over; {p} is not remotely interested {zone}.",
    "🦵 {p} takes it off his instep {zone}.",
    "🦵 A tidy interception from {p} {zone}.",
    "🦵 {p} gets goal-side and the attack fizzles out {zone}.",
    "🦵 Cool as you like from {p} {zone}.",
    "🦵 {p} nudges him off balance and takes over {zone}.",
    "🦵 A big challenge {zone}, and {p} wins it fairly.",
    "🦵 {p} wins it and holds his ground {zone}.",
    "🦵 Blocked off, boxed in, and taken by {p} {zone}.",
    "🦵 {p} sticks out a boot, and that is enough {zone}.",
    "🦵 Perfectly weighted defending from {p} {zone}.",
    "🦵 {p} refuses the dummy and takes the ball {zone}.",
    "🦵 A tough tackle {zone}, and {p} wins it clean.",
    "🦵 {p} times the interception to the yard {zone}.",
    "🦵 He is dispossessed {zone} — {p} did that beautifully.",
    "🦵 The ball is hooked back to a teammate by {p} {zone}.",
    "🦵 {p} wins it, gets up, and asks for it again {zone}.",
    "🦵 A no-nonsense block by {p} {zone}.",
    "🦵 Steady from {p} {zone}. He is reading this game well.",
    "🦵 {p} makes it look simple {zone}.",
    "🦵 A tackle with the studs down and the timing right {zone}.",
    "🦵 {p} wins it in front and turns upfield {zone}.",
    "🦵 The forward is smothered by {p} {zone}.",
    "🦵 {p} does the ugly work {zone}, and nobody notices.",
    "🦵 One touch to win it, one to move it — {p} {zone}.",
    "🦵 Anticipation from {p} {zone}, and the ball is his.",
    "🦵 {p} makes the tackle and springs the counter {zone}.",
    "🦵 Firm shoulder, clean ball, {p} {zone}.",
    "🦵 {p} recovers superbly to make the challenge {zone}.",
    "🦵 A brilliant last-man tackle by {p} {zone}.",
    "🦵 The attacker looks for a foul; the referee waves it on.",
    "🦵 {p} wins the ball and there is no argument {zone}.",
    "🦵 Snuffed out by {p} {zone}.",
    "🦵 {p} narrows the angle and takes it {zone}.",
    "🦵 A sound tackle from {p} {zone}, and {team} build again.",
    "🦵 {p} rides the challenge and comes away with it {zone}.",
    "🦵 Beaten once, {p} recovers and wins it back {zone}.",
    "🦵 The header from {p} is clean and away {zone}.",
    "🦵 {p} scoops it away from danger {zone}.",
    "🦵 Two defenders, one ball, and it is {p} who takes it {zone}.",
    "🦵 {p} makes his body big and wins it {zone}.",
    "🦵 A clever bit of defending by {p} {zone}.",
    "🦵 {p} holds him up until help arrives, then takes it {zone}.",
    "🦵 A gritty challenge from {p} {zone}.",
    "🦵 {p} steals in behind and takes it off him {zone}.",
    "🦵 The turnover belongs to {p} {zone}.",
    "🦵 {p} slides, wins it, and is back up in one movement {zone}.",
    "🦵 Nothing flashy from {p} {zone} — just a good tackle.",
    "🦵 {p} chops the run in half and takes possession {zone}.",
    "🦵 Well read and well won by {p} {zone}.",
    "🦵 {p} gets a foot in and the move is over {zone}.",
    "🦵 It is a strong challenge {zone}, and {p} comes out with it.",
    "🦵 {p} tidies it up {zone} and looks for a pass.",
    "🦵 The attacker runs out of ideas and {p} takes it {zone}.",
    "🦵 {p} pinches it and plays the simple ball {zone}.",
    "🦵 A really good bit of defending from {p} {zone}.",
    "🦵 {p} does not give him an inch {zone}.",
  ],
  // ── chance (150) ────────────────────────────────────────────────────────────
  chance: [
    "{p} is through! Just the keeper to beat…",
    "A yard of space for {p}, and he winds up…",
    "{team} slice it open — {p} has the ball at his feet…",
    "Here is the opening for {team} — {p} takes aim…",
    "The ball drops to {p} eight yards out…",
    "{p} spins his marker and looks up…",
    "It falls perfectly for {p}…",
    "{team} get in behind! {p} is the man…",
    "A clever dummy from the front man, and {p} runs onto it…",
    "{p} is picked out at the far post…",
    "One touch to control, one to shoot — {p}…",
    "{p} drops a shoulder and there is the gap…",
    "{team} work the overlap and {p} is in…",
    "It is two against one, and {p} has the ball…",
    "{p} cuts inside and everything opens up…",
    "The through ball is perfect and {p} is away…",
    "{p} meets the cross on the run…",
    "A mix-up at the back, and {p} smells it…",
    "{p} steals a yard at the near post…",
    "The ball breaks to {p} on the edge…",
    "{team} have men over — {p} is in acres…",
    "{p} skips past one, and past two…",
    "Head up, and {p} takes it on…",
    "{p} is free at the back post and the ball is coming…",
    "The offside trap fails, and {p} is through…",
    "A first-time flick sends {p} clear…",
    "{p} steadies himself twelve yards out…",
    "A glorious chance for {team} — {p} to finish…",
    "The cutback finds {p} unmarked…",
    "{p} gets across his man and stretches for it…",
    "{team} break with numbers, and {p} leads it…",
    "{p} is a yard clear of the last defender…",
    "A dinked ball over the top, and {p} is chasing…",
    "Nobody picks {p} up, and the ball is dropping…",
    "{p} rides one challenge and keeps going…",
    "The keeper is stranded and {p} has the ball…",
    "{p} shapes to bend it into the far corner…",
    "A gaping hole in the middle, and {p} runs into it…",
    "{p} chests it down inside the box…",
    "A sight {opp} will not enjoy — {p} bearing down on goal…",
    "{p} bursts clear of the lot of them…",
    "The rebound sits up for {p}…",
    "{p} is set, and the goal is at his mercy…",
    "A one-two, and {p} is in behind…",
    "It is opening up for {team}. {p} takes the shot on…",
    "{p} beats the offside line by a stride…",
    "The ball is worked wide and back in to {p}…",
    "{p} has time. Perhaps too much time…",
    "Six yards out, and it is falling to {p}…",
    "{opp} are all over the place, and {p} has the ball…",
    "{p} charges into the area with only green in front of him…",
    "A wonderful pass releases {p}…",
    "{p} nutmegs the defender and is away…",
    "{team} counter at speed. {p} carries it…",
    "The volley is lining up for {p}…",
    "{p} has a free header in the middle…",
    "A slip at the back, and {p} pounces…",
    "It sits up nicely for {p} on the penalty spot…",
    "{p} is on his weaker foot, but he fancies it…",
    "A clipped cross, and {p} attacks it…",
    "Two touches to get clear, and {p} looks to finish…",
    "The defence backs off and {p} takes his chance…",
    "{p} is loitering on the edge of the box, and the ball drops…",
    "{team} switch it, and suddenly {p} is one on one…",
    "The rebound falls to {p} with the goal gaping…",
    "{p} drives at the retreating defence…",
    "Panic in the {opp} box, and {p} is the closest to it…",
    "{p} takes the ball across the face of goal…",
    "The ball is threaded through and {p} runs onto it…",
    "{p} shrugs off his man inside the area…",
    "A chance to settle this — {p} with the ball…",
    "{p} is queuing up at the far post…",
    "Half a yard is all {p} needs, and he has it…",
    "The keeper comes, and {p} has the chance to go round him…",
    "{p} arrives late into the box, unmarked…",
    "A deflection lands at {p}'s feet in the six-yard box…",
    "{team} pour forward. {p} is in the thick of it…",
    "{p} lifts his head and picks his spot…",
    "A darting run from {p} beats the whole back line…",
    "The chance is there for {p}, and the crowd is up…",
    "{p} controls it on his thigh and swivels…",
    "It is all happening — {p} through on goal…",
    "{team} are in! {p} has the ball and options…",
    "{p} is played in behind the full-back…",
    "A stepover, another, and {p} is clear…",
    "The ball is laid back to {p} and he can hit it…",
    "{p} takes it early, before the block arrives…",
    "He has beaten his man; {p} looks up for the finish…",
    "The pull-back is measured, and {p} arrives…",
    "{p} touches it past the sliding defender…",
    "A glorious opening for {team}, and {p} is the man…",
    "{p} finds a pocket ten yards out…",
    "The ball sits up beautifully for {p}…",
    "{p} on the half-volley from the edge…",
    "{team} have three men in the box and the ball is coming…",
    "{p} runs across the defender and gets in front…",
    "A moment of quality from {p} takes him clear…",
    "The keeper is off his line, and {p} has spotted it…",
    "{p} has the goal at his mercy…",
    "A scuffed clearance drops to {p} in the danger area…",
    "{p} rounds one man and steadies himself…",
    "{team} are through the middle and {p} is bearing down…",
    "The ball breaks perfectly for {p} on the angle…",
    "{p} looks for the near post…",
    "A driven cross, and {p} gambles at the front stick…",
    "{p} is on the shoulder and the ball goes over the top…",
    "The defence is stretched and {p} runs into the space…",
    "{p} decides to have a go from distance…",
    "It drops out of the sky to {p}…",
    "{p} is unmarked. Somebody should be with him…",
    "A slide-rule pass, and {p} is in…",
    "{p} makes the run, and the ball comes…",
    "Half a chance for {p}, and he takes it on…",
    "{p} is bundled, stays on his feet, and shoots…",
    "{team} smell a goal here. {p} shapes to strike it…",
    "The header is looping down towards {p}…",
    "{p} is picked out on the penalty spot…",
    "This is the moment for {p}…",
    "A quick one-two on the edge, and {p} is free…",
    "{p} works it onto his right and lets fly…",
    "The final ball is inch-perfect, and {p} is onto it…",
    "{p} has escaped his marker at the corner…",
    "The break is on! {p} carries it forward with support…",
    "{p} against the last defender, and he goes for it…",
    "They have left {p} completely alone…",
    "{p} takes a touch and opens up his body…",
    "The pass splits them, and {p} is clear…",
    "{p} arrives at the near post ahead of the keeper…",
    "A huge chance for {team}, and it falls to {p}…",
    "{p} rolls his man and drives at goal…",
    "The ball drops over the defender's head to {p}…",
    "{p} sets himself for the shot…",
    "A gorgeous first touch from {p} takes him clear…",
    "{p} is in on the angle with the keeper narrowing it…",
    "{team} have carved this open, and {p} is the finisher…",
    "A weak header back, and {p} is onto it…",
    "{p} gets the wrong side of his man and is away…",
    "The ball is in the corridor and {p} is chasing it…",
    "{p} takes it on his chest and swings a leg…",
    "Space opens ahead of {p} and he strides into it…",
    "{p} goes down the outside and cuts back in…",
    "This could be the chance of the match for {p}…",
    "{p} shifts it left, then right, and shoots…",
    "The knock-down finds {p} in the middle…",
    "{p} is put clean through by a defensive slip…",
    "Everything opens up. {p} is in on goal…",
    "{p} has a shooting chance, and the crowd urge him on…",
    "The ball is worked to {p} on the edge of the area…",
    "{p} has a sniff here…",
  ],
  // ── shot_saved (120) ────────────────────────────────────────────────────────
  shot_saved: [
    "🧤 A flying save! {p} thought that was in.",
    "🧤 Fingertips! The {opp} keeper claws it away from {p}.",
    "🧤 Superb! {p} is denied at the near post.",
    "🧤 The keeper spreads himself and blocks {p} with his legs.",
    "🧤 Up he goes, and tips {p}'s effort over.",
    "🧤 Straight at the keeper — {p} will be disappointed with that.",
    "🧤 A strong wrist keeps {p} out.",
    "🧤 Somehow he keeps it out! {p} holds his head.",
    "🧤 Down low to his left, and the {opp} keeper holds it.",
    "🧤 Smothered at the feet of {p}.",
    "🧤 {p} strikes it well, but the keeper is equal to it.",
    "🧤 A reflex save! No idea how he saw that from {p}.",
    "🧤 Pushed round the post. {p} cannot believe it.",
    "🧤 The keeper stands tall and {p} finds only his chest.",
    "🧤 Saved with the legs! {p} had the whole goal to aim at.",
    "🧤 A brave block at close range denies {p}.",
    "🧤 That is world class from the {opp} goalkeeper.",
    "🧤 Tipped onto the bar and away — {p} was inches from it.",
    "🧤 {p} goes for power, and the keeper goes with him.",
    "🧤 Held. A comfortable one in the end for {opp}.",
    "🧤 The keeper reads the placement and gets across to {p}'s shot.",
    "🧤 A double save! {p} cannot beat him twice.",
    "🧤 Wonderful goalkeeping — the header from {p} is turned aside.",
    "🧤 He gets a glove to it, and that is all it needed.",
    "🧤 {p} picks his corner and it is still not enough.",
    "🧤 The keeper narrows the angle and {p} hits him.",
    "🧤 Down quickly to smother {p}'s low drive.",
    "🧤 Beaten away, and {opp} scramble the loose ball clear.",
    "🧤 A strong hand from the keeper stops {p} in his tracks.",
    "🧤 What a stop! That has kept {opp} in this.",
    "🧤 {p} thumps it and the keeper punches it clear.",
    "🧤 Palmed over the top. A big moment, that.",
    "🧤 The keeper stays big and {p} cannot find a way past.",
    "🧤 An outstanding stop, low to his right, from {p}'s effort.",
    "🧤 {p} looks to the heavens; the keeper looks delighted.",
    "🧤 Blocked by the keeper's trailing leg!",
    "🧤 He is quick off his line and blocks {p}.",
    "🧤 Denied again! {opp} have a goalkeeper in form.",
    "🧤 A firm save, and no rebound for {team}.",
    "🧤 {p} tries to dink it and the keeper reaches up to claim.",
    "🧤 Held above his head. Confident stuff from {opp}.",
    "🧤 The volley from {p} is met by a solid pair of gloves.",
    "🧤 Saved, and the flag stays down — {p} was onside.",
    "🧤 A save with his face, very nearly! {p} is thwarted.",
    "🧤 The keeper gets down well at his near post.",
    "🧤 {p} hits it sweetly and it is beaten out.",
    "🧤 Stopped, and {opp} can breathe again.",
    "🧤 An acrobatic save keeps {p} out.",
    "🧤 Up and over. The {opp} keeper is enjoying himself.",
    "🧤 The header from {p} is scooped off the line.",
    "🧤 That is a save of the very highest order.",
    "🧤 {p} rolls it goalward and the keeper gathers.",
    "🧤 A stinging shot, and a fine parry.",
    "🧤 He tips it wide with his trailing hand.",
    "🧤 {p} shoots across him and the keeper adjusts brilliantly.",
    "🧤 A save {opp} will treasure.",
    "🧤 The keeper spills it, then grabs it at the second attempt.",
    "🧤 Two saves in ten seconds, and {p} is furious.",
    "🧤 Beaten out, and the follow-up is blocked as well.",
    "🧤 {p} goes for the roof of the net and the keeper flies.",
    "🧤 A comfortable take in the end, but it was struck well.",
    "🧤 A goalkeeping masterclass — {p} shakes his head.",
    "🧤 The shot from {p} is turned behind for a corner.",
    "🧤 That is why he is in the side. A brilliant stop.",
    "🧤 Saved low down. {p} needed more elevation on it.",
    "🧤 The keeper is onto it in a flash.",
    "🧤 {p} makes him work, and he is up to it.",
    "🧤 A one-handed save, and it is a good one.",
    "🧤 He beats it out with both fists.",
    "🧤 The effort from {p} is smothered on the line.",
    "🧤 An enormous save at a big moment for {opp}.",
    "🧤 {p} drills it low and hard, and it is stopped.",
    "🧤 Blocked and held. Nothing doing for {team}.",
    "🧤 The keeper does not move, and it hits him.",
    "🧤 Lucky or brilliant? Either way, {p} has not scored.",
    "🧤 Instinctive from the keeper — that was point blank.",
    "🧤 The keeper sticks out a boot and diverts {p}'s shot.",
    "🧤 Turned around the upright at full stretch.",
    "🧤 A dive to his right, and a strong hand on {p}'s shot.",
    "🧤 He holds it at the second time of asking.",
    "🧤 {opp} survive. What a save that is.",
    "🧤 The keeper gets both hands behind it.",
    "🧤 Saved! And {team} appeal for a corner they will not get.",
    "🧤 A wonderful reaction stop from close range.",
    "🧤 {p} could hit that ten times and score nine.",
    "🧤 Stopped on the line by a keeper going the right way.",
    "🧤 A vital intervention from the {opp} goalkeeper.",
    "🧤 Pushed out to safety, and the flag goes up anyway.",
    "🧤 {p}'s header is held at the second attempt.",
    "🧤 He claims it under pressure with bodies all around him.",
    "🧤 The keeper reads {p} like a book.",
    "🧤 A save, a scramble, and eventually {opp} clear it.",
    "🧤 Great feet from the keeper to block {p}.",
    "🧤 It is repelled, and the {opp} bench are up applauding.",
    "🧤 That should have been a goal. It is not.",
    "🧤 The dip beats him but the reach does not — saved.",
    "🧤 Right into the keeper's midriff from {p}.",
    "🧤 A save with the shoulder, and it loops behind.",
    "🧤 {p} rifles it and the keeper somehow gets there.",
    "🧤 Superb anticipation, and the shot is gathered.",
    "🧤 The keeper is beaten, but the ball is not past him.",
    "🧤 Denied at his near post; {p} wanted the far one.",
    "🧤 It squirms towards the line and the keeper falls on it.",
    "🧤 Big save. {team} keep coming, though.",
    "🧤 Well struck by {p}, better saved.",
    "🧤 That is a stop that changes the mood.",
    "🧤 The keeper gets a strong left hand on it.",
    "🧤 {p} is thwarted by a goalkeeper in inspired form.",
    "🧤 He races out and blocks with everything he has.",
    "🧤 A stunning save low to his left from {p}'s effort.",
    "🧤 Beaten away, and {opp} finally hack it clear.",
    "🧤 The keeper does brilliantly to adjust to the deflection.",
    "🧤 Held at chest height, and {p} groans.",
    "🧤 A crucial save for {opp}.",
    "🧤 That was destined for the corner until the glove arrived.",
    "🧤 {p} looks for the bottom corner and finds a goalkeeper.",
    "🧤 A block, a save, and a hurried clearance.",
    "🧤 The keeper is out quickly to narrow it, and it works.",
    "🧤 Well saved, and even {p} applauds it.",
    "🧤 Kept out by the keeper's knee, of all things.",
  ],
  // ── shot_missed (120) ───────────────────────────────────────────────────────
  shot_missed: [
    "{p} leans back and it sails into the crowd.",
    "Wide! {p} had to hit the target from there.",
    "That is a horrible miss from {p}.",
    "{p} snatches at it and the ball goes nowhere near.",
    "Over the top from {p}, and he knows it was a good chance.",
    "Dragged across the face of goal by {p}.",
    "{p} slices it wide of the far post.",
    "A yard the wrong side of the post from {p}.",
    "{p} gets it all wrong and scuffs it into the ground.",
    "Skewed off his shin — {p} is embarrassed.",
    "{p} takes an age and finally pokes it into the side netting.",
    "Into the side netting from {p}. It looked in from behind.",
    "{p} tries to be too clever and passes it wide.",
    "The header from {p} loops the wrong side of the post.",
    "{p} nods it over from six yards!",
    "Miles high! {p} will have nightmares about that one.",
    "{p} shanks it out for a throw.",
    "A tame effort from {p}, dribbling wide.",
    "He gets no purchase on it, and {p} watches it drift past.",
    "{p} pulls it wide with the goal begging.",
    "A dreadful connection, and the chance has gone.",
    "{p} goes for the far corner and misses the whole goal.",
    "Sliced. {p} puts his hands on his head.",
    "A glorious chance spurned by {p}.",
    "{p} takes one touch too many and the shot is rushed and wide.",
    "The ball flies over the bar and out of the ground, near enough.",
    "{p} scoops it high and handsome.",
    "Off balance, and {p} cannot keep it down.",
    "{p} strikes it well, but a yard wide.",
    "He looks up, picks his spot, and misses it entirely.",
    "{p} steers it the wrong side of the upright.",
    "A free header, and {p} puts it wide.",
    "Wasteful from {team}. {p} should have done far better.",
    "{p} lashes at it and the ball ends up in the stand.",
    "It comes off his standing foot, and {p} is furious.",
    "The volley from {p} is spectacular and completely wrong.",
    "{p} tries to place it and lacks the power.",
    "A weak effort trickles wide of the post.",
    "{p} blazes it into a wall of bodies and away.",
    "Just past the upright. {p} was inches from glory.",
    "{p} leaves it to a teammate, and neither of them shoots.",
    "Overhit, over the bar, over and done with.",
    "{p} goes for glory from thirty yards and it is never close.",
    "He rushes it. {p} had more time than he thought.",
    "A hurried finish from {p}, dragged wide.",
    "{p} cuts across the ball and it spins away.",
    "The chance is gone — {p} takes it on his wrong foot and misses.",
    "{p} skies it, and the groan says everything.",
    "Wide of the near post, and {opp} escape.",
    "{p} tries the chip and it lands on the roof of the net.",
    "That is going into orbit off {p}'s boot.",
    "A first-time hit from {p}, and it is wild.",
    "{p} stretches and can only steer it past the post.",
    "The ball loops off his knee and over.",
    "{p} misjudges the bounce and shoots into the ground.",
    "It is a bad miss, and {p} knows it before it lands.",
    "{p} whacks it wide from a lovely position.",
    "Everything was right except the finish from {p}.",
    "The defender does just enough, and {p}'s shot goes wide.",
    "{p} pushes it wide with only the keeper to beat.",
    "That has gone closer to the corner flag than the goal.",
    "{p} snatches at the half-chance and lifts it over.",
    "Nowhere near. {p} throws his head back.",
    "The finish lets him down; {p} put far too much on it.",
    "{p} thrashes at it and misses the target.",
    "A poor decision from {p}, and a worse shot.",
    "Off the outside of his boot, and wide.",
    "{p} shoots when the pass was on, and it flies over.",
    "A gilt-edged chance, and {p} has wasted it.",
    "{p} slips as he shoots and it goes into the crowd.",
    "The header is powerful; the direction is not.",
    "{p} sends it wide and the bench sink into their seats.",
    "Wildly over. {p} needs to calm himself down.",
    "{p} thumps it into the advertising boards.",
    "The keeper does not even have to move.",
    "{p} misses the target from twelve yards. Dreadful.",
    "It cannons off a defender and behind for nothing.",
    "{p} gets the connection wrong and it dribbles harmlessly wide.",
    "A cross or a shot? Either way, {p} sees it go out.",
    "{p} has the goal at his mercy and puts it in the stand.",
    "A shot with the outside of the foot, and it never bends back.",
    "{p} chops it wide when he had time to pick a corner.",
    "The chance disappears — {p} took far too long.",
    "Wide again. {team} are being wasteful here.",
    "{p} shoots first time and it is high and wide.",
    "The touch is good. The finish is not.",
    "{p} spoons it up and it drops behind the goal.",
    "A rasping effort from {p}, and it misses by a foot.",
    "That is the miss of the match so far from {p}.",
    "{p} tries to bend it and it stays stubbornly straight.",
    "The ball squirms off his laces and wide.",
    "{p} rifles it well over the crossbar.",
    "A glorious opportunity, and {p} does not hit the target.",
    "{p} goes for the near post and misses it.",
    "It drops just the wrong side of the post.",
    "{p} runs out of room and shoots into the side netting.",
    "The angle was tight, but {p} will still be annoyed.",
    "A rare miss from {p}, and it is a bad one.",
    "{p} tries to steer it and takes all the pace off it.",
    "That has flown well over. {p} mutters to himself.",
    "{p} strikes the ball and the pitch at the same time.",
    "A big chance for {team}, and it is wasted by {p}.",
    "{p} leans back too far and the ball follows him.",
    "The finish is hurried and it goes wide.",
    "{p} beats everyone, and then beats the goal too.",
    "The header from {p} drops onto the roof of the net.",
    "{p} is a whisker away from the far corner.",
    "A sight of goal, and {p} does not take it.",
    "{p} thrashes it into row Z.",
    "The shot is charged down and spins behind for nothing.",
    "{p} needed to be calmer there, and he was not.",
    "That has gone about ten yards wide.",
    "{p} miscues completely and it goes out for a throw.",
    "Everything but the finish from {p}.",
    "{p} gets it stuck under his feet and shoots into a body.",
    "Wide, and {opp} clear their heads.",
    "{p} pulls his shot and it never troubles the keeper.",
    "A big swing, and a big miss from {p}.",
    "The ball flies wide and {p} appeals for a corner in hope.",
    "{p} could not have missed by very much more.",
  ],
  // ── goal (120) ──────────────────────────────────────────────────────────────
  goal: [
    "⚽ THERE IT IS! {p} smashes it in for {team}!",
    "⚽ {p} sweeps it home — a beautiful finish!",
    "⚽ GOAL! Bottom corner, and {p} knew all along!",
    "⚽ He has scored! {p} slides it under the keeper!",
    "⚽ Emphatic! {p} thumps it into the roof of the net!",
    "⚽ {p} side-foots it in with the outside of his boot!",
    "⚽ GOAL FOR {team}! {p} is the man!",
    "⚽ Coolness personified — {p} rolls it in!",
    "⚽ {p} heads it in at the far post!",
    "⚽ A thunderbolt from {p}!",
    "⚽ {p} rounds the keeper and taps it home!",
    "⚽ Buried into the far corner by {p}!",
    "⚽ {p} gets the faintest of touches, and it is in!",
    "⚽ A poacher's finish! {p} was in the right place!",
    "⚽ {p} lashes it past the keeper — no chance!",
    "⚽ It is in! {p} turns and runs to the corner!",
    "⚽ A first-time strike from {p} and the net bulges!",
    "⚽ {p} dinks it over the keeper! Audacious!",
    "⚽ Bang! {p} finds the top corner!",
    "⚽ {team} score, and {p} is mobbed!",
    "⚽ He does not miss those — {p} makes it count!",
    "⚽ {p} bundles it over the line!",
    "⚽ A scruffy one, but they all count for {team}!",
    "⚽ {p} nods it down and in!",
    "⚽ Left foot, laces, in — {p}!",
    "⚽ {p} sends the keeper the wrong way and strokes it in!",
    "⚽ The net ripples. {p} has done it!",
    "⚽ Off the underside of the bar and in! {p} scores!",
    "⚽ {p} smashes it in off the far post!",
    "⚽ A header from {p}, and it is a good one!",
    "⚽ {p} arrives late and side-foots it home!",
    "⚽ Simple as that. {p} taps in!",
    "⚽ {p} rifles it in from the edge of the box!",
    "⚽ The finish is ice cold from {p}!",
    "⚽ {p} slots it through the keeper's legs!",
    "⚽ He picks his spot, and {p} finds it!",
    "⚽ {p} hooks it in on the turn!",
    "⚽ What a hit! {p} from distance!",
    "⚽ {p} scores with his weaker foot!",
    "⚽ It creeps in at the near post — {p}!",
    "⚽ {p} volleys it home on the run!",
    "⚽ A wonderful team goal, finished by {p}!",
    "⚽ {p} pounces on the rebound and scores!",
    "⚽ Deflected in off {p}, and he will take it!",
    "⚽ The keeper gets a hand to it and {p} still scores!",
    "⚽ {p} steers it into the corner with the side of his foot!",
    "⚽ Absolutely hammered in by {p}!",
    "⚽ {p} flicks it in at the near post!",
    "⚽ Off the post and in! {p} has scored!",
    "⚽ {p} shrugs off his man and finishes!",
    "⚽ There is the reward for {team}, and it is {p}!",
    "⚽ A goal on the break, finished superbly by {p}!",
    "⚽ {p} chests it down and volleys it in!",
    "⚽ Unstoppable. {p} scores for {team}!",
    "⚽ A header down and into the corner from {p}!",
    "⚽ {p} scuffs it and it still goes in!",
    "⚽ Right through the middle — {p} finishes it off!",
    "⚽ {p} gets in front of his man and glances it in!",
    "⚽ Take a bow, {p}!",
    "⚽ {p} makes it look easy!",
    "⚽ The finish matches the build-up. {p} scores!",
    "⚽ A daisy-cutter from {p}, and it is in!",
    "⚽ {p} drills it low across the keeper!",
    "⚽ A brilliant individual goal from {p}!",
    "⚽ {p} does not even have to break stride!",
    "⚽ Slammed home by {p}!",
    "⚽ {p} is there at the back post to finish!",
    "⚽ It nestles in the corner. {p} has scored!",
    "⚽ {p} finishes first time and the crowd erupt!",
    "⚽ A goalkeeper's nightmare, and {p} takes full advantage!",
    "⚽ {p} lifts it over the diving keeper!",
    "⚽ Bundled in from close range by {p}!",
    "⚽ {p} curls it beyond the keeper's reach!",
    "⚽ Precision from {p} — right into the bottom corner!",
    "⚽ That is out of the top drawer from {p}!",
    "⚽ {p} strikes it early and it flies in!",
    "⚽ A composed finish from {p} for {team}!",
    "⚽ {p} makes it count on the counter!",
    "⚽ Hit with venom by {p}, and it is in!",
    "⚽ A goal to savour, scored by {p}!",
    "⚽ {p} nicks in ahead of the keeper and pokes it home!",
    "⚽ The header is powerful, and {p} has scored!",
    "⚽ {p} taps in from a yard out!",
    "⚽ A goal of real quality from {p}!",
    "⚽ {p} beats him at the near post!",
    "⚽ The ball is in the net and {team} are away celebrating!",
    "⚽ {p} finishes with the outside of his foot!",
    "⚽ Straight down the middle as the keeper dives — {p}!",
    "⚽ He waits, and waits, and {p} slides it in!",
    "⚽ Off the bar, down, and over the line! {p} scores!",
    "⚽ {p} smashes it through a crowd of bodies and in!",
    "⚽ A quite wonderful strike from {p}!",
    "⚽ {p} sticks out a leg and diverts it in!",
    "⚽ It flies in off the underside of the crossbar!",
    "⚽ {p} times his run and heads it home!",
    "⚽ Cool head, clean strike, goal for {team}!",
    "⚽ {p} punishes them!",
    "⚽ The goal his play deserved — {p} scores!",
    "⚽ {p} lifts the roof with that finish!",
    "⚽ A quite superb finish from {p}!",
    "⚽ Low, hard, and in. {p}!",
    "⚽ {p} lets it run across him and passes it into the net!",
    "⚽ Nothing the keeper could do about that from {p}!",
    "⚽ {p} hammers it in at the second attempt!",
    "⚽ From an impossible angle, {p} finds a way!",
    "⚽ {p} rises above them all and heads it in!",
    "⚽ Clipped over the keeper by {p}!",
    "⚽ That is a striker's finish from {p}!",
    "⚽ {p} does the hard bit and the easy bit!",
    "⚽ Buried! {p} does not celebrate for long!",
    "⚽ {p} spins and finishes in one movement!",
    "⚽ Goal! {team} have their reward, and {p} has his!",
    "⚽ A deflection wrong-foots the keeper — {p} scores!",
    "⚽ {p} squeezes it in at the near post!",
    "⚽ Brilliant! {p} finishes from a tight angle!",
    "⚽ {p} hits it on the half-volley and it screams in!",
    "⚽ In off the far upright from {p}!",
    "⚽ {p} sweeps home the cutback!",
    "⚽ Clinical, ruthless, and {p} has scored for {team}!",
  ],
  // ── foul (80) ───────────────────────────────────────────────────────────────
  foul: [
    "A clumsy challenge from {p} {zone}, and the whistle goes.",
    "Late from {p} {zone}. The referee has seen it.",
    "Off the ball, and {p} is the guilty man.",
    "{p} tugs the shirt {zone} and gets caught.",
    "That is a foul all day long from {p}.",
    "{p} slides in and gets nothing but ankle {zone}.",
    "A trip {zone}, and {opp} have a free kick.",
    "{p} leans in with the arm and is penalised {zone}.",
    "The referee has no choice — {p} took the man {zone}.",
    "{p} misses the ball and takes everything else {zone}.",
    "A shove in the back from {p} {zone}.",
    "{p} arrives far too late {zone}.",
    "Frustration from {p} {zone}, and it costs a free kick.",
    "A tactical foul from {p} to stop the break {zone}.",
    "{p} sticks out a leg and the man goes over {zone}.",
    "He is caught by {p} {zone}, and stays down for a moment.",
    "{p} argues, but he knows he caught him {zone}.",
    "A clip of the heels from {p} {zone}.",
    "That is careless from {p} {zone}. Free kick to {opp}.",
    "{p} bundles him over {zone}.",
    "The elbow is high from {p} {zone}, and the referee blows.",
    "{p} wrestles him to the ground at the set piece.",
    "The referee spots the pull from {p} {zone}.",
    "{p} makes a real mess of the challenge {zone}.",
    "He goes to ground and {p} takes him out {zone}.",
    "A silly one from {p} {zone}, with no need for it.",
    "{p} clatters into the back of him {zone}.",
    "Cynical stuff from {p} — the break is snuffed out {zone}.",
    "{p} cannot get out of the way in time {zone}.",
    "Two-footed? No. But it is a foul from {p} {zone}.",
    "{p} concedes it far too cheaply {zone}.",
    "A body check from {p} {zone}, and the free kick is given.",
    "{p} rakes down his shin {zone}, and away goes the whistle.",
    "The referee gives it against {p} {zone}, to his obvious disgust.",
    "{p} is done for the shirt-pull {zone}.",
    "A poor challenge from {p} {zone}, and {opp} have it back.",
    "{p} jumps into him {zone}.",
    "He is bundled off the ball, and {p} is penalised {zone}.",
    "{p} goes in hard {zone} and gets the man.",
    "The forward makes the most of it, but {p} did catch him {zone}.",
    "{p} steps across him {zone} — obstruction, says the referee.",
    "A trailing leg from {p} {zone}.",
    "Free kick to {opp}. {p} was clumsy {zone}.",
    "{p} rushes out and takes the man down {zone}.",
    "It is a soft one, but {p} will not complain too loudly {zone}.",
    "{p} hauls him back by the arm {zone}.",
    "The referee blows for the push by {p} {zone}.",
    "{p} lunges and misses everything but the shin {zone}.",
    "That is a needless foul by {p} {zone}.",
    "{p} catches him with the follow-through {zone}.",
    "A dangerous challenge from {p} {zone} — the bench are furious.",
    "{p} was second favourite and made the tackle anyway {zone}.",
    "The whistle goes. {p} holds his hands up {zone}.",
    "A stray boot from {p} {zone}.",
    "{p} gives away a free kick in a poor area {zone}.",
    "He nudges the runner, and {p} is penalised {zone}.",
    "The tackle from {p} is mistimed by a fraction {zone}.",
    "{p} takes his man rather than the ball {zone}.",
    "A block by {p} {zone}, and the referee does not like it.",
    "{p} barges into him {zone} and the whistle sounds.",
    "There is contact, and {p} is the one who made it {zone}.",
    "{p} kicks through the ball and into the man {zone}.",
    "Foul, and {p} disputes it {zone}. He will not win.",
    "A silly trip from {p} {zone}.",
    "{p} pulls him down as the counter starts {zone}.",
    "The referee is right on top of it — foul by {p} {zone}.",
    "{p} slides straight through him {zone}.",
    "It is a stonewall foul from {p} {zone}.",
    "{p} gives {opp} a free kick with a rash challenge {zone}.",
    "He tries to nick it and takes the leg instead — {p} {zone}.",
    "{p} climbs all over him at the back post.",
    "The referee sees the hold from {p} {zone}.",
    "{p} loses his footing and slides into him {zone}.",
    "A frustrated foul from {p} {zone}.",
    "{p} clips his ankles as he goes past {zone}.",
    "The challenge from {p} is late and clumsy {zone}.",
    "{p} is beaten, and so he fouls him {zone}.",
    "An unnecessary shove from {p} {zone}, and {opp} have the ball.",
    "{p} plants a hand on his shoulder {zone}, and down he goes.",
  ],
  // ── corner (80) ─────────────────────────────────────────────────────────────
  corner: [
    "It is a corner to {team}, and {p} stands over it.",
    "{p} shapes to whip it in for {team}.",
    "Everyone forward for {team} as {p} prepares the delivery.",
    "The corner is {team}'s. {p} takes a long run-up.",
    "{p} swings his arm — this one is going to the back post.",
    "Deflected behind. {team} have a corner and {p} will take it.",
    "{p} sets it down and waits for the referee's nod.",
    "The keeper barks his orders as {p} lines up the corner.",
    "A corner for {team}, and the centre-halves lumber forward.",
    "{p} looks to pick out a runner at the near post.",
    "In-swinger or out-swinger? {p} keeps them guessing.",
    "{team} have a corner. A chance to really hurt them.",
    "{p} beckons a teammate over — something is planned here.",
    "The ball goes on the spot and {p} steps back.",
    "Another corner for {team}. The pressure is building.",
    "{p} rolls his shoulders and eyes up the six-yard box.",
    "A short one is on, but {p} decides against it.",
    "Corner {team}. {p} will be aiming for the crowd of bodies.",
    "{p} takes it right-footed from the left.",
    "The box is packed and {p} has to find a gap.",
    "{team} win a corner, and a nervous buzz goes round the ground.",
    "{p} places the ball carefully inside the arc.",
    "The delivery is coming; {team} are loading up.",
    "Everyone up for this one as {p} prepares to swing it in.",
    "{p} waits for the big men to take up their positions.",
    "A corner, and {team} have found some rhythm.",
    "{p} has a fine delivery on him — this is dangerous.",
    "The set piece is {team}'s, and {p} has the ball.",
    "{p} signals for the near post.",
    "It is worked out for a corner. {p} to deliver it.",
    "{team} will fancy this. {p} is over the ball.",
    "{p} takes his time; the referee is watching the clock.",
    "The corner comes to {p}, and the box fills up.",
    "{p} is going to go deep with this one.",
    "A dangerous moment for {opp} as {p} runs up.",
    "{p} takes it quickly to catch them napping.",
    "The defenders jostle as {p} prepares.",
    "Corner to {team}, and the keeper comes off his line early.",
    "{p} raises a hand and the runs begin.",
    "The ball is placed. {p} steps away and looks up.",
    "A big moment — {team} have a corner and bodies in the box.",
    "{p} will curl this one towards the penalty spot.",
    "A corner won off the last defender; {p} to take it.",
    "{p} tucks his shirt in and gets on with it.",
    "The near-post flick is on, and {p} knows it.",
    "{team} keep coming, and here is another corner.",
    "{p} looks to whip it in low and hard.",
    "A short corner routine is set up — {p} looks for the pass.",
    "The referee checks for shirt-pulling before {p} takes it.",
    "{p} adjusts the ball twice. He is fussy about this.",
    "{p} takes the corner from the right-hand side.",
    "A chance for {team} to load the box, and {p} delivers.",
    "The corner count is climbing for {team}. {p} is over another.",
    "{p} thumps it in with real pace.",
    "A set piece in a good spot, and {p} takes charge.",
    "The crowd rises as {p} steps up to take it.",
    "{p} points to the far post before he strikes it.",
    "Corner for {team}, and the tall lads have arrived.",
    "{p} waves the ballboy away and takes it.",
    "Time for something clever from {p} here.",
    "{p} sends it towards the penalty spot as they attack it.",
    "The ball is on the quadrant, and {p} is ready.",
    "A corner for {team}. Bodies pour into the box.",
    "{p} takes a breath before delivering it.",
    "A moment of danger for {opp} — {p} to swing it in.",
    "{p} eyes up the near post and steps back.",
    "This set piece could be decisive. {p} to take it.",
    "Corner. {team} have their tails right up.",
    "{p} shapes to cross, and the marking gets tighter.",
    "It goes behind off a defender. Corner {team}, {p} over it.",
    "{p} is the designated taker, and he takes his time.",
    "The corner is floated in by {p}.",
    "{p} calls for the ball and jogs across.",
    "The delivery from {p} has to beat the first man.",
    "{team} have another set piece, and {p} is the man.",
    "{p} pulls his socks up and gets on with it.",
    "Corner to {team} — {opp} look nervous about this.",
    "{p} readies himself, and the box is a wrestling match.",
    "The ball is out for a corner and {p} is already jogging over.",
    "A corner, and {team} send the centre-back forward for it.",
  ],
  // ── free_kick (60) ──────────────────────────────────────────────────────────
  free_kick: [
    "{p} places the ball and steps back for {team}.",
    "The referee marks out his line; {p} waits.",
    "{p} will shoot from here. He always does.",
    "A free kick in a lovely spot for {team} — {p} to take it.",
    "{p} paces out his run-up carefully.",
    "The wall shuffles across, and {p} is not happy about it.",
    "{team} have a set piece worth having; {p} stands over it.",
    "{p} has two men standing over it — one of them is a decoy.",
    "This is well within range for {p}.",
    "The keeper organises his wall as {p} waits.",
    "{p} rubs the ball on his shirt and sets it down.",
    "A dangerous free kick, and {p} fancies the top corner.",
    "{team} will load the box for this one; {p} to deliver.",
    "{p} looks up, then down, then up again.",
    "The referee steps the wall back ten yards for {p}.",
    "{p} has scored these before. {opp} know it.",
    "A free kick near the halfway line — {p} will send it long.",
    "{p} takes it quickly and catches them cold.",
    "The whistle goes and {p} is over the ball in a flash.",
    "A dead ball for {team}, and everything stops.",
    "{p} bends down to fix the ball just so.",
    "The wall jumps early, and {p} waits again.",
    "{p} looks for the run at the far post.",
    "A promising position for {team}. {p} has the ball.",
    "{p} will try to bend this around the wall.",
    "The referee is unhappy with the wall; {p} waits patiently.",
    "{p} asks for the ball and waves the crowd up.",
    "A set piece from wide — {p} to whip it in for {team}.",
    "{p} has a long stride and a big left foot.",
    "The stadium hushes as {p} prepares.",
    "{p} points to the near post before he takes it.",
    "A free kick that {team} really have to make count.",
    "{p} runs a hand through his hair and steps back.",
    "A chance to test the keeper, and {p} will take it.",
    "{p} shouts his instructions before he strikes it.",
    "The box is crowded; {p} needs a good delivery here.",
    "{p} has been waiting all match for one of these.",
    "A free kick right on the corner of the box for {team}.",
    "{p} looks like he is going over the wall with this.",
    "The wall links arms as {p} settles the ball.",
    "{p} could cross it or shoot it. Nobody is quite sure.",
    "A foul and a fine position — {p} takes charge for {team}.",
    "{p} paws at the turf and sets himself.",
    "The free kick is deep, and {p} will float it in.",
    "{p} waits for his big centre-half to arrive.",
    "This is his sort of range. {p} eyes it up.",
    "A dead-ball opportunity for {team}, and {p} is over it.",
    "{p} sizes up the wall and the keeper's position.",
    "The referee blows to signal, and {p} moves in.",
    "{p} runs over the ball and leaves it for nobody.",
    "A free kick within shooting distance. {p} likes this.",
    "{p} sets it, steps back, and stares at the keeper.",
    "The keeper points and shouts; {p} ignores him entirely.",
    "{p} has a decision to make here for {team}.",
    "A booking, and a free kick in a dangerous spot; {p} steps up.",
    "{p} takes the responsibility for {team}.",
    "The wall is five strong, and {p} still fancies it.",
    "{p} rolls it a yard forward and nobody complains.",
    "A set piece in the golden zone, and {p} has it.",
    "{p} waits for the whistle with his hands on his hips.",
  ],
  // ── fatigue (60) ────────────────────────────────────────────────────────────
  fatigue: [
    "{p} is running on fumes now.",
    "The legs have gone for {p}.",
    "{p} pulls up short of the run — there is nothing left.",
    "A bent back and hands on knees from {p} {zone}.",
    "{p} waves a teammate through; he cannot go again.",
    "That is the ninth sprint in five minutes, and {p} is done.",
    "{p} is a yard off it now, and it shows.",
    "The gaffer is watching {p} closely — he is out on his feet.",
    "{p} takes a moment at the throw-in to catch his breath.",
    "He is jogging where he used to sprint. {p} is tiring badly.",
    "{p} looks over to the bench, blowing hard.",
    "Cramp is threatening for {p}.",
    "{p} shakes out his legs and grimaces.",
    "The pace has dropped out of {p}'s game.",
    "{p} cannot make the recovery run in time.",
    "A tired lunge from {p} — that is fatigue talking.",
    "{p} has covered a lot of ground and he is feeling every yard.",
    "Heavy legs for {p} {zone}.",
    "{p} stands with his hands on his head, drained.",
    "He is second to everything now. {p} is spent.",
    "{p} asks for water at the first opportunity.",
    "The socks come down for {p} — never a good sign.",
    "{p} is puffing hard and the game is passing him by.",
    "That burst has taken everything {p} had left.",
    "{p} slows to a walk and takes a deep breath.",
    "The tank is empty for {p}.",
    "{p} tries to sprint and the body says no.",
    "Weary from {p} — he mistimes it because he is tired.",
    "{p} stretches out a hamstring and carries on.",
    "The tempo is killing {p} now.",
    "{p} has stopped making the runs into the box.",
    "He looks exhausted. {p} needs the whistle.",
    "{p} labours back into position.",
    "That is not the {p} we saw in the first half.",
    "Fatigue is creeping into everything {p} does.",
    "{p} lets it go rather than chase it — that says a lot.",
    "The engine is running down for {p}.",
    "{p} bends double at the break in play.",
    "Every stride looks like hard work for {p} now.",
    "{p} has given everything, and it is starting to tell.",
    "He drags himself back — {p} is shattered.",
    "The last few minutes have taken it out of {p}.",
    "{p} pats his chest; he is struggling for breath.",
    "A tired pass from {p}, and it is the legs, not the technique.",
    "{p} loses his man because he simply cannot follow him.",
    "The bench are getting somebody ready; {p} looks finished.",
    "There is nothing in reserve. {p} is done.",
    "{p} jogs, walks, and then stops altogether.",
    "The legs are heavy, and the mind follows, for {p}.",
    "{p} appeals for a foul mainly to get a breather.",
    "That is a tired player. {p} needs help.",
    "{p} lets the ball run out rather than chase it.",
    "He is blowing hard, is {p}.",
    "{p} has been at full tilt for an hour and it shows.",
    "The intensity has dropped right off for {p}.",
    "{p} winces as he sets off again.",
    "There is no burst left in {p} at all.",
    "{p} takes a long look towards the bench.",
    "Exhaustion is written all over {p}.",
  ],
  // ── sub (50) ────────────────────────────────────────────────────────────────
  sub: [
    "🔄 {name} is on for {team}; {off} is done for the day.",
    "🔄 A tactical switch by {team} — {off} off, {name} on.",
    "🔄 {name} sprints on. {off} trudges off.",
    "🔄 {team} freshen it up: {name} for {off}.",
    "🔄 The gaffer has seen enough; {name} replaces {off}.",
    "🔄 {name} bounces on the spot, and on he comes for {off}.",
    "🔄 A change of shape for {team} as {name} replaces {off}.",
    "🔄 {off} is furious to be coming off. {name} takes his place.",
    "🔄 New legs for {team}: {name} on, {off} off.",
    "🔄 {name} gets his chance; {off} makes way.",
    "🔄 {team} use another of their changes — {name} for {off}.",
    "🔄 A big call from the bench: {off} comes off for {name}.",
    "🔄 {off} applauds the supporters on his way past {name}.",
    "🔄 {name} is thrown on as {team} look for something different.",
    "🔄 The board is up. It is {off}, and {name} is ready.",
    "🔄 {name} takes the field for {team}, replacing {off}.",
    "🔄 A like-for-like swap: {name} in for {off}.",
    "🔄 {team} go again — {name} on for a weary {off}.",
    "🔄 {off} shakes a few hands, and {name} joins the fray.",
    "🔄 {name} has been warming up a while; now he comes on for {off}.",
    "🔄 Fresh energy for {team} with {name} replacing {off}.",
    "🔄 {off} makes a slow walk off; {name} takes over.",
    "🔄 The change is made. {name} for {off}, {team}.",
    "🔄 {name} is on, and he has a point to prove for {team}.",
    "🔄 {team} reshuffle: {off} withdrawn, {name} introduced.",
    "🔄 {off} has run himself into the ground. {name} takes the shirt.",
    "🔄 {name} comes on with instructions ringing in his ears.",
    "🔄 A change up front for {team}: {name} in for {off}.",
    "🔄 {off} gets a warm hand as {name} enters the fray.",
    "🔄 {team} turn to the bench. {name} replaces {off}.",
    "🔄 {name} is on to see this one out for {team}.",
    "🔄 The number goes up for {off}; {name} is ready to go.",
    "🔄 {name} enters the game as {off} departs.",
    "🔄 A change with intent — {name} on, {off} off.",
    "🔄 {off} has had a difficult afternoon. {name} takes over.",
    "🔄 {name} is introduced to add some pace for {team}.",
    "🔄 {off} is replaced by {name} as {team} tinker with it.",
    "🔄 {name} on, {off} off. {team} are changing this.",
    "🔄 The bench comes into play: {name} for {off}.",
    "🔄 {name} pulls his socks up and comes on for {off}.",
    "🔄 {team} make the switch — {off} is spent, {name} is fresh.",
    "🔄 {off} looks bitterly disappointed as {name} takes his place.",
    "🔄 That is a big change from {team}: {name} on for {off}.",
    "🔄 {name} joins the action; {off} takes a seat.",
    "🔄 A cautious change from {team}; {name} replaces {off}.",
    "🔄 {name} gets a rousing welcome as he replaces {off}.",
    "🔄 The final roll of the dice: {name} on, {off} off.",
    "🔄 {name} strips off the tracksuit and comes on for {off}.",
    "🔄 {off} is given a rest, and {name} is asked to deliver.",
    "🔄 {team} send {name} on with the crowd right behind him.",
  ],
  // ── yellow_card (40) ────────────────────────────────────────────────────────
  yellow_card: [
    "🟨 Into the book goes {p}. That was coming.",
    "🟨 {p} is booked for a cynical trip.",
    "🟨 A caution for {p} — he will have to be careful now.",
    "🟨 The referee reaches for his pocket, and {p} knows why.",
    "🟨 {p} protests, but the yellow card stays out.",
    "🟨 Booked for dissent. {p} said far too much.",
    "🟨 {p} is cautioned for a tactical foul on the break.",
    "🟨 A yellow for {p}, and {team} may have to think about him.",
    "🟨 That is a booking, and {p} cannot argue with it.",
    "🟨 {p} goes in late and pays for it with a caution.",
    "🟨 The referee has a word and then produces the card for {p}.",
    "🟨 {p} is booked for kicking the ball away.",
    "🟨 A first booking for {p}, and it is a fair one.",
    "🟨 {p} takes one for the team, and takes the yellow.",
    "🟨 Cautioned. {p} was nowhere near the ball.",
    "🟨 The card comes out. {p} shakes his head at it.",
    "🟨 A yellow card for persistent fouling by {p}.",
    "🟨 {p} is booked for pulling the shirt.",
    "🟨 That is a needless booking for {p}.",
    "🟨 {p} is shown yellow, and the crowd let the referee know.",
    "🟨 A caution for {p} — the gaffer will not be pleased.",
    "🟨 {p} is booked, and now he is walking a tightrope.",
    "🟨 In the book for a challenge with the studs showing.",
    "🟨 {p} gets a yellow for that lunge.",
    "🟨 The referee is right on the spot. Booking for {p}.",
    "🟨 {p} appeals to his teammates. Nobody backs him up.",
    "🟨 A yellow card for time-wasting by {p}.",
    "🟨 {p} is cautioned for a shoulder charge that went too far.",
    "🟨 His name is taken; {p} must be careful from here.",
    "🟨 A booking, and a free kick in a dangerous spot as well.",
    "🟨 {p} clatters him, and the referee has no option.",
    "🟨 The yellow is shown, and {p} apologises to his opponent.",
    "🟨 {p} is booked for stopping a promising attack.",
    "🟨 The referee explains it; {p} nods and moves away.",
    "🟨 A caution for {p}, and {team} will be nervous now.",
    "🟨 A booking for the challenge, and another word after it.",
    "🟨 {p} is in the book after a moment of pure frustration.",
    "🟨 A yellow card. {p} was very nearly the last man.",
    "🟨 The referee has been patient with {p}. No longer.",
    "🟨 {p} is booked, and he was fortunate not to see worse.",
  ],
  // ── injury (40) ─────────────────────────────────────────────────────────────
  injury: [
    "🚑 {p} is in trouble here — that looks like a hamstring.",
    "🚑 The physio sprints on to {p}, and it does not look good.",
    "🚑 {p} clutches his thigh and waves towards the bench.",
    "🚑 Concern for {team} as {p} lies flat on the turf.",
    "🚑 {p} rolls over in pain, and play is stopped.",
    "🚑 A twisted knee for {p}. He cannot continue.",
    "🚑 That is a nasty one. {p} is being helped off.",
    "🚑 {p} tries to stand and immediately sits back down.",
    "🚑 An awkward landing, and {p} is hurt.",
    "🚑 {p} pulls up sharply — no contact at all.",
    "🚑 A blow for {team}: {p} cannot carry on.",
    "🚑 {p} is holding his calf and shaking his head.",
    "🚑 The medical staff surround {p}.",
    "🚑 {p} takes a heavy knock and stays down.",
    "🚑 He is limping badly. {p} is finished for the day.",
    "🚑 A worrying moment for {team} — {p} is down.",
    "🚑 {p} signals straight away; he knows it is serious.",
    "🚑 That is the end of {p}'s afternoon.",
    "🚑 {p} punches the ground in frustration.",
    "🚑 Ice and a bandage for {p}, and then the walk off.",
    "🚑 {p} came down on his shoulder and it looks painful.",
    "🚑 The gaffer is already turning to the bench about {p}.",
    "🚑 An innocuous moment, and {p} is in a heap.",
    "🚑 {p} felt something go, and down he goes.",
    "🚑 A cut above the eye for {p}, and he needs treatment.",
    "🚑 {p} hobbles to the touchline with an arm around a shoulder.",
    "🚑 A real setback for {team} — {p} is out of this one.",
    "🚑 {p} tests it, tries a jog, and gives up on it.",
    "🚑 The whole ground goes quiet for {p}.",
    "🚑 {p} holds his groin and calls for help.",
    "🚑 An ankle rolled, and {p} cannot put weight on it.",
    "🚑 {p} is helped up but cannot walk it off.",
    "🚑 A collision, and it is {p} who comes off worst.",
    "🚑 {p} sits up, looks at the bench, and shakes his head.",
    "🚑 There is no way {p} can continue for {team}.",
    "🚑 {p} grimaces as he stretches out the leg.",
    "🚑 A muscle problem for {p}, and it ends his match.",
    "🚑 The applause follows {p} as he limps away.",
    "🚑 {p} is done. {team} have a decision to make now.",
  ],
  // ── woodwork (30) ───────────────────────────────────────────────────────────
  woodwork: [
    "🪵 THE BAR! {p} is denied by the woodwork!",
    "🪵 It smacks the post and stays out! Cruel on {p}!",
    "🪵 Off the inside of the post and away to safety!",
    "🪵 {p} hits the frame of the goal and holds his head!",
    "🪵 The upright saves {opp}! What a strike from {p}!",
    "🪵 Crashed against the crossbar by {p}!",
    "🪵 The post is rattling, and so are {opp}!",
    "🪵 So close! {p}'s effort clips the top of the bar!",
    "🪵 Off the woodwork and back into play — chaos!",
    "🪵 {p} beats the keeper, and the post beats him!",
    "🪵 Onto the bar and over! Inches from a goal!",
    "🪵 It hits one post and rolls across the face of goal!",
    "🪵 {p} strikes the base of the post!",
    "🪵 What a moment — the bar comes to {opp}'s rescue!",
    "🪵 {p} will not get a better chance, and the frame denies him!",
    "🪵 A cannon of a shot, and the crossbar shakes!",
    "🪵 Off the post, off the keeper, and clear!",
    "🪵 The woodwork is doing the defending for {opp}!",
    "🪵 {p} cannot believe it — that was in all the way.",
    "🪵 Bar! And the rebound is hacked away!",
    "🪵 The far post comes to the rescue for {opp}!",
    "🪵 {p} thunders it against the bar and it flies clear!",
    "🪵 An inch either side and that is a goal for {team}!",
    "🪵 It clatters the post with the keeper beaten!",
    "🪵 The ball ricochets off the frame and out of play!",
    "🪵 {p} curls it onto the outside of the post!",
    "🪵 Off the bar, down, and out — no goal!",
    "🪵 The woodwork saves {opp} again! {p} is beside himself!",
    "🪵 A rasping drive from {p} rebounds off the upright!",
  ],
  // ── penalty (20) ────────────────────────────────────────────────────────────
  penalty: [
    "⚠️ It is a spot kick for {team}! {p} places the ball…",
    "⚠️ Penalty! {opp} are furious, but the referee is certain.",
    "⚠️ {p} takes the ball, and nobody argues with him.",
    "⚠️ The referee points to the spot — a huge moment for {team}.",
    "⚠️ {p} steps up with the whole ground watching him.",
    "⚠️ A penalty to {team}, and {p} has the responsibility.",
    "⚠️ The keeper dances on his line as {p} sets the ball down.",
    "⚠️ {p} wipes his brow and steps back for the penalty.",
    "⚠️ Given! A foul in the box, and {team} have a penalty.",
    "⚠️ {p} will take it. He has been waiting for this.",
    "⚠️ The referee waves the protests away — penalty for {team}.",
    "⚠️ {p} looks at the keeper, then the ball, then the keeper again.",
    "⚠️ It is twelve yards, and it is {p}'s to take.",
    "⚠️ A cool head is needed here from {p}.",
    "⚠️ Spot kick, {team}. The stadium holds its breath.",
    "⚠️ {p} grabs the ball off a teammate. He wants this one.",
    "⚠️ Penalty given, and {opp} surround the referee in vain.",
    "⚠️ {p} takes a long, slow walk to the spot.",
    "⚠️ The keeper tries every trick he knows on {p}.",
    "⚠️ A penalty for {team}, and everything rests on {p}.",
  ],
  // ── penalty_missed (20) ─────────────────────────────────────────────────────
  penalty_missed: [
    "❌ He has missed it! {p} puts the penalty wide!",
    "❌ Saved! The keeper reads {p} all the way!",
    "❌ Off the post! {p} has spurned it!",
    "❌ {p} slips as he strikes it, and it is dreadful!",
    "❌ Over the bar! {p} cannot bear to look!",
    "❌ The keeper stands tall and blocks {p} with his legs!",
    "❌ {p} tries the cheeky finish and it goes horribly wrong!",
    "❌ Onto the crossbar and away! Agony for {p}!",
    "❌ Saved low to his left! What a moment for {opp}!",
    "❌ {p} scuffs it and the keeper gathers it easily!",
    "❌ A wretched penalty from {p}, wide of the near post.",
    "❌ It is kept out! {p} sinks to his knees!",
    "❌ {p} goes for the corner and misses the target completely!",
    "❌ The keeper guesses right, and {team} have thrown one away!",
    "❌ {p} hits it far too close to the keeper!",
    "❌ Missed! A hush, and then a roar from the {opp} supporters!",
    "❌ {p} sends it into the crowd behind the goal!",
    "❌ The save is made, and the rebound is scrambled away!",
    "❌ That is a terrible penalty, and {p} knows it!",
    "❌ {p} will be replaying that one for a long, long time.",
  ],
  // ── red_card (20) ───────────────────────────────────────────────────────────
  red_card: [
    "🟥 He is off! {p} leaves {team} with ten men.",
    "🟥 The referee sends {p} down the tunnel!",
    "🟥 A dismissal for {p} — {team} are in serious trouble now.",
    "🟥 {p} is shown the red card, and the game changes.",
    "🟥 Off he goes. {p} cannot complain about that one.",
    "🟥 {team} lose {p}, and they must reorganise quickly.",
    "🟥 {p} is dismissed! The bench are up in arms!",
    "🟥 The long walk for {p}, and {team} have a mountain to climb.",
    "🟥 That is the end of {p}'s afternoon — sent off.",
    "🟥 {p} sees red, and {team} are a man down.",
    "🟥 The card is out, and {p} is on his way.",
    "🟥 A red for {p}! He argues, but he is going.",
    "🟥 {p} kicks a water bottle over as he goes.",
    "🟥 The referee is decisive: {p} is off.",
    "🟥 {team} are down to ten. {p} has let them down badly.",
    "🟥 {p} is sent from the pitch, and the gaffer is fuming.",
    "🟥 It is red for {p}, and the shape has to change.",
    "🟥 Dismissed! {p} tugs at his shirt as he trudges away.",
    "🟥 {p} is off, and {team} will have to dig very deep.",
    "🟥 No arguments about that one. {p} has to go.",
  ],
  // ── kickoff (20) ────────────────────────────────────────────────────────────
  kickoff: [
    "The whistle goes, and we are off.",
    "It begins.",
    "The ball is rolling.",
    "The referee blows, and battle commences.",
    "Here we go — the game is on.",
    "The first whistle sounds and the crowd rises.",
    "We are up and running.",
    "Kick-off. The tension is here already.",
    "And they are away.",
    "The opening whistle, and the noise goes up.",
    "It is under way at last.",
    "The ball is nudged forward and the match begins.",
    "Right, then. Here we go.",
    "The referee gets it started, and the crowd find their voice.",
    "A big afternoon begins.",
    "Both sides ready, and we are off.",
    "The whistle. The roar. The game.",
    "That is the signal — the match is live.",
    "We are away, and the first ball goes long.",
  ],
};
