// Match-commentary authoring pack 1. One author owns this file.
// Keys are match event types; use {p} {team} {opp} {zone} {off} {name} placeholders.
import type { CommentaryBank } from './extra.js';
export const CM_EXTRA_1: CommentaryBank = {
  loose_ball: [
    // ── ricochets & deflections ──
    'It cannons off a shin and spins away {zone}.',
    'Deflected, and now nobody knows where it is {zone}.',
    'A ricochet {zone} sends it looping over everyone.',
    'Off the knee of {p} and away {zone}.',
    'It rattles between three pairs of legs {zone}.',
    'The ball pings off a defender’s backside and dribbles {zone}.',
    'A wicked deflection takes it away from {p}.',
    'It clips a heel and skews off {zone}.',
    'Pinball {zone} — it comes off two players and sits up.',
    'Bounces off {p} and rolls loose {zone}.',
    'It hits the referee! Play carries on, ball loose {zone}.',
    'A boot, a chest, a thigh — and the ball ends up {zone} with nobody.',
    'The clearance smacks the man charging it down and loops {zone}.',
    'Off {p}, off his marker, and it breaks {zone}.',
    'Everything is being deflected {zone} at the moment.',
    // ── heavy touches ──
    'Too heavy from {p} and it runs away from him {zone}.',
    '{p} takes one touch too many and it’s gone {zone}.',
    'The touch is a yard long and {p} has lost it {zone}.',
    'He tried to knock it past his man — too far, {p}.',
    '{p} lets it get under his feet {zone}.',
    'A shocker of a first touch from {p}.',
    'It bounces off {p}’s laces and away {zone}.',
    '{p} reaches for it and can only shovel it {zone}.',
    'Nothing under control there from {p}.',
    'The ball got big on {p} {zone} and he’s lost it.',
    // ── blocked & half clearances ──
    'Blocked! The clearance rebounds straight back {zone}.',
    'Charged down, and the ball spins up {zone}.',
    'Half-cleared, and it drops invitingly {zone}.',
    'The header only travels ten yards — loose {zone}.',
    'Hooked away, but only into the traffic {zone}.',
    'The clearance is blocked and comes back at them twice as fast.',
    'A weak headed clearance from {p} lands {zone}.',
    'They get it away, but it comes straight back {zone}.',
    '{team} clear their lines — well, half of them.',
    'Up in the air, down {zone}, still nobody’s ball.',
    // ── scrambles ──
    'A proper scramble {zone} — bodies everywhere.',
    'Chaos {zone}. Four players, one ball, nobody in charge.',
    'It’s a lottery {zone} and the ball squirts free.',
    'Absolute pinball {zone}.',
    'Boots flying {zone} and the ball comes loose.',
    'A pile-up {zone}, and out it pops.',
    'Nobody can get a proper contact on it {zone}.',
    'Scrappy stuff {zone} — three men swing and miss.',
    'A tangle of legs {zone}, and the ball squeezes out.',
    'It’s a mess {zone}, and it stays a mess.',
    // ── mis-controls ──
    '{p} takes his eye off it and it’s away {zone}.',
    'The ball skips off {p}’s shin {zone}.',
    'Tries to kill it on his chest — {p} can’t.',
    '{p} lets the bounce beat him {zone}.',
    'A poor cushion from {p}, and it’s loose {zone}.',
    '{p} traps it about a foot further than he meant to.',
    'He was thinking about the pass before the touch, {p}.',
    '{p} stretches, toe-pokes it, and it runs away {zone}.',
    'The chest control from {p} is all wrong {zone}.',
    '{p} tries to be clever with the outside of the boot and loses it.',
    // ── tackles that break loose ──
    'The tackle wins it, but nobody comes away with it {zone}.',
    'A crunching challenge {zone} and the ball flies free.',
    'Both men go in hard — the ball is the only winner {zone}.',
    'The block is good, but the ball spins up {zone}.',
    '{p} gets a toe in and it breaks loose {zone}.',
    'Fifty-fifty {zone}, and neither of them keeps it.',
    'The challenge sends it looping over both of them.',
    'A shin-to-shin collision {zone}, and it squirts away.',
    'Won and lost in the same movement {zone}.',
    'Two hard men, one ball, and it ends up nowhere.',
    // ── keeper spills & punches ──
    'The keeper can only parry, and it’s live {zone}.',
    'Spilled! It drops loose in front of goal.',
    'Punched clear, but only to the edge of the area.',
    'The keeper flaps at it and the ball drops {zone}.',
    'He gets a strong hand to it and shoves it away {zone}.',
    'The catch is fumbled and the ball is loose at his feet.',
    'Palmed up in the air, and now everyone wants it.',
    'The keeper races out, misses, and it runs {zone}.',
    'He can only push it out into the danger area.',
    'Handling error — and it sits up for anybody.',
    // ── defenders slicing it ──
    '{p} slices it horribly {zone}.',
    'Off the outside of the boot, and it balloons {zone}.',
    '{p} tries to hook it clear and shanks it.',
    'A dreadful contact from {p} — it goes sideways {zone}.',
    '{p} gets under it and it goes straight up.',
    'He scuffs it, {p}, and it trickles {zone}.',
    'A hospital touch from {p} {zone}.',
    'Skewed off {p}’s standing foot {zone}.',
    'That’s come off the shin, off the hip, off nothing at all.',
    '{p} swings and gets nowhere near it.',
    // ── out of play ──
    'It runs out of play, and neither side claims it.',
    'Nobody chases it — out for a throw {zone}.',
    'It trickles over the line with everyone watching.',
    'Out. And there’s a bit of argument about whose it is.',
    'The ball runs dead {zone}; the linesman’s flag settles it.',
    'That’s gone, {zone}, and the throw-in comes back.',
    'A tired arm goes up, but the ball has already gone out.',
    'Both of them let it go, and both of them regret it.',
    'It rolls out for a goal kick with {p} standing over it.',
    'Out of play, and the ball boy is quicker than anyone.',
    // ── two players, one ball ──
    'Two men go for it {zone} and neither wins it.',
    'They both arrive at once — the ball comes off worst.',
    'A collision {zone} and the ball rolls free.',
    'Head-to-head {zone}, and it drops between them.',
    'They square up for it {zone} and it bobbles away from both.',
    'Two of them stretch, and the ball goes under both boots.',
    'Shoulder to shoulder {zone}, and the ball breaks.',
    '{p} and his marker climb together — neither gets a header on it.',
    'They cancel each other out {zone}.',
    'Both go to ground and the ball goes nowhere.',
    // ── bobbles & surface ──
    'The bounce betrays {p} {zone}.',
    'A nasty bobble {zone} and {p} can’t deal with it.',
    'The pitch is cutting up, and the ball skids away from {p}.',
    'It sits up wickedly {zone} and {p} is beaten by it.',
    'The ball hits a divot and jumps over {p}’s foot.',
    'That surface isn’t helping — a horrible bounce {zone}.',
    'It skips off the wet grass and runs away {zone}.',
    'The ball checks up on {p} at the worst moment.',
    'An awkward height {zone} — too low to head, too high to kill.',
    'It scoots through {zone} quicker than anyone expects.',
    // ── interceptions ──
    'Read and cut out {zone}, but the interception runs loose.',
    'The pass never gets there — snuffed out {zone}.',
    '{p} telegraphs it and a leg comes out {zone}.',
    'Intercepted, and immediately given away again {zone}.',
    'A foot comes in and the pass dies {zone}.',
    'Cut out on the way through {zone}.',
    'They saw that one coming from a mile off.',
    '{p}’s ball into the channel is picked off {zone}.',
    'Chest-high interception {zone}, and it drops for nobody.',
    'Nipped in front of {p} — but the touch is too strong.',
    // ── over/underhit passes ──
    'Overhit by {p} — it runs through to nobody {zone}.',
    'Underhit! {p} leaves it short {zone}.',
    'Too much on that from {p} {zone}.',
    'A yard behind the runner, and the move dies {zone}.',
    '{p} looks for the through ball, but it’s a foot too heavy.',
    'The weight is all wrong from {p} {zone}.',
    'That pass had two men in mind and found neither.',
    '{p} aims for the switch and finds the advertising boards.',
    'Miscued from {p} and gifted straight back {zone}.',
    'Hit into a gap where there was no runner {zone}.',
    // ── aerial ──
    'Up it goes, and nobody attacks it {zone}.',
    'The header drops short and it’s a free-for-all {zone}.',
    'A flick-on that finds nobody {zone}.',
    'They both jump too early, and the ball sails on.',
    'Nodded down into no-man’s-land {zone}.',
    'The long ball bounces once, twice, and away {zone}.',
    '{p} misjudges the flight completely.',
    'A knock-down with nobody following in.',
    'It drops out of the sky {zone} and catches everybody flat.',
    'A tame header {zone} that goes straight to nobody.',
    // ── crosses & final third scraps ──
    'The cross is cut out and the second ball breaks {zone}.',
    'Cleared to the edge, and it’s scrappy again {zone}.',
    'Half-blocked at the near post and it spins across.',
    'The delivery is behind everybody and runs {zone}.',
    'A dangerous ball, but too close to the keeper — loose {zone}.',
    'It squirms through the six-yard box with nobody on it.',
    'The cut-back is intercepted and the ball pings {zone}.',
    'Everyone in the box swings at it, nobody connects.',
    'One touch away from a chance, and it’s gone.',
    'It flashes across the face of goal and out the other side.',
    // ── pressure & panic ──
    'Panic {zone} — hoofed away by nobody in particular.',
    'Under pressure, {p} just gets rid of it {zone}.',
    'No time on the ball {zone}, and it’s given away.',
    '{p} is hurried into it and it goes loose {zone}.',
    'The press forces the error, and the ball is free {zone}.',
    'Nowhere to go, so {p} lets it run out {zone}.',
    'Rushed by {p} and rushed badly {zone}.',
    'He’s got two on him — {p} loses it {zone}.',
    'Squeezed on the touchline, {p} gives it up.',
    'Backed into a corner {zone} and the ball goes.',
    // ── slower, drier beats ──
    'Loose ball {zone}.',
    'Nobody’s ball {zone}.',
    'Scrappy.',
    'It breaks {zone}.',
    'Untidy from {team}.',
    'And again, it’s loose {zone}.',
    'That was a messy few seconds {zone}.',
    'Neither side can settle it {zone}.',
    'Possession changes hands three times in five seconds.',
    'This has become a scrap {zone}.',
    'A period of pure attrition {zone}.',
    'No rhythm to this at all {zone}.',
    'It’s all elbows and second balls {zone}.',
    'A ball for nobody {zone}.',
    'Bitty stuff {zone}.',
    // ── momentum-flavoured loose ball ──
    'The ball breaks and {team} are quicker to it — but only just.',
    'Fifty-fifty {zone}, and it stays fifty-fifty.',
    '{opp} think they’ve won it; they haven’t.',
    'It falls between the lines and both sides hesitate.',
    'The second ball is the whole game right now.',
    '{team} are gambling on the loose ones {zone}.',
    'A break of the ball, and nobody gambles on it.',
    'It runs harmlessly through to the keeper in the end.',
    'It ends up back with the goalkeeper, and everyone resets.',
    'That one comes to nothing {zone}.',
    // ── keeper/defensive resets ──
    'The keeper gathers it at the second attempt.',
    'A defender finally puts a foot on it {zone}.',
    'Shepherded out by {p} after all that.',
    '{p} calmly ends the pinball {zone}.',
    'Someone in a {team} shirt eventually settles it {zone}.',
    'It takes three attempts, but {team} get it under control.',
    'The scramble ends with a hopeful punt {zone}.',
    'Order restored, eventually {zone}.',
    'A boot through it and we start again {zone}.',
    'Cleared into the stand. That’ll do for them.',
    // ── more variety ──
    '{p} slips as he goes to strike it and the ball runs off {zone}.',
    'His standing foot gives way and {p} loses it {zone}.',
    'Caught in two minds, {p} does neither {zone}.',
    'He looks up, hesitates, and it’s taken off his toe.',
    '{p} tries the flick and it doesn’t come off {zone}.',
    'The backheel from {p} finds nobody {zone}.',
    'A drag-back that drags it straight out of play.',
    '{p} attempts the nutmeg and it hits the shin.',
    'The step-over doesn’t work, and neither does the touch after it.',
    'One too many stepovers from {p} {zone}.',
    'A miscommunication {zone} — they both leave it.',
    'They both shout for it, and neither goes.',
    '"Yours!" "Yours!" — and it’s nobody’s.',
    'A mix-up between two {team} shirts {zone}.',
    'The pass is played to where his man was, not where he is.',
    'The wind holds it up and {p} is beaten by the flight.',
    'It skids on the wet turf and runs {zone}.',
    'A greasy surface, and {p} pays for it.',
    'Ball spinning wildly {zone} — impossible to control.',
    'It comes off the post of the goalframe advertising and away.',
    'The rebound off the block sits up for the taking.',
    'Everyone waits for the bounce, and the bounce never comes.',
    'The offside trap breaks down, and so does the ball.',
    'Nudged away from {p} by an arm across the chest.',
    'He’s barged off it, {p}, but the ref sees nothing.',
    'Shouldered off the ball {zone}.',
    'The ball is dug out from under his own feet by {p}.',
    'A poor throw-in, straight into trouble {zone}.',
    'The throw is taken quickly and given away quicker.',
    'The goal kick is nodded straight back {zone}.',
    'Long ball, long clearance, and back it comes.',
    'Tennis {zone}, and nobody wants to end the rally.',
    'This has been up and down the pitch four times.',
    'They keep giving it back to each other {zone}.',
    'It ends up with the keeper by pure accident.',
    'That was somewhere between a pass and a clearance.',
    'Half a shot, half a cross, no result at all.',
    'A hopeful punt {zone} that nobody gets near.',
    'The switch of play is horribly overcooked.',
    'It goes out for a throw off {p}’s heel.',
    'Bundled away {zone} by anyone in a shirt.',
    'A sliced clearance loops up, and hearts stop briefly.',
    'A hurried hack {zone} — job done, badly.',
    'The ball is dragged back, then dragged away by an opponent.',
    '{p} shields it, loses it, and chases it {zone}.',
    'He runs it into trouble, does {p} {zone}.',
    'Straight into the back of his own man {zone}.',
    'Off his teammate and out for a throw.',
    'They collide with each other going for the same ball.',
    'A comedy of errors {zone}, and the ball is still loose.',
    'It bounces off two heads and lands at nobody’s feet.',
    'Handbags brewing {zone} as the ball trickles away.',
  ],
  tackle_won: [
    // ── ⚡ pressing turnovers (high up the pitch) ──
    '⚡ Hounded into the mistake — {p} has it for {team}!',
    '⚡ {p} won’t let him breathe, and the ball is {team}’s.',
    '⚡ Straight back at them! {p} wins it and {team} are away.',
    '⚡ {team} swarm him — {p} comes out with it.',
    '⚡ {p} sniffs the loose pass and pounces.',
    '⚡ That’s the trap sprung, and {p} is the one who springs it.',
    '⚡ No escape for him — {p} takes it off his toe.',
    '⚡ {p} chases down a lost cause and wins it back.',
    '⚡ Pressure, pressure, and finally {p} gets his reward.',
    '⚡ {team} don’t give him a second, and {p} nicks it.',
    '⚡ Robbed! {p} does him for pace and thought.',
    '⚡ {p} comes flying in and takes ball and man — all legal.',
    '⚡ A brilliant read from {p}, and {team} have it in a lovely spot.',
    '⚡ He dawdles, and {p} makes him pay.',
    '⚡ {p} bites, and this time he gets it.',
    '⚡ {team} press as a unit; {p} finishes the job.',
    '⚡ Nowhere to pass, and {p} takes it away from him.',
    '⚡ {p} shows a foot, then takes it — clever stuff.',
    '⚡ Turned inside out and dispossessed — {p} with the ball.',
    '⚡ That is aggressive defending, and {p} times it perfectly.',
    '⚡ {p} squeezes him against the line and wins the ball.',
    '⚡ Caught dwelling! {p} steals in behind him.',
    '⚡ The touch is heavy and {p} is on it in a flash.',
    '⚡ {team} smell blood, and {p} gets there first.',
    '⚡ {p} snaps at his heels until the ball comes free.',
    '⚡ A gift, and {p} accepts it with both hands.',
    '⚡ {opp} try to play out and {p} punishes them.',
    '⚡ That’s what the gaffer wants — {p} wins it back immediately.',
    '⚡ Six seconds after losing it, {team} have it again.',
    '⚡ {p} throws himself at the pass and comes away with it.',
    '⚡ A brave block from {p}, and the ball is {team}’s.',
    '⚡ He steps across him and it’s {p} with the ball.',
    '⚡ {p} forces him inside, then takes it.',
    '⚡ Cornered by two {team} shirts, he loses it to {p}.',
    '⚡ {p} intercepts the pass out from the back — big moment.',
    '⚡ The energy of {p} is relentless, and it pays.',
    '⚡ {p} anticipates it perfectly and cuts in front.',
    '⚡ That’s a proper press from {team}, led by {p}.',
    '⚡ Ball won high, and {team} have numbers ahead of it.',
    '⚡ {p} gets tight and refuses to let him turn.',
    '⚡ He tries the turn, {p} is ready for it.',
    '⚡ Dispossessed under the coaching staff’s noses — {p} has it.',
    '⚡ A poor touch, a quick {p}, and {team} are in business.',
    '⚡ Won back in an instant by {p} — {team} pouring forward.',
    '⚡ {p} nips in and there’s daylight ahead of him.',
    '⚡ Aggressive, front-foot stuff from {p}.',
    '⚡ {p} makes the tackle and stays on his feet — even better.',
    '⚡ Poked away by {p} and picked up by a teammate.',
    '⚡ {p} is a nuisance, and {opp} have had enough of him.',
    '⚡ There’s the turnover {team} have been chasing all half.',
    '⚡ Not a foul, just a fine tackle from {p}.',
    '⚡ {p} times the challenge to the split second.',
    '⚡ Ball, all ball — {p} wins it cleanly and dangerously.',
    '⚡ {p} closes the angle and forces the error.',
    '⚡ The pass back is short, and {p} is onto it.',
    '⚡ {team} have won it in a very good area indeed.',
    '⚡ Turnover! And {opp} are horribly exposed.',
    '⚡ {p} lunges, connects, and the ball breaks {team}’s way.',
    '⚡ He’s got a sniff of it all afternoon, {p}, and there it is.',
    '⚡ {p} presses the trigger and the whole side follows.',
    '⚡ Won by {p} with sheer stubbornness.',
    '⚡ {opp} panic under it, and {p} collects the mess.',
    '⚡ {p} arrives like a train and takes the ball.',
    '⚡ Two touches too many, and {p} makes him regret both.',
    '⚡ {team} force it long, then win the header — {p} at the heart of it.',
    '⚡ {p} steals it and looks up immediately.',
    '⚡ A poacher’s tackle from {p}, if there is such a thing.',
    '⚡ {p} shuts the door and takes the ball with him.',
    '⚡ {opp} can’t get out of their own half with {p} like this.',
    '⚡ Snapped up by {p} — {team} in a dangerous spot.',
    // ── 🦵 ordinary tackles ──
    '🦵 A textbook challenge from {p} {zone}.',
    '🦵 {p} plants his foot and comes away with it {zone}.',
    '🦵 Perfectly timed by {p} {zone} — not a hint of a foul.',
    '🦵 The slide is clean, and {p} takes ball and momentum.',
    '🦵 {p} shows him the touchline and shepherds it away.',
    '🦵 A calm interception from {p} {zone}.',
    '🦵 {p} gets his body across and the ball is {team}’s.',
    '🦵 Muscled off it {zone} — {p} is too strong.',
    '🦵 {p} rides the shoulder and comes out with the ball.',
    '🦵 He waits, he waits, and {p} takes it at the perfect moment.',
    '🦵 A sitting tackle from {p} and it’s {team} ball {zone}.',
    '🦵 {p} sticks out a leg and it’s enough {zone}.',
    '🦵 The winger runs into {p} and gets nothing.',
    '🦵 Bullied off the ball {zone} by {p}.',
    '🦵 {p} backs off, backs off, and then strikes {zone}.',
    '🦵 A lovely bit of defending from {p} {zone}.',
    '🦵 Nothing flashy from {p} — just a good, hard tackle {zone}.',
    '🦵 The ball is out of there, and {p} did all the work.',
    '🦵 {p} reads the pass before it’s played {zone}.',
    '🦵 Cut out by {p}, who was two moves ahead {zone}.',
    '🦵 A big block from {p} and {team} recover it {zone}.',
    '🦵 {p} throws his body in the way and wins the ball.',
    '🦵 Brave defending {zone} from {p} — head where the boots were.',
    '🦵 {p} arrives at the same time as the ball, and only takes the ball.',
    '🦵 That’s how to defend a one-on-one — {p} is faultless {zone}.',
    '🦵 {p} jockeys him wide and then takes it {zone}.',
    '🦵 Patience from {p}, and the reward {zone}.',
    '🦵 A clean sweep of the leg, and {p} has it {zone}.',
    '🦵 {p} nicks it away from under him {zone}.',
    '🦵 Toe-poked clear by {p} at full stretch {zone}.',
    '🦵 {p} stretches out a boot and diverts it {zone}.',
    '🦵 The last ditch is where {p} lives, and he wins it again.',
    '🦵 An old-fashioned challenge from {p} {zone}.',
    '🦵 {p} thumps into the tackle and stands up out of it.',
    '🦵 That is a proper defender’s tackle {zone}.',
    '🦵 The crowd like that one — {p} wins it {zone}.',
    '🦵 Won cleanly by {p}, and {team} can build again.',
    '🦵 {p} nudges him off balance and takes possession {zone}.',
    '🦵 Firm but fair from {p} {zone}.',
    '🦵 {p} makes the challenge look easy {zone}.',
    '🦵 He never leaves the ground, {p} — and never needs to.',
    '🦵 Head up, feet quick, {p} takes it {zone}.',
    '🦵 A crunching tackle {zone}, and it’s all ball.',
    '🦵 {p} sees the danger early and snuffs it out {zone}.',
    '🦵 The through ball is cut out by {p} {zone}.',
    '🦵 Intercepted low by {p} {zone}, and the danger passes.',
    '🦵 {p} sniffs it out {zone} before it develops.',
    '🦵 Good positioning from {p} — the tackle is almost incidental.',
    '🦵 {p} is exactly where he needs to be {zone}.',
    '🦵 He simply refuses to be beaten there, {p}.',
    '🦵 A shoulder, a step, and {p} has the ball {zone}.',
    '🦵 {p} gets the wrong side and still wins it {zone}.',
    '🦵 Recovery tackle from {p}, and it’s a beauty {zone}.',
    '🦵 Chased down and won back by {p} {zone}.',
    '🦵 Twenty yards of running, one touch, ball won — {p}.',
    '🦵 {p} tracks the runner all the way and takes it {zone}.',
    '🦵 He does the unglamorous work, {p}, and does it well.',
    '🦵 {p} sticks with him and eventually forces the error {zone}.',
    '🦵 Dogged from {p} {zone}, and he gets his reward.',
    '🦵 An honest challenge {zone}, and {team} have possession.',
    '🦵 The ball is nicked away by {p} {zone} with the outside of his boot.',
    '🦵 {p} hooks it back into play and keeps it for {team}.',
    '🦵 A well-judged shepherd from {p}, and it runs safe.',
    '🦵 Shielded, shepherded, and claimed by {p} {zone}.',
    '🦵 {p} steps out of the line and wins it {zone}.',
    '🦵 Aggressive from the back — {p} steps in {zone}.',
    '🦵 {p} comes out of defence with it {zone}, chest out.',
    '🦵 Won on the halfway and away they go.',
    '🦵 A midfielder’s tackle {zone}, and a good one.',
    '🦵 {p} snuffs out the attack {zone} with one movement.',
    '🦵 Not spectacular, but exactly right from {p} {zone}.',
    '🦵 {p} tidies up {zone}, as he has all afternoon.',
    '🦵 Quietly excellent from {p} {zone}.',
    '🦵 {p} mops it up {zone} without any fuss.',
    '🦵 The ball is {team}’s again, thanks to {p} {zone}.',
    '🦵 Another one won by {p} {zone}.',
    '🦵 {p} keeps winning these {zone}.',
    '🦵 {p} again! He’s all over the pitch.',
    '🦵 That’s the third he’s won in as many minutes.',
    '🦵 {p} loves this side of the game {zone}.',
    '🦵 A rugged bit of work from {p} {zone}.',
    '🦵 Grit and timing from {p} {zone}.',
    '🦵 The tackle is met with a roar {zone}.',
    '🦵 {p} takes the ball and half the man — the ref waves it on.',
    '🦵 It was close, but that was all ball from {p}.',
    '🦵 The appeals come, but {p} won it fairly {zone}.',
    '🦵 Nothing in it, says the referee — {p} keeps the ball.',
    '🦵 A fair shoulder charge and {p} has it {zone}.',
    '🦵 {p} outmuscles him and turns away with it.',
    '🦵 He was never getting past {p} there.',
    '🦵 {p} makes his mind up and gets it right {zone}.',
    '🦵 Decisive from {p} {zone}.',
    '🦵 No hesitation from {p}, and the ball is won {zone}.',
    '🦵 A clean, committed tackle {zone}.',
    '🦵 {p} wins the duel and starts the counter himself.',
    '🦵 Ball won by {p} {zone}, and immediately {team} look forward.',
    '🦵 {p} wins it and finds a teammate in the same movement.',
    '🦵 Tackle, look up, pass — {p} makes it all look simple.',
    '🦵 From defending to attacking in one touch from {p}.',
    '🦵 {p} breaks it up {zone} and keeps the move alive.',
    '🦵 A brilliant slide from {p} {zone} — and he’s up straight away.',
    '🦵 Down and up in a flash, {p}, with the ball at his feet.',
    '🦵 That challenge lifts the whole side.',
    '🦵 {p} thunders in {zone} and the bench are up applauding.',
    '🦵 The dugout loves that from {p}.',
    '🦵 A tackle that means something, {zone}, from {p}.',
    '🦵 {p} wins it and lets him know about it.',
    '🦵 Won by a whisker from {p} {zone}.',
    '🦵 Fingertips of a challenge, and it’s enough {zone}.',
    '🦵 The tiniest of touches from {p} sends it away {zone}.',
    '🦵 {p} deflects the pass out of danger {zone}.',
    '🦵 Half a yard is all {p} needs {zone}.',
    '🦵 {p} gets a leg in when there was no leg to get in.',
    '🦵 From nowhere, {p} appears and takes the ball.',
    '🦵 He came out of the shadows there, {p}.',
    '🦵 {p} makes up ten yards and still wins the tackle.',
    '🦵 A sprint, a slide, and {p} has it {zone}.',
    '🦵 {p} is first to it {zone}, as usual.',
    '🦵 Reactions of a cat from {p} {zone}.',
    '🦵 {p} wins the header and the second ball {zone}.',
    '🦵 Everything that comes near {p} stays with {team}.',
    '🦵 Solid, dependable defending from {p} {zone}.',
    '🦵 {p} is having one of those afternoons {zone}.',
    '🦵 The challenge stands up and so does {p}.',
    '🦵 No need to dive in — {p} simply takes it {zone}.',
    '🦵 A masterclass in staying on your feet from {p}.',
    '🦵 {p} eases him off it {zone}. Strength and timing.',
    '🦵 That’s the ball, and {team} go again {zone}.',
    '🦵 A thumping challenge from {p} {zone}, and the ball stays in {team} hands.',
    '🦵 {p} wins the fifty-fifty {zone} and comes out on top.',
  ],
  chance: [
    '{p} is through, and the crowd are on their feet…',
    'The ball drops perfectly for {p}, eight yards out…',
    'A yard of space is all {p} wanted, and he’s got it…',
    '{p} spins away from his marker and looks up…',
    'Here’s the opening — {p} winds up…',
    '{team} slice {opp} open, and {p} is the man free…',
    '{p} takes it round the last man…',
    'Only the keeper to beat for {p}…',
    'The defence is nowhere — {p} has time to pick his spot…',
    '{p} steps inside and the goal opens up in front of him…',
    'One touch to control, one to shoot — {p} is ready…',
    'A brilliant ball releases {p} in behind…',
    '{p} is clean through on goal for {team}…',
    'The cut-back finds {p} arriving on the penalty spot…',
    '{p} rises unmarked at the far post…',
    'It’s dropped to {p} inside the six-yard box…',
    'Enormous chance for {team} — {p} can’t miss from there, surely…',
    '{p} is picked out at the back stick, all on his own…',
    'The cross is perfect, and {p} attacks it…',
    'A stepover, a shift, and {p} has a shooting angle…',
    '{p} beats his man on the outside and cuts it back onto his left…',
    'Space opens up outside the box and {p} likes the look of this…',
    '{p} lets it run across his body and pulls the trigger…',
    'The header is nodded down into the path of {p}…',
    '{p} is first to the flick-on, and he’s away…',
    '{opp} are all over the place, and {p} is running at them…',
    'Three passes, and {team} are in — {p} bearing down…',
    '{p} nutmegs his marker and drives at the defence…',
    'The defence backs off and backs off, and {p} decides to have a go…',
    '{p} is teed up twenty yards out with nobody near him…',
    'That’s a wonderful ball over the top, and {p} is onto it…',
    '{p} chests it down on the edge of the area…',
    'A dummy from the striker lets it run to {p}…',
    'The keeper is stranded, and {p} has the ball at his feet…',
    '{p} rounds the goalkeeper…',
    'It falls kindly for {p} in the danger zone…',
    'The rebound sits up for {p}, six yards out…',
    'A scramble, and the ball lands at {p}’s feet in front of goal…',
    '{p} pounces on the loose ball inside the box…',
    'Half a chance for {p}, and he goes for it…',
    'It’s a tight angle, but {p} fancies it…',
    'From nothing, {p} manufactures a sight of goal…',
    '{p} conjures a yard out of nowhere…',
    'The pass splits two defenders and {p} is in…',
    'Through the eye of a needle, and {p} is clear…',
    '{p} plays the one-two and keeps running…',
    'Give and go, and {p} is in behind the line…',
    'The overlap comes, but {p} keeps it himself…',
    '{p} drives infield and the shooting lane opens…',
    'Onto his weaker foot, but {p} doesn’t care…',
    'He’s got the whole goal to aim at, {p}…',
    'The offside trap fails, and {p} has acres…',
    '{p} times the run to perfection and he’s away…',
    'A brilliant first touch takes {p} clear of the defender…',
    '{p} kills it dead and sets himself…',
    '{team} break with three against two — {p} carries it…',
    'Four on two! {team} are in, and {p} has options…',
    'They pour forward, and {p} is the spare man…',
    '{p} is haring towards goal with the defence trailing…',
    'The break is on for {team}, and it’s {p} leading it…',
    'From their corner to our chance — {p} is running clear…',
    '{p} beats the offside line by half a yard…',
    'The flag stays down and {p} is through…',
    'It’s two on one, and {p} has to decide…',
    'A long, raking pass, and {p} has stolen a march…',
    '{p} is a step quicker than his marker and that’s that…',
    'Sheer pace from {p}, and he’s in the box…',
    '{p} shrugs off the challenge and drives on…',
    'He rides one tackle, then another, and {p} is clear…',
    'Nobody can lay a glove on {p} here…',
    'The last defender is beaten and {p} is bearing down…',
    'A brilliant run from deep by {p}, arriving late…',
    '{p} ghosts in unnoticed at the back post…',
    'Completely unmarked, {p} has all the time he wants…',
    'How has nobody picked up {p} there…',
    '{opp} have gone to sleep and {p} is in…',
    'Awful defending, and {p} has a gift…',
    'A dreadful backpass leaves {p} with the ball and an open goal ahead…',
    'The keeper flaps, and {p} has a header at an empty net…',
    '{p} steals in ahead of the defender at the near post…',
    'A flick at the front post from {p}…',
    'The corner is met perfectly by {p}…',
    '{p} climbs highest at the set piece…',
    'The free kick is nodded across and {p} is waiting…',
    'The knock-down finds {p} eight yards out…',
    'Second phase from the corner, and {p} shapes to volley…',
    'It drops out of the sky and {p} tries the volley…',
    '{p} meets it on the half-volley from the edge of the box…',
    'A first-time strike coming from {p}…',
    '{p} takes it on the drop…',
    'On the swivel, {p} goes for goal…',
    'A bicycle kick from {p}! He’s gone for it…',
    'He tries the audacious from {p} — the outside of the boot…',
    '{p} attempts to lob the goalkeeper…',
    'Cheeky from {p}, he’s tried to dink it…',
    '{p} spots the keeper off his line…',
    'He’s going for it from distance, {p}…',
    'Thirty yards out, and {p} is thinking about it…',
    '{p} strikes it from range…',
    'A dip and a swerve on this effort from {p}…',
    'He gives it everything from way out, {p}…',
    '{p} finds himself in space in the D…',
    'The ball rolls into {p}’s path, twenty-five yards out…',
    'The lay-off is perfect, and {p} runs onto it…',
    'Set for {p}, and he’s got a clear sight…',
    '{p} takes the lay-off in his stride…',
    'A perfect set-up, and {p} has to hit the target…',
    'It’s all on {p} now…',
    'This is the moment for {team}…',
    'A huge opportunity for {team} here…',
    '{team} sense blood, and {p} is in the thick of it…',
    'The whole ground holds its breath as {p} shapes…',
    'The bench are up. {p} has a chance…',
    'This is a big one for {p}…',
    'Everything stops. {p}, one on one…',
    '{p} has been waiting all afternoon for this…',
    'Here’s his chance to be the hero — {p}…',
    'It’s written for {p} here…',
    '{p} takes a touch. He shouldn’t have taken a touch…',
    'He’s got time — maybe too much time, {p}…',
    'Time to think can be a curse. {p} looks up…',
    'The angle is closing, but {p} goes anyway…',
    'It’s tight, and the keeper is out quickly, but {p} is committed…',
    '{p} has to get this away early…',
    'He’s off balance, but {p} still gets a shot away…',
    'Stretching for it, {p} makes a connection…',
    'Falling backwards, {p} still manages to strike it…',
    'A defender is scrambling back, but {p} has the shot…',
    'One chance, one touch, and {p} is in…',
    'Sliding in at the far post comes {p}…',
    '{p} slides in to meet the low cross…',
    'A diving header from {p}…',
    'He throws himself at it, {p}…',
    'Full-length dive to reach it — {p} gets a head on it…',
    'The delivery is inch-perfect and {p} attacks it with his head…',
    '{p} plants a header goalwards from six yards…',
    '{p} gets across his marker and glances it…',
    'Free header for {p}, and he has to bury this…',
    'A back-post header for {p}, completely free…',
    'It’s worked beautifully and {p} is in on the angle…',
    'The move is a thing of beauty, and {p} is at the end of it…',
    'Twelve passes and {p} arrives to finish it…',
    'A wonderful team goal in the making — {p} to apply the touch…',
    'Everything has led to this, and {p} is the man…',
    'One touch each, and {p} is through the middle…',
    '{team} carve them apart, and {p} is free…',
    'They’ve pulled {opp} all over the place, and {p} is in the gap…',
    'The switch finds {p} completely unmarked…',
    'A crossfield ball, and {p} has the whole flank…',
    '{p} is one on one with the full back and he goes at him…',
    '{p} chops inside and looks for the far corner…',
  ],
  shot_saved: [
    '🧤 Superb! A strong wrist keeps {p} out.',
    '🧤 Tipped over! The keeper gets a fingertip to {p}’s effort.',
    '🧤 Pushed round the post — brilliant goalkeeping against {p}.',
    '🧤 He’s there! The keeper smothers it at {p}’s feet.',
    '🧤 Out he comes, and he wins the duel with {p}.',
    '🧤 Spread himself beautifully, and {p} can’t beat him.',
    '🧤 A save from the top drawer keeps {p} out.',
    '🧤 Full stretch! Somehow he claws {p}’s shot away.',
    '🧤 Down low to his right — the keeper holds it.',
    '🧤 Straight at him, and {p} knows he’s wasted it.',
    '🧤 Well struck by {p}, but the keeper is equal to it.',
    '🧤 Comfortable in the end, and {p} looks to the sky.',
    '🧤 Parried away, and {opp} scramble it clear.',
    '🧤 He can only push it out, but nobody follows in for {team}.',
    '🧤 Held! A clean, calm catch to deny {p}.',
    '🧤 Two hands, safely gathered — no chance for {p}.',
    '🧤 Beaten away at the near post; {p} thought that was in.',
    '🧤 What a stop! {p} cannot believe it.',
    '🧤 That is world class from the goalkeeper.',
    '🧤 An unbelievable reflex save denies {p}.',
    '🧤 From point blank range, he keeps out {p}.',
    '🧤 How has he saved that? {p} is on his knees.',
    '🧤 The keeper stands tall and {p} hits him.',
    '🧤 A big body in the way, and {p} is thwarted.',
    '🧤 Blocked by the goalkeeper’s legs — a fine save.',
    '🧤 Strong hands. {p} hit it well and it wasn’t enough.',
    '🧤 Diving to his left, he gets there — {p} denied.',
    '🧤 Wrong-footed, but he still gets a hand on it!',
    '🧤 He guessed, and he guessed right — {p} foiled.',
    '🧤 A save with the boot! Extraordinary from the keeper.',
    '🧤 Somehow it stays out, and {p} holds his head.',
    '🧤 That was heading for the bottom corner until the keeper intervened.',
    '🧤 Destined for the top corner, and he’s flown to reach it.',
    '🧤 Arched backwards and tipped it over — magnificent.',
    '🧤 Up and over the bar it goes, off the keeper’s glove.',
    '🧤 Onto the crossbar and away from the save.',
    '🧤 Behind for a corner, and {team} go again.',
    '🧤 A corner is all {team} get for that effort from {p}.',
    '🧤 The rebound is smothered before {team} can pounce.',
    '🧤 He holds on at the second attempt with {p} closing in.',
    '🧤 The keeper is having a marvellous afternoon.',
    '🧤 That’s his best of the day, and it denies {p}.',
    '🧤 {opp}’s number one is proving impossible to beat.',
    '🧤 He’s keeping {opp} in this single-handedly.',
    '🧤 Another one for the highlight reel from the goalkeeper.',
    '🧤 {p} has done everything right and still hasn’t scored.',
    '🧤 Nothing wrong with the finish — everything right with the save.',
    '🧤 {p} deserved better than that.',
    '🧤 The strike was true; the goalkeeping was better.',
    '🧤 {p} did all the hard work and found the keeper in the way.',
    '🧤 Saved, and {team} appeal for a corner they’ve already got.',
    '🧤 A firm shot from {p} is turned behind.',
    '🧤 Pushed out to safety, and the danger fades.',
    '🧤 Palmed clear and headed away by a defender.',
    '🧤 Punched clear as {p} came in for the second bite.',
    '🧤 Claimed above the heads of the crowd in the box.',
    '🧤 He plucks {p}’s header out of the air.',
    '🧤 A header from {p}, and the keeper is right behind it.',
    '🧤 The header is powerful, but so is the save.',
    '🧤 Down to his right to keep out {p}’s header.',
    '🧤 A one-handed stop from the free kick.',
    '🧤 The set piece is met well, and met by the goalkeeper too.',
    '🧤 {p}’s low drive is turned round the upright.',
    '🧤 Along the ground, and the keeper gets down well.',
    '🧤 A stinging shot from range is beaten away.',
    '🧤 From thirty yards it dips late, but he’s got it covered.',
    '🧤 It swerved viciously and he still held it.',
    '🧤 Well judged by the keeper, who let it come to him.',
    '🧤 He never moved his feet and never had to.',
    '🧤 Routine in the end, and {p} won’t like that.',
    '🧤 A tame effort from {p}, easily gathered.',
    '🧤 Not enough on it from {p} — the keeper collects.',
    '🧤 Too close to the goalkeeper from {p}.',
    '🧤 That’s a chance gone for {team}.',
    '🧤 {p} picked the wrong corner, and the keeper punished him.',
    '🧤 He’s telegraphed it, {p}, and the keeper reads it easily.',
    '🧤 Well saved — and {p} should have squared it.',
    '🧤 The keeper made himself big, and {p} had nowhere to go.',
    '🧤 Narrowed the angle perfectly, and {p} ran out of goal.',
    '🧤 Off his line quickly and the danger from {p} is gone.',
    '🧤 Sliding out, he takes the ball off {p}’s toe.',
    '🧤 Brave from the goalkeeper — he takes a boot in the ribs for that.',
    '🧤 He wears the follow-through, and he doesn’t care.',
    '🧤 Down at the feet of {p} and he holds on.',
    '🧤 Courageous stuff, and {p} is denied.',
    '🧤 Smothered on the line as {p} tried to lift it.',
    '🧤 The dink is caught! {p} tried to be too clever.',
    '🧤 He waited, and {p} blinked first.',
    '🧤 Standing up until the last second — brilliant technique.',
    '🧤 Star jump from the goalkeeper, and it works.',
    '🧤 Blocked with his chest — no idea how.',
    '🧤 It hits him on the shoulder and loops to safety.',
    '🧤 Lucky or not, it’s a save, and {p} has nothing.',
    '🧤 A hand, a knee, anything — the ball stays out.',
    '🧤 Instinct alone from the goalkeeper there.',
    '🧤 No time to react, and yet he has.',
    '🧤 From six yards! An astonishing save from {p}’s effort.',
    '🧤 The deflection nearly beat him, but the keeper adjusts.',
    '🧤 It took a nick on the way and he still got there.',
    '🧤 Recovering across his goal, he claws it away.',
    '🧤 Beaten and then unbeaten in the space of a second.',
    '🧤 He’s scrambled back to keep {p}’s shot out.',
    '🧤 A save and a hold, with {team} bodies queueing up.',
    '🧤 {opp} breathe again after that save.',
    '🧤 The keeper takes the sting out of it and holds.',
    '🧤 Cushioned, controlled, collected — a proper goalkeeper.',
    '🧤 Nothing spectacular, but exactly what was needed.',
    '🧤 He makes it look simple, and it wasn’t.',
    '🧤 A save that keeps {opp} in this match.',
    '🧤 That could be a huge moment for {opp}.',
    '🧤 The save is greeted like a goal at that end.',
    '🧤 His defenders mob him, and rightly so.',
    '🧤 {p} applauds him. What else can he do.',
    '🧤 A rueful smile from {p} — he knows.',
    '🧤 {p} puts his hands on his head; that was the chance.',
    '🧤 {team} thought they had it. The keeper thought otherwise.',
    '🧤 So nearly the goal {team} needed, and a save to deny them.',
    '🧤 Held under pressure, with two {team} shirts snapping at him.',
    '🧤 Gathered at the near post as the cross came in.',
    '🧤 A stop from {p} at the front post, and it’s behind.',
  ],
  shot_missed: [
    '❌ Over the top! {p} leans back and it sails away.',
    '❌ Wide of the near post from {p}.',
    '❌ A yard the wrong side of the upright — agony for {p}.',
    '❌ Inches wide! {p} can’t look.',
    '❌ It flashes across the face of goal and past the far post.',
    '❌ {p} scuffs it and it dribbles harmlessly wide.',
    '❌ Sliced! {p} gets it all wrong.',
    '❌ Into the side netting from {p} — for a moment it looked in.',
    '❌ Into the stands. {p} caught that one far too well.',
    '❌ High, wide and not handsome from {p}.',
    '❌ That’s a dreadful miss from {p}.',
    '❌ How has he missed that? {p} is beside himself.',
    '❌ An open goal, and {p} has put it wide.',
    '❌ From six yards, {p} contrives to miss.',
    '❌ Unforgivable from {p} — he had to score.',
    '❌ He’ll be having nightmares about that one, {p}.',
    '❌ Easier to score, and {p} has missed it.',
    '❌ Oh dear. {p} won’t want to see that again.',
    '❌ The gaffer can’t watch. {p} has spurned it.',
    '❌ {p} buries his face in his shirt.',
    '❌ Hands on head from {p}. He knows.',
    '❌ {p} looks to the heavens. That was the moment.',
    '❌ Teammates hold their heads as {p}’s effort goes wide.',
    '❌ A groan around the ground as {p} misses.',
    '❌ Silence, then a sigh. {p} has missed the target.',
    '❌ Dragged wide by {p} with the keeper beaten.',
    '❌ The keeper was beaten — the post wasn’t there to help him, but {p} missed anyway.',
    '❌ He had the whole goal and picked the one place he couldn’t score.',
    '❌ Snatched at it, {p}, and it flies over.',
    '❌ Too eager from {p}, and the ball ends up in row Z.',
    '❌ He rushed it, {p}, and it shows.',
    '❌ A hurried effort from {p} that never threatens.',
    '❌ Off balance, and {p} skies it.',
    '❌ Falling away as he strikes, {p} sends it wide.',
    '❌ He can’t get his body over it, and {p} lifts it.',
    '❌ On the stretch, {p} can only steer it wide.',
    '❌ Half a yard short of a proper contact for {p}.',
    '❌ It comes off the shin and spins wide from {p}.',
    '❌ A poor connection from {p} and it trickles wide.',
    '❌ Wrong foot, wrong angle, wrong result for {p}.',
    '❌ {p} takes the wrong option and drags it across goal.',
    '❌ He should have squared it. {p} shoots and misses.',
    '❌ Greedy from {p} — two men were free.',
    '❌ {p} tries to place it and gets neither power nor accuracy.',
    '❌ Aiming for the corner, {p} finds the corner flag instead.',
    '❌ Too clever from {p}, and it ends in nothing.',
    '❌ He tried to dink it and got the height horribly wrong.',
    '❌ The lob from {p} clears the bar by some distance.',
    '❌ {p} attempts the outrageous, and it goes outrageously wide.',
    '❌ Ambitious from {p}, and it clears everything.',
    '❌ From thirty-five yards, {p} lets fly — and it’s miles off.',
    '❌ A speculative one from {p} that never looked like troubling anyone.',
    '❌ Hopeful rather than dangerous from {p}.',
    '❌ He fancied that from range, {p}. Nobody else did.',
    '❌ Long range and long gone from {p}.',
    '❌ The volley from {p} rockets over the crossbar.',
    '❌ A dipping effort from {p} that dips a fraction too late.',
    '❌ It rises when he wanted it to fall — {p} is furious.',
    '❌ The half-volley from {p} balloons over.',
    '❌ Fresh air! {p} swings and misses completely.',
    '❌ He misses it entirely, {p} — the ball runs out for a goal kick.',
    '❌ Air shot from {p}. That’s embarrassing.',
    '❌ The header from {p} is nodded wide.',
    '❌ {p} can’t keep the header down and it flies over.',
    '❌ A free header, and {p} has put it the wrong side of the post.',
    '❌ He got too much on the header and it clears the bar.',
    '❌ Glanced wide by {p} from the corner.',
    '❌ {p} rises well and heads it just past the upright.',
    '❌ The header loops up and drops the wrong side of the netting.',
    '❌ Wide from the set piece, and {opp} clear their heads.',
    '❌ Blocked and deflected wide — nothing on target from {team}.',
    '❌ Charged down, and it spins away for a goal kick.',
    '❌ A defender gets a crucial touch and it goes wide of the post.',
    '❌ It takes a deflection and looped just past the far corner.',
    '❌ Off a defender and out, and {team} want a corner they won’t get.',
    '❌ {p}’s effort is smothered on the way and runs wide.',
    '❌ Deflected over, and {team} have another set piece at least.',
    '❌ A big block, and {p}’s shot flies wide.',
    '❌ It clips the last man and drifts the wrong side.',
    '❌ There’s a nick on it, and it wasn’t a helpful one for {p}.',
    '❌ Straight into the side netting from a narrow angle.',
    '❌ The angle beat him in the end, {p}.',
    '❌ No angle at all, and {p} tried anyway.',
    '❌ He’d run himself out of room, {p}, and it shows.',
    '❌ Too tight for {p}, and it goes across the face and out.',
    '❌ The keeper barely has to move as it drifts wide.',
    '❌ The keeper watches it all the way past his post.',
    '❌ Never in doubt for the goalkeeper — wide from {p}.',
    '❌ No save required. {p} has missed the target.',
    '❌ A goal kick, and {team} have wasted a good position.',
    '❌ Chance gone. {team} won’t get many better.',
    '❌ That was {team}’s best moment, and it’s been thrown away.',
    '❌ You don’t get many of those, and {p} has passed it up.',
    '❌ A big let-off for {opp}, and they know it.',
    '❌ {opp} escape, and the defenders look at each other.',
    '❌ Relief in the {opp} back four.',
    '❌ They got away with one there, {opp}.',
    '❌ Somehow the ball is not in the net.',
    '❌ It stays goalless from that attack, and {p} is bewildered.',
    '❌ {p} throws his head back — he expected the net to bulge.',
    '❌ He wheels away thinking it’s in. It isn’t.',
    '❌ He’d already started celebrating, {p}. Too soon.',
    '❌ A half-raised arm from {p}, and then the truth.',
    '❌ Not this time for {p}.',
    '❌ Another one that won’t go in for {p} today.',
    '❌ {p} is having one of those afternoons in front of goal.',
    '❌ The confidence is draining out of {p}.',
    '❌ You could see it in his run-up — {p} wasn’t sure.',
    '❌ A striker’s nightmare. {p} skews it wide.',
    '❌ Wide again. {team} are becoming their own worst enemy.',
    '❌ {team} keep creating; {team} keep missing.',
    '❌ Effort after effort from {team}, and nothing on target.',
    '❌ Wasteful. That’s the word for {team} right now.',
    '❌ {p} gets his head in his hands as it flies wide.',
    '❌ A rasping drive from {p} that clears the stand roof.',
    '❌ That’s still going, and it’s heading for the car park.',
    '❌ Row Z gets a souvenir, courtesy of {p}.',
    '❌ Someone in the back row is going home with that.',
    '❌ Well over. {p} needed to get his laces through it.',
    '❌ He leant back and paid for it, {p}.',
    '❌ Body shape all wrong from {p}, and it shows in the flight.',
  ],
  goal: [
    '⚽ GOAL! {p} smashes it into the roof of the net for {team}!',
    '⚽ IN OFF THE POST! {p} has done it for {team}!',
    '⚽ Bottom corner! {p} picks his spot beautifully.',
    '⚽ Top corner! An unstoppable strike from {p}!',
    '⚽ {p} rifles it home and wheels away!',
    '⚽ He’s buried it! {p} gives {team} the goal they wanted.',
    '⚽ GOAL! Cool as you like from {p}.',
    '⚽ A sublime finish from {p} — {team} are celebrating!',
    '⚽ {p} slots it past the keeper without breaking stride.',
    '⚽ Slotted home! {p} makes it look easy.',
    '⚽ {p} rolls it into the far corner. Ice cold.',
    '⚽ Side-footed and perfect from {p}!',
    '⚽ {p} dinks it over the keeper — audacious and brilliant!',
    '⚽ Chipped! {p} has the nerve to lift it over him.',
    '⚽ {p} rounds the keeper and taps in for {team}!',
    '⚽ Round the goalkeeper, and {p} has the simplest of finishes!',
    '⚽ Nutmegged the keeper! {p} scores for {team}!',
    '⚽ Through his legs and in — outrageous from {p}!',
    '⚽ {p} thumps it in from twenty-five yards!',
    '⚽ WHAT A HIT! {p} from distance, and it flies in!',
    '⚽ From range! {p} catches it perfectly.',
    '⚽ A screamer from {p}! {team} are ahead of themselves with joy.',
    '⚽ Dipping, swerving, unstoppable — {p} scores a beauty!',
    '⚽ That is a goal worth the admission on its own, from {p}.',
    '⚽ {p} strikes it sweetly and the net bulges!',
    '⚽ Bang! First time from {p} and it’s in.',
    '⚽ A first-time finish from {p} — no need to control it!',
    '⚽ On the volley! {p} connects perfectly for {team}!',
    '⚽ A half-volley from {p}, and it screams into the corner.',
    '⚽ Struck on the drop by {p} and it rockets in!',
    '⚽ HEADER! {p} powers it past the keeper!',
    '⚽ {p} rises above everyone and heads {team} in front of the noise!',
    '⚽ A bullet header from {p}!',
    '⚽ Glanced in by {p} at the near post!',
    '⚽ {p} nods it down and into the corner — textbook.',
    '⚽ A towering leap from {p} and the ball is in the net.',
    '⚽ Unmarked at the back post, {p} makes no mistake.',
    '⚽ From the corner! {p} gets on the end of it for {team}!',
    '⚽ The set piece works to perfection and {p} finishes it.',
    '⚽ Straight from the training ground, and {p} applies the touch.',
    '⚽ Free kick, and it’s in! {p} finds the corner from the set piece!',
    '⚽ Over the wall and in! {p} with a wonderful free kick!',
    '⚽ Whipped in and turned home by {p}!',
    '⚽ A poacher’s goal from {p} — right place, right time.',
    '⚽ {p} gambles on the rebound and gets his reward!',
    '⚽ He follows it in, {p}, and bundles it over the line!',
    '⚽ Scrambled in! It’s ugly, but {p} won’t care.',
    '⚽ It goes in off {p}’s knee — they all count!',
    '⚽ Off the shin, off the post, and in! {p} has scored!',
    '⚽ Deflected past the keeper, and {p} takes it!',
    '⚽ A goal out of nothing from {p}!',
    '⚽ {p} conjures a finish from an impossible angle!',
    '⚽ From nowhere! {p} finds a way for {team}.',
    '⚽ The narrowest of angles, and {p} has squeezed it in!',
    '⚽ In at the near post! The keeper won’t enjoy watching that back.',
    '⚽ Under the goalkeeper and in — {p} will take it!',
    '⚽ Straight through the keeper’s hands! {p} has a goal.',
    '⚽ A dreadful error, and {p} punishes it ruthlessly.',
    '⚽ {opp} have gifted that one, and {p} says thank you.',
    '⚽ Awful defending, clinical finishing — {p} scores.',
    '⚽ {p} pounces on the mistake and {team} lead the celebration.',
    '⚽ The press pays off and {p} rolls it into an empty net.',
    '⚽ Won high, finished low — {p} completes it.',
    '⚽ On the counter! {p} finishes off a devastating break.',
    '⚽ Three passes from their box to ours, and {p} applies the finish.',
    '⚽ A breakaway goal of real quality, taken by {p}.',
    '⚽ {team} spring forward and {p} does the rest!',
    '⚽ A team goal to savour, and {p} is the man who scores it.',
    '⚽ Beautiful football from {team}, finished by {p}.',
    '⚽ Passed into the net by {team}, with {p} the last touch.',
    '⚽ That’s been coming, and {p} is the one to deliver it.',
    '⚽ Reward at last for {team}, and {p} is the scorer.',
    '⚽ Persistence pays for {p} and for {team}!',
    '⚽ He’s been quiet all afternoon — not any more. {p} scores.',
    '⚽ {p} has waited all game for that, and he doesn’t waste it.',
    '⚽ One chance, one goal. That’s what {p} does.',
    '⚽ Clinical is the only word for {p} there.',
    '⚽ Ruthless from {p}!',
    '⚽ Ice in the veins for {p} — he never looked like missing.',
    '⚽ Composure personified from {p}.',
    '⚽ He took his time and picked his corner — {p} is a class act.',
    '⚽ The keeper had no chance whatsoever with {p}’s finish.',
    '⚽ You cannot save that. {p} has struck it perfectly.',
    '⚽ It’s in before the goalkeeper has moved.',
    '⚽ Absolutely unstoppable from {p}.',
    '⚽ The net rips and the ground erupts for {team}!',
    '⚽ Bedlam! {p} has scored for {team}!',
    '⚽ Pandemonium as {p} finds the net!',
    '⚽ Away he goes to the corner flag — {p} has scored!',
    '⚽ {p} slides on his knees; {team} are away!',
    '⚽ He’s in among his own supporters, {p}.',
    '⚽ The bench empties. {p} has done it.',
    '⚽ {team} mob {p} and nobody wants to let go.',
    '⚽ Arms out, shirt pulled over his head — {p} has scored a big one.',
    '⚽ Look at what that means to {p}.',
    '⚽ A roar that will be heard for miles — {p} scores!',
    '⚽ {p} points to the sky. That one meant something.',
    '⚽ He doesn’t celebrate — but {p} has scored.',
    '⚽ Straight-faced from {p}, and straight into the net.',
    '⚽ Back to the halfway line, no fuss, and {p} has his goal.',
    '⚽ Picks the ball out and gets on with it — {p} means business.',
    '⚽ {p} beats his man and finishes with the outside of the boot!',
    '⚽ Cut inside and curled home by {p}!',
    '⚽ Onto his favoured foot and into the far corner from {p}.',
    '⚽ He shifts it once and bends it in — {p} is some player.',
    '⚽ The curl on that from {p} is a joy.',
    '⚽ Whipped into the far top corner by {p}!',
    '⚽ {p} drives into the box and stabs it home!',
    '⚽ Toe-poked in by {p} before the keeper could set himself.',
    '⚽ Improvised and finished by {p} in a heartbeat.',
    '⚽ Nothing pretty about it, but {p} has scored for {team}.',
    '⚽ Bundled over the line by {p} in the melee!',
    '⚽ Six yards, six inches, six seconds of chaos — and {p} scores.',
    '⚽ It squeezes over the line and {p} claims it!',
    '⚽ Over the line! {p} gets the final touch for {team}.',
    '⚽ Chest and finish! {p} does it all himself.',
    '⚽ Controlled on the thigh and hammered in by {p}.',
    '⚽ Two touches — one to set, one to score. {p} is deadly.',
    '⚽ He never broke stride, {p}, and neither did the ball.',
    '⚽ In it goes, and {team} have the goal their play deserved.',
  ],
  foul: [
    'The whistle goes — {p} has taken the man {zone}.',
    'Clumsy from {p}. Free kick to {opp} {zone}.',
    '{p} goes through the back of him {zone}.',
    'Late and clumsy from {p} — the referee has a word.',
    'A trip from {p}, and {opp} have the free kick.',
    '{p} mistimes it badly {zone} and takes his man down.',
    'That’s a foul all day long from {p}.',
    'No complaints about that one — {p} caught him.',
    '{p} holds him back {zone}, and the whistle blows.',
    'A shirt-pull from {p}. The referee spots it.',
    '{p} sticks an arm out and the man goes down.',
    'Barged over by {p} {zone}.',
    'A shoulder too many from {p}, and it’s a free kick.',
    '{p} leads with the elbow {zone} — the referee isn’t happy.',
    'The referee calls it back for a foul by {p} {zone}.',
    'Advantage played, and then brought back — foul by {p}.',
    '{p} nudges him in the back and the flag goes up.',
    'A blocking foul from {p} {zone}.',
    'That’s obstruction from {p}, plain and simple.',
    '{p} backs into his man and it’s given against him.',
    'Studs showing from {p} — a dangerous one {zone}.',
    'A high boot from {p}, and the referee stops play.',
    '{p} catches him on the ankle {zone}.',
    'Down goes the winger, and {p} is the culprit.',
    'A rash challenge from {p} {zone}.',
    'Dived in and got it wrong, {p}.',
    '{p} lunges and takes man rather than ball.',
    'All momentum and no timing from {p}.',
    'Committed too early, {p}, and paid the price.',
    'He was second to it, {p}, and it’s a foul.',
    'A professional foul from {p} to stop the break {zone}.',
    'Cynical stuff from {p} — that’s stopped a promising move.',
    '{p} takes one for the team {zone}.',
    'He had to do it, {p}, but it’s still a foul.',
    'Tactical from {p}, and {opp} are furious.',
    'The referee has seen enough of that from {p}.',
    'A soft one, that, but the whistle has gone against {p}.',
    '{p} can’t believe it — he thinks he won the ball.',
    '{p} protests, and gets nowhere.',
    '{team} are up in arms; the referee is unmoved.',
    'Contact, and down he goes. Free kick {opp}.',
    'Minimal contact from {p}, but it’s enough for the referee.',
    'A theatrical fall, but the foul stands against {p}.',
    'He made a meal of it, but {p} did catch him.',
    'The referee buys it, and {p} is annoyed.',
    '{p} argues the point and is waved away.',
    'A stoppage {zone}, and the physio has a look.',
    'Both men down, and the whistle has gone against {p}.',
    'A collision {zone}, and it’s given against {p}.',
    'Handball! {p} can’t claim that one was accidental.',
    'The ball strikes {p}’s arm and the referee blows.',
    'Arm away from the body — that’s a foul from {p}.',
    'A foul throw, of all things, from {p}.',
    'Offside — {p} strayed a fraction too early.',
    'The flag is up against {p} {zone}.',
    'A late challenge from {p} sparks a few words.',
    'Tempers rising after that one from {p}.',
    'Handbags {zone} following the foul by {p}.',
    'The referee steps between them after {p}’s challenge.',
    'A few players are getting involved. The referee calms it down.',
    'A niggly foul from {p} — the sort that irritates.',
    '{p} has been leaving a bit on people all afternoon.',
    'Another one from {p}; he’s getting close to a booking.',
    'That’s his third of the half from {p}.',
    'The referee has a quiet word with {p}. No card, this time.',
    'A warning, nothing more, for {p}.',
    'The gaffer will be delighted with that cynicism from {p}.',
    'A stop-the-game foul from {p} {zone}.',
    '{p} kills the counter-attack with a tug of the shirt.',
    'That’s stopped {opp} in their tracks — foul by {p}.',
    'A dangerous free kick conceded by {p} {zone}.',
    '{p} gives away a free kick in a horrible area.',
    'That’s an invitation to {opp}, courtesy of {p}.',
    '{p} has given them a chance from the set piece.',
    'A needless foul from {p} — nowhere near the goal at the time.',
    'No need for that from {p}.',
    'Frustration showing from {p} there.',
    'A tired challenge from {p} {zone}.',
    'Legs gone, and {p} concedes the foul.',
    'He couldn’t get there, so {p} made sure nobody did.',
  ],
  corner: [
    'Corner {team}. Everyone forward.',
    'A corner for {team} — {p} has the flag.',
    '{p} will whip this in from the right.',
    'Inswinger coming from {p}.',
    'An outswinger from {p} this time.',
    '{p} beckons the big centre half forward.',
    'The keeper comes out to organise his six-yard box.',
    '{p} places it carefully and takes a long look up.',
    'They go short — {p} rolls it and takes the return.',
    'A short corner routine from {team}, worked by {p}.',
    'Trained routine coming, and {p} starts it.',
    '{p} raises an arm — that’s the signal for something.',
    'Bodies pouring into the box for {team}.',
    'Even the goalkeeper is thinking about coming up.',
    '{p} takes his time. {team} need this.',
    'A rare set-piece opportunity for {team}, taken by {p}.',
    '{team} have looked dangerous from these all afternoon.',
    'This has been their best route to goal — {p} to deliver.',
    'Third corner in a row for {team}. The pressure is building.',
    'Another corner. {opp} cannot get out.',
    '{p} stands over it and the noise rises.',
    'The referee waves them back before {p} can take it.',
    'A bit of pushing and shoving as {p} waits.',
    'Shirts being tugged everywhere before this corner.',
    'The referee warns them both, then lets {p} get on with it.',
    'It’s a wrestling match in there before the ball is even struck.',
    '{p} to swing it toward the near post.',
    'Aiming for the back post, {p}.',
    'A deep one from {p}, looking for the far side.',
    '{p} drills it low into the near-post area.',
    'A driven corner from {p} — dangerous if anyone gets a touch.',
    'Floated in gently by {p}.',
    'Hung up in the air for the big men by {p}.',
    'Whipped hard by {p}, and it takes some stopping.',
    '{p} goes for the corner where the keeper doesn’t want to come.',
    'Right into the danger area from {p}.',
    'The delivery from {p} looks a good one.',
    '{p} has to beat the first man here.',
    'They’ve got a man on both posts, {opp}.',
    '{opp} defend it zonally. Interesting.',
    'Man-to-man marking from {opp}, and it’s getting physical.',
    '{opp} have three big lads back there — no easy header.',
    'A big moment for {team}, and {p} is trusted with it.',
    '{p} takes the corner. He’s good at these.',
    'They’ve worked hard for this. {p} over it.',
    'A chance to build some pressure — corner {team}.',
    'Corner {team}, and the ground finds its voice.',
    'Set piece for {team}, {p} to deliver from the flag.',
    'The crowd behind that goal are up. Corner {team}.',
    '{p} jogs across and picks up the ball.',
    'A little wave of the arm from {p}, and in it comes.',
    'The wind is swirling — {p} will need to judge this.',
    '{p} makes sure the ball is inside the quadrant.',
    'A quick corner from {p}, catching {opp} napping!',
    '{p} takes it quickly — that’s clever.',
    'They’re not ready, and {p} has spotted it.',
    'Taken short and worked back to {p} on the edge.',
    '{team} recycle it and go again.',
    '{p} will cross from deep instead.',
    'It’s worked back out to {p} for a second delivery.',
    'A second corner immediately — {team} keep coming.',
    'Deflected behind, and it’s another one for {team}.',
    'Headed out for a corner, and here we go again.',
    'The block sends it behind. Corner {team}, {p} to take.',
    '{p} looks up, sees the crowd of bodies, and picks his moment.',
    'Everyone up for {team}, and {p} stands over the ball.',
    'This is a big set piece for {team}.',
    '{team} sense something from this corner.',
    'A dangerous moment coming from {p}’s corner.',
    '{p} takes a deep breath and starts his run.',
    'Two strides and {p} sends it in.',
    'The near post is loaded and {p} aims for it.',
    'They’ve pulled everyone to the back post — {p} sees it.',
    '{p} finds the one gap in a crowded box.',
    'A clever dummy run before {p} delivers it.',
    'Screening the keeper — that’s deliberate from {team}.',
    'They’ve blocked the keeper off, and {p} takes advantage.',
    'A well-rehearsed routine from {team} at this corner.',
    'The gaffer is signalling from the touchline as {p} waits.',
    'Instructions from the bench, and {p} nods and takes it.',
  ],
  free_kick: [
    'Free kick {team}, and {p} likes these…',
    '{p} places the ball and steps back five paces…',
    'The wall lines up; {p} waits for the whistle…',
    'Referee marks out ten yards as {p} gets ready…',
    'Four in the wall, and {p} is going for goal…',
    '{p} is going to shoot from here — no doubt about it…',
    'This is right in his range for {p}…',
    'A free kick on the edge of the box for {team}…',
    'Just outside the area, and {p} stands over it…',
    'A yard or two further and {p} would be shooting; he might anyway…',
    'Two men over it for {team} — a routine coming…',
    '{p} and a teammate stand over the ball, and only one will take it…',
    'The dummy run goes past it, and {p} is left with the ball…',
    '{p} looks like he’ll cross rather than shoot…',
    'He’ll whip it in, will {p}…',
    'A delivery into the mixer coming from {p}…',
    '{p} eyes the far post as the box fills up…',
    'Everyone up for {team} — including the goalkeeper…',
    'The keeper has come up for this one, and {p} waits…',
    'A big set-piece moment for {team}, and {p} has it…',
    '{p} wipes his boot on his sock and settles…',
    'He’s got the ball just how he wants it now, {p}…',
    'A little shuffle of the feet from {p}…',
    'The crowd hush as {p} stands over it…',
    'The whole ground is watching {p}…',
    'One kick could change this, and {p} has it…',
    '{p} rolls his shoulders and steps up…',
    'Three steps, a deep breath, and {p} is ready…',
    'The referee tells the wall to hold, and {p} waits…',
    'A little argument about the wall’s distance before {p} takes it…',
    'The spray comes out, the line is drawn, {p} is ready…',
    '{p} appeals for the wall to be moved back…',
    'Free kick in a lovely position for {team} — {p} to strike it…',
    'A gilt-edged set piece for {team}, and {p} fancies it…',
    'This is exactly where {p} wants them…',
    'Dead centre, twenty-two yards. Perfect for {p}…',
    'Wide on the right, and {p} will send it in…',
    'From the left touchline, {p} has a delivery to make…',
    'Deep free kick for {team}, and {p} looks to load the box…',
    'A free kick in their own half, but {team} still go long…',
    '{p} will just play it short and keep it…',
    'They take it quickly! {p} spots a runner…',
    '{p} plays it short and {team} keep the move alive…',
    'No wall needed — {p} rolls it sideways…',
    'The quick free kick catches {opp} out of position…',
    'A cute one — {p} goes under the wall…',
    'He’s tried to roll it under the jumping wall, has {p}…',
    '{p} shapes to blast it and clips it instead…',
    'A curler is coming from {p}…',
    'Knuckleball from {p} — this one will move in the air…',
    'He’ll go over the wall and hope it dips, {p}…',
    '{p} takes the direct route and hammers it…',
    'A left-footer over the wall for {p}…',
    'The goalkeeper shuffles his wall one last time as {p} waits…',
    'The keeper points and shouts; {p} ignores it all…',
    'The referee’s whistle, and {p} moves…',
    '{p} strides in, and this is struck well…',
    'Here it comes from {p}…',
    'This is a real chance for {team} from the set piece…',
    'Danger for {opp} here, with {p} standing over it…',
  ],
  fatigue: [
    '{p} is out on his feet {zone}.',
    'The legs have gone for {p} — he can barely jog.',
    'Cramp for {p}. He’s stretching it out {zone}.',
    '{p} is limping through the fatigue now.',
    'You can see the exhaustion in {p}.',
    '{p} is walking. He simply cannot run any more.',
    'Bent double, hands on knees, {p} is finished.',
    'A long afternoon is catching up with {p}.',
    '{p} is running on fumes {zone}.',
    'That’s a player with nothing left in the tank.',
    '{p} waves at the bench — he needs help.',
    'A look towards the touchline from {p}. He’s asking the question.',
    '{p} tries to signal he’s alright. He isn’t.',
    'He’s shaking his head, {p}. The tank is empty.',
    'The gaffer has spotted it — {p} is struggling badly.',
    '{p} is a passenger now.',
    'He’s given everything, {p}, and there’s nothing left.',
    'The tempo has drained {p} completely.',
    'All that pressing has caught up with {p}.',
    '{p} has covered miles today, and it shows.',
    'He can’t get back to help, {p}.',
    '{p} is fifteen yards behind the play and losing ground.',
    'The recovery run from {p} is more of a stroll.',
    'He watches the man go by. {p} has no answer.',
    '{p} is beaten for pace by tiredness, not talent.',
    'Heavy legs from {p} {zone}.',
    'That first touch is fatigue as much as anything, from {p}.',
    'Tired legs make tired decisions — {p} is showing it.',
    '{p}’s passing has gone since he tired.',
    'The quality is dropping with the energy for {p}.',
    'He’s hanging on, {p}.',
    '{p} is playing on memory now.',
    'Sheer willpower keeping {p} going.',
    'He won’t come off, {p}, but he should.',
    'Stubborn as anything, {p}, but he’s done.',
    'The heat is telling on {p}.',
    'It’s been a punishing pace, and {p} has paid for it.',
    '{p} is gulping down air {zone}.',
    'Hands on hips, chest heaving — {p} needs the whistle.',
    'A stoppage would be very welcome for {p} right now.',
    'He’s taking every second he can, {p}.',
    'Every throw-in is a rest for {p} now.',
    '{p} is going down for a stretch — it buys a moment.',
    'Trainers coming on, and {p} takes a drink.',
    'A quick word and a bottle of water for {p}.',
    'The physio works on {p}’s calf on the touchline.',
    'That’s cramp, and {p} is in real discomfort.',
    'His hamstring is tightening — {p} can feel it.',
    'A teammate stretches the leg out for {p}.',
    'He’s flat on his back, {p}, calf in the air.',
    '{p} tries a sprint and immediately regrets it.',
    'That burst finished him, {p}.',
    'One more run in him, and {p} has just used it.',
    'A tiring {p} loses his man far too easily.',
    'He’s a yard off everything now, {p}.',
    'The intensity has dropped since {p} tired.',
    '{team} are running on empty {zone}, {p} especially.',
    'Legs are heavy all over the pitch, and {p} looks worst of all.',
    'The last ten minutes have taken everything out of {p}.',
    '{p} looks up at the clock, and it hasn’t moved.',
  ],
  sub: [
    '🔄 {team} make a change: {name} on, {off} off.',
    '🔄 The gaffer turns to the bench — {name} for {off}.',
    '🔄 {off} trudges off; {name} is straight into the action.',
    '🔄 {name} was warming up for ten minutes, and here he comes for {off}.',
    '🔄 A tactical switch from {team}: {off} makes way for {name}.',
    '🔄 {off} has run himself into the ground; {name} takes over.',
    '🔄 {name} strips off and comes on in place of {off}.',
    '🔄 {off} isn’t happy about it, but off he goes. {name} on.',
    '🔄 A shake of the hand for {off} from the gaffer; {name} is on.',
    '🔄 {off} takes his time getting off — {name} waits on the touchline.',
    '🔄 {name} gets his instructions and replaces {off} for {team}.',
    '🔄 A last word from the bench, and {name} comes on for {off}.',
    '🔄 {team} freshen it up: {name} in, {off} out.',
    '🔄 New legs for {team} — {name} replaces {off}.',
    '🔄 {off} gets a standing ovation as {name} takes his place.',
    '🔄 Applause all round for {off}; {name} has a lot to live up to.',
    '🔄 The captain’s armband changes hands as {off} departs for {name}.',
    '🔄 {name} is on for {off}, and {team} shuffle their shape.',
    '🔄 A change of system for {team} with {name} on for {off}.',
    '🔄 {team} go more attacking: {name} replaces {off}.',
    '🔄 Shoring it up, {team} — {name} comes on for {off}.',
    '🔄 A defensive change from {team}: {off} off, {name} on.',
    '🔄 {name} on for {off}. That’s an interesting one.',
    '🔄 {team} shut the door: {name} in for {off}.',
    '🔄 {name} comes on with a clear job to do, and {off} is done.',
    '🔄 A big call from the touchline — {off} is hooked, {name} on.',
    '🔄 {off} can’t hide his frustration. {name} takes his place.',
    '🔄 A dispirited {off} leaves the pitch; {name} enters.',
    '🔄 {off} throws his gloves at the bench. {name} is on for {team}.',
    '🔄 The gaffer has seen enough of {off} — on comes {name}.',
    '🔄 {name} is thrown on to change the game for {team}.',
    '🔄 A roll of the dice: {name} on in place of {off}.',
    '🔄 The game-changer is coming on — {name} for {off}.',
    '🔄 {team} go for it: {name} replaces {off}.',
    '🔄 Here’s the move everyone has been waiting for — {name} on, {off} off.',
    '🔄 {name} jogs on to a warm reception from the {team} fans.',
    '🔄 A big cheer for {name} as {off} makes way.',
    '🔄 {name} sprints on. {off} does not sprint off.',
    '🔄 Every second counts, and {off} knows it — slowly off, {name} on.',
    '🔄 The board goes up: {off}’s number. {name} takes his place.',
    '🔄 Fourth official raises the board; it’s {off} coming off for {name}.',
    '🔄 A quick handshake at the touchline between {off} and {name}.',
    '🔄 {off} and {name} exchange a word on the way past.',
    '🔄 Fresh legs from the bench for {team}: {name} for {off}.',
    '🔄 A tiring {off} is replaced by {name}.',
    '🔄 {off} was struggling; {name} comes on for {team}.',
    '🔄 Precautionary, that — {off} comes off and {name} is on.',
    '🔄 {team} won’t risk {off} any longer. {name} is on.',
    '🔄 Debut, perhaps, for {name} — he replaces {off}.',
    '🔄 A moment {name} will remember, coming on for {off}.',
  ],
  yellow_card: [
    '{p} sees yellow for that challenge.',
    'A booking for {p} — it was coming.',
    'That’s a caution for {p}, and it was thoroughly deserved.',
    'Into the book goes {p}.',
    '{p} is shown the yellow and shrugs.',
    'A yellow card for dissent — {p} said too much.',
    '{p} is booked for arguing. That was avoidable.',
    'Yellow for {p}: he threw the ball away.',
    'Time-wasting, and {p} pays for it with a booking.',
    'A cynical foul, a cynical booking — {p} takes one for the team.',
    '{p} is booked for stopping the counter. Textbook.',
    'A professional foul and a professional yellow card for {p}.',
    'That’s a bad one from {p}, and he’s lucky it’s only yellow.',
    '{p} could have seen red for that. He gets yellow.',
    'The referee reaches for his pocket and {p} braces himself.',
    '{p} pleads his case and gets a yellow anyway.',
    'A shake of the head from {p} as the card comes out.',
    '{p} looks stunned. The referee is unmoved.',
    'His teammates surround the referee. {p} is booked regardless.',
    'A caution for {p}, and now he has to be careful.',
    'Yellow card {p}. He’ll be walking a tightrope from here.',
    '{p} is one bad tackle from an early bath.',
    'The gaffer will be worried about {p} now.',
    'Booked — and {p} might not last the ninety.',
    'That’s the caution, and {p} knows he can’t go in like that again.',
    'A booking for {p}, and the gaffer is on the touchline shouting.',
    '{p} gets a talking-to from his own captain after the card.',
    'The card is shown, and {p} walks away without a word.',
    'A wry smile from {p} as the yellow comes out.',
    '{p} applauds the referee sarcastically. That is not clever.',
    'The crowd bay for it, and the referee obliges — {p} is booked.',
    'A soft booking, that, and {p} is entitled to feel aggrieved.',
    'Harsh on {p}, but the referee has been consistent.',
    'The referee has been waiting to book someone, and it’s {p}.',
    'A yellow for a foul on the halfway line — {p} is bemused.',
    '{p} is booked for a challenge he didn’t need to make.',
    'Frustration from {p}, and it costs him a caution.',
    'Kicked out in temper, and {p} is rightly booked.',
    'The referee calls {p} over and shows him yellow.',
    'A stern lecture and a yellow card for {p}.',
  ],
  injury: [
    '🚑 {p} is down, and this looks bad for {team}.',
    '🚑 He’s clutching his hamstring — {p} is in trouble.',
    '🚑 {p} felt something go. That’s him finished.',
    '🚑 Straight down without a challenge — the worst kind for {p}.',
    '🚑 {p} tries to stand and can’t put weight on it.',
    '🚑 The stretcher is being called for {p}.',
    '🚑 {p} is helped from the pitch by two of the staff.',
    '🚑 An arm around each shoulder, and {p} hobbles off.',
    '🚑 The knee has twisted awkwardly under {p}.',
    '🚑 It’s the ankle for {p}, and it’s already swelling.',
    '🚑 A bad landing, and {p} is holding his shoulder.',
    '🚑 A clash of heads, and {p} is receiving treatment.',
    '🚑 The head injury protocol for {p} — {team} cannot take a risk.',
    '🚑 Blood on the shirt, and {p} needs attention.',
    '🚑 {p} can’t continue. {team} will have to reshape.',
    '🚑 That’s a blow for {team} — {p} is done for the day.',
    '🚑 A worried look between the physios over {p}.',
    '🚑 The medical team wave to the bench immediately.',
    '🚑 {p} is furious with his own body.',
    '🚑 He punches the turf, does {p}. He knew straight away.',
    '🚑 {p} is in tears as he leaves the pitch.',
    '🚑 A long look at the sky from {p}. That’s a big one.',
    '🚑 {p} pulled up mid-sprint and went straight down.',
    '🚑 He’s pulled up sharply — {p} has felt his hamstring go.',
    '🚑 The calf has gone for {p}.',
    '🚑 {p} tried to run it off and lasted about ten seconds.',
    '🚑 One more attempt from {p}, and he immediately signals to come off.',
    '🚑 He can’t go on, {p}. The arm goes up.',
    '🚑 {p} takes his shinpads out before he’s even off the pitch.',
    '🚑 Ice pack straight on it for {p} on the touchline.',
    '🚑 An awkward fall, and {p} has landed badly on his wrist.',
    '🚑 That was a heavy challenge, and {p} is the one who suffers.',
    '🚑 He’s taken a boot to the ankle and {p} can’t shake it off.',
    '🚑 The physio shakes his head at the bench — {p} is coming off.',
    '🚑 A groin problem, by the looks of it, for {p}.',
    '🚑 {p} stretches it, tests it, and gives up on it.',
    '🚑 {team} have lost {p}, and that changes things.',
    '🚑 A big miss for {team} — {p} cannot carry on.',
    '🚑 The whole ground applauds {p} off the pitch.',
    '🚑 {p} goes straight down the tunnel. That says everything.',
  ],
  woodwork: [
    '🪵 CROSSBAR! {p} is a whisker away for {team}!',
    '🪵 The upright saves {opp}! {p} is distraught.',
    '🪵 Off the inside of the post and out! How is that not a goal?',
    '🪵 It smacks the bar and bounces down on the line — and away!',
    '🪵 The woodwork rescues {opp} again.',
    '🪵 {p} beats the keeper and finds the frame of the goal.',
    '🪵 A thunderous strike from {p} rattles the crossbar!',
    '🪵 The bar is still shaking after that one from {p}.',
    '🪵 Onto the post and straight back into the keeper’s arms.',
    '🪵 Off the far post and across the face — nobody can turn it in!',
    '🪵 The rebound off the woodwork is scrambled clear.',
    '🪵 An inch either way and {p} is a hero.',
    '🪵 Millimetres from a goal for {team}!',
    '🪵 That’s the closest anyone will come today, and it stays out.',
    '🪵 {p} holds his head — the post has denied him.',
    '🪵 Cruel on {p}. That deserved a goal.',
    '🪵 A brilliant free kick from {p} clips the top of the bar.',
    '🪵 The header from {p} thumps against the upright!',
    '🪵 Off the bar, off the keeper, and somehow out.',
    '🪵 It hits one post, rolls along the line, and hits the other!',
    '🪵 The goal frame is having a marvellous game for {opp}.',
    '🪵 {opp} have the woodwork to thank for that one.',
    '🪵 Everyone thought that was in — including {p}.',
    '🪵 The net didn’t move, but everything else did.',
    '🪵 A collective gasp as {p}’s effort hits the frame.',
    '🪵 The volley from {p} cracks off the underside of the bar.',
    '🪵 Down off the bar and hooked away before it crosses.',
    '🪵 Struck perfectly by {p}, and the post gets in the way.',
    '🪵 {team} cannot believe it — the woodwork again!',
    '🪵 That’s twice they’ve hit the frame. It’s not their day.',
  ],
  penalty: [
    '⚠️ The referee points to the spot! {team} have a penalty!',
    '⚠️ Penalty! And {opp} are furious about it.',
    '⚠️ He’s given it! {p} places the ball on the spot…',
    '⚠️ Twelve yards, and {p} has the responsibility…',
    '⚠️ {p} takes the ball off his teammate. He’s taking it…',
    '⚠️ A big moment. {p} steps up for {team}…',
    '⚠️ The keeper is dancing on his line as {p} waits…',
    '⚠️ {p} places it, steps back, and blows out his cheeks…',
    '⚠️ The whole ground is watching {p} and nobody else…',
    '⚠️ The referee clears the box. {p} is ready…',
    '⚠️ Penalty {team}! This is a chance to change everything…',
    '⚠️ The keeper has done his homework; {p} knows it…',
    '⚠️ {opp} surround the referee, and it changes nothing…',
    '⚠️ Booked for the challenge, and now {p} has the penalty…',
    '⚠️ A stonewall penalty, and {p} will take it…',
    '⚠️ No doubt about that one. {p} stands over the ball…',
    '⚠️ Soft, some will say — but it’s a penalty to {team}…',
    '⚠️ {p} looks up once and then only at the ball…',
    '⚠️ Nerves of steel required now for {p}…',
    '⚠️ Spot kick {team}, and {p} has never looked more alone…',
  ],
  penalty_missed: [
    '❌ Off the post! The penalty from {p} stays out!',
    '❌ Onto the crossbar! {p} has missed from the spot!',
    '❌ Saved! The keeper flies to his left and denies {p}!',
    '❌ A brilliant save, and {p} is inconsolable.',
    '❌ The keeper stood up, and {p} blinked first.',
    '❌ {p} tried to be clever and the keeper didn’t move.',
    '❌ The panenka has failed! {p} will never live that down.',
    '❌ Dragged wide of the post. What a miss from {p}.',
    '❌ Skied it! {p} has put the penalty into the stands.',
    '❌ {p} slips as he strikes it and it goes miles wide.',
    '❌ Too close to the keeper from {p}, and it’s pushed away.',
    '❌ Saved, and the rebound is hacked clear before {p} can react.',
    '❌ The keeper guessed right and {p} has been denied.',
    '❌ {p} hesitated in the run-up and paid for it.',
    '❌ Down goes the goalkeeper, and up go the {opp} supporters!',
    '❌ {p} cannot look. The chance has gone.',
    '❌ A huge moment missed by {p}.',
    '❌ That could be the miss that decides this.',
    '❌ {p} covers his face with his shirt.',
    '❌ Teammates rush to console {p}. Nothing they say will help.',
  ],
  red_card: [
    '{p} is sent off, and {team} must play on with ten.',
    'The referee has no option — {p} is dismissed.',
    'That’s a red, and nobody in {team} can argue.',
    '{p} sees red and the game changes completely.',
    'Off he goes. {p} has let {team} down badly.',
    'A moment of madness from {p}, and he’s gone.',
    '{p} loses his head, and {team} lose a man.',
    'The long walk for {p}, to a chorus of jeers.',
    '{p} refuses to leave, and his teammates have to push him.',
    'The captain steers {p} towards the tunnel.',
    '{p} goes down the tunnel without applauding anyone.',
    'He knows what he’s done, {p}. Straight off.',
    'A dreadful challenge from {p}, and the red card is inevitable.',
    'Studs up, over the ball — {p} is off for that.',
    '{p} raises his hands, and that is always a red.',
    'The referee reaches for the top pocket. {p} is going.',
    'Denying a clear goalscoring opportunity — {p} has to go.',
    'The last man, and {p} pays the ultimate price.',
    '{team} are a man light, and there is a long way to go.',
    'A red card, and {team} now have a mountain to climb.',
  ],
  kickoff: [
    'The whistle goes and we are away!',
    'And we begin!',
    'Off we go, then.',
    'The referee checks his watch, and away we go.',
    'Rolled back from the centre circle, and this one is live.',
    'The ball is in play. Here we go.',
    'Handshakes done, and the match is on.',
    'A wall of noise greets the first kick.',
    'The ground is bouncing as we get started.',
    'Both sides ready, and the referee sets us off.',
    'It’s underway, and the tempo is high already.',
    'And with that whistle, everything begins.',
    'Straight down the line, and we are up and running.',
    'They kick off and immediately go long.',
    'The first ball is hoofed into the corner. Familiar stuff.',
    'A cagey start expected, and the ball is rolling.',
    'The referee’s whistle cuts through the noise. Game on.',
    'Ninety minutes to settle it. Here we go.',
    'Everything to play for, and we are away.',
    'The wait is over. Kick-off.',
  ],
};
